import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define the activities
artifact_intake = Transition(label='Artifact Intake')
condition_check = Transition(label='Condition Check')
material_test = Transition(label='Material Test')
archival_search = Transition(label='Archival Search')
style_compare = Transition(label='Style Compare')
expert_review = Transition(label='Expert Review')
restoration_check = Transition(label='Restoration Check')
provenance_trace = Transition(label='Provenance Trace')
legal_verify = Transition(label='Legal Verify')
value_appraise = Transition(label='Value Appraise')
catalog_entry = Transition(label='Catalog Entry')
marketing_plan = Transition(label='Marketing Plan')
auction_setup = Transition(label='Auction Setup')
certify_final = Transition(label='Certify Final')
sales_report = Transition(label='Sales Report')

# Define the partial order
root = StrictPartialOrder(nodes=[artifact_intake, condition_check, material_test, archival_search, style_compare, expert_review, restoration_check, provenance_trace, legal_verify, value_appraise, catalog_entry, marketing_plan, auction_setup, certify_final, sales_report])

# Define the dependencies
root.order.add_edge(artifact_intake, condition_check)
root.order.add_edge(artifact_intake, material_test)
root.order.add_edge(artifact_intake, archival_search)
root.order.add_edge(artifact_intake, style_compare)
root.order.add_edge(artifact_intake, expert_review)
root.order.add_edge(artifact_intake, restoration_check)
root.order.add_edge(artifact_intake, provenance_trace)
root.order.add_edge(artifact_intake, legal_verify)
root.order.add_edge(artifact_intake, value_appraise)
root.order.add_edge(artifact_intake, catalog_entry)
root.order.add_edge(artifact_intake, marketing_plan)
root.order.add_edge(artifact_intake, auction_setup)
root.order.add_edge(artifact_intake, certify_final)
root.order.add_edge(artifact_intake, sales_report)

root.order.add_edge(condition_check, material_test)
root.order.add_edge(condition_check, archival_search)
root.order.add_edge(condition_check, style_compare)
root.order.add_edge(condition_check, expert_review)
root.order.add_edge(condition_check, restoration_check)
root.order.add_edge(condition_check, provenance_trace)
root.order.add_edge(condition_check, legal_verify)
root.order.add_edge(condition_check, value_appraise)
root.order.add_edge(condition_check, catalog_entry)
root.order.add_edge(condition_check, marketing_plan)
root.order.add_edge(condition_check, auction_setup)
root.order.add_edge(condition_check, certify_final)
root.order.add_edge(condition_check, sales_report)

root.order.add_edge(material_test, archival_search)
root.order.add_edge(material_test, style_compare)
root.order.add_edge(material_test, expert_review)
root.order.add_edge(material_test, restoration_check)
root.order.add_edge(material_test, provenance_trace)
root.order.add_edge(material_test, legal_verify)
root.order.add_edge(material_test, value_appraise)
root.order.add_edge(material_test, catalog_entry)
root.order.add_edge(material_test, marketing_plan)
root.order.add_edge(material_test, auction_setup)
root.order.add_edge(material_test, certify_final)
root.order.add_edge(material_test, sales_report)

root.order.add_edge(archival_search, style_compare)
root.order.add_edge(archival_search, expert_review)
root.order.add_edge(archival_search, restoration_check)
root.order.add_edge(archival_search, provenance_trace)
root.order.add_edge(archival_search, legal_verify)
root.order.add_edge(archival_search, value_appraise)
root.order.add_edge(archival_search, catalog_entry)
root.order.add_edge(archival_search, marketing_plan)
root.order.add_edge(archival_search, auction_setup)
root.order.add_edge(archival_search, certify_final)
root.order.add_edge(archival_search, sales_report)

root.order.add_edge(style_compare, expert_review)
root.order.add_edge(style_compare, restoration_check)
root.order.add_edge(style_compare, provenance_trace)
root.order.add_edge(style_compare, legal_verify)
root.order.add_edge(style_compare, value_appraise)
root.order.add_edge(style_compare, catalog_entry)
root.order.add_edge(style_compare, marketing_plan)
root.order.add_edge(style_compare, auction_setup)
root.order.add_edge(style_compare, certify_final)
root.order.add_edge(style_compare, sales_report)

root.order.add_edge(expert_review, restoration_check)
root.order.add_edge(expert_review, provenance_trace)
root.order.add_edge(expert_review, legal_verify)
root.order.add_edge(expert_review, value_appraise)
root.order.add_edge(expert_review, catalog_entry)
root.order.add_edge(expert_review, marketing_plan)
root.order.add_edge(expert_review, auction_setup)
root.order.add_edge(expert_review, certify_final)
root.order.add_edge(expert_review, sales_report)

root.order.add_edge(restoration_check, provenance_trace)
root.order.add_edge(restoration_check, legal_verify)
root.order.add_edge(restoration_check, value_appraise)
root.order.add_edge(restoration_check, catalog_entry)
root.order.add_edge(restoration_check, marketing_plan)
root.order.add_edge(restoration_check, auction_setup)
root.order.add_edge(restoration_check, certify_final)
root.order.add_edge(restoration_check, sales_report)

root.order.add_edge(provenance_trace, legal_verify)
root.order.add_edge(provenance_trace, value_appraise)
root.order.add_edge(provenance_trace, catalog_entry)
root.order.add_edge(provenance_trace, marketing_plan)
root.order.add_edge(provenance_trace, auction_setup)
root.order.add_edge(provenance_trace, certify_final)
root.order.add_edge(provenance_trace, sales_report)

root.order.add_edge(legal_verify, value_appraise)
root.order.add_edge(legal_verify, catalog_entry)
root.order.add_edge(legal_verify, marketing_plan)
root.order.add_edge(legal_verify, auction_setup)
root.order.add_edge(legal_verify, certify_final)
root.order.add_edge(legal_verify, sales_report)

root.order.add_edge(value_appraise, catalog_entry)
root.order.add_edge(value_appraise, marketing_plan)
root.order.add_edge(value_appraise, auction_setup)
root.order.add_edge(value_appraise, certify_final)
root.order.add_edge(value_appraise, sales_report)

root.order.add_edge(catalog_entry, marketing_plan)
root.order.add_edge(catalog_entry, auction_setup)
root.order.add_edge(catalog_entry, certify_final)
root.order.add_edge(catalog_entry, sales_report)

root.order.add_edge(marketing_plan, auction_setup)
root.order.add_edge(marketing_plan, certify_final)
root.order.add_edge(marketing_plan, sales_report)

root.order.add_edge(auction_setup, certify_final)
root.order.add_edge(auction_setup, sales_report)

root.order.add_edge(certify_final, sales_report)