import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

intel_gathering = Transition(label='Intel Gathering')
risk_assess = Transition(label='Risk Assess')
behavior_scan = Transition(label='Behavior Scan')
network_monitor = Transition(label='Network Monitor')
audit_conduct = Transition(label='Audit Conduct')
flag_suspicion = Transition(label='Flag Suspicion')
legal_review = Transition(label='Legal Review')
compliance_check = Transition(label='Compliance Check')
employee_train = Transition(label='Employee Train')
threat_simulate = Transition(label='Threat Simulate')
incident_plan = Transition(label='Incident Plan')
response_drill = Transition(label='Response Drill')
data_encrypt = Transition(label='Data Encrypt')
partner_liaison = Transition(label='Partner Liaison')
report_generate = Transition(label='Report Generate')
feedback_loop = Transition(label='Feedback Loop')

xor1 = OperatorPOWL(operator=Operator.XOR, children=[flag_suspicion, legal_review])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[compliance_check, employee_train])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[threat_simulate, incident_plan])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[response_drill, data_encrypt])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[partner_liaison, report_generate])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[feedback_loop, report_generate])

root = StrictPartialOrder(nodes=[intel_gathering, risk_assess, behavior_scan, network_monitor, audit_conduct, xor1, xor2, xor3, xor4, xor5, xor6])
root.order.add_edge(intel_gathering, risk_assess)
root.order.add_edge(risk_assess, behavior_scan)
root.order.add_edge(behavior_scan, network_monitor)
root.order.add_edge(network_monitor, audit_conduct)
root.order.add_edge(audit_conduct, xor1)
root.order.add_edge(audit_conduct, xor2)
root.order.add_edge(audit_conduct, xor3)
root.order.add_edge(audit_conduct, xor4)
root.order.add_edge(audit_conduct, xor5)
root.order.add_edge(audit_conduct, xor6)
root.order.add_edge(xor1, flag_suspicion)
root.order.add_edge(xor1, legal_review)
root.order.add_edge(xor2, compliance_check)
root.order.add_edge(xor2, employee_train)
root.order.add_edge(xor3, threat_simulate)
root.order.add_edge(xor3, incident_plan)
root.order.add_edge(xor4, response_drill)
root.order.add_edge(xor4, data_encrypt)
root.order.add_edge(xor5, partner_liaison)
root.order.add_edge(xor5, report_generate)
root.order.add_edge(xor6, feedback_loop)
root.order.add_edge(xor6, report_generate)