from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define the transitions (activities)
artifact_intake = Transition(label='Artifact Intake')
provenance_check = Transition(label='Provenance Check')
material_sampling = Transition(label='Material Sampling')
scientific_test = Transition(label='Scientific Test')
expert_review = Transition(label='Expert Review')
archive_search = Transition(label='Archive Search')
legal_verify = Transition(label='Legal Verify')
ownership_confirm = Transition(label='Ownership Confirm')
compliance_audit = Transition(label='Compliance Audit')
data_documentation = Transition(label='Data Documentation')
interim_report = Transition(label='Interim Report')
department_review = Transition(label='Department Review')
consensus_meeting = Transition(label='Consensus Meeting')
final_approval = Transition(label='Final Approval')
artifact_release = Transition(label='Artifact Release')

# Define the partial order
root = StrictPartialOrder(nodes=[artifact_intake, provenance_check, material_sampling, scientific_test, expert_review, archive_search, legal_verify, ownership_confirm, compliance_audit, data_documentation, interim_report, department_review, consensus_meeting, final_approval, artifact_release])

# Define the dependencies between activities
root.order.add_edge(artifact_intake, provenance_check)
root.order.add_edge(artifact_intake, material_sampling)
root.order.add_edge(artifact_intake, scientific_test)
root.order.add_edge(artifact_intake, expert_review)
root.order.add_edge(provenance_check, archive_search)
root.order.add_edge(provenance_check, legal_verify)
root.order.add_edge(provenance_check, ownership_confirm)
root.order.add_edge(provenance_check, compliance_audit)
root.order.add_edge(provenance_check, data_documentation)
root.order.add_edge(provenance_check, interim_report)
root.order.add_edge(provenance_check, department_review)
root.order.add_edge(provenance_check, consensus_meeting)
root.order.add_edge(provenance_check, final_approval)
root.order.add_edge(provenance_check, artifact_release)
root.order.add_edge(material_sampling, scientific_test)
root.order.add_edge(material_sampling, expert_review)
root.order.add_edge(material_sampling, archive_search)
root.order.add_edge(material_sampling, legal_verify)
root.order.add_edge(material_sampling, ownership_confirm)
root.order.add_edge(material_sampling, compliance_audit)
root.order.add_edge(material_sampling, data_documentation)
root.order.add_edge(material_sampling, interim_report)
root.order.add_edge(material_sampling, department_review)
root.order.add_edge(material_sampling, consensus_meeting)
root.order.add_edge(material_sampling, final_approval)
root.order.add_edge(material_sampling, artifact_release)
root.order.add_edge(scientific_test, expert_review)
root.order.add_edge(scientific_test, archive_search)
root.order.add_edge(scientific_test, legal_verify)
root.order.add_edge(scientific_test, ownership_confirm)
root.order.add_edge(scientific_test, compliance_audit)
root.order.add_edge(scientific_test, data_documentation)
root.order.add_edge(scientific_test, interim_report)
root.order.add_edge(scientific_test, department_review)
root.order.add_edge(scientific_test, consensus_meeting)
root.order.add_edge(scientific_test, final_approval)
root.order.add_edge(scientific_test, artifact_release)
root.order.add_edge(expert_review, archive_search)
root.order.add_edge(expert_review, legal_verify)
root.order.add_edge(expert_review, ownership_confirm)
root.order.add_edge(expert_review, compliance_audit)
root.order.add_edge(expert_review, data_documentation)
root.order.add_edge(expert_review, interim_report)
root.order.add_edge(expert_review, department_review)
root.order.add_edge(expert_review, consensus_meeting)
root.order.add_edge(expert_review, final_approval)
root.order.add_edge(expert_review, artifact_release)
root.order.add_edge(archive_search, legal_verify)
root.order.add_edge(archive_search, ownership_confirm)
root.order.add_edge(archive_search, compliance_audit)
root.order.add_edge(archive_search, data_documentation)
root.order.add_edge(archive_search, interim_report)
root.order.add_edge(archive_search, department_review)
root.order.add_edge(archive_search, consensus_meeting)
root.order.add_edge(archive_search, final_approval)
root.order.add_edge(archive_search, artifact_release)
root.order.add_edge(legal_verify, ownership_confirm)
root.order.add_edge(legal_verify, compliance_audit)
root.order.add_edge(legal_verify, data_documentation)
root.order.add_edge(legal_verify, interim_report)
root.order.add_edge(legal_verify, department_review)
root.order.add_edge(legal_verify, consensus_meeting)
root.order.add_edge(legal_verify, final_approval)
root.order.add_edge(legal_verify, artifact_release)
root.order.add_edge(ownership_confirm, compliance_audit)
root.order.add_edge(ownership_confirm, data_documentation)
root.order.add_edge(ownership_confirm, interim_report)
root.order.add_edge(ownership_confirm, department_review)
root.order.add_edge(ownership_confirm, consensus_meeting)
root.order.add_edge(ownership_confirm, final_approval)
root.order.add_edge(ownership_confirm, artifact_release)
root.order.add_edge(compliance_audit, data_documentation)
root.order.add_edge(compliance_audit, interim_report)
root.order.add_edge(compliance_audit, department_review)
root.order.add_edge(compliance_audit, consensus_meeting)
root.order.add_edge(compliance_audit, final_approval)
root.order.add_edge(compliance_audit, artifact_release)
root.order.add_edge(data_documentation, interim_report)
root.order.add_edge(data_documentation, department_review)
root.order.add_edge(data_documentation, consensus_meeting)
root.order.add_edge(data_documentation, final_approval)
root.order.add_edge(data_documentation, artifact_release)
root.order.add_edge(interim_report, department_review)
root.order.add_edge(interim_report, consensus_meeting)
root.order.add_edge(interim_report, final_approval)
root.order.add_edge(interim_report, artifact_release)
root.order.add_edge(department_review, consensus_meeting)
root.order.add_edge(department_review, final_approval)
root.order.add_edge(department_review, artifact_release)
root.order.add_edge(consensus_meeting, final_approval)
root.order.add_edge(consensus_meeting, artifact_release)
root.order.add_edge(final_approval, artifact_release)

print(root)