from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition

# Define each activity as a transition
site_survey = Transition(label='Site Survey')
design_layout = Transition(label='Design Layout')
install_modules = Transition(label='Install Modules')
calibrate_climate = Transition(label='Calibrate Climate')
prepare_nutrients = Transition(label='Prepare Nutrients')
select_seeds = Transition(label='Select Seeds')
start_germination = Transition(label='Start Germination')
deploy_sensors = Transition(label='Deploy Sensors')
monitor_growth = Transition(label='Monitor Growth')
manage_pests = Transition(label='Manage Pests')
schedule_harvest = Transition(label='Schedule Harvest')
process_waste = Transition(label='Process Waste')
optimize_energy = Transition(label='Optimize Energy')
conduct_training = Transition(label='Conduct Training')
update_records = Transition(label='Update Records')
review_performance = Transition(label='Review Performance')

# Define the partial order graph
root = StrictPartialOrder()

# Add the transitions to the partial order
root.add_transition(site_survey)
root.add_transition(design_layout)
root.add_transition(install_modules)
root.add_transition(calibrate_climate)
root.add_transition(prepare_nutrients)
root.add_transition(select_seeds)
root.add_transition(start_germination)
root.add_transition(deploy_sensors)
root.add_transition(monitor_growth)
root.add_transition(manage_pests)
root.add_transition(schedule_harvest)
root.add_transition(process_waste)
root.add_transition(optimize_energy)
root.add_transition(conduct_training)
root.add_transition(update_records)
root.add_transition(review_performance)

# Define the dependencies between the transitions
root.order.add_edge(site_survey, design_layout)
root.order.add_edge(design_layout, install_modules)
root.order.add_edge(install_modules, calibrate_climate)
root.order.add_edge(calibrate_climate, prepare_nutrients)
root.order.add_edge(prepare_nutrients, select_seeds)
root.order.add_edge(select_seeds, start_germination)
root.order.add_edge(start_germination, deploy_sensors)
root.order.add_edge(deploy_sensors, monitor_growth)
root.order.add_edge(monitor_growth, manage_pests)
root.order.add_edge(manage_pests, schedule_harvest)
root.order.add_edge(schedule_harvest, process_waste)
root.order.add_edge(process_waste, optimize_energy)
root.order.add_edge(optimize_energy, conduct_training)
root.order.add_edge(conduct_training, update_records)
root.order.add_edge(update_records, review_performance)