from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition

# Define transitions
send_notification = Transition(label='Send notification')
prepare_financial_statements = Transition(label='Prepare financial statements')
gather_necessary_documents = Transition(label='Gather necessary documents')
check_regulatory_updates = Transition(label='Check regulatory updates')
complete_risk_assessment = Transition(label='Complete risk assessment/mitigation')
evaluate_compliance_risks = Transition(label='Evaluate compliance risks')
evaluate_financial_risks = Transition(label='Evaluate financial risks')
evaluate_operational_risks = Transition(label='Evaluate operational risks')
conduct_data_analysis = Transition(label='Conduct data analysis')
conduct_interviews = Transition(label='Conduct interviews')
perform_site_visits = Transition(label='Perform site visits')
launch_detailed_investigation = Transition(label='Launch detailed investigation')
review_submission = Transition(label='Review submission')
send_report_for_revision = Transition(label='Send report for revision')
update_and_resubmit_report = Transition(label='Update and resubmit report')
compile_audit_report = Transition(label='Compile audit report')
review_report_by_audit_director = Transition(label='Review report by audit director')
approve_report = Transition(label='Approve report')
distribute_final_report = Transition(label='Distribute final report')
archive_report = Transition(label='Archive report')
close_audit_process = Transition(label='Close audit process')
request_clarifications = Transition(label='Request clarifications of discrepancies')
receive_clarifications = Transition(label='Receive clarifications')

# Define partial order
root = StrictPartialOrder(nodes=[send_notification, prepare_financial_statements, gather_necessary_documents, check_regulatory_updates, complete_risk_assessment, evaluate_compliance_risks, evaluate_financial_risks, evaluate_operational_risks, conduct_data_analysis, conduct_interviews, perform_site_visits, launch_detailed_investigation, review_submission, send_report_for_revision, update_and_resubmit_report, compile_audit_report, review_report_by_audit_director, approve_report, distribute_final_report, archive_report, close_audit_process, request_clarifications, receive_clarifications])

# Define order
root.order.add_edge(send_notification, prepare_financial_statements)
root.order.add_edge(send_notification, gather_necessary_documents)
root.order.add_edge(prepare_financial_statements, check_regulatory_updates)
root.order.add_edge(gather_necessary_documents, check_regulatory_updates)
root.order.add_edge(check_regulatory_updates, complete_risk_assessment)
root.order.add_edge(complete_risk_assessment, evaluate_compliance_risks)
root.order.add_edge(complete_risk_assessment, evaluate_financial_risks)
root.order.add_edge(complete_risk_assessment, evaluate_operational_risks)
root.order.add_edge(evaluate_compliance_risks, conduct_data_analysis)
root.order.add_edge(evaluate_compliance_risks, conduct_interviews)
root.order.add_edge(evaluate_compliance_risks, perform_site_visits)
root.order.add_edge(evaluate_financial_risks, conduct_data_analysis)
root.order.add_edge(evaluate_financial_risks, conduct_interviews)
root.order.add_edge(evaluate_financial_risks, perform_site_visits)
root.order.add_edge(evaluate_operational_risks, conduct_data_analysis)
root.order.add_edge(evaluate_operational_risks, conduct_interviews)
root.order.add_edge(evaluate_operational_risks, perform_site_visits)
root.order.add_edge(conduct_data_analysis, review_submission)
root.order.add_edge(conduct_interviews, review_submission)
root.order.add_edge(perform_site_visits, review_submission)
root.order.add_edge(review_submission, send_report_for_revision)
root.order.add_edge(send_report_for_revision, update_and_resubmit_report)
root.order.add_edge(update_and_resubmit_report, compile_audit_report)
root.order.add_edge(compile_audit_report, review_report_by_audit_director)
root.order.add_edge(review_report_by_audit_director, approve_report)
root.order.add_edge(approve_report, distribute_final_report)
root.order.add_edge(distribute_final_report, archive_report)
root.order.add_edge(archive_report, close_audit_process)
root.order.add_edge(approve_report, request_clarifications)
root.order.add_edge(request_clarifications, receive_clarifications)
root.order.add_edge(receive_clarifications, close_audit_process)