import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_analysis = Transition(label='Site Analysis')
load_test = Transition(label='Load Test')
sunlight_map = Transition(label='Sunlight Map')
medium_select = Transition(label='Medium Select')
hydro_design = Transition(label='Hydro Design')
procure_seeds = Transition(label='Procure Seeds')
install_irrigation = Transition(label='Install Irrigation')
setup_climate = Transition(label='Setup Climate')
create_schedule = Transition(label='Create Schedule')
pest_control = Transition(label='Pest Control')
monitor_growth = Transition(label='Monitor Growth')
adjust_systems = Transition(label='Adjust Systems')
harvest_crops = Transition(label='Harvest Crops')
package_produce = Transition(label='Package Produce')
engage_community = Transition(label='Engage Community')
host_workshops = Transition(label='Host Workshops')

root = StrictPartialOrder(nodes=[site_analysis, load_test, sunlight_map, medium_select, hydro_design, procure_seeds, install_irrigation, setup_climate, create_schedule, pest_control, monitor_growth, adjust_systems, harvest_crops, package_produce, engage_community, host_workshops])
root.order.add_edge(site_analysis, load_test)
root.order.add_edge(site_analysis, sunlight_map)
root.order.add_edge(site_analysis, medium_select)
root.order.add_edge(site_analysis, hydro_design)
root.order.add_edge(site_analysis, procure_seeds)
root.order.add_edge(site_analysis, install_irrigation)
root.order.add_edge(site_analysis, setup_climate)
root.order.add_edge(site_analysis, create_schedule)
root.order.add_edge(site_analysis, pest_control)
root.order.add_edge(site_analysis, monitor_growth)
root.order.add_edge(site_analysis, adjust_systems)
root.order.add_edge(site_analysis, harvest_crops)
root.order.add_edge(site_analysis, package_produce)
root.order.add_edge(site_analysis, engage_community)
root.order.add_edge(site_analysis, host_workshops)