from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

Milk_Collection = Transition(label='Milk Collection')
Culture_Prep = Transition(label='Culture Prep')
Curd_Formation = Transition(label='Curd Formation')
Whey_Separation = Transition(label='Whey Separation')
Molding_Cheese = Transition(label='Molding Cheese')
Salting_Process = Transition(label='Salting Process')
Initial_Aging = Transition(label='Initial Aging')
Humidity_Control = Transition(label='Humidity Control')
Temperature_Check = Transition(label='Temperature Check')
Flavor_Testing = Transition(label='Flavor Testing')
Final_Aging = Transition(label='Final Aging')
Packaging_Artisanal = Transition(label='Packaging Artisanal')
Label_Printing = Transition(label='Label Printing')
Inventory_Audit = Transition(label='Inventory Audit')
Order_Fulfillment = Transition(label='Order Fulfillment')
Subscription_Setup = Transition(label='Subscription Setup')
Event_Marketing = Transition(label='Event Marketing')

root = StrictPartialOrder(nodes=[Milk_Collection, Culture_Prep, Curd_Formation, Whey_Separation, Molding_Cheese, Salting_Process, Initial_Aging, Humidity_Control, Temperature_Check, Flavor_Testing, Final_Aging, Packaging_Artisanal, Label_Printing, Inventory_Audit, Order_Fulfillment, Subscription_Setup, Event_Marketing])
root.order.add_edge(Milk_Collection, Culture_Prep)
root.order.add_edge(Culture_Prep, Curd_Formation)
root.order.add_edge(Curd_Formation, Whey_Separation)
root.order.add_edge(Whey_Separation, Molding_Cheese)
root.order.add_edge(Molding_Cheese, Salting_Process)
root.order.add_edge(Salting_Process, Initial_Aging)
root.order.add_edge(Initial_Aging, Humidity_Control)
root.order.add_edge(Humidity_Control, Temperature_Check)
root.order.add_edge(Temperature_Check, Flavor_Testing)
root.order.add_edge(Flavor_Testing, Final_Aging)
root.order.add_edge(Final_Aging, Packaging_Artisanal)
root.order.add_edge(Packaging_Artisanal, Label_Printing)
root.order.add_edge(Label_Printing, Inventory_Audit)
root.order.add_edge(Inventory_Audit, Order_Fulfillment)
root.order.add_edge(Order_Fulfillment, Subscription_Setup)
root.order.add_edge(Subscription_Setup, Event_Marketing)