from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define each activity as a Transition
artifact_intake = Transition(label='Artifact Intake')
visual_scan = Transition(label='Visual Scan')
material_test = Transition(label='Material Test')
radiocarbon_check = Transition(label='Radiocarbon Check')
provenance_search = Transition(label='Provenance Search')
archive_review = Transition(label='Archive Review')
expert_consult = Transition(label='Expert Consult')
microscope_exam = Transition(label='Microscope Exam')
infrared_scan = Transition(label='Infrared Scan')
legal_verify = Transition(label='Legal Verify')
condition_report = Transition(label='Condition Report')
digital_catalog = Transition(label='Digital Catalog')
ownership_audit = Transition(label='Ownership Audit')
restoration_plan = Transition(label='Restoration Plan')
final_approval = Transition(label='Final Approval')
authentication_cert = Transition(label='Authentication Cert')

# Define the POWL model
root = StrictPartialOrder(
    nodes=[
        artifact_intake,
        visual_scan,
        material_test,
        radiocarbon_check,
        provenance_search,
        archive_review,
        expert_consult,
        microscope_exam,
        infrared_scan,
        legal_verify,
        condition_report,
        digital_catalog,
        ownership_audit,
        restoration_plan,
        final_approval,
        authentication_cert
    ],
    order=[
        (artifact_intake, visual_scan),
        (artifact_intake, material_test),
        (artifact_intake, radiocarbon_check),
        (artifact_intake, provenance_search),
        (artifact_intake, archive_review),
        (artifact_intake, expert_consult),
        (artifact_intake, microscope_exam),
        (artifact_intake, infrared_scan),
        (artifact_intake, legal_verify),
        (artifact_intake, condition_report),
        (artifact_intake, digital_catalog),
        (artifact_intake, ownership_audit),
        (artifact_intake, restoration_plan),
        (artifact_intake, final_approval),
        (artifact_intake, authentication_cert),
        (visual_scan, material_test),
        (visual_scan, radiocarbon_check),
        (visual_scan, provenance_search),
        (visual_scan, archive_review),
        (visual_scan, expert_consult),
        (visual_scan, microscope_exam),
        (visual_scan, infrared_scan),
        (visual_scan, legal_verify),
        (visual_scan, condition_report),
        (visual_scan, digital_catalog),
        (visual_scan, ownership_audit),
        (visual_scan, restoration_plan),
        (visual_scan, final_approval),
        (visual_scan, authentication_cert),
        (material_test, radiocarbon_check),
        (material_test, provenance_search),
        (material_test, archive_review),
        (material_test, expert_consult),
        (material_test, microscope_exam),
        (material_test, infrared_scan),
        (material_test, legal_verify),
        (material_test, condition_report),
        (material_test, digital_catalog),
        (material_test, ownership_audit),
        (material_test, restoration_plan),
        (material_test, final_approval),
        (material_test, authentication_cert),
        (radiocarbon_check, provenance_search),
        (radiocarbon_check, archive_review),
        (radiocarbon_check, expert_consult),
        (radiocarbon_check, microscope_exam),
        (radiocarbon_check, infrared_scan),
        (radiocarbon_check, legal_verify),
        (radiocarbon_check, condition_report),
        (radiocarbon_check, digital_catalog),
        (radiocarbon_check, ownership_audit),
        (radiocarbon_check, restoration_plan),
        (radiocarbon_check, final_approval),
        (radiocarbon_check, authentication_cert),
        (provenance_search, archive_review),
        (provenance_search, expert_consult),
        (provenance_search, microscope_exam),
        (provenance_search, infrared_scan),
        (provenance_search, legal_verify),
        (provenance_search, condition_report),
        (provenance_search, digital_catalog),
        (provenance_search, ownership_audit),
        (provenance_search, restoration_plan),
        (provenance_search, final_approval),
        (provenance_search, authentication_cert),
        (archive_review, expert_consult),
        (archive_review, microscope_exam),
        (archive_review, infrared_scan),
        (archive_review, legal_verify),
        (archive_review, condition_report),
        (archive_review, digital_catalog),
        (archive_review, ownership_audit),
        (archive_review, restoration_plan),
        (archive_review, final_approval),
        (archive_review, authentication_cert),
        (expert_consult, microscope_exam),
        (expert_consult, infrared_scan),
        (expert_consult, legal_verify),
        (expert_consult, condition_report),
        (expert_consult, digital_catalog),
        (expert_consult, ownership_audit),
        (expert_consult, restoration_plan),
        (expert_consult, final_approval),
        (expert_consult, authentication_cert),
        (microscope_exam, infrared_scan),
        (microscope_exam, legal_verify),
        (microscope_exam, condition_report),
        (microscope_exam, digital_catalog),
        (microscope_exam, ownership_audit),
        (microscope_exam, restoration_plan),
        (microscope_exam, final_approval),
        (microscope_exam, authentication_cert),
        (infrared_scan, legal_verify),
        (infrared_scan, condition_report),
        (infrared_scan, digital_catalog),
        (infrared_scan, ownership_audit),
        (infrared_scan, restoration_plan),
        (infrared_scan, final_approval),
        (infrared_scan, authentication_cert),
        (legal_verify, condition_report),
        (legal_verify, digital_catalog),
        (legal_verify, ownership_audit),
        (legal_verify, restoration_plan),
        (legal_verify, final_approval),
        (legal_verify, authentication_cert),
        (condition_report, digital_catalog),
        (condition_report, ownership_audit),
        (condition_report, restoration_plan),
        (condition_report, final_approval),
        (condition_report, authentication_cert),
        (digital_catalog, ownership_audit),
        (digital_catalog, restoration_plan),
        (digital_catalog, final_approval),
        (digital_catalog, authentication_cert),
        (ownership_audit, restoration_plan),
        (ownership_audit, final_approval),
        (ownership_audit, authentication_cert),
        (restoration_plan, final_approval),
        (restoration_plan, authentication_cert),
        (final_approval, authentication_cert)
    ]
)