import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define the POWL transitions
site_survey = Transition(label='Site Survey')
permit_check = Transition(label='Permit Check')
hive_setup = Transition(label='Hive Setup')
community_meet = Transition(label='Community Meet')
hive_monitor = Transition(label='Hive Monitor')
pest_control = Transition(label='Pest Control')
honey_harvest = Transition(label='Honey Harvest')
data_logging = Transition(label='Data Logging')
workshop_plan = Transition(label='Workshop Plan')
supply_order = Transition(label='Supply Order')
volunteer_coord = Transition(label='Volunteer Coord')
regulation_review = Transition(label='Regulation Review')
pollination_map = Transition(label='Pollination Map')
apiary_audit = Transition(label='Apiary Audit')
feedback_gather = Transition(label='Feedback Gather')
waste_manage = Transition(label='Waste Manage')

# Define the POWL operators
site_survey_to_permit_check = OperatorPOWL(operator=Operator.XOR, children=[site_survey, permit_check])
permit_check_to_hive_setup = OperatorPOWL(operator=Operator.XOR, children=[permit_check, hive_setup])
hive_setup_to_community_meet = OperatorPOWL(operator=Operator.XOR, children=[hive_setup, community_meet])
community_meet_to_hive_monitor = OperatorPOWL(operator=Operator.XOR, children=[community_meet, hive_monitor])
hive_monitor_to_pest_control = OperatorPOWL(operator=Operator.XOR, children=[hive_monitor, pest_control])
pest_control_to_honey_harvest = OperatorPOWL(operator=Operator.XOR, children=[pest_control, honey_harvest])
honey_harvest_to_data_logging = OperatorPOWL(operator=Operator.XOR, children=[honey_harvest, data_logging])
data_logging_to_workshop_plan = OperatorPOWL(operator=Operator.XOR, children=[data_logging, workshop_plan])
workshop_plan_to_supply_order = OperatorPOWL(operator=Operator.XOR, children=[workshop_plan, supply_order])
supply_order_to_volunteer_coord = OperatorPOWL(operator=Operator.XOR, children=[supply_order, volunteer_coord])
volunteer_coord_to_regulation_review = OperatorPOWL(operator=Operator.XOR, children=[volunteer_coord, regulation_review])
regulation_review_to_pollination_map = OperatorPOWL(operator=Operator.XOR, children=[regulation_review, pollination_map])
pollination_map_to_apiary_audit = OperatorPOWL(operator=Operator.XOR, children=[pollination_map, apiary_audit])
apiary_audit_to_feedback_gather = OperatorPOWL(operator=Operator.XOR, children=[apiary_audit, feedback_gather])
feedback_gather_to_waste_manage = OperatorPOWL(operator=Operator.XOR, children=[feedback_gather, waste_manage])

# Define the root POWL
root = StrictPartialOrder(nodes=[site_survey, permit_check, hive_setup, community_meet, hive_monitor, pest_control, honey_harvest, data_logging, workshop_plan, supply_order, volunteer_coord, regulation_review, pollination_map, apiary_audit, feedback_gather, waste_manage])
root.order.add_edge(site_survey, permit_check)
root.order.add_edge(permit_check, hive_setup)
root.order.add_edge(hive_setup, community_meet)
root.order.add_edge(community_meet, hive_monitor)
root.order.add_edge(hive_monitor, pest_control)
root.order.add_edge(pest_control, honey_harvest)
root.order.add_edge(honey_harvest, data_logging)
root.order.add_edge(data_logging, workshop_plan)
root.order.add_edge(workshop_plan, supply_order)
root.order.add_edge(supply_order, volunteer_coord)
root.order.add_edge(volunteer_coord, regulation_review)
root.order.add_edge(regulation_review, pollination_map)
root.order.add_edge(pollination_map, apiary_audit)
root.order.add_edge(apiary_audit, feedback_gather)
root.order.add_edge(feedback_gather, waste_manage)