import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

provenance_check = Transition(label='Provenance Check')
material_testing = Transition(label='Material Testing')
expert_review = Transition(label='Expert Review')
legal_verify = Transition(label='Legal Verify')
risk_assess = Transition(label='Risk Assess')
insurance_quote = Transition(label='Insurance Quote')
catalog_entry = Transition(label='Catalog Entry')
digital_scan = Transition(label='Digital Scan')
condition_report = Transition(label='Condition Report')
transport_plan = Transition(label='Transport Plan')
customs_clear = Transition(label='Customs Clear')
certification = Transition(label='Certification')
exhibit_setup = Transition(label='Exhibit Setup')
owner_notify = Transition(label='Owner Notify')
final_audit = Transition(label='Final Audit')

# Define the workflow
root = StrictPartialOrder(nodes=[provenance_check, material_testing, expert_review, legal_verify, risk_assess, insurance_quote, catalog_entry, digital_scan, condition_report, transport_plan, customs_clear, certification, exhibit_setup, owner_notify, final_audit])

# Define dependencies between activities
root.order.add_edge(provenance_check, material_testing)
root.order.add_edge(provenance_check, expert_review)
root.order.add_edge(provenance_check, legal_verify)
root.order.add_edge(provenance_check, risk_assess)
root.order.add_edge(provenance_check, insurance_quote)
root.order.add_edge(provenance_check, catalog_entry)
root.order.add_edge(provenance_check, digital_scan)
root.order.add_edge(provenance_check, condition_report)
root.order.add_edge(provenance_check, transport_plan)
root.order.add_edge(provenance_check, customs_clear)
root.order.add_edge(provenance_check, certification)
root.order.add_edge(provenance_check, exhibit_setup)
root.order.add_edge(provenance_check, owner_notify)
root.order.add_edge(provenance_check, final_audit)

root.order.add_edge(material_testing, expert_review)
root.order.add_edge(material_testing, legal_verify)
root.order.add_edge(material_testing, risk_assess)
root.order.add_edge(material_testing, insurance_quote)
root.order.add_edge(material_testing, catalog_entry)
root.order.add_edge(material_testing, digital_scan)
root.order.add_edge(material_testing, condition_report)
root.order.add_edge(material_testing, transport_plan)
root.order.add_edge(material_testing, customs_clear)
root.order.add_edge(material_testing, certification)
root.order.add_edge(material_testing, exhibit_setup)
root.order.add_edge(material_testing, owner_notify)
root.order.add_edge(material_testing, final_audit)

root.order.add_edge(expert_review, legal_verify)
root.order.add_edge(expert_review, risk_assess)
root.order.add_edge(expert_review, insurance_quote)
root.order.add_edge(expert_review, catalog_entry)
root.order.add_edge(expert_review, digital_scan)
root.order.add_edge(expert_review, condition_report)
root.order.add_edge(expert_review, transport_plan)
root.order.add_edge(expert_review, customs_clear)
root.order.add_edge(expert_review, certification)
root.order.add_edge(expert_review, exhibit_setup)
root.order.add_edge(expert_review, owner_notify)
root.order.add_edge(expert_review, final_audit)

root.order.add_edge(legal_verify, risk_assess)
root.order.add_edge(legal_verify, insurance_quote)
root.order.add_edge(legal_verify, catalog_entry)
root.order.add_edge(legal_verify, digital_scan)
root.order.add_edge(legal_verify, condition_report)
root.order.add_edge(legal_verify, transport_plan)
root.order.add_edge(legal_verify, customs_clear)
root.order.add_edge(legal_verify, certification)
root.order.add_edge(legal_verify, exhibit_setup)
root.order.add_edge(legal_verify, owner_notify)
root.order.add_edge(legal_verify, final_audit)

root.order.add_edge(risk_assess, insurance_quote)
root.order.add_edge(risk_assess, catalog_entry)
root.order.add_edge(risk_assess, digital_scan)
root.order.add_edge(risk_assess, condition_report)
root.order.add_edge(risk_assess, transport_plan)
root.order.add_edge(risk_assess, customs_clear)
root.order.add_edge(risk_assess, certification)
root.order.add_edge(risk_assess, exhibit_setup)
root.order.add_edge(risk_assess, owner_notify)
root.order.add_edge(risk_assess, final_audit)

root.order.add_edge(insurance_quote, catalog_entry)
root.order.add_edge(insurance_quote, digital_scan)
root.order.add_edge(insurance_quote, condition_report)
root.order.add_edge(insurance_quote, transport_plan)
root.order.add_edge(insurance_quote, customs_clear)
root.order.add_edge(insurance_quote, certification)
root.order.add_edge(insurance_quote, exhibit_setup)
root.order.add_edge(insurance_quote, owner_notify)
root.order.add_edge(insurance_quote, final_audit)

root.order.add_edge(catalog_entry, digital_scan)
root.order.add_edge(catalog_entry, condition_report)
root.order.add_edge(catalog_entry, transport_plan)
root.order.add_edge(catalog_entry, customs_clear)
root.order.add_edge(catalog_entry, certification)
root.order.add_edge(catalog_entry, exhibit_setup)
root.order.add_edge(catalog_entry, owner_notify)
root.order.add_edge(catalog_entry, final_audit)

root.order.add_edge(digital_scan, condition_report)
root.order.add_edge(digital_scan, transport_plan)
root.order.add_edge(digital_scan, customs_clear)
root.order.add_edge(digital_scan, certification)
root.order.add_edge(digital_scan, exhibit_setup)
root.order.add_edge(digital_scan, owner_notify)
root.order.add_edge(digital_scan, final_audit)

root.order.add_edge(condition_report, transport_plan)
root.order.add_edge(condition_report, customs_clear)
root.order.add_edge(condition_report, certification)
root.order.add_edge(condition_report, exhibit_setup)
root.order.add_edge(condition_report, owner_notify)
root.order.add_edge(condition_report, final_audit)

root.order.add_edge(transport_plan, customs_clear)
root.order.add_edge(transport_plan, certification)
root.order.add_edge(transport_plan, exhibit_setup)
root.order.add_edge(transport_plan, owner_notify)
root.order.add_edge(transport_plan, final_audit)

root.order.add_edge(customs_clear, certification)
root.order.add_edge(customs_clear, exhibit_setup)
root.order.add_edge(customs_clear, owner_notify)
root.order.add_edge(customs_clear, final_audit)

root.order.add_edge(certification, exhibit_setup)
root.order.add_edge(certification, owner_notify)
root.order.add_edge(certification, final_audit)

root.order.add_edge(exhibit_setup, owner_notify)
root.order.add_edge(exhibit_setup, final_audit)

root.order.add_edge(owner_notify, final_audit)