import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

farm_selection = Transition(label='Farm Selection')
milk_testing = Transition(label='Milk Testing')
batch_pasteurize = Transition(label='Batch Pasteurize')
culture_add = Transition(label='Culture Add')
curd_cut = Transition(label='Curd Cut')
whey_drain = Transition(label='Whey Drain')
mold_inoculate = Transition(label='Mold Inoculate')
press_form = Transition(label='Press Form')
salt_rub = Transition(label='Salt Rub')
aging_monitor = Transition(label='Aging Monitor')
flavor_adjust = Transition(label='Flavor Adjust')
packaging_design = Transition(label='Packaging Design')
label_approval = Transition(label='Label Approval')
order_processing = Transition(label='Order Processing')
cold_storage = Transition(label='Cold Storage')
delivery_schedule = Transition(label='Delivery Schedule')
retail_setup = Transition(label='Retail Setup')
feedback_collect = Transition(label='Feedback Collect')
skip = SilentTransition()

# Define the POWL model
farm_to_milk_testing = OperatorPOWL(operator=Operator.LOOP, children=[farm_selection, milk_testing])
milk_testing_to_batch_pasteurize = OperatorPOWL(operator=Operator.LOOP, children=[milk_testing, batch_pasteurize])
batch_pasteurize_to_culture_add = OperatorPOWL(operator=Operator.LOOP, children=[batch_pasteurize, culture_add])
culture_add_to_curd_cut = OperatorPOWL(operator=Operator.LOOP, children=[culture_add, curd_cut])
curd_cut_to_whey_drain = OperatorPOWL(operator=Operator.LOOP, children=[curd_cut, whey_drain])
whey_drain_to_mold_inoculate = OperatorPOWL(operator=Operator.LOOP, children=[whey_drain, mold_inoculate])
mold_inoculate_to_press_form = OperatorPOWL(operator=Operator.LOOP, children=[mold_inoculate, press_form])
press_form_to_salt_rub = OperatorPOWL(operator=Operator.LOOP, children=[press_form, salt_rub])
salt_rub_to_aging_monitor = OperatorPOWL(operator=Operator.LOOP, children=[salt_rub, aging_monitor])
aging_monitor_to_flavor_adjust = OperatorPOWL(operator=Operator.LOOP, children=[aging_monitor, flavor_adjust])
flavor_adjust_to_packaging_design = OperatorPOWL(operator=Operator.LOOP, children=[flavor_adjust, packaging_design])
packaging_design_to_label_approval = OperatorPOWL(operator=Operator.LOOP, children=[packaging_design, label_approval])
label_approval_to_order_processing = OperatorPOWL(operator=Operator.LOOP, children=[label_approval, order_processing])
order_processing_to_cold_storage = OperatorPOWL(operator=Operator.LOOP, children=[order_processing, cold_storage])
cold_storage_to_delivery_schedule = OperatorPOWL(operator=Operator.LOOP, children=[cold_storage, delivery_schedule])
delivery_schedule_to_retail_setup = OperatorPOWL(operator=Operator.LOOP, children=[delivery_schedule, retail_setup])
retail_setup_to_feedback_collect = OperatorPOWL(operator=Operator.LOOP, children=[retail_setup, feedback_collect])

root = StrictPartialOrder(nodes=[farm_to_milk_testing, milk_testing_to_batch_pasteurize, batch_pasteurize_to_culture_add, culture_add_to_curd_cut, curd_cut_to_whey_drain, whey_drain_to_mold_inoculate, mold_inoculate_to_press_form, press_form_to_salt_rub, salt_rub_to_aging_monitor, aging_monitor_to_flavor_adjust, flavor_adjust_to_packaging_design, packaging_design_to_label_approval, label_approval_to_order_processing, order_processing_to_cold_storage, cold_storage_to_delivery_schedule, delivery_schedule_to_retail_setup, retail_setup_to_feedback_collect])
root.order.add_edge(farm_to_milk_testing, milk_testing_to_batch_pasteurize)
root.order.add_edge(milk_testing_to_batch_pasteurize, batch_pasteurize_to_culture_add)
root.order.add_edge(batch_pasteurize_to_culture_add, culture_add_to_curd_cut)
root.order.add_edge(culture_add_to_curd_cut, curd_cut_to_whey_drain)
root.order.add_edge(curd_cut_to_whey_drain, whey_drain_to_mold_inoculate)
root.order.add_edge(whey_drain_to_mold_inoculate, mold_inoculate_to_press_form)
root.order.add_edge(mold_inoculate_to_press_form, press_form_to_salt_rub)
root.order.add_edge(press_form_to_salt_rub, salt_rub_to_aging_monitor)
root.order.add_edge(salt_rub_to_aging_monitor, aging_monitor_to_flavor_adjust)
root.order.add_edge(aging_monitor_to_flavor_adjust, flavor_adjust_to_packaging_design)
root.order.add_edge(flavor_adjust_to_packaging_design, packaging_design_to_label_approval)
root.order.add_edge(packaging_design_to_label_approval, label_approval_to_order_processing)
root.order.add_edge(label_approval_to_order_processing, order_processing_to_cold_storage)
root.order.add_edge(order_processing_to_cold_storage, cold_storage_to_delivery_schedule)
root.order.add_edge(cold_storage_to_delivery_schedule, delivery_schedule_to_retail_setup)
root.order.add_edge(delivery_schedule_to_retail_setup, retail_setup_to_feedback_collect)