import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

initial_assess = Transition(label='Initial Assess')
disassemble_parts = Transition(label='Disassemble Parts')
ultrasonic_clean = Transition(label='Ultrasonic Clean')
inspect_components = Transition(label='Inspect Components')
fabricate_gears = Transition(label='Fabricate Gears')
dial_restoration = Transition(label='Dial Restoration')
repaint_markers = Transition(label='Repaint Markers')
reassemble_movement = Transition(label='Reassemble Movement')
lubricate_bearings = Transition(label='Lubricate Bearings')
calibrate_timing = Transition(label='Calibrate Timing')
polish_case = Transition(label='Polish Case')
re_case_watch = Transition(label='Re-case Watch')
quality_testing = Transition(label='Quality Testing')
document_process = Transition(label='Document Process')
package_product = Transition(label='Package Product')

skip = SilentTransition()

loop1 = OperatorPOWL(operator=Operator.LOOP, children=[fabricate_gears, inspect_components])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[dial_restoration, repaint_markers])
loop3 = OperatorPOWL(operator=Operator.LOOP, children=[reassemble_movement, lubricate_bearings, calibrate_timing])
loop4 = OperatorPOWL(operator=Operator.LOOP, children=[polish_case, re_case_watch])
xor1 = OperatorPOWL(operator=Operator.XOR, children=[quality_testing, document_process])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[package_product, skip])

root = StrictPartialOrder(nodes=[initial_assess, disassemble_parts, ultrasonic_clean, loop1, inspect_components, fabricate_gears, loop2, dial_restoration, loop3, repaint_markers, loop4, polish_case, re_case_watch, quality_testing, document_process, xor1, xor2])
root.order.add_edge(initial_assess, disassemble_parts)
root.order.add_edge(disassemble_parts, ultrasonic_clean)
root.order.add_edge(ultrasonic_clean, loop1)
root.order.add_edge(loop1, inspect_components)
root.order.add_edge(inspect_components, fabricate_gears)
root.order.add_edge(fabricate_gears, loop2)
root.order.add_edge(loop2, dial_restoration)
root.order.add_edge(dial_restoration, loop3)
root.order.add_edge(loop3, repaint_markers)
root.order.add_edge(repaint_markers, loop4)
root.order.add_edge(loop4, polish_case)
root.order.add_edge(polish_case, re_case_watch)
root.order.add_edge(re_case_watch, quality_testing)
root.order.add_edge(quality_testing, document_process)
root.order.add_edge(document_process, xor1)
root.order.add_edge(xor1, package_product)
root.order.add_edge(package_product, xor2)