import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

permit_securing = Transition(label='Permit Securing')
structure_check = Transition(label='Structure Check')
soil_testing = Transition(label='Soil Testing')
water_analysis = Transition(label='Water Analysis')
material_sourcing = Transition(label='Material Sourcing')
planter_setup = Transition(label='Planter Setup')
sensor_install = Transition(label='Sensor Install')
irrigation_setup = Transition(label='Irrigation Setup')
vendor_liaison = Transition(label='Vendor Liaison')
staff_training = Transition(label='Staff Training')
pest_control = Transition(label='Pest Control')
produce_marketing = Transition(label='Produce Marketing')
crop_rotation = Transition(label='Crop Rotation')
health_audit = Transition(label='Health Audit')
waste_composting = Transition(label='Waste Composting')

skip = SilentTransition()

permit_check = OperatorPOWL(operator=Operator.XOR, children=[permit_securing, skip])
structure = OperatorPOWL(operator=Operator.XOR, children=[structure_check, skip])
soil = OperatorPOWL(operator=Operator.XOR, children=[soil_testing, skip])
water = OperatorPOWL(operator=Operator.XOR, children=[water_analysis, skip])
materials = OperatorPOWL(operator=Operator.XOR, children=[material_sourcing, skip])
planter = OperatorPOWL(operator=Operator.XOR, children=[planter_setup, skip])
sensor = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, skip])
irrigation = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, skip])
vendor = OperatorPOWL(operator=Operator.XOR, children=[vendor_liaison, skip])
staff = OperatorPOWL(operator=Operator.XOR, children=[staff_training, skip])
pest = OperatorPOWL(operator=Operator.XOR, children=[pest_control, skip])
produce = OperatorPOWL(operator=Operator.XOR, children=[produce_marketing, skip])
crop = OperatorPOWL(operator=Operator.XOR, children=[crop_rotation, skip])
health = OperatorPOWL(operator=Operator.XOR, children=[health_audit, skip])
waste = OperatorPOWL(operator=Operator.XOR, children=[waste_composting, skip])

root = StrictPartialOrder(nodes=[permit_check, structure, soil, water, materials, planter, sensor, irrigation, vendor, staff, pest, produce, crop, health, waste])
root.order.add_edge(permit_check, structure)
root.order.add_edge(structure, soil)
root.order.add_edge(soil, water)
root.order.add_edge(water, materials)
root.order.add_edge(materials, planter)
root.order.add_edge(planter, sensor)
root.order.add_edge(sensor, irrigation)
root.order.add_edge(irrigation, vendor)
root.order.add_edge(vendor, staff)
root.order.add_edge(staff, pest)
root.order.add_edge(pest, produce)
root.order.add_edge(produce, crop)
root.order.add_edge(crop, health)
root.order.add_edge(health, waste)