import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
ingredient_sourcing = Transition(label='Ingredient Sourcing')
botanical_extraction = Transition(label='Botanical Extraction')
initial_blending = Transition(label='Initial Blending')
sensory_testing = Transition(label='Sensory Testing')
chemical_analysis = Transition(label='Chemical Analysis')
recipe_refinement = Transition(label='Recipe Refinement')
stability_check = Transition(label='Stability Check')
client_sampling = Transition(label='Client Sampling')
feedback_review = Transition(label='Feedback Review')
final_adjustment = Transition(label='Final Adjustment')
custom_packaging = Transition(label='Custom Packaging')
label_design = Transition(label='Label Design')
hand_labeling = Transition(label='Hand Labeling')
regulatory_audit = Transition(label='Regulatory Audit')
batch_documentation = Transition(label='Batch Documentation')
limited_release = Transition(label='Limited Release')
market_launch = Transition(label='Market Launch')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[ingredient_sourcing, botanical_extraction, initial_blending])
xor = OperatorPOWL(operator=Operator.XOR, children=[sensory_testing, chemical_analysis])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[recipe_refinement, stability_check])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[client_sampling, feedback_review])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[final_adjustment, custom_packaging])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[label_design, hand_labeling])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[regulatory_audit, batch_documentation])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[limited_release, market_launch])
root = StrictPartialOrder(nodes=[loop, xor, xor2, xor3, xor4, xor5, xor6, xor7])
root.order.add_edge(loop, xor)
root.order.add_edge(xor, xor2)
root.order.add_edge(xor2, xor3)
root.order.add_edge(xor3, xor4)
root.order.add_edge(xor4, xor5)
root.order.add_edge(xor5, xor6)
root.order.add_edge(xor6, xor7)