from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define the transitions for each activity
source_materials = Transition(label='Source Materials')
vet_suppliers = Transition(label='Vet Suppliers')
design_modules = Transition(label='Design Modules')
prototype_build = Transition(label='Prototype Build')
test_durability = Transition(label='Test Durability')
secure_permits = Transition(label='Secure Permits')
map_habitats = Transition(label='Map Habitats')
micro_warehouse = Transition(label='Micro Warehouse')
inventory_sync = Transition(label='Inventory Sync')
pack_sustainably = Transition(label='Pack Sustainably')
route_optimize = Transition(label='Route Optimize')
engage_community = Transition(label='Engage Community')
collect_feedback = Transition(label='Collect Feedback')
adjust_production = Transition(label='Adjust Production')
partner_ngos = Transition(label='Partner NGOs')
launch_campaign = Transition(label='Launch Campaign')
monitor_sensors = Transition(label='Monitor Sensors')
report_impact = Transition(label='Report Impact')

# Define the partial order model
root = StrictPartialOrder()

# Define the dependencies between the activities
root.add_transition(source_materials)
root.add_transition(vet_suppliers)
root.add_transition(design_modules)
root.add_transition(prototype_build)
root.add_transition(test_durability)
root.add_transition(secure_permits)
root.add_transition(map_habitats)
root.add_transition(micro_warehouse)
root.add_transition(inventory_sync)
root.add_transition(pack_sustainably)
root.add_transition(route_optimize)
root.add_transition(engage_community)
root.add_transition(collect_feedback)
root.add_transition(adjust_production)
root.add_transition(partner_ngos)
root.add_transition(launch_campaign)
root.add_transition(monitor_sensors)
root.add_transition(report_impact)

# Define the partial order dependencies
root.order.add_edge(source_materials, vet_suppliers)
root.order.add_edge(vet_suppliers, design_modules)
root.order.add_edge(design_modules, prototype_build)
root.order.add_edge(prototype_build, test_durability)
root.order.add_edge(test_durability, secure_permits)
root.order.add_edge(secure_permits, map_habitats)
root.order.add_edge(map_habitats, micro_warehouse)
root.order.add_edge(micro_warehouse, inventory_sync)
root.order.add_edge(inventory_sync, pack_sustainably)
root.order.add_edge(pack_sustainably, route_optimize)
root.order.add_edge(route_optimize, engage_community)
root.order.add_edge(engage_community, collect_feedback)
root.order.add_edge(collect_feedback, adjust_production)
root.order.add_edge(adjust_production, partner_ngos)
root.order.add_edge(partner_ngos, launch_campaign)
root.order.add_edge(launch_campaign, monitor_sensors)
root.order.add_edge(monitor_sensors, report_impact)