from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition

# Define the POWL model
A = Transition(label='Site Select')
B = Transition(label='Env Assess')
C = Transition(label='Design Modules')
D = Transition(label='Hydroponics Setup')
E = Transition(label='Software Dev')
F = Transition(label='Seed Choose')
G = Transition(label='LED Install')
H = Transition(label='Train Staff')
I = Transition(label='Compliance Check')
J = Transition(label='Engage Community')
K = Transition(label='Plant Crops')
L = Transition(label='Monitor Growth')
M = Transition(label='Optimize Yields')
N = Transition(label='Waste Manage')
O = Transition(label='Energy Audit')
P = Transition(label='Water Recycle')
root = StrictPartialOrder(nodes=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P])
root.order.add_edge(A, B)
root.order.add_edge(B, C)
root.order.add_edge(C, D)
root.order.add_edge(D, E)
root.order.add_edge(E, F)
root.order.add_edge(F, G)
root.order.add_edge(G, H)
root.order.add_edge(H, I)
root.order.add_edge(I, J)
root.order.add_edge(J, K)
root.order.add_edge(K, L)
root.order.add_edge(L, M)
root.order.add_edge(M, N)
root.order.add_edge(N, O)
root.order.add_edge(O, P)