import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

artifact_intake = Transition(label='Artifact Intake')
initial_survey = Transition(label='Initial Survey')
material_test = Transition(label='Material Test')
historical_check = Transition(label='Historical Check')
registry_search = Transition(label='Registry Search')
owner_interview = Transition(label='Owner Interview')
condition_report = Transition(label='Condition Report')
forgeries_scan = Transition(label='Forgery Scan')
digital_tagging = Transition(label='Digital Tagging')
ledger_entry = Transition(label='Ledger Entry')
expert_review = Transition(label='Expert Review')
legal_verify = Transition(label='Legal Verify')
provenance_draft = Transition(label='Provenance Draft')
client_approval = Transition(label='Client Approval')
final_certificate = Transition(label='Final Certificate')
archive_storage = Transition(label='Archive Storage')

skip = SilentTransition()

artifact_flow = OperatorPOWL(operator=Operator.XOR, children=[artifact_intake, skip])
initial_survey_flow = OperatorPOWL(operator=Operator.XOR, children=[initial_survey, skip])
material_test_flow = OperatorPOWL(operator=Operator.XOR, children=[material_test, skip])
historical_check_flow = OperatorPOWL(operator=Operator.XOR, children=[historical_check, skip])
registry_search_flow = OperatorPOWL(operator=Operator.XOR, children=[registry_search, skip])
owner_interview_flow = OperatorPOWL(operator=Operator.XOR, children=[owner_interview, skip])
condition_report_flow = OperatorPOWL(operator=Operator.XOR, children=[condition_report, skip])
forgeries_scan_flow = OperatorPOWL(operator=Operator.XOR, children=[forgeries_scan, skip])
digital_tagging_flow = OperatorPOWL(operator=Operator.XOR, children=[digital_tagging, skip])
ledger_entry_flow = OperatorPOWL(operator=Operator.XOR, children=[ledger_entry, skip])
expert_review_flow = OperatorPOWL(operator=Operator.XOR, children=[expert_review, skip])
legal_verify_flow = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, skip])
provenance_draft_flow = OperatorPOWL(operator=Operator.XOR, children=[provenance_draft, skip])
client_approval_flow = OperatorPOWL(operator=Operator.XOR, children=[client_approval, skip])
final_certificate_flow = OperatorPOWL(operator=Operator.XOR, children=[final_certificate, skip])
archive_storage_flow = OperatorPOWL(operator=Operator.XOR, children=[archive_storage, skip])

root = StrictPartialOrder(nodes=[artifact_flow, initial_survey_flow, material_test_flow, historical_check_flow, registry_search_flow, owner_interview_flow, condition_report_flow, forgeries_scan_flow, digital_tagging_flow, ledger_entry_flow, expert_review_flow, legal_verify_flow, provenance_draft_flow, client_approval_flow, final_certificate_flow, archive_storage_flow])
root.order.add_edge(artifact_flow, initial_survey_flow)
root.order.add_edge(initial_survey_flow, material_test_flow)
root.order.add_edge(material_test_flow, historical_check_flow)
root.order.add_edge(historical_check_flow, registry_search_flow)
root.order.add_edge(registry_search_flow, owner_interview_flow)
root.order.add_edge(owner_interview_flow, condition_report_flow)
root.order.add_edge(condition_report_flow, forgeries_scan_flow)
root.order.add_edge(forgeries_scan_flow, digital_tagging_flow)
root.order.add_edge(digital_tagging_flow, ledger_entry_flow)
root.order.add_edge(ledger_entry_flow, expert_review_flow)
root.order.add_edge(expert_review_flow, legal_verify_flow)
root.order.add_edge(legal_verify_flow, provenance_draft_flow)
root.order.add_edge(provenance_draft_flow, client_approval_flow)
root.order.add_edge(client_approval_flow, final_certificate_flow)
root.order.add_edge(final_certificate_flow, archive_storage_flow)