import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

milk_sourcing = Transition(label='Milk Sourcing')
diet_monitoring = Transition(label='Diet Monitoring')
culture_selection = Transition(label='Culture Selection')
milk_pasteurize = Transition(label='Milk Pasteurize')
curd_cutting = Transition(label='Curd Cutting')
whey_draining = Transition(label='Whey Draining')
mold_inoculate = Transition(label='Mold Inoculate')
press_forming = Transition(label='Press Forming')
salt_application = Transition(label='Salt Application')
aging_setup = Transition(label='Aging Setup')
humidity_control = Transition(label='Humidity Control')
flavor_testing = Transition(label='Flavor Testing')
packaging_design = Transition(label='Packaging Design')
order_processing = Transition(label='Order Processing')
retail_delivery = Transition(label='Retail Delivery')
event_coordination = Transition(label='Event Coordination')
feedback_review = Transition(label='Feedback Review')

skip = SilentTransition()

milk_sourcing_to_diet_monitoring = OperatorPOWL(operator=Operator.XOR, children=[milk_sourcing, diet_monitoring])
diet_monitoring_to_culture_selection = OperatorPOWL(operator=Operator.XOR, children=[diet_monitoring, culture_selection])
culture_selection_to_milk_pasteurize = OperatorPOWL(operator=Operator.XOR, children=[culture_selection, milk_pasteurize])
milk_pasteurize_to_curd_cutting = OperatorPOWL(operator=Operator.XOR, children=[milk_pasteurize, curd_cutting])
curd_cutting_to_whey_draining = OperatorPOWL(operator=Operator.XOR, children=[curd_cutting, whey_draining])
whey_draining_to_mold_inoculate = OperatorPOWL(operator=Operator.XOR, children=[whey_draining, mold_inoculate])
mold_inoculate_to_press_forming = OperatorPOWL(operator=Operator.XOR, children=[mold_inoculate, press_forming])
press_forming_to_salt_application = OperatorPOWL(operator=Operator.XOR, children=[press_forming, salt_application])
salt_application_to_aging_setup = OperatorPOWL(operator=Operator.XOR, children=[salt_application, aging_setup])
aging_setup_to_humidity_control = OperatorPOWL(operator=Operator.XOR, children=[aging_setup, humidity_control])
humidity_control_to_flavor_testing = OperatorPOWL(operator=Operator.XOR, children=[humidity_control, flavor_testing])
flavor_testing_to_packaging_design = OperatorPOWL(operator=Operator.XOR, children=[flavor_testing, packaging_design])
packaging_design_to_order_processing = OperatorPOWL(operator=Operator.XOR, children=[packaging_design, order_processing])
order_processing_to_retail_delivery = OperatorPOWL(operator=Operator.XOR, children=[order_processing, retail_delivery])
retail_delivery_to_event_coordination = OperatorPOWL(operator=Operator.XOR, children=[retail_delivery, event_coordination])
event_coordination_to_feedback_review = OperatorPOWL(operator=Operator.XOR, children=[event_coordination, feedback_review])

root = StrictPartialOrder(nodes=[milk_sourcing_to_diet_monitoring, diet_monitoring_to_culture_selection, culture_selection_to_milk_pasteurize, milk_pasteurize_to_curd_cutting, curd_cutting_to_whey_draining, whey_draining_to_mold_inoculate, mold_inoculate_to_press_forming, press_forming_to_salt_application, salt_application_to_aging_setup, aging_setup_to_humidity_control, humidity_control_to_flavor_testing, flavor_testing_to_packaging_design, packaging_design_to_order_processing, order_processing_to_retail_delivery, retail_delivery_to_event_coordination, event_coordination_to_feedback_review])
root.order.add_edge(milk_sourcing_to_diet_monitoring, diet_monitoring_to_culture_selection)
root.order.add_edge(diet_monitoring_to_culture_selection, culture_selection_to_milk_pasteurize)
root.order.add_edge(culture_selection_to_milk_pasteurize, milk_pasteurize_to_curd_cutting)
root.order.add_edge(milk_pasteurize_to_curd_cutting, curd_cutting_to_whey_draining)
root.order.add_edge(curd_cutting_to_whey_draining, whey_draining_to_mold_inoculate)
root.order.add_edge(whey_draining_to_mold_inoculate, mold_inoculate_to_press_forming)
root.order.add_edge(mold_inoculate_to_press_forming, press_forming_to_salt_application)
root.order.add_edge(press_forming_to_salt_application, salt_application_to_aging_setup)
root.order.add_edge(salt_application_to_aging_setup, aging_setup_to_humidity_control)
root.order.add_edge(aging_setup_to_humidity_control, humidity_control_to_flavor_testing)
root.order.add_edge(humidity_control_to_flavor_testing, flavor_testing_to_packaging_design)
root.order.add_edge(flavor_testing_to_packaging_design, packaging_design_to_order_processing)
root.order.add_edge(packaging_design_to_order_processing, order_processing_to_retail_delivery)
root.order.add_edge(order_processing_to_retail_delivery, retail_delivery_to_event_coordination)
root.order.add_edge(retail_delivery_to_event_coordination, event_coordination_to_feedback_review)