from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition

# Define the activities
risk_assess = Transition(label='Risk Assess')
source_alternatives = Transition(label='Source Alternatives')
supplier_audit = Transition(label='Supplier Audit')
contract_review = Transition(label='Contract Review')
regulation_check = Transition(label='Regulation Check')
inventory_scan = Transition(label='Inventory Scan')
logistics_reroute = Transition(label='Logistics Reroute')
customs_notify = Transition(label='Customs Notify')
stakeholder_alert = Transition(label='Stakeholder Alert')
data_analyze = Transition(label='Data Analyze')
cost_forecast = Transition(label='Cost Forecast')
compliance_verify = Transition(label='Compliance Verify')
scenario_plan = Transition(label='Scenario Plan')
decision_gate = Transition(label='Decision Gate')
feedback_loop = Transition(label='Feedback Loop')
report_generate = Transition(label='Report Generate')
market_monitor = Transition(label='Market Monitor')
team_sync = Transition(label='Team Sync')

# Define the process
xor1 = OperatorPOWL(operator=Operator.XOR, children=[source_alternatives, supplier_audit])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[contract_review, regulation_check])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[inventory_scan, logistics_reroute])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[customs_notify, stakeholder_alert])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[data_analyze, cost_forecast])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[compliance_verify, scenario_plan])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[decision_gate, feedback_loop])
xor8 = OperatorPOWL(operator=Operator.XOR, children=[report_generate, market_monitor])
xor9 = OperatorPOWL(operator=Operator.XOR, children=[team_sync, risk_assess])

root = StrictPartialOrder(nodes=[xor1, xor2, xor3, xor4, xor5, xor6, xor7, xor8, xor9])
root.order.add_edge(xor1, xor2)
root.order.add_edge(xor2, xor3)
root.order.add_edge(xor3, xor4)
root.order.add_edge(xor4, xor5)
root.order.add_edge(xor5, xor6)
root.order.add_edge(xor6, xor7)
root.order.add_edge(xor7, xor8)
root.order.add_edge(xor8, xor9)
root.order.add_edge(xor9, xor1)