import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define activities
artifact_receipt = Transition(label='Artifact Receipt')
initial_inspection = Transition(label='Initial Inspection')
material_testing = Transition(label='Material Testing')
provenance_check = Transition(label='Provenance Check')
digital_imaging = Transition(label='Digital Imaging')
database_search = Transition(label='Database Search')
expert_consult = Transition(label='Expert Consult')
legal_review = Transition(label='Legal Review')
cultural_audit = Transition(label='Cultural Audit')
condition_report = Transition(label='Condition Report')
risk_assessment = Transition(label='Risk Assessment')
insurance_setup = Transition(label='Insurance Setup')
transport_plan = Transition(label='Transport Plan')
final_certification = Transition(label='Final Certification')
archive_entry = Transition(label='Archive Entry')
publication_prep = Transition(label='Publication Prep')

# Define the POWL model
artifact_receipt_node = StrictPartialOrder(nodes=[artifact_receipt])
initial_inspection_node = StrictPartialOrder(nodes=[initial_inspection])
material_testing_node = StrictPartialOrder(nodes=[material_testing])
provenance_check_node = StrictPartialOrder(nodes=[provenance_check])
digital_imaging_node = StrictPartialOrder(nodes=[digital_imaging])
database_search_node = StrictPartialOrder(nodes=[database_search])
expert_consult_node = StrictPartialOrder(nodes=[expert_consult])
legal_review_node = StrictPartialOrder(nodes=[legal_review])
cultural_audit_node = StrictPartialOrder(nodes=[cultural_audit])
condition_report_node = StrictPartialOrder(nodes=[condition_report])
risk_assessment_node = StrictPartialOrder(nodes=[risk_assessment])
insurance_setup_node = StrictPartialOrder(nodes=[insurance_setup])
transport_plan_node = StrictPartialOrder(nodes=[transport_plan])
final_certification_node = StrictPartialOrder(nodes=[final_certification])
archive_entry_node = StrictPartialOrder(nodes=[archive_entry])
publication_prep_node = StrictPartialOrder(nodes=[publication_prep])

# Define the partial order
root = StrictPartialOrder()
root.order.add_edge(artifact_receipt_node, initial_inspection_node)
root.order.add_edge(initial_inspection_node, material_testing_node)
root.order.add_edge(material_testing_node, provenance_check_node)
root.order.add_edge(provenance_check_node, digital_imaging_node)
root.order.add_edge(digital_imaging_node, database_search_node)
root.order.add_edge(database_search_node, expert_consult_node)
root.order.add_edge(expert_consult_node, legal_review_node)
root.order.add_edge(legal_review_node, cultural_audit_node)
root.order.add_edge(cultural_audit_node, condition_report_node)
root.order.add_edge(condition_report_node, risk_assessment_node)
root.order.add_edge(risk_assessment_node, insurance_setup_node)
root.order.add_edge(insurance_setup_node, transport_plan_node)
root.order.add_edge(transport_plan_node, final_certification_node)
root.order.add_edge(final_certification_node, archive_entry_node)
root.order.add_edge(archive_entry_node, publication_prep_node)

print(root)