import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define the activities
site_survey = Transition(label='Site Survey')
structural_audit = Transition(label='Structural Audit')
climate_design = Transition(label='Climate Design')
lighting_setup = Transition(label='Lighting Setup')
irrigation_plan = Transition(label='Irrigation Plan')
nutrient_mix = Transition(label='Nutrient Mix')
sensor_install = Transition(label='Sensor Install')
ai_calibration = Transition(label='AI Calibration')
pest_scan = Transition(label='Pest Scan')
energy_audit = Transition(label='Energy Audit')
renewable_sync = Transition(label='Renewable Sync')
data_modeling = Transition(label='Data Modeling')
staff_briefing = Transition(label='Staff Briefing')
compliance_check = Transition(label='Compliance Check')
community_meet = Transition(label='Community Meet')
yield_review = Transition(label='Yield Review')
feedback_loop = Transition(label='Feedback Loop')

# Define the process
site_survey_node = OperatorPOWL(operator=Operator.FORK, children=[structural_audit])
structural_audit_node = OperatorPOWL(operator=Operator.XOR, children=[climate_design, lighting_setup])
climate_design_node = OperatorPOWL(operator=Operator.XOR, children=[irrigation_plan, nutrient_mix])
lighting_setup_node = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, ai_calibration])
irrigation_plan_node = OperatorPOWL(operator=Operator.XOR, children=[pest_scan, energy_audit])
nutrient_mix_node = OperatorPOWL(operator=Operator.XOR, children=[renewable_sync, data_modeling])
sensor_install_node = OperatorPOWL(operator=Operator.XOR, children=[staff_briefing, compliance_check])
ai_calibration_node = OperatorPOWL(operator=Operator.XOR, children=[community_meet, yield_review])
pest_scan_node = OperatorPOWL(operator=Operator.XOR, children=[feedback_loop, site_survey])
energy_audit_node = OperatorPOWL(operator=Operator.XOR, children=[site_survey, structural_audit])
renewable_sync_node = OperatorPOWL(operator=Operator.XOR, children=[climate_design, lighting_setup])
data_modeling_node = OperatorPOWL(operator=Operator.XOR, children=[irrigation_plan, nutrient_mix])
staff_briefing_node = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, ai_calibration])
compliance_check_node = OperatorPOWL(operator=Operator.XOR, children=[pest_scan, energy_audit])
community_meet_node = OperatorPOWL(operator=Operator.XOR, children=[renewable_sync, data_modeling])
yield_review_node = OperatorPOWL(operator=Operator.XOR, children=[staff_briefing, compliance_check])
feedback_loop_node = OperatorPOWL(operator=Operator.XOR, children=[community_meet, yield_review])

# Define the partial order
root = StrictPartialOrder(nodes=[site_survey_node, structural_audit_node, climate_design_node, lighting_setup_node, irrigation_plan_node, nutrient_mix_node, sensor_install_node, ai_calibration_node, pest_scan_node, energy_audit_node, renewable_sync_node, data_modeling_node, staff_briefing_node, compliance_check_node, community_meet_node, yield_review_node, feedback_loop_node])
root.order.add_edge(site_survey_node, structural_audit_node)
root.order.add_edge(structural_audit_node, climate_design_node)
root.order.add_edge(structural_audit_node, lighting_setup_node)
root.order.add_edge(climate_design_node, irrigation_plan_node)
root.order.add_edge(climate_design_node, nutrient_mix_node)
root.order.add_edge(lighting_setup_node, sensor_install_node)
root.order.add_edge(lighting_setup_node, ai_calibration_node)
root.order.add_edge(pest_scan_node, feedback_loop_node)
root.order.add_edge(pest_scan_node, energy_audit_node)
root.order.add_edge(energy_audit_node, renewable_sync_node)
root.order.add_edge(energy_audit_node, data_modeling_node)
root.order.add_edge(sensor_install_node, staff_briefing_node)
root.order.add_edge(sensor_install_node, compliance_check_node)
root.order.add_edge(ai_calibration_node, community_meet_node)
root.order.add_edge(ai_calibration_node, yield_review_node)
root.order.add_edge(site_survey_node, pest_scan_node)
root.order.add_edge(site_survey_node, energy_audit_node)
root.order.add_edge(climate_design_node, renewable_sync_node)
root.order.add_edge(climate_design_node, data_modeling_node)
root.order.add_edge(lighting_setup_node, staff_briefing_node)
root.order.add_edge(lighting_setup_node, compliance_check_node)
root.order.add_edge(pest_scan_node, community_meet_node)
root.order.add_edge(pest_scan_node, yield_review_node)