from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define the activities
milk_sourcing = Transition(label='Milk Sourcing')
quality_testing = Transition(label='Quality Testing')
curd_processing = Transition(label='Curd Processing')
salt_application = Transition(label='Salt Application')
mold_inoculation = Transition(label='Mold Inoculation')
press_molding = Transition(label='Press Molding')
brine_soaking = Transition(label='Brine Soaking')
aging_setup = Transition(label='Aging Setup')
humidity_control = Transition(label='Humidity Control')
microbial_check = Transition(label='Microbial Check')
packaging_design = Transition(label='Packaging Design')
label_printing = Transition(label='Label Printing')
trace_logging = Transition(label='Trace Logging')
distribution_plan = Transition(label='Distribution Plan')
customer_review = Transition(label='Customer Review')
inventory_audit = Transition(label='Inventory Audit')
sustainability_audit = Transition(label='Sustainability Audit')

# Define the process flow
milk_sourcing_to_quality_testing = OperatorPOWL(operator=Operator.XOR, children=[milk_sourcing, quality_testing])
quality_testing_to_curd_processing = OperatorPOWL(operator=Operator.XOR, children=[quality_testing, curd_processing])
curd_processing_to_salt_application = OperatorPOWL(operator=Operator.XOR, children=[curd_processing, salt_application])
salt_application_to_mold_inoculation = OperatorPOWL(operator=Operator.XOR, children=[salt_application, mold_inoculation])
mold_inoculation_to_press_molding = OperatorPOWL(operator=Operator.XOR, children=[mold_inoculation, press_molding])
press_molding_to_brine_soaking = OperatorPOWL(operator=Operator.XOR, children=[press_molding, brine_soaking])
brine_soaking_to_aging_setup = OperatorPOWL(operator=Operator.XOR, children=[brine_soaking, aging_setup])
aging_setup_to_humidity_control = OperatorPOWL(operator=Operator.XOR, children=[aging_setup, humidity_control])
humidity_control_to_microbial_check = OperatorPOWL(operator=Operator.XOR, children=[humidity_control, microbial_check])
microbial_check_to_packaging_design = OperatorPOWL(operator=Operator.XOR, children=[microbial_check, packaging_design])
packaging_design_to_label_printing = OperatorPOWL(operator=Operator.XOR, children=[packaging_design, label_printing])
label_printing_to_trace_logging = OperatorPOWL(operator=Operator.XOR, children=[label_printing, trace_logging])
trace_logging_to_distribution_plan = OperatorPOWL(operator=Operator.XOR, children=[trace_logging, distribution_plan])
distribution_plan_to_customer_review = OperatorPOWL(operator=Operator.XOR, children=[distribution_plan, customer_review])
customer_review_to_inventory_audit = OperatorPOWL(operator=Operator.XOR, children=[customer_review, inventory_audit])
inventory_audit_to_sustainability_audit = OperatorPOWL(operator=Operator.XOR, children=[inventory_audit, sustainability_audit])

# Create the root POWL model
root = StrictPartialOrder(nodes=[milk_sourcing_to_quality_testing, quality_testing_to_curd_processing, curd_processing_to_salt_application, salt_application_to_mold_inoculation, mold_inoculation_to_press_molding, press_molding_to_brine_soaking, brine_soaking_to_aging_setup, aging_setup_to_humidity_control, humidity_control_to_microbial_check, microbial_check_to_packaging_design, packaging_design_to_label_printing, label_printing_to_trace_logging, trace_logging_to_distribution_plan, distribution_plan_to_customer_review, customer_review_to_inventory_audit, inventory_audit_to_sustainability_audit])
root.order.add_edge(milk_sourcing_to_quality_testing, quality_testing_to_curd_processing)
root.order.add_edge(quality_testing_to_curd_processing, curd_processing_to_salt_application)
root.order.add_edge(curd_processing_to_salt_application, salt_application_to_mold_inoculation)
root.order.add_edge(salt_application_to_mold_inoculation, mold_inoculation_to_press_molding)
root.order.add_edge(mold_inoculation_to_press_molding, press_molding_to_brine_soaking)
root.order.add_edge(press_molding_to_brine_soaking, brine_soaking_to_aging_setup)
root.order.add_edge(brine_soaking_to_aging_setup, aging_setup_to_humidity_control)
root.order.add_edge(aging_setup_to_humidity_control, humidity_control_to_microbial_check)
root.order.add_edge(humidity_control_to_microbial_check, microbial_check_to_packaging_design)
root.order.add_edge(microbial_check_to_packaging_design, packaging_design_to_label_printing)
root.order.add_edge(packaging_design_to_label_printing, label_printing_to_trace_logging)
root.order.add_edge(label_printing_to_trace_logging, trace_logging_to_distribution_plan)
root.order.add_edge(trace_logging_to_distribution_plan, distribution_plan_to_customer_review)
root.order.add_edge(distribution_plan_to_customer_review, customer_review_to_inventory_audit)
root.order.add_edge(customer_review_to_inventory_audit, inventory_audit_to_sustainability_audit)