import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
A = Transition(label='Site Survey')
B = Transition(label='Structural Audit')
C = Transition(label='Permit Filing')
D = Transition(label='Design Layout')
E = Transition(label='Install HVAC')
F = Transition(label='Set Lighting')
G = Transition(label='Build Racks')
H = Transition(label='Install Hydroponics')
I = Transition(label='Configure Sensors')
J = Transition(label='Select Crops')
K = Transition(label='Seed Planting')
L = Transition(label='Monitor Growth')
M = Transition(label='Nutrient Mixing')
N = Transition(label='Staff Training')
O = Transition(label='Market Launch')
P = Transition(label='Waste Recycling')
Q = Transition(label='Customer Onboarding')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)