from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_survey = Transition(label='Site Survey')
load_test = Transition(label='Load Test')
soil_sample = Transition(label='Soil Sample')
crop_select = Transition(label='Crop Select')
irrigation_plan = Transition(label='Irrigation Plan')
permit_apply = Transition(label='Permit Apply')
material_order = Transition(label='Material Order')
bed_install = Transition(label='Bed Install')
pest_control = Transition(label='Pest Control')
solar_setup = Transition(label='Solar Setup')
staff_train = Transition(label='Staff Train')
market_outreach = Transition(label='Market Outreach')
system_setup = Transition(label='System Setup')
supplier_contact = Transition(label='Supplier Contact')
health_monitor = Transition(label='Health Monitor')

skip = SilentTransition()

site_survey_choice = OperatorPOWL(operator=Operator.XOR, children=[site_survey, load_test])
soil_sample_choice = OperatorPOWL(operator=Operator.XOR, children=[soil_sample, skip])
crop_select_choice = OperatorPOWL(operator=Operator.XOR, children=[crop_select, skip])
irrigation_plan_choice = OperatorPOWL(operator=Operator.XOR, children=[irrigation_plan, skip])
permit_apply_choice = OperatorPOWL(operator=Operator.XOR, children=[permit_apply, skip])
material_order_choice = OperatorPOWL(operator=Operator.XOR, children=[material_order, skip])
bed_install_choice = OperatorPOWL(operator=Operator.XOR, children=[bed_install, skip])
pest_control_choice = OperatorPOWL(operator=Operator.XOR, children=[pest_control, skip])
solar_setup_choice = OperatorPOWL(operator=Operator.XOR, children=[solar_setup, skip])
staff_train_choice = OperatorPOWL(operator=Operator.XOR, children=[staff_train, skip])
market_outreach_choice = OperatorPOWL(operator=Operator.XOR, children=[market_outreach, skip])
system_setup_choice = OperatorPOWL(operator=Operator.XOR, children=[system_setup, skip])
supplier_contact_choice = OperatorPOWL(operator=Operator.XOR, children=[supplier_contact, skip])
health_monitor_choice = OperatorPOWL(operator=Operator.XOR, children=[health_monitor, skip])

root = StrictPartialOrder(nodes=[site_survey_choice, soil_sample_choice, crop_select_choice, irrigation_plan_choice, permit_apply_choice, material_order_choice, bed_install_choice, pest_control_choice, solar_setup_choice, staff_train_choice, market_outreach_choice, system_setup_choice, supplier_contact_choice, health_monitor_choice])
root.order.add_edge(site_survey_choice, soil_sample_choice)
root.order.add_edge(soil_sample_choice, crop_select_choice)
root.order.add_edge(crop_select_choice, irrigation_plan_choice)
root.order.add_edge(irrigation_plan_choice, permit_apply_choice)
root.order.add_edge(permit_apply_choice, material_order_choice)
root.order.add_edge(material_order_choice, bed_install_choice)
root.order.add_edge(bed_install_choice, pest_control_choice)
root.order.add_edge(pest_control_choice, solar_setup_choice)
root.order.add_edge(solar_setup_choice, staff_train_choice)
root.order.add_edge(staff_train_choice, market_outreach_choice)
root.order.add_edge(market_outreach_choice, system_setup_choice)
root.order.add_edge(system_setup_choice, supplier_contact_choice)
root.order.add_edge(supplier_contact_choice, health_monitor_choice)