from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition

# Define activities
milk_sourcing = Transition(label='Milk Sourcing')
culture_prep = Transition(label='Culture Prep')
milk_pasturize = Transition(label='Milk Pasteurize')
coagulation = Transition(label='Coagulation')
curd_cutting = Transition(label='Curd Cutting')
whey_draining = Transition(label='Whey Draining')
hand_molding = Transition(label='Hand Molding')
pressing = Transition(label='Pressing')
salting = Transition(label='Salting')
rind_treatment = Transition(label='Rind Treatment')
aging_setup = Transition(label='Aging Setup')
microclimate_control = Transition(label='Microclimate Control')
flavor_profiling = Transition(label='Flavor Profiling')
quality_check = Transition(label='Quality Check')
sensory_review = Transition(label='Sensory Review')
texture_inspect = Transition(label='Texture Inspect')
eco_packaging = Transition(label='Eco Packaging')
batch_labeling = Transition(label='Batch Labeling')
blockchain_log = Transition(label='Blockchain Log')
niche_shipping = Transition(label='Niche Shipping')

# Define partial order
root = StrictPartialOrder(nodes=[milk_sourcing, culture_prep, milk_pasturize, coagulation, curd_cutting, whey_draining, hand_molding, pressing, salting, rind_treatment, aging_setup, microclimate_control, flavor_profiling, quality_check, sensory_review, texture_inspect, eco_packaging, batch_labeling, blockchain_log, niche_shipping])

# Define dependencies
root.order.add_edge(milk_sourcing, culture_prep)
root.order.add_edge(milk_sourcing, milk_pasturize)
root.order.add_edge(milk_sourcing, coagulation)
root.order.add_edge(milk_sourcing, curd_cutting)
root.order.add_edge(milk_sourcing, whey_draining)
root.order.add_edge(milk_sourcing, hand_molding)
root.order.add_edge(milk_sourcing, pressing)
root.order.add_edge(milk_sourcing, salting)
root.order.add_edge(milk_sourcing, rind_treatment)
root.order.add_edge(milk_sourcing, aging_setup)
root.order.add_edge(milk_sourcing, microclimate_control)
root.order.add_edge(milk_sourcing, flavor_profiling)
root.order.add_edge(milk_sourcing, quality_check)
root.order.add_edge(milk_sourcing, sensory_review)
root.order.add_edge(milk_sourcing, texture_inspect)
root.order.add_edge(milk_sourcing, eco_packaging)
root.order.add_edge(milk_sourcing, batch_labeling)
root.order.add_edge(milk_sourcing, blockchain_log)
root.order.add_edge(milk_sourcing, niche_shipping)

root.order.add_edge(culture_prep, milk_pasturize)
root.order.add_edge(culture_prep, coagulation)
root.order.add_edge(culture_prep, curd_cutting)
root.order.add_edge(culture_prep, whey_draining)
root.order.add_edge(culture_prep, hand_molding)
root.order.add_edge(culture_prep, pressing)
root.order.add_edge(culture_prep, salting)
root.order.add_edge(culture_prep, rind_treatment)
root.order.add_edge(culture_prep, aging_setup)
root.order.add_edge(culture_prep, microclimate_control)
root.order.add_edge(culture_prep, flavor_profiling)
root.order.add_edge(culture_prep, quality_check)
root.order.add_edge(culture_prep, sensory_review)
root.order.add_edge(culture_prep, texture_inspect)
root.order.add_edge(culture_prep, eco_packaging)
root.order.add_edge(culture_prep, batch_labeling)
root.order.add_edge(culture_prep, blockchain_log)
root.order.add_edge(culture_prep, niche_shipping)

root.order.add_edge(milk_pasturize, coagulation)
root.order.add_edge(milk_pasturize, curd_cutting)
root.order.add_edge(milk_pasturize, whey_draining)
root.order.add_edge(milk_pasturize, hand_molding)
root.order.add_edge(milk_pasturize, pressing)
root.order.add_edge(milk_pasturize, salting)
root.order.add_edge(milk_pasturize, rind_treatment)
root.order.add_edge(milk_pasturize, aging_setup)
root.order.add_edge(milk_pasturize, microclimate_control)
root.order.add_edge(milk_pasturize, flavor_profiling)
root.order.add_edge(milk_pasturize, quality_check)
root.order.add_edge(milk_pasturize, sensory_review)
root.order.add_edge(milk_pasturize, texture_inspect)
root.order.add_edge(milk_pasturize, eco_packaging)
root.order.add_edge(milk_pasturize, batch_labeling)
root.order.add_edge(milk_pasturize, blockchain_log)
root.order.add_edge(milk_pasturize, niche_shipping)

root.order.add_edge(coagulation, curd_cutting)
root.order.add_edge(coagulation, whey_draining)
root.order.add_edge(coagulation, hand_molding)
root.order.add_edge(coagulation, pressing)
root.order.add_edge(coagulation, salting)
root.order.add_edge(coagulation, rind_treatment)
root.order.add_edge(coagulation, aging_setup)
root.order.add_edge(coagulation, microclimate_control)
root.order.add_edge(coagulation, flavor_profiling)
root.order.add_edge(coagulation, quality_check)
root.order.add_edge(coagulation, sensory_review)
root.order.add_edge(coagulation, texture_inspect)
root.order.add_edge(coagulation, eco_packaging)
root.order.add_edge(coagulation, batch_labeling)
root.order.add_edge(coagulation, blockchain_log)
root.order.add_edge(coagulation, niche_shipping)

root.order.add_edge(curd_cutting, whey_draining)
root.order.add_edge(curd_cutting, hand_molding)
root.order.add_edge(curd_cutting, pressing)
root.order.add_edge(curd_cutting, salting)
root.order.add_edge(curd_cutting, rind_treatment)
root.order.add_edge(curd_cutting, aging_setup)
root.order.add_edge(curd_cutting, microclimate_control)
root.order.add_edge(curd_cutting, flavor_profiling)
root.order.add_edge(curd_cutting, quality_check)
root.order.add_edge(curd_cutting, sensory_review)
root.order.add_edge(curd_cutting, texture_inspect)
root.order.add_edge(curd_cutting, eco_packaging)
root.order.add_edge(curd_cutting, batch_labeling)
root.order.add_edge(curd_cutting, blockchain_log)
root.order.add_edge(curd_cutting, niche_shipping)

root.order.add_edge(whey_draining, hand_molding)
root.order.add_edge(whey_draining, pressing)
root.order.add_edge(whey_draining, salting)
root.order.add_edge(whey_draining, rind_treatment)
root.order.add_edge(whey_draining, aging_setup)
root.order.add_edge(whey_draining, microclimate_control)
root.order.add_edge(whey_draining, flavor_profiling)
root.order.add_edge(whey_draining, quality_check)
root.order.add_edge(whey_draining, sensory_review)
root.order.add_edge(whey_draining, texture_inspect)
root.order.add_edge(whey_draining, eco_packaging)
root.order.add_edge(whey_draining, batch_labeling)
root.order.add_edge(whey_draining, blockchain_log)
root.order.add_edge(whey_draining, niche_shipping)

root.order.add_edge(hand_molding, pressing)
root.order.add_edge(hand_molding, salting)
root.order.add_edge(hand_molding, rind_treatment)
root.order.add_edge(hand_molding, aging_setup)
root.order.add_edge(hand_molding, microclimate_control)
root.order.add_edge(hand_molding, flavor_profiling)
root.order.add_edge(hand_molding, quality_check)
root.order.add_edge(hand_molding, sensory_review)
root.order.add_edge(hand_molding, texture_inspect)
root.order.add_edge(hand_molding, eco_packaging)
root.order.add_edge(hand_molding, batch_labeling)
root.order.add_edge(hand_molding, blockchain_log)
root.order.add_edge(hand_molding, niche_shipping)

root.order.add_edge(pressing, salting)
root.order.add_edge(pressing, rind_treatment)
root.order.add_edge(pressing, aging_setup)
root.order.add_edge(pressing, microclimate_control)
root.order.add_edge(pressing, flavor_profiling)
root.order.add_edge(pressing, quality_check)
root.order.add_edge(pressing, sensory_review)
root.order.add_edge(pressing, texture_inspect)
root.order.add_edge(pressing, eco_packaging)
root.order.add_edge(pressing, batch_labeling)
root.order.add_edge(pressing, blockchain_log)
root.order.add_edge(pressing, niche_shipping)

root.order.add_edge(salting, rind_treatment)
root.order.add_edge(salting, aging_setup)
root.order.add_edge(salting, microclimate_control)
root.order.add_edge(salting, flavor_profiling)
root.order.add_edge(salting, quality_check)
root.order.add_edge(salting, sensory_review)
root.order.add_edge(salting, texture_inspect)
root.order.add_edge(salting, eco_packaging)
root.order.add_edge(salting, batch_labeling)
root.order.add_edge(salting, blockchain_log)
root.order.add_edge(salting, niche_shipping)

root.order.add_edge(rind_treatment, aging_setup)
root.order.add_edge(rind_treatment, microclimate_control)
root.order.add_edge(rind_treatment, flavor_profiling)
root.order.add_edge(rind_treatment, quality_check)
root.order.add_edge(rind_treatment, sensory_review)
root.order.add_edge(rind_treatment, texture_inspect)
root.order.add_edge(rind_treatment, eco_packaging)
root.order.add_edge(rind_treatment, batch_labeling)
root.order.add_edge(rind_treatment, blockchain_log)
root.order.add_edge(rind_treatment, niche_shipping)

root.order.add_edge(aging_setup, microclimate_control)
root.order.add_edge(aging_setup, flavor_profiling)
root.order.add_edge(aging_setup, quality_check)
root.order.add_edge(aging_setup, sensory_review)
root.order.add_edge(aging_setup, texture_inspect)
root.order.add_edge(aging_setup, eco_packaging)
root.order.add_edge(aging_setup, batch_labeling)
root.order.add_edge(aging_setup, blockchain_log)
root.order.add_edge(aging_setup, niche_shipping)

root.order.add_edge(microclimate_control, flavor_profiling)
root.order.add_edge(microclimate_control, quality_check)
root.order.add_edge(microclimate_control, sensory_review)
root.order.add_edge(microclimate_control, texture_inspect)
root.order.add_edge(microclimate_control, eco_packaging)
root.order.add_edge(microclimate_control, batch_labeling)
root.order.add_edge(microclimate_control, blockchain_log)
root.order.add_edge(microclimate_control, niche_shipping)

root.order.add_edge(flavor_profiling, quality_check)
root.order.add_edge(flavor_profiling, sensory_review)
root.order.add_edge(flavor_profiling, texture_inspect)
root.order.add_edge(flavor_profiling, eco_packaging)
root.order.add_edge(flavor_profiling, batch_labeling)
root.order.add_edge(flavor_profiling, blockchain_log)
root.order.add_edge(flavor_profiling, niche_shipping)

root.order.add_edge(quality_check, sensory_review)
root.order.add_edge(quality_check, texture_inspect)
root.order.add_edge(quality_check, eco_packaging)
root.order.add_edge(quality_check, batch_labeling)
root.order.add_edge(quality_check, blockchain_log)
root.order.add_edge(quality_check, niche_shipping)

root.order.add_edge(sensory_review, texture_inspect)
root.order.add_edge(sensory_review, eco_packaging)
root.order.add_edge(sensory_review, batch_labeling)
root.order.add_edge(sensory_review, blockchain_log)
root.order.add_edge(sensory_review, niche_shipping)

root.order.add_edge(texture_inspect, eco_packaging)
root.order.add_edge(texture_inspect, batch_labeling)
root.order.add_edge(texture_inspect, blockchain_log)
root.order.add_edge(texture_inspect, niche_shipping)

root.order.add_edge(eco_packaging, batch_labeling)
root.order.add_edge(eco_packaging, blockchain_log)
root.order.add_edge(eco_packaging, niche_shipping)

root.order.add_edge(batch_labeling, blockchain_log)
root.order.add_edge(batch_labeling, niche_shipping)

root.order.add_edge(blockchain_log, niche_shipping)