import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define activities
milk_sourcing = Transition(label='Milk Sourcing')
culture_selection = Transition(label='Culture Selection')
milk_testing = Transition(label='Milk Testing')
curd_formation = Transition(label='Curd Formation')
whey_separation = Transition(label='Whey Separation')
molding_cheese = Transition(label='Molding Cheese')
salting_process = Transition(label='Salting Process')
aging_setup = Transition(label='Aging Setup')
env_monitoring = Transition(label='Env Monitoring')
flavor_profiling = Transition(label='Flavor Profiling')
packaging_design = Transition(label='Packaging Design')
blockchain_entry = Transition(label='Blockchain Entry')
quality_audit = Transition(label='Quality Audit')
retail_sync = Transition(label='Retail Sync')
transport_prep = Transition(label='Transport Prep')
delivery_tracking = Transition(label='Delivery Tracking')
customer_feedback = Transition(label='Customer Feedback')

# Define the POWL model
xor1 = OperatorPOWL(operator=Operator.XOR, children=[aging_setup, env_monitoring])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[flavor_profiling, packaging_design])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[blockchain_entry, quality_audit])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[retail_sync, transport_prep])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[delivery_tracking, customer_feedback])
root = StrictPartialOrder(nodes=[milk_sourcing, culture_selection, milk_testing, curd_formation, whey_separation, molding_cheese, salting_process, xor1, xor2, xor3, xor4, xor5])
root.order.add_edge(milk_sourcing, culture_selection)
root.order.add_edge(milk_sourcing, milk_testing)
root.order.add_edge(milk_testing, curd_formation)
root.order.add_edge(curd_formation, whey_separation)
root.order.add_edge(whey_separation, molding_cheese)
root.order.add_edge(molding_cheese, salting_process)
root.order.add_edge(salting_process, xor1)
root.order.add_edge(salting_process, xor2)
root.order.add_edge(aging_setup, env_monitoring)
root.order.add_edge(flavor_profiling, packaging_design)
root.order.add_edge(blockchain_entry, quality_audit)
root.order.add_edge(retail_sync, transport_prep)
root.order.add_edge(transport_prep, delivery_tracking)
root.order.add_edge(delivery_tracking, customer_feedback)