from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition

client_brief = Transition(label='Client Brief')
spec_analysis = Transition(label='Spec Analysis')
material_sourcing = Transition(label='Material Sourcing')
component_vetting = Transition(label='Component Vetting')
frame_assembly = Transition(label='Frame Assembly')
sensor_install = Transition(label='Sensor Install')
propulsion_setup = Transition(label='Propulsion Setup')
calibration = Transition(label='Calibration')
software_load = Transition(label='Software Load')
flight_test = Transition(label='Flight Test')
ai_training = Transition(label='AI Training')
qa_review = Transition(label='QA Review')
mission_pack = Transition(label='Mission Pack')
client_training = Transition(label='Client Training')
deployment_support = Transition(label='Deployment Support')

xor1 = OperatorPOWL(operator=Operator.XOR, children=[spec_analysis, material_sourcing])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[component_vetting, frame_assembly])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, propulsion_setup])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[calibration, software_load])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[flight_test, ai_training])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[qa_review, mission_pack])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[client_training, deployment_support])

loop1 = OperatorPOWL(operator=Operator.LOOP, children=[xor1, xor2])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[xor3, xor4])
loop3 = OperatorPOWL(operator=Operator.LOOP, children=[xor5, xor6])
loop4 = OperatorPOWL(operator=Operator.LOOP, children=[xor7, client_brief])

root = StrictPartialOrder(nodes=[loop1, loop2, loop3, loop4])
root.order.add_edge(loop1, loop2)
root.order.add_edge(loop2, loop3)
root.order.add_edge(loop3, loop4)
root.order.add_edge(loop4, client_brief)