from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition

A = Transition(label='Site Survey')
B = Transition(label='Structure Check')
C = Transition(label='Hydroponic Install')
D = Transition(label='Lighting Setup')
E = Transition(label='Climate Control')
F = Transition(label='Seed Selection')
G = Transition(label='Nutrient Mix')
H = Transition(label='Water Recycling')
I = Transition(label='Sensor Deploy')
J = Transition(label='Pest Control')
K = Transition(label='Growth Monitor')
L = Transition(label='Harvest Plan')
M = Transition(label='Packaging Prep')
N = Transition(label='Delivery Route')
O = Transition(label='Data Analysis')
P = Transition(label='Yield Forecast')
Q = SilentTransition()
R = SilentTransition()

loop1 = OperatorPOWL(operator=Operator.LOOP, children=[A, B])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[C, D, E])
loop3 = OperatorPOWL(operator=Operator.LOOP, children=[F, G, H, I, J])
loop4 = OperatorPOWL(operator=Operator.LOOP, children=[K, L, M, N, O, P])

xor1 = OperatorPOWL(operator=Operator.XOR, children=[Q, R])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[xor1, xor1])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[xor2, xor2])

root = StrictPartialOrder(nodes=[loop1, loop2, loop3, loop4, xor3])
root.order.add_edge(loop1, loop2)
root.order.add_edge(loop2, loop3)
root.order.add_edge(loop3, loop4)
root.order.add_edge(loop4, xor3)
root.order.add_edge(xor3, xor3)