import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define the activities
site_survey = Transition(label='Site Survey')
design_layout = Transition(label='Design Layout')
system_assembly = Transition(label='System Assembly')
climate_setup = Transition(label='Climate Setup')
light_calibration = Transition(label='Light Calibration')
seed_selection = Transition(label='Seed Selection')
seedling_prep = Transition(label='Seedling Prep')
nutrient_mix = Transition(label='Nutrient Mix')
irrigation_setup = Transition(label='Irrigation Setup')
sensor_install = Transition(label='Sensor Install')
data_integration = Transition(label='Data Integration')
waste_routing = Transition(label='Waste Routing')
energy_audit = Transition(label='Energy Audit')
regulation_check = Transition(label='Regulation Check')
operational_test = Transition(label='Operational Test')
community_outreach = Transition(label='Community Outreach')

# Define the control flow operators
xor1 = OperatorPOWL(operator=Operator.XOR, children=[regulation_check, community_outreach])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[operational_test, xor1])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[nutrient_mix, xor2])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor3])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor4])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor5])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor6])
xor8 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor7])
xor9 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor8])
xor10 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor9])
xor11 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor10])
xor12 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor11])
xor13 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor12])
xor14 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor13])
xor15 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor14])
xor16 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor15])
xor17 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor16])
xor18 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor17])
xor19 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor18])
xor20 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor19])
xor21 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor20])
xor22 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor21])
xor23 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor22])
xor24 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor23])
xor25 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor24])
xor26 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor25])
xor27 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor26])
xor28 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor27])
xor29 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor28])
xor30 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor29])
xor31 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor30])
xor32 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor31])
xor33 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor32])
xor34 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor33])
xor35 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor34])
xor36 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor35])
xor37 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor36])
xor38 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor37])
xor39 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor38])
xor40 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor39])
xor41 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor40])
xor42 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor41])
xor43 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor42])
xor44 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor43])
xor45 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor44])
xor46 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor45])
xor47 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor46])
xor48 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor47])
xor49 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor48])
xor50 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor49])
xor51 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor50])
xor52 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor51])
xor53 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor52])
xor54 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor53])
xor55 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor54])
xor56 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor55])
xor57 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor56])
xor58 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor57])
xor59 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor58])
xor60 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor59])
xor61 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor60])
xor62 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor61])
xor63 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor62])
xor64 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor63])
xor65 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor64])
xor66 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor65])
xor67 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor66])
xor68 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor67])
xor69 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor68])
xor70 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor69])
xor71 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor70])
xor72 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor71])
xor73 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor72])
xor74 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor73])
xor75 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor74])
xor76 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor75])
xor77 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor76])
xor78 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor77])
xor79 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor78])
xor80 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor79])
xor81 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor80])
xor82 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor81])
xor83 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor82])
xor84 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor83])
xor85 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor84])
xor86 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor85])
xor87 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor86])
xor88 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor87])
xor89 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor88])
xor90 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor89])
xor91 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor90])
xor92 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor91])
xor93 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor92])
xor94 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor93])
xor95 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor94])
xor96 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor95])
xor97 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor96])
xor98 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor97])
xor99 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor98])
xor100 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor99])
xor101 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor100])
xor102 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor101])
xor103 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor102])
xor104 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor103])
xor105 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor104])
xor106 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor105])
xor107 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor106])
xor108 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor107])
xor109 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor108])
xor110 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor109])
xor111 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor110])
xor112 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor111])
xor113 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor112])
xor114 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor113])
xor115 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor114])
xor116 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor115])
xor117 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor116])
xor118 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor117])
xor119 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor118])
xor120 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor119])
xor121 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor120])
xor122 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor121])
xor123 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor122])
xor124 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor123])
xor125 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor124])
xor126 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor125])
xor127 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor126])
xor128 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor127])
xor129 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor128])
xor130 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor129])
xor131 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor130])
xor132 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor131])
xor133 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor132])
xor134 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor133])
xor135 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor134])
xor136 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor135])
xor137 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor136])
xor138 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor137])
xor139 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor138])
xor140 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor139])
xor141 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor140])
xor142 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor141])
xor143 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor142])
xor144 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor143])
xor145 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor144])
xor146 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor145])
xor147 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor146])
xor148 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor147])
xor149 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor148])
xor150 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor149])
xor151 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor150])
xor152 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor151])
xor153 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor152])
xor154 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor153])
xor155 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor154])
xor156 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor155])
xor157 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor156])
xor158 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor157])
xor159 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor158])
xor160 = OperatorPOWL(operator=Operator.XOR, children=[waste_routing, xor159])
xor161 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, xor160])
xor162 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, xor161])
xor163 = OperatorPOWL(operator=Operator.XOR, children=[seedling_prep, xor162])
xor164 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, xor163])
xor165 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, xor164])
xor166 = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, xor165])
xor167 = OperatorPOWL(operator=