import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_analysis = Transition(label='Site Analysis')
env_scanning = Transition(label='Env Scanning')
farm_design = Transition(label='Farm Design')
nutrient_mix = Transition(label='Nutrient Mix')
seed_automation = Transition(label='Seed Automation')
growth_monitor = Transition(label='Growth Monitor')
pest_control = Transition(label='Pest Control')
ai_diagnostics = Transition(label='AI Diagnostics')
harvest_plan = Transition(label='Harvest Plan')
robotic_sort = Transition(label='Robotic Sort')
packaging_line = Transition(label='Packaging Line')
community_input = Transition(label='Community Input')
data_aggregation = Transition(label='Data Aggregation')
waste_recycle = Transition(label='Waste Recycle')
sustainability = Transition(label='Sustainability')

skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[site_analysis, env_scanning])
xor = OperatorPOWL(operator=Operator.XOR, children=[farm_design, skip])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[nutrient_mix, skip])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[seed_automation, skip])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[growth_monitor, skip])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[pest_control, skip])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[ai_diagnostics, skip])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[harvest_plan, skip])
xor8 = OperatorPOWL(operator=Operator.XOR, children=[robotic_sort, skip])
xor9 = OperatorPOWL(operator=Operator.XOR, children=[packaging_line, skip])
xor10 = OperatorPOWL(operator=Operator.XOR, children=[community_input, skip])
xor11 = OperatorPOWL(operator=Operator.XOR, children=[data_aggregation, skip])
xor12 = OperatorPOWL(operator=Operator.XOR, children=[waste_recycle, skip])
xor13 = OperatorPOWL(operator=Operator.XOR, children=[sustainability, skip])

root = StrictPartialOrder(nodes=[loop, xor, xor2, xor3, xor4, xor5, xor6, xor7, xor8, xor9, xor10, xor11, xor12, xor13])
root.order.add_edge(loop, xor)
root.order.add_edge(xor, xor2)
root.order.add_edge(xor2, xor3)
root.order.add_edge(xor3, xor4)
root.order.add_edge(xor4, xor5)
root.order.add_edge(xor5, xor6)
root.order.add_edge(xor6, xor7)
root.order.add_edge(xor7, xor8)
root.order.add_edge(xor8, xor9)
root.order.add_edge(xor9, xor10)
root.order.add_edge(xor10, xor11)
root.order.add_edge(xor11, xor12)
root.order.add_edge(xor12, xor13)
root.order.add_edge(xor13, loop)