A = Transition(label='Site Survey')
B = Transition(label='Design Modules')
C = Transition(label='Install Sensors')
D = Transition(label='Calibrate Climate')
E = Transition(label='Select Seeds')
F = Transition(label='Optimize Nutrients')
G = Transition(label='Deploy Robots')
H = Transition(label='Monitor Growth')
I = Transition(label='Detect Pests')
J = Transition(label='Analyze Data')
K = Transition(label='Harvest Crops')
L = Transition(label='Customize Pack')
M = Transition(label='Recycle Waste')
N = Transition(label='Audit Energy')
O = Transition(label='Align Demand')

skip = SilentTransition()
loop1 = OperatorPOWL(operator=Operator.LOOP, children=[A, B, C, D])
xor1 = OperatorPOWL(operator=Operator.XOR, children=[E, skip])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[F, xor1])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[G, xor2])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[H, xor3])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[I, xor4])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[J, xor5])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[K, xor6])
xor8 = OperatorPOWL(operator=Operator.XOR, children=[L, xor7])
xor9 = OperatorPOWL(operator=Operator.XOR, children=[M, xor8])
xor10 = OperatorPOWL(operator=Operator.XOR, children=[N, xor9])
xor11 = OperatorPOWL(operator=Operator.XOR, children=[O, xor10])
root = StrictPartialOrder(nodes=[loop1, xor11])
root.order.add_edge(loop1, xor11)

print(root)