import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
from pm4py.objects.process_tree.utils.powl import powl_to_process_tree
from pm4py.objects.process_tree.utils.powl import process_tree_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri
from pm4py.objects.process_tree.utils.powl import petri_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_net
from pm4py.objects.process_tree.utils.powl import petri_net_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_graph
from pm4py.objects.process_tree.utils.powl import petri_graph_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_graphml
from pm4py.objects.process_tree.utils.powl import petri_graphml_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_xml
from pm4py.objects.process_tree.utils.powl import petri_xml_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_yml
from pm4py.objects.process_tree.utils.powl import petri_yml_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_json
from pm4py.objects.process_tree.utils.powl import petri_json_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_yaml
from pm4py.objects.process_tree.utils.powl import petri_yaml_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_dot
from pm4py.objects.process_tree.utils.powl import petri_dot_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_gv
from pm4py.objects.process_tree.utils.powl import petri_gv_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tikz
from pm4py.objects.process_tree.utils.powl import petri_tikz_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_latex
from pm4py.objects.process_tree.utils.powl import petri_latex_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_markdown
from pm4py.objects.process_tree.utils.powl import petri_markdown_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_rst
from pm4py.objects.process_tree.utils.powl import petri_rst_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_pptx
from pm4py.objects.process_tree.utils.powl import petri_pptx_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_pdf
from pm4py.objects.process_tree.utils.powl import petri_pdf_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_svg
from pm4py.objects.process_tree.utils.powl import petri_svg_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_png
from pm4py.objects.process_tree.utils.powl import petri_png_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_jpg
from pm4py.objects.process_tree.utils.powl import petri_jpg_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_bmp
from pm4py.objects.process_tree.utils.powl import petri_bmp_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_gif
from pm4py.objects.process_tree.utils.powl import petri_gif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tga
from pm4py.objects.process_tree.utils.powl import petri_tga_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tif
from pm4py.objects.process_tree.utils.powl import petri_tif_to_powl
from pm4py.objects.process_tree.utils.powl import powl_to_petri_tiff
from pm4py.objects.process_tree.utils.powl import petri_tiff_to_powl
from pm4py.objects.process_tree.utils.powl import