from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define the transitions
provenance_check = Transition(label='Provenance Check')
material_scan = Transition(label='Material Scan')
wear_analysis = Transition(label='Wear Analysis')
image_capture = Transition(label='Image Capture')
pattern_match = Transition(label='Pattern Match')
ownership_verify = Transition(label='Ownership Verify')
ethics_review = Transition(label='Ethics Review')
carbon_dating = Transition(label='Carbon Dating')
restoration_eval = Transition(label='Restoration Eval')
report_draft = Transition(label='Report Draft')
stakeholder_review = Transition(label='Stakeholder Review')
archive_data = Transition(label='Archive Data')
exhibit_approve = Transition(label='Exhibit Approve')
condition_monitor = Transition(label='Condition Monitor')
final_certification = Transition(label='Final Certification')

# Define the silent transitions
skip = SilentTransition()

# Define the loop and choice operators
loop_provenance = OperatorPOWL(operator=Operator.LOOP, children=[provenance_check, material_scan])
xor_wear_pattern = OperatorPOWL(operator=Operator.XOR, children=[wear_analysis, skip])
xor_image_match = OperatorPOWL(operator=Operator.XOR, children=[image_capture, skip])
xor_ethics = OperatorPOWL(operator=Operator.XOR, children=[pattern_match, skip])
xor_ownership = OperatorPOWL(operator=Operator.XOR, children=[ownership_verify, skip])
xor_cultural_sensitivity = OperatorPOWL(operator=Operator.XOR, children=[ethics_review, skip])
xor_cultural_verification = OperatorPOWL(operator=Operator.XOR, children=[carbon_dating, skip])
xor_restoration = OperatorPOWL(operator=Operator.XOR, children=[restoration_eval, skip])
xor_report = OperatorPOWL(operator=Operator.XOR, children=[report_draft, skip])
xor_stakeholder = OperatorPOWL(operator=Operator.XOR, children=[stakeholder_review, skip])
xor_archive = OperatorPOWL(operator=Operator.XOR, children=[archive_data, skip])
xor_exhibit = OperatorPOWL(operator=Operator.XOR, children=[exhibit_approve, skip])
xor_condition = OperatorPOWL(operator=Operator.XOR, children=[condition_monitor, skip])
xor_final = OperatorPOWL(operator=Operator.XOR, children=[final_certification, skip])

# Define the root POWL model
root = StrictPartialOrder(nodes=[loop_provenance, xor_wear_pattern, xor_image_match, xor_ethics, xor_ownership, xor_cultural_sensitivity, xor_cultural_verification, xor_restoration, xor_report, xor_stakeholder, xor_archive, xor_exhibit, xor_condition, xor_final])
root.order.add_edge(loop_provenance, xor_wear_pattern)
root.order.add_edge(loop_provenance, xor_image_match)
root.order.add_edge(loop_provenance, xor_ethics)
root.order.add_edge(loop_provenance, xor_ownership)
root.order.add_edge(loop_provenance, xor_cultural_sensitivity)
root.order.add_edge(loop_provenance, xor_cultural_verification)
root.order.add_edge(loop_provenance, xor_restoration)
root.order.add_edge(loop_provenance, xor_report)
root.order.add_edge(loop_provenance, xor_stakeholder)
root.order.add_edge(loop_provenance, xor_archive)
root.order.add_edge(loop_provenance, xor_exhibit)
root.order.add_edge(loop_provenance, xor_condition)
root.order.add_edge(loop_provenance, xor_final)
root.order.add_edge(xor_wear_pattern, xor_image_match)
root.order.add_edge(xor_wear_pattern, xor_ethics)
root.order.add_edge(xor_wear_pattern, xor_ownership)
root.order.add_edge(xor_wear_pattern, xor_cultural_sensitivity)
root.order.add_edge(xor_wear_pattern, xor_cultural_verification)
root.order.add_edge(xor_wear_pattern, xor_restoration)
root.order.add_edge(xor_wear_pattern, xor_report)
root.order.add_edge(xor_wear_pattern, xor_stakeholder)
root.order.add_edge(xor_wear_pattern, xor_archive)
root.order.add_edge(xor_wear_pattern, xor_exhibit)
root.order.add_edge(xor_wear_pattern, xor_condition)
root.order.add_edge(xor_wear_pattern, xor_final)
root.order.add_edge(xor_image_match, xor_ethics)
root.order.add_edge(xor_image_match, xor_ownership)
root.order.add_edge(xor_image_match, xor_cultural_sensitivity)
root.order.add_edge(xor_image_match, xor_cultural_verification)
root.order.add_edge(xor_image_match, xor_restoration)
root.order.add_edge(xor_image_match, xor_report)
root.order.add_edge(xor_image_match, xor_stakeholder)
root.order.add_edge(xor_image_match, xor_archive)
root.order.add_edge(xor_image_match, xor_exhibit)
root.order.add_edge(xor_image_match, xor_condition)
root.order.add_edge(xor_image_match, xor_final)
root.order.add_edge(xor_ethics, xor_ownership)
root.order.add_edge(xor_ethics, xor_cultural_sensitivity)
root.order.add_edge(xor_ethics, xor_cultural_verification)
root.order.add_edge(xor_ethics, xor_restoration)
root.order.add_edge(xor_ethics, xor_report)
root.order.add_edge(xor_ethics, xor_stakeholder)
root.order.add_edge(xor_ethics, xor_archive)
root.order.add_edge(xor_ethics, xor_exhibit)
root.order.add_edge(xor_ethics, xor_condition)
root.order.add_edge(xor_ethics, xor_final)
root.order.add_edge(xor_ownership, xor_cultural_sensitivity)
root.order.add_edge(xor_ownership, xor_cultural_verification)
root.order.add_edge(xor_ownership, xor_restoration)
root.order.add_edge(xor_ownership, xor_report)
root.order.add_edge(xor_ownership, xor_stakeholder)
root.order.add_edge(xor_ownership, xor_archive)
root.order.add_edge(xor_ownership, xor_exhibit)
root.order.add_edge(xor_ownership, xor_condition)
root.order.add_edge(xor_ownership, xor_final)
root.order.add_edge(xor_cultural_sensitivity, xor_cultural_verification)
root.order.add_edge(xor_cultural_sensitivity, xor_restoration)
root.order.add_edge(xor_cultural_sensitivity, xor_report)
root.order.add_edge(xor_cultural_sensitivity, xor_stakeholder)
root.order.add_edge(xor_cultural_sensitivity, xor_archive)
root.order.add_edge(xor_cultural_sensitivity, xor_exhibit)
root.order.add_edge(xor_cultural_sensitivity, xor_condition)
root.order.add_edge(xor_cultural_sensitivity, xor_final)
root.order.add_edge(xor_cultural_verification, xor_restoration)
root.order.add_edge(xor_cultural_verification, xor_report)
root.order.add_edge(xor_cultural_verification, xor_stakeholder)
root.order.add_edge(xor_cultural_verification, xor_archive)
root.order.add_edge(xor_cultural_verification, xor_exhibit)
root.order.add_edge(xor_cultural_verification, xor_condition)
root.order.add_edge(xor_cultural_verification, xor_final)
root.order.add_edge(xor_restoration, xor_report)
root.order.add_edge(xor_restoration, xor_stakeholder)
root.order.add_edge(xor_restoration, xor_archive)
root.order.add_edge(xor_restoration, xor_exhibit)
root.order.add_edge(xor_restoration, xor_condition)
root.order.add_edge(xor_restoration, xor_final)
root.order.add_edge(xor_report, xor_stakeholder)
root.order.add_edge(xor_report, xor_archive)
root.order.add_edge(xor_report, xor_exhibit)
root.order.add_edge(xor_report, xor_condition)
root.order.add_edge(xor_report, xor_final)
root.order.add_edge(xor_stakeholder, xor_archive)
root.order.add_edge(xor_stakeholder, xor_exhibit)
root.order.add_edge(xor_stakeholder, xor_condition)
root.order.add_edge(xor_stakeholder, xor_final)
root.order.add_edge(xor_archive, xor_exhibit)
root.order.add_edge(xor_archive, xor_condition)
root.order.add_edge(xor_archive, xor_final)
root.order.add_edge(xor_exhibit, xor_condition)
root.order.add_edge(xor_exhibit, xor_final)
root.order.add_edge(xor_condition, xor_final)