import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
A = Transition(label='Site Survey')
B = Transition(label='Design Layout')
C = Transition(label='Material Sourcing')
D = Transition(label='System Assembly')
E = Transition(label='Sensor Install')
F = Transition(label='Nutrient Prep')
G = Transition(label='Water Testing')
H = Transition(label='Climate Setup')
I = Transition(label='Data Integration')
J = Transition(label='Growth Monitoring')
K = Transition(label='Pest Control')
L = Transition(label='Waste Sorting')
M = Transition(label='Harvest Plan')
N = Transition(label='Produce Pack')
O = Transition(label='Energy Audit')
P = Transition(label='Community Setup')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip, loop])
root = StrictPartialOrder(nodes=[xor])
root.order.add_edge(xor, loop)
root.order.add_edge(loop, xor)