import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
from pm4py.objects.powl.utils import build_powl_model

# Define activities
site_survey = Transition(label='Site Survey')
load_test = Transition(label='Load Test')
soil_sample = Transition(label='Soil Sample')
crop_select = Transition(label='Crop Select')
irrigation_plan = Transition(label='Irrigation Plan')
permit_apply = Transition(label='Permit Apply')
material_order = Transition(label='Material Order')
bed_install = Transition(label='Bed Install')
pest_control = Transition(label='Pest Control')
solar_setup = Transition(label='Solar Setup')
staff_train = Transition(label='Staff Train')
market_outreach = Transition(label='Market Outreach')
system_setup = Transition(label='System Setup')
supplier_contact = Transition(label='Supplier Contact')
health_monitor = Transition(label='Health Monitor')

# Define operators
xor = OperatorPOWL(operator=Operator.XOR, children=[permit_apply, material_order])
loop1 = OperatorPOWL(operator=Operator.LOOP, children=[site_survey, load_test, soil_sample, crop_select, irrigation_plan])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[pest_control, solar_setup, staff_train, market_outreach, system_setup, supplier_contact])
loop3 = OperatorPOWL(operator=Operator.LOOP, children=[health_monitor])

# Build POWL model
root = StrictPartialOrder()
root.nodes = [site_survey, load_test, soil_sample, crop_select, irrigation_plan, permit_apply, material_order, bed_install, pest_control, solar_setup, staff_train, market_outreach, system_setup, supplier_contact, health_monitor]
root.order.add_edge(site_survey, load_test)
root.order.add_edge(site_survey, soil_sample)
root.order.add_edge(site_survey, crop_select)
root.order.add_edge(site_survey, irrigation_plan)
root.order.add_edge(load_test, permit_apply)
root.order.add_edge(load_test, material_order)
root.order.add_edge(soil_sample, permit_apply)
root.order.add_edge(soil_sample, material_order)
root.order.add_edge(crop_select, permit_apply)
root.order.add_edge(crop_select, material_order)
root.order.add_edge(irrigation_plan, permit_apply)
root.order.add_edge(irrigation_plan, material_order)
root.order.add_edge(permit_apply, bed_install)
root.order.add_edge(material_order, bed_install)
root.order.add_edge(pest_control, solar_setup)
root.order.add_edge(pest_control, staff_train)
root.order.add_edge(pest_control, market_outreach)
root.order.add_edge(pest_control, system_setup)
root.order.add_edge(pest_control, supplier_contact)
root.order.add_edge(solar_setup, staff_train)
root.order.add_edge(solar_setup, market_outreach)
root.order.add_edge(solar_setup, system_setup)
root.order.add_edge(solar_setup, supplier_contact)
root.order.add_edge(staff_train, market_outreach)
root.order.add_edge(staff_train, system_setup)
root.order.add_edge(staff_train, supplier_contact)
root.order.add_edge(market_outreach, system_setup)
root.order.add_edge(market_outreach, supplier_contact)
root.order.add_edge(system_setup, supplier_contact)
root.order.add_edge(health_monitor, health_monitor)
root.order.add_edge(permit_apply, xor)
root.order.add_edge(material_order, xor)
root.order.add_edge(bed_install, loop1)
root.order.add_edge(pest_control, loop2)
root.order.add_edge(system_setup, loop3)