root = StrictPartialOrder(nodes=[Transition(label='Site Survey'), Transition(label='Load Test'), Transition(label='Soil Sample'), Transition(label='Crop Select'), Transition(label='Irrigation Plan'), Transition(label='Permit Apply'), Transition(label='Material Order'), Transition(label='Bed Install'), Transition(label='Pest Control'), Transition(label='Solar Setup'), Transition(label='Staff Train'), Transition(label='Market Outreach'), Transition(label='System Setup'), Transition(label='Supplier Contact'), Transition(label='Health Monitor')])

# Define the dependencies for the partial order
root.order.add_edge(Transition(label='Site Survey'), Transition(label='Load Test'))
root.order.add_edge(Transition(label='Load Test'), Transition(label='Soil Sample'))
root.order.add_edge(Transition(label='Soil Sample'), Transition(label='Crop Select'))
root.order.add_edge(Transition(label='Crop Select'), Transition(label='Irrigation Plan'))
root.order.add_edge(Transition(label='Irrigation Plan'), Transition(label='Permit Apply'))
root.order.add_edge(Transition(label='Permit Apply'), Transition(label='Material Order'))
root.order.add_edge(Transition(label='Material Order'), Transition(label='Bed Install'))
root.order.add_edge(Transition(label='Bed Install'), Transition(label='Pest Control'))
root.order.add_edge(Transition(label='Pest Control'), Transition(label='Solar Setup'))
root.order.add_edge(Transition(label='Solar Setup'), Transition(label='Staff Train'))
root.order.add_edge(Transition(label='Staff Train'), Transition(label='Market Outreach'))
root.order.add_edge(Transition(label='Market Outreach'), Transition(label='System Setup'))
root.order.add_edge(Transition(label='System Setup'), Transition(label='Supplier Contact'))
root.order.add_edge(Transition(label='Supplier Contact'), Transition(label='Health Monitor'))

root.order.add_edge(Transition(label='Site Survey'), Transition(label='Soil Sample'))
root.order.add_edge(Transition(label='Site Survey'), Transition(label='Crop Select'))
root.order.add_edge(Transition(label='Site Survey'), Transition(label='Irrigation Plan'))
root.order.add_edge(Transition(label='Site Survey'), Transition(label='Permit Apply'))
root.order.add_edge(Transition(label='Site Survey'), Transition(label='Material Order'))
root.order.add_edge(Transition(label='Site Survey'), Transition(label='Bed Install'))
root.order.add_edge(Transition(label='Site Survey'), Transition(label='Pest Control'))
root.order.add_edge(Transition(label='Site Survey'), Transition(label='Solar Setup'))
root.order.add_edge(Transition(label='Site Survey'), Transition(label='Staff Train'))
root.order.add_edge(Transition(label='Site Survey'), Transition(label='Market Outreach'))
root.order.add_edge(Transition(label='Site Survey'), Transition(label='System Setup'))
root.order.add_edge(Transition(label='Site Survey'), Transition(label='Supplier Contact'))
root.order.add_edge(Transition(label='Site Survey'), Transition(label='Health Monitor'))

root.order.add_edge(Transition(label='Load Test'), Transition(label='Soil Sample'))
root.order.add_edge(Transition(label='Load Test'), Transition(label='Crop Select'))
root.order.add_edge(Transition(label='Load Test'), Transition(label='Irrigation Plan'))
root.order.add_edge(Transition(label='Load Test'), Transition(label='Permit Apply'))
root.order.add_edge(Transition(label='Load Test'), Transition(label='Material Order'))
root.order.add_edge(Transition(label='Load Test'), Transition(label='Bed Install'))
root.order.add_edge(Transition(label='Load Test'), Transition(label='Pest Control'))
root.order.add_edge(Transition(label='Load Test'), Transition(label='Solar Setup'))
root.order.add_edge(Transition(label='Load Test'), Transition(label='Staff Train'))
root.order.add_edge(Transition(label='Load Test'), Transition(label='Market Outreach'))
root.order.add_edge(Transition(label='Load Test'), Transition(label='System Setup'))
root.order.add_edge(Transition(label='Load Test'), Transition(label='Supplier Contact'))
root.order.add_edge(Transition(label='Load Test'), Transition(label='Health Monitor'))

root.order.add_edge(Transition(label='Soil Sample'), Transition(label='Crop Select'))
root.order.add_edge(Transition(label='Soil Sample'), Transition(label='Irrigation Plan'))
root.order.add_edge(Transition(label='Soil Sample'), Transition(label='Permit Apply'))
root.order.add_edge(Transition(label='Soil Sample'), Transition(label='Material Order'))
root.order.add_edge(Transition(label='Soil Sample'), Transition(label='Bed Install'))
root.order.add_edge(Transition(label='Soil Sample'), Transition(label='Pest Control'))
root.order.add_edge(Transition(label='Soil Sample'), Transition(label='Solar Setup'))
root.order.add_edge(Transition(label='Soil Sample'), Transition(label='Staff Train'))
root.order.add_edge(Transition(label='Soil Sample'), Transition(label='Market Outreach'))
root.order.add_edge(Transition(label='Soil Sample'), Transition(label='System Setup'))
root.order.add_edge(Transition(label='Soil Sample'), Transition(label='Supplier Contact'))
root.order.add_edge(Transition(label='Soil Sample'), Transition(label='Health Monitor'))

root.order.add_edge(Transition(label='Crop Select'), Transition(label='Irrigation Plan'))
root.order.add_edge(Transition(label='Crop Select'), Transition(label='Permit Apply'))
root.order.add_edge(Transition(label='Crop Select'), Transition(label='Material Order'))
root.order.add_edge(Transition(label='Crop Select'), Transition(label='Bed Install'))
root.order.add_edge(Transition(label='Crop Select'), Transition(label='Pest Control'))
root.order.add_edge(Transition(label='Crop Select'), Transition(label='Solar Setup'))
root.order.add_edge(Transition(label='Crop Select'), Transition(label='Staff Train'))
root.order.add_edge(Transition(label='Crop Select'), Transition(label='Market Outreach'))
root.order.add_edge(Transition(label='Crop Select'), Transition(label='System Setup'))
root.order.add_edge(Transition(label='Crop Select'), Transition(label='Supplier Contact'))
root.order.add_edge(Transition(label='Crop Select'), Transition(label='Health Monitor'))

root.order.add_edge(Transition(label='Irrigation Plan'), Transition(label='Permit Apply'))
root.order.add_edge(Transition(label='Irrigation Plan'), Transition(label='Material Order'))
root.order.add_edge(Transition(label='Irrigation Plan'), Transition(label='Bed Install'))
root.order.add_edge(Transition(label='Irrigation Plan'), Transition(label='Pest Control'))
root.order.add_edge(Transition(label='Irrigation Plan'), Transition(label='Solar Setup'))
root.order.add_edge(Transition(label='Irrigation Plan'), Transition(label='Staff Train'))
root.order.add_edge(Transition(label='Irrigation Plan'), Transition(label='Market Outreach'))
root.order.add_edge(Transition(label='Irrigation Plan'), Transition(label='System Setup'))
root.order.add_edge(Transition(label='Irrigation Plan'), Transition(label='Supplier Contact'))
root.order.add_edge(Transition(label='Irrigation Plan'), Transition(label='Health Monitor'))

root.order.add_edge(Transition(label='Permit Apply'), Transition(label='Material Order'))
root.order.add_edge(Transition(label='Permit Apply'), Transition(label='Bed Install'))
root.order.add_edge(Transition(label='Permit Apply'), Transition(label='Pest Control'))
root.order.add_edge(Transition(label='Permit Apply'), Transition(label='Solar Setup'))
root.order.add_edge(Transition(label='Permit Apply'), Transition(label='Staff Train'))
root.order.add_edge(Transition(label='Permit Apply'), Transition(label='Market Outreach'))
root.order.add_edge(Transition(label='Permit Apply'), Transition(label='System Setup'))
root.order.add_edge(Transition(label='Permit Apply'), Transition(label='Supplier Contact'))
root.order.add_edge(Transition(label='Permit Apply'), Transition(label='Health Monitor'))

root.order.add_edge(Transition(label='Material Order'), Transition(label='Bed Install'))
root.order.add_edge(Transition(label='Material Order'), Transition(label='Pest Control'))
root.order.add_edge(Transition(label='Material Order'), Transition(label='Solar Setup'))
root.order.add_edge(Transition(label='Material Order'), Transition(label='Staff Train'))
root.order.add_edge(Transition(label='Material Order'), Transition(label='Market Outreach'))
root.order.add_edge(Transition(label='Material Order'), Transition(label='System Setup'))
root.order.add_edge(Transition(label='Material Order'), Transition(label='Supplier Contact'))
root.order.add_edge(Transition(label='Material Order'), Transition(label='Health Monitor'))

root.order.add_edge(Transition(label='Bed Install'), Transition(label='Pest Control'))
root.order.add_edge(Transition(label='Bed Install'), Transition(label='Solar Setup'))
root.order.add_edge(Transition(label='Bed Install'), Transition(label='Staff Train'))
root.order.add_edge(Transition(label='Bed Install'), Transition(label='Market Outreach'))
root.order.add_edge(Transition(label='Bed Install'), Transition(label='System Setup'))
root.order.add_edge(Transition(label='Bed Install'), Transition(label='Supplier Contact'))
root.order.add_edge(Transition(label='Bed Install'), Transition(label='Health Monitor'))

root.order.add_edge(Transition(label='Pest Control'), Transition(label='Solar Setup'))
root.order.add_edge(Transition(label='Pest Control'), Transition(label='Staff Train'))
root.order.add_edge(Transition(label='Pest Control'), Transition(label='Market Outreach'))
root.order.add_edge(Transition(label='Pest Control'), Transition(label='System Setup'))
root.order.add_edge(Transition(label='Pest Control'), Transition(label='Supplier Contact'))
root.order.add_edge(Transition(label='Pest Control'), Transition(label='Health Monitor'))

root.order.add_edge(Transition(label='Solar Setup'), Transition(label='Staff Train'))
root.order.add_edge(Transition(label='Solar Setup'), Transition(label='Market Outreach'))
root.order.add_edge(Transition(label='Solar Setup'), Transition(label='System Setup'))
root.order.add_edge(Transition(label='Solar Setup'), Transition(label='Supplier Contact'))
root.order.add_edge(Transition(label='Solar Setup'), Transition(label='Health Monitor'))

root.order.add_edge(Transition(label='Staff Train'), Transition(label='Market Outreach'))
root.order.add_edge(Transition(label='Staff Train'), Transition(label='System Setup'))
root.order.add_edge(Transition(label='Staff Train'), Transition(label='Supplier Contact'))
root.order.add_edge(Transition(label='Staff Train'), Transition(label='Health Monitor'))

root.order.add_edge(Transition(label='Market Outreach'), Transition(label='System Setup'))
root.order.add_edge(Transition(label='Market Outreach'), Transition(label='Supplier Contact'))
root.order.add_edge(Transition(label='Market Outreach'), Transition(label='Health Monitor'))

root.order.add_edge(Transition(label='System Setup'), Transition(label='Supplier Contact'))
root.order.add_edge(Transition(label='System Setup'), Transition(label='Health Monitor'))

root.order.add_edge(Transition(label='Supplier Contact'), Transition(label='Health Monitor'))