import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define the activities
activities = {
    'Seed Selection': Transition(label='Seed Selection'),
    'Germination Start': Transition(label='Germination Start'),
    'Seedling Transplant': Transition(label='Seedling Transplant'),
    'Nutrient Mix': Transition(label='Nutrient Mix'),
    'Water Delivery': Transition(label='Water Delivery'),
    'Light Adjustment': Transition(label='Light Adjustment'),
    'Climate Control': Transition(label='Climate Control'),
    'Sensor Monitoring': Transition(label='Sensor Monitoring'),
    'Health Check': Transition(label='Health Check'),
    'Pest Control': Transition(label='Pest Control'),
    'Harvest Planning': Transition(label='Harvest Planning'),
    'Crop Harvest': Transition(label='Crop Harvest'),
    'Waste Sorting': Transition(label='Waste Sorting'),
    'Biomass Process': Transition(label='Biomass Process'),
    'Energy Recycling': Transition(label='Energy Recycling'),
    'Data Analysis': Transition(label='Data Analysis'),
    'Yield Forecast': Transition(label='Yield Forecast')
}

# Create the POWL model
root = StrictPartialOrder()

# Define the process flow
root.add_transition(activities['Seed Selection'])
root.add_transition(activities['Germination Start'])
root.add_transition(activities['Seedling Transplant'])
root.add_transition(activities['Nutrient Mix'])
root.add_transition(activities['Water Delivery'])
root.add_transition(activities['Light Adjustment'])
root.add_transition(activities['Climate Control'])
root.add_transition(activities['Sensor Monitoring'])
root.add_transition(activities['Health Check'])
root.add_transition(activities['Pest Control'])
root.add_transition(activities['Harvest Planning'])
root.add_transition(activities['Crop Harvest'])
root.add_transition(activities['Waste Sorting'])
root.add_transition(activities['Biomass Process'])
root.add_transition(activities['Energy Recycling'])
root.add_transition(activities['Data Analysis'])
root.add_transition(activities['Yield Forecast'])

# Define the loop and choice structures
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.XOR, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.XOR, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.XOR, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.XOR, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.XOR, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.XOR, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.XOR, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['Light Adjustment'], activities['Climate Control'], activities['Sensor Monitoring'], activities['Health Check'], activities['Pest Control'], activities['Harvest Planning'], activities['Crop Harvest'], activities['Waste Sorting'], activities['Biomass Process'], activities['Energy Recycling'], activities['Data Analysis'], activities['Yield Forecast']]))
root.add_transition(OperatorPOWL(operator=Operator.LOOP, children=[activities['Seed Selection'], activities['Germination Start'], activities['Seedling Transplant'], activities['Nutrient Mix'], activities['Water Delivery'], activities['