root = StrictPartialOrder(nodes=[
    Transition(label='Seed Sourcing'),
    Transition(label='Germination Check'),
    Transition(label='Nutrient Mix'),
    Transition(label='Automated Planting'),
    Transition(label='Climate Control'),
    Transition(label='Crop Scanning'),
    Transition(label='Pest Monitoring'),
    Transition(label='Growth Analysis'),
    Transition(label='Robotic Harvest'),
    Transition(label='Quality Sort'),
    Transition(label='Eco Packaging'),
    Transition(label='Blockchain Track'),
    Transition(label='Route Planning'),
    Transition(label='Feedback Collect'),
    Transition(label='Waste Recycling'),
    Transition(label='Data Analytics'),
    Transition(label='Demand Forecast'),
    Transition(label='Maintenance Alert')
])
root.order.add_edge(root.nodes[0], root.nodes[1])
root.order.add_edge(root.nodes[1], root.nodes[2])
root.order.add_edge(root.nodes[2], root.nodes[3])
root.order.add_edge(root.nodes[3], root.nodes[4])
root.order.add_edge(root.nodes[4], root.nodes[5])
root.order.add_edge(root.nodes[5], root.nodes[6])
root.order.add_edge(root.nodes[6], root.nodes[7])
root.order.add_edge(root.nodes[7], root.nodes[8])
root.order.add_edge(root.nodes[8], root.nodes[9])
root.order.add_edge(root.nodes[9], root.nodes[10])
root.order.add_edge(root.nodes[10], root.nodes[11])
root.order.add_edge(root.nodes[11], root.nodes[12])
root.order.add_edge(root.nodes[12], root.nodes[13])
root.order.add_edge(root.nodes[13], root.nodes[14])
root.order.add_edge(root.nodes[14], root.nodes[15])
root.order.add_edge(root.nodes[15], root.nodes[16])
root.order.add_edge(root.nodes[16], root.nodes[17])
root.order.add_edge(root.nodes[17], root.nodes[18])