root = StrictPartialOrder(nodes=[
    Transition(label='Milk Sourcing'),
    Transition(label='Quality Testing'),
    Transition(label='Milk Pasteurize'),
    Transition(label='Culture Addition'),
    Transition(label='Curd Cutting'),
    Transition(label='Whey Drain'),
    Transition(label='Cheese Molding'),
    Transition(label='Controlled Aging'),
    Transition(label='Sensory Check'),
    Transition(label='Health Certify'),
    Transition(label='Custom Labeling'),
    Transition(label='Cold Packaging'),
    Transition(label='Logistics Setup'),
    Transition(label='Export Docs'),
    Transition(label='Customs Clearance'),
    Transition(label='Shipment Track'),
    Transition(label='Client Feedback')
])
root.order.add_edge(root.nodes[0], root.nodes[1])
root.order.add_edge(root.nodes[1], root.nodes[2])
root.order.add_edge(root.nodes[2], root.nodes[3])
root.order.add_edge(root.nodes[3], root.nodes[4])
root.order.add_edge(root.nodes[4], root.nodes[5])
root.order.add_edge(root.nodes[5], root.nodes[6])
root.order.add_edge(root.nodes[6], root.nodes[7])
root.order.add_edge(root.nodes[7], root.nodes[8])
root.order.add_edge(root.nodes[8], root.nodes[9])
root.order.add_edge(root.nodes[9], root.nodes[10])
root.order.add_edge(root.nodes[10], root.nodes[11])
root.order.add_edge(root.nodes[11], root.nodes[12])
root.order.add_edge(root.nodes[12], root.nodes[13])
root.order.add_edge(root.nodes[13], root.nodes[14])
root.order.add_edge(root.nodes[14], root.nodes[15])
root.order.add_edge(root.nodes[15], root.nodes[16])