root = StrictPartialOrder(nodes=[Transition('Client Consult'), Transition('Spec Finalize'), Transition('Design Draft'), Transition('Aerodynamics Test'), Transition('AI Integration'), Transition('Material Sourcing'), Transition('Component Order'), Transition('Assembly Line'), Transition('Firmware Install'), Transition('Environmental Test'), Transition('Quality Check'), Transition('Brand Packaging'), Transition('Shipping Prep'), Transition('Delivery Schedule'), Transition('Post-Sale Support')])

root.order.add_edge(Transition('Client Consult'), Transition('Spec Finalize'))
root.order.add_edge(Transition('Spec Finalize'), Transition('Design Draft'))
root.order.add_edge(Transition('Design Draft'), Transition('Aerodynamics Test'))
root.order.add_edge(Transition('Aerodynamics Test'), Transition('AI Integration'))
root.order.add_edge(Transition('AI Integration'), Transition('Material Sourcing'))
root.order.add_edge(Transition('Material Sourcing'), Transition('Component Order'))
root.order.add_edge(Transition('Component Order'), Transition('Assembly Line'))
root.order.add_edge(Transition('Assembly Line'), Transition('Firmware Install'))
root.order.add_edge(Transition('Firmware Install'), Transition('Environmental Test'))
root.order.add_edge(Transition('Environmental Test'), Transition('Quality Check'))
root.order.add_edge(Transition('Quality Check'), Transition('Brand Packaging'))
root.order.add_edge(Transition('Brand Packaging'), Transition('Shipping Prep'))
root.order.add_edge(Transition('Shipping Prep'), Transition('Delivery Schedule'))
root.order.add_edge(Transition('Delivery Schedule'), Transition('Post-Sale Support'))