import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
site_survey = Transition(label='Site Survey')
light_mapping = Transition(label='Light Mapping')
water_testing = Transition(label='Water Testing')
design_modules = Transition(label='Design Modules')
iot_setup = Transition(label='IoT Setup')
sensor_calibration = Transition(label='Sensor Calibration')
nutrient_mix = Transition(label='Nutrient Mix')
climate_control = Transition(label='Climate Control')
regulatory_check = Transition(label='Regulatory Check')
community_meet = Transition(label='Community Meet')
energy_audit = Transition(label='Energy Audit')
staff_training = Transition(label='Staff Training')
installation = Transition(label='Installation')
system_testing = Transition(label='System Testing')
yield_analysis = Transition(label='Yield Analysis')
resource_audit = Transition(label='Resource Audit')
impact_review = Transition(label='Impact Review')

loop1 = OperatorPOWL(operator=Operator.LOOP, children=[site_survey, light_mapping, water_testing, design_modules])
xor1 = OperatorPOWL(operator=Operator.XOR, children=[iot_setup, sensor_calibration])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[nutrient_mix, climate_control])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[regulatory_check, community_meet])
loop3 = OperatorPOWL(operator=Operator.LOOP, children=[energy_audit, staff_training])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[installation, system_testing])
loop4 = OperatorPOWL(operator=Operator.LOOP, children=[yield_analysis, resource_audit])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[impact_review, None])

root = StrictPartialOrder(nodes=[loop1, xor1, loop2, xor2, loop3, xor3, loop4, xor4])
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, loop2)
root.order.add_edge(loop2, xor2)
root.order.add_edge(xor2, loop3)
root.order.add_edge(loop3, xor3)
root.order.add_edge(xor3, loop4)
root.order.add_edge(loop4, xor4)