import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
SiteAssess = Transition(label='Site Assess')
LoadTesting = Transition(label='Load Testing')
ClimateStudy = Transition(label='Climate Study')
MediumPrep = Transition(label='Medium Prep')
BedInstall = Transition(label='Bed Install')
IrrigationSetup = Transition(label='Irrigation Setup')
CropSelect = Transition(label='Crop Select')
PestControl = Transition(label='Pest Control')
CommunityMeet = Transition(label='Community Meet')
MonitorDeploy = Transition(label='Monitor Deploy')
WasteCycle = Transition(label='Waste Cycle')
YieldForecast = Transition(label='Yield Forecast')
MarketLink = Transition(label='Market Link')
WorkshopPlan = Transition(label='Workshop Plan')
TechIntegrate = Transition(label='Tech Integrate')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[SiteAssess, LoadTesting, ClimateStudy, MediumPrep, BedInstall, IrrigationSetup, CropSelect, PestControl, CommunityMeet, MonitorDeploy, WasteCycle, YieldForecast, MarketLink, WorkshopPlan, TechIntegrate])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)