A = Transition(label='Initial Inquiry')
B = Transition(label='Document Review')
C = Transition(label='Historical Research')
D = Transition(label='Material Sampling')
E = Transition(label='Forensic Testing')
F = Transition(label='Ownership Audit')
G = Transition(label='Legal Verification')
H = Transition(label='Ethical Screening')
I = Transition(label='Expert Consultation')
J = Transition(label='Cultural Assessment')
K = Transition(label='Condition Survey')
L = Transition(label='Provenance Mapping')
M = Transition(label='Risk Analysis')
N = Transition(label='Report Compilation')
O = Transition(label='Acquisition Approval')
P = Transition(label='Repatriation Review')
Q = Transition(label='Archival Storage')
skip = SilentTransition()

xor1 = OperatorPOWL(operator=Operator.XOR, children=[A, B])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[C, D])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[E, F])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[G, H])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[I, J])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[K, L])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[M, N])
xor8 = OperatorPOWL(operator=Operator.XOR, children=[O, P])
xor9 = OperatorPOWL(operator=Operator.XOR, children=[Q, skip])

loop1 = OperatorPOWL(operator=Operator.LOOP, children=[xor1, xor2])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[xor3, xor4])
loop3 = OperatorPOWL(operator=Operator.LOOP, children=[xor5, xor6])
loop4 = OperatorPOWL(operator=Operator.LOOP, children=[xor7, xor8])
loop5 = OperatorPOWL(operator=Operator.LOOP, children=[xor9, skip])

root = StrictPartialOrder(nodes=[loop1, loop2, loop3, loop4, loop5])
root.order.add_edge(loop1, loop2)
root.order.add_edge(loop2, loop3)
root.order.add_edge(loop3, loop4)
root.order.add_edge(loop4, loop5)
root.order.add_edge(loop5, loop1)