root = StrictPartialOrder(
    nodes=[
        Transition(label='Initial Inquiry'),
        Transition(label='Document Review'),
        Transition(label='Historical Research'),
        Transition(label='Material Sampling'),
        Transition(label='Forensic Testing'),
        Transition(label='Ownership Audit'),
        Transition(label='Legal Verification'),
        Transition(label='Ethical Screening'),
        Transition(label='Expert Consultation'),
        Transition(label='Cultural Assessment'),
        Transition(label='Condition Survey'),
        Transition(label='Provenance Mapping'),
        Transition(label='Risk Analysis'),
        Transition(label='Report Compilation'),
        Transition(label='Acquisition Approval'),
        Transition(label='Repatriation Review'),
        Transition(label='Archival Storage'),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Initial Inquiry'), Transition(label='Document Review')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Historical Research'), Transition(label='Material Sampling')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Forensic Testing'), Transition(label='Ownership Audit')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Legal Verification'), Transition(label='Ethical Screening')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Expert Consultation'), Transition(label='Cultural Assessment')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Condition Survey'), Transition(label='Provenance Mapping')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Risk Analysis'), Transition(label='Report Compilation')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Acquisition Approval'), Transition(label='Repatriation Review')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Archival Storage'), Transition(label='Initial Inquiry')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Archival Storage'), Transition(label='Document Review')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Archival Storage'), Transition(label='Historical Research')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Archival Storage'), Transition(label='Material Sampling')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Archival Storage'), Transition(label='Forensic Testing')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Archival Storage'), Transition(label='Ownership Audit')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Archival Storage'), Transition(label='Legal Verification')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Archival Storage'), Transition(label='Ethical Screening')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Archival Storage'), Transition(label='Expert Consultation')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Archival Storage'), Transition(label='Cultural Assessment')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Archival Storage'), Transition(label='Condition Survey')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Archival Storage'), Transition(label='Provenance Mapping')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Archival Storage'), Transition(label='Risk Analysis')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Archival Storage'), Transition(label='Report Compilation')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Archival Storage'), Transition(label='Acquisition Approval')]),
        OperatorPOWL(operator=Operator.LOOP, children=[Transition(label='Archival Storage'), Transition(label='Repatriation Review')]),
    ],
    order=[
        ('Initial Inquiry', 'Document Review'),
        ('Initial Inquiry', 'Historical Research'),
        ('Initial Inquiry', 'Material Sampling'),
        ('Initial Inquiry', 'Forensic Testing'),
        ('Initial Inquiry', 'Ownership Audit'),
        ('Initial Inquiry', 'Legal Verification'),
        ('Initial Inquiry', 'Ethical Screening'),
        ('Initial Inquiry', 'Expert Consultation'),
        ('Initial Inquiry', 'Cultural Assessment'),
        ('Initial Inquiry', 'Condition Survey'),
        ('Initial Inquiry', 'Provenance Mapping'),
        ('Initial Inquiry', 'Risk Analysis'),
        ('Initial Inquiry', 'Report Compilation'),
        ('Initial Inquiry', 'Acquisition Approval'),
        ('Initial Inquiry', 'Repatriation Review'),
        ('Initial Inquiry', 'Archival Storage'),
        ('Document Review', 'Historical Research'),
        ('Document Review', 'Material Sampling'),
        ('Document Review', 'Forensic Testing'),
        ('Document Review', 'Ownership Audit'),
        ('Document Review', 'Legal Verification'),
        ('Document Review', 'Ethical Screening'),
        ('Document Review', 'Expert Consultation'),
        ('Document Review', 'Cultural Assessment'),
        ('Document Review', 'Condition Survey'),
        ('Document Review', 'Provenance Mapping'),
        ('Document Review', 'Risk Analysis'),
        ('Document Review', 'Report Compilation'),
        ('Document Review', 'Acquisition Approval'),
        ('Document Review', 'Repatriation Review'),
        ('Document Review', 'Archival Storage'),
        ('Historical Research', 'Material Sampling'),
        ('Historical Research', 'Forensic Testing'),
        ('Historical Research', 'Ownership Audit'),
        ('Historical Research', 'Legal Verification'),
        ('Historical Research', 'Ethical Screening'),
        ('Historical Research', 'Expert Consultation'),
        ('Historical Research', 'Cultural Assessment'),
        ('Historical Research', 'Condition Survey'),
        ('Historical Research', 'Provenance Mapping'),
        ('Historical Research', 'Risk Analysis'),
        ('Historical Research', 'Report Compilation'),
        ('Historical Research', 'Acquisition Approval'),
        ('Historical Research', 'Repatriation Review'),
        ('Historical Research', 'Archival Storage'),
        ('Material Sampling', 'Forensic Testing'),
        ('Material Sampling', 'Ownership Audit'),
        ('Material Sampling', 'Legal Verification'),
        ('Material Sampling', 'Ethical Screening'),
        ('Material Sampling', 'Expert Consultation'),
        ('Material Sampling', 'Cultural Assessment'),
        ('Material Sampling', 'Condition Survey'),
        ('Material Sampling', 'Provenance Mapping'),
        ('Material Sampling', 'Risk Analysis'),
        ('Material Sampling', 'Report Compilation'),
        ('Material Sampling', 'Acquisition Approval'),
        ('Material Sampling', 'Repatriation Review'),
        ('Material Sampling', 'Archival Storage'),
        ('Forensic Testing', 'Ownership Audit'),
        ('Forensic Testing', 'Legal Verification'),
        ('Forensic Testing', 'Ethical Screening'),
        ('Forensic Testing', 'Expert Consultation'),
        ('Forensic Testing', 'Cultural Assessment'),
        ('Forensic Testing', 'Condition Survey'),
        ('Forensic Testing', 'Provenance Mapping'),
        ('Forensic Testing', 'Risk Analysis'),
        ('Forensic Testing', 'Report Compilation'),
        ('Forensic Testing', 'Acquisition Approval'),
        ('Forensic Testing', 'Repatriation Review'),
        ('Forensic Testing', 'Archival Storage'),
        ('Ownership Audit', 'Legal Verification'),
        ('Ownership Audit', 'Ethical Screening'),
        ('Ownership Audit', 'Expert Consultation'),
        ('Ownership Audit', 'Cultural Assessment'),
        ('Ownership Audit', 'Condition Survey'),
        ('Ownership Audit', 'Provenance Mapping'),
        ('Ownership Audit', 'Risk Analysis'),
        ('Ownership Audit', 'Report Compilation'),
        ('Ownership Audit', 'Acquisition Approval'),
        ('Ownership Audit', 'Repatriation Review'),
        ('Ownership Audit', 'Archival Storage'),
        ('Legal Verification', 'Ethical Screening'),
        ('Legal Verification', 'Expert Consultation'),
        ('Legal Verification', 'Cultural Assessment'),
        ('Legal Verification', 'Condition Survey'),
        ('Legal Verification', 'Provenance Mapping'),
        ('Legal Verification', 'Risk Analysis'),
        ('Legal Verification', 'Report Compilation'),
        ('Legal Verification', 'Acquisition Approval'),
        ('Legal Verification', 'Repatriation Review'),
        ('Legal Verification', 'Archival Storage'),
        ('Ethical Screening', 'Expert Consultation'),
        ('Ethical Screening', 'Cultural Assessment'),
        ('Ethical Screening', 'Condition Survey'),
        ('Ethical Screening', 'Provenance Mapping'),
        ('Ethical Screening', 'Risk Analysis'),
        ('Ethical Screening', 'Report Compilation'),
        ('Ethical Screening', 'Acquisition Approval'),
        ('Ethical Screening', 'Repatriation Review'),
        ('Ethical Screening', 'Archival Storage'),
        ('Expert Consultation', 'Cultural Assessment'),
        ('Expert Consultation', 'Condition Survey'),
        ('Expert Consultation', 'Provenance Mapping'),
        ('Expert Consultation', 'Risk Analysis'),
        ('Expert Consultation', 'Report Compilation'),
        ('Expert Consultation', 'Acquisition Approval'),
        ('Expert Consultation', 'Repatriation Review'),
        ('Expert Consultation', 'Archival Storage'),
        ('Cultural Assessment', 'Condition Survey'),
        ('Cultural Assessment', 'Provenance Mapping'),
        ('Cultural Assessment', 'Risk Analysis'),
        ('Cultural Assessment', 'Report Compilation'),
        ('Cultural Assessment', 'Acquisition Approval'),
        ('Cultural Assessment', 'Repatriation Review'),
        ('Cultural Assessment', 'Archival Storage'),
        ('Condition Survey', 'Provenance Mapping'),
        ('Condition Survey', 'Risk Analysis'),
        ('Condition Survey', 'Report Compilation'),
        ('Condition Survey', 'Acquisition Approval'),
        ('Condition Survey', 'Repatriation Review'),
        ('Condition Survey', 'Archival Storage'),
        ('Provenance Mapping', 'Risk Analysis'),
        ('Provenance Mapping', 'Report Compilation'),
        ('Provenance Mapping', 'Acquisition Approval'),
        ('Provenance Mapping', 'Repatriation Review'),
        ('Provenance Mapping', 'Archival Storage'),
        ('Risk Analysis', 'Report Compilation'),
        ('Risk Analysis', 'Acquisition Approval'),
        ('Risk Analysis', 'Repatriation Review'),
        ('Risk Analysis', 'Archival Storage'),
        ('Report Compilation', 'Acquisition Approval'),
        ('Report Compilation', 'Repatriation Review'),
        ('Report Compilation', 'Archival Storage'),
        ('Acquisition Approval', 'Repatriation Review'),
        ('Acquisition Approval', 'Archival Storage'),
        ('Repatriation Review', 'Archival Storage'),
    ]
)