import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
A = Transition(label='Site Analysis')
B = Transition(label='Env Assessment')
C = Transition(label='System Design')
D = Transition(label='Equipment Order')
E = Transition(label='Seed Selection')
F = Transition(label='Install Modules')
G = Transition(label='Calibrate Systems')
H = Transition(label='Staff Training')
I = Transition(label='Plant Seeding')
J = Transition(label='IoT Monitoring')
K = Transition(label='Data Analytics')
L = Transition(label='Nutrient Adjust')
M = Transition(label='Pest Control')
N = Transition(label='Maintenance Check')
O = Transition(label='Market Launch')
P = Transition(label='Logistics Setup')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[I, J, K, L, M, N, O, P])
xor = OperatorPOWL(operator=Operator.XOR, children=[F, G, H, skip])
root = StrictPartialOrder(nodes=[A, B, C, D, E, xor, loop])
root.order.add_edge(A, B)
root.order.add_edge(B, C)
root.order.add_edge(C, D)
root.order.add_edge(D, E)
root.order.add_edge(E, xor)
root.order.add_edge(xor, F)
root.order.add_edge(F, G)
root.order.add_edge(G, H)
root.order.add_edge(H, xor)
root.order.add_edge(xor, I)
root.order.add_edge(I, J)
root.order.add_edge(J, K)
root.order.add_edge(K, L)
root.order.add_edge(L, M)
root.order.add_edge(M, N)
root.order.add_edge(N, O)
root.order.add_edge(O, P)
root.order.add_edge(P, loop)