A = Transition(label='Site Survey')
B = Transition(label='Env Analysis')
C = Transition(label='Module Design')
D = Transition(label='Seed Selection')
E = Transition(label='Nutrient Mix')
F = Transition(label='Climate Setup')
G = Transition(label='LED Install')
H = Transition(label='Sensor Deploy')
I = Transition(label='Pest Control')
J = Transition(label='Waste Recycle')
K = Transition(label='Hydro Test')
L = Transition(label='Staff Train')
M = Transition(label='Yield Forecast')
N = Transition(label='Market Plan')
O = Transition(label='Data Review')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O])
xor = OperatorPOWL(operator=Operator.XOR, children=[loop, skip])
root = StrictPartialOrder(nodes=[xor])
root.order.add_edge(loop, xor)