root = StrictPartialOrder(
    nodes=[
        Transition(label='Site Analysis'),
        Transition(label='Zoning Review'),
        Transition(label='Modular Design'),
        Transition(label='Climate Setup'),
        Transition(label='Nutrient Mix'),
        Transition(label='Seed Selection'),
        Transition(label='AI Monitoring'),
        Transition(label='Lighting Control'),
        Transition(label='Energy Audit'),
        Transition(label='Water Reclaim'),
        Transition(label='Waste Sorting'),
        Transition(label='Community Meet'),
        Transition(label='Staff Training'),
        Transition(label='Yield Forecast'),
        Transition(label='Market Sync'),
        Transition(label='Supply Chain'),
        OperatorPOWL(operator=Operator.LOOP, children=[
            Transition(label='Site Analysis'),
            Transition(label='Zoning Review'),
            Transition(label='Modular Design'),
            Transition(label='Climate Setup'),
            Transition(label='Nutrient Mix'),
            Transition(label='Seed Selection'),
            Transition(label='AI Monitoring'),
            Transition(label='Lighting Control'),
            Transition(label='Energy Audit'),
            Transition(label='Water Reclaim'),
            Transition(label='Waste Sorting'),
            Transition(label='Community Meet'),
            Transition(label='Staff Training'),
            Transition(label='Yield Forecast'),
            Transition(label='Market Sync'),
            Transition(label='Supply Chain')
        ]),
        OperatorPOWL(operator=Operator.XOR, children=[
            Transition(label='Energy Audit'),
            OperatorPOWL(operator=Operator.LOOP, children=[
                Transition(label='Site Analysis'),
                Transition(label='Zoning Review'),
                Transition(label='Modular Design'),
                Transition(label='Climate Setup'),
                Transition(label='Nutrient Mix'),
                Transition(label='Seed Selection'),
                Transition(label='AI Monitoring'),
                Transition(label='Lighting Control'),
                Transition(label='Energy Audit'),
                Transition(label='Water Reclaim'),
                Transition(label='Waste Sorting'),
                Transition(label='Community Meet'),
                Transition(label='Staff Training'),
                Transition(label='Yield Forecast'),
                Transition(label='Market Sync'),
                Transition(label='Supply Chain')
            ])
        ])
    ],
    order={
        ('Site Analysis', 'Zoning Review'): None,
        ('Site Analysis', 'Modular Design'): None,
        ('Site Analysis', 'Climate Setup'): None,
        ('Site Analysis', 'Nutrient Mix'): None,
        ('Site Analysis', 'Seed Selection'): None,
        ('Site Analysis', 'AI Monitoring'): None,
        ('Site Analysis', 'Lighting Control'): None,
        ('Site Analysis', 'Energy Audit'): None,
        ('Site Analysis', 'Water Reclaim'): None,
        ('Site Analysis', 'Waste Sorting'): None,
        ('Site Analysis', 'Community Meet'): None,
        ('Site Analysis', 'Staff Training'): None,
        ('Site Analysis', 'Yield Forecast'): None,
        ('Site Analysis', 'Market Sync'): None,
        ('Site Analysis', 'Supply Chain'): None,
        ('Zoning Review', 'Modular Design'): None,
        ('Zoning Review', 'Climate Setup'): None,
        ('Zoning Review', 'Nutrient Mix'): None,
        ('Zoning Review', 'Seed Selection'): None,
        ('Zoning Review', 'AI Monitoring'): None,
        ('Zoning Review', 'Lighting Control'): None,
        ('Zoning Review', 'Energy Audit'): None,
        ('Zoning Review', 'Water Reclaim'): None,
        ('Zoning Review', 'Waste Sorting'): None,
        ('Zoning Review', 'Community Meet'): None,
        ('Zoning Review', 'Staff Training'): None,
        ('Zoning Review', 'Yield Forecast'): None,
        ('Zoning Review', 'Market Sync'): None,
        ('Zoning Review', 'Supply Chain'): None,
        ('Modular Design', 'Climate Setup'): None,
        ('Modular Design', 'Nutrient Mix'): None,
        ('Modular Design', 'Seed Selection'): None,
        ('Modular Design', 'AI Monitoring'): None,
        ('Modular Design', 'Lighting Control'): None,
        ('Modular Design', 'Energy Audit'): None,
        ('Modular Design', 'Water Reclaim'): None,
        ('Modular Design', 'Waste Sorting'): None,
        ('Modular Design', 'Community Meet'): None,
        ('Modular Design', 'Staff Training'): None,
        ('Modular Design', 'Yield Forecast'): None,
        ('Modular Design', 'Market Sync'): None,
        ('Modular Design', 'Supply Chain'): None,
        ('Climate Setup', 'Nutrient Mix'): None,
        ('Climate Setup', 'Seed Selection'): None,
        ('Climate Setup', 'AI Monitoring'): None,
        ('Climate Setup', 'Lighting Control'): None,
        ('Climate Setup', 'Energy Audit'): None,
        ('Climate Setup', 'Water Reclaim'): None,
        ('Climate Setup', 'Waste Sorting'): None,
        ('Climate Setup', 'Community Meet'): None,
        ('Climate Setup', 'Staff Training'): None,
        ('Climate Setup', 'Yield Forecast'): None,
        ('Climate Setup', 'Market Sync'): None,
        ('Climate Setup', 'Supply Chain'): None,
        ('Nutrient Mix', 'Seed Selection'): None,
        ('Nutrient Mix', 'AI Monitoring'): None,
        ('Nutrient Mix', 'Lighting Control'): None,
        ('Nutrient Mix', 'Energy Audit'): None,
        ('Nutrient Mix', 'Water Reclaim'): None,
        ('Nutrient Mix', 'Waste Sorting'): None,
        ('Nutrient Mix', 'Community Meet'): None,
        ('Nutrient Mix', 'Staff Training'): None,
        ('Nutrient Mix', 'Yield Forecast'): None,
        ('Nutrient Mix', 'Market Sync'): None,
        ('Nutrient Mix', 'Supply Chain'): None,
        ('Seed Selection', 'AI Monitoring'): None,
        ('Seed Selection', 'Lighting Control'): None,
        ('Seed Selection', 'Energy Audit'): None,
        ('Seed Selection', 'Water Reclaim'): None,
        ('Seed Selection', 'Waste Sorting'): None,
        ('Seed Selection', 'Community Meet'): None,
        ('Seed Selection', 'Staff Training'): None,
        ('Seed Selection', 'Yield Forecast'): None,
        ('Seed Selection', 'Market Sync'): None,
        ('Seed Selection', 'Supply Chain'): None,
        ('AI Monitoring', 'Lighting Control'): None,
        ('AI Monitoring', 'Energy Audit'): None,
        ('AI Monitoring', 'Water Reclaim'): None,
        ('AI Monitoring', 'Waste Sorting'): None,
        ('AI Monitoring', 'Community Meet'): None,
        ('AI Monitoring', 'Staff Training'): None,
        ('AI Monitoring', 'Yield Forecast'): None,
        ('AI Monitoring', 'Market Sync'): None,
        ('AI Monitoring', 'Supply Chain'): None,
        ('Lighting Control', 'Energy Audit'): None,
        ('Lighting Control', 'Water Reclaim'): None,
        ('Lighting Control', 'Waste Sorting'): None,
        ('Lighting Control', 'Community Meet'): None,
        ('Lighting Control', 'Staff Training'): None,
        ('Lighting Control', 'Yield Forecast'): None,
        ('Lighting Control', 'Market Sync'): None,
        ('Lighting Control', 'Supply Chain'): None,
        ('Energy Audit', 'Water Reclaim'): None,
        ('Energy Audit', 'Waste Sorting'): None,
        ('Energy Audit', 'Community Meet'): None,
        ('Energy Audit', 'Staff Training'): None,
        ('Energy Audit', 'Yield Forecast'): None,
        ('Energy Audit', 'Market Sync'): None,
        ('Energy Audit', 'Supply Chain'): None,
        ('Water Reclaim', 'Waste Sorting'): None,
        ('Water Reclaim', 'Community Meet'): None,
        ('Water Reclaim', 'Staff Training'): None,
        ('Water Reclaim', 'Yield Forecast'): None,
        ('Water Reclaim', 'Market Sync'): None,
        ('Water Reclaim', 'Supply Chain'): None,
        ('Waste Sorting', 'Community Meet'): None,
        ('Waste Sorting', 'Staff Training'): None,
        ('Waste Sorting', 'Yield Forecast'): None,
        ('Waste Sorting', 'Market Sync'): None,
        ('Waste Sorting', 'Supply Chain'): None,
        ('Community Meet', 'Staff Training'): None,
        ('Community Meet', 'Yield Forecast'): None,
        ('Community Meet', 'Market Sync'): None,
        ('Community Meet', 'Supply Chain'): None,
        ('Staff Training', 'Yield Forecast'): None,
        ('Staff Training', 'Market Sync'): None,
        ('Staff Training', 'Supply Chain'): None,
        ('Yield Forecast', 'Market Sync'): None,
        ('Yield Forecast', 'Supply Chain'): None,
        ('Market Sync', 'Supply Chain'): None
    }
)