import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
root = StrictPartialOrder(nodes=[])
root.order = set()
for activity in ['Site Survey', 'Regulation Check', 'Design Modules', 'Install Hydroponics', 'Integrate Sensors', 'Calibrate Nutrients', 'Program Climate', 'Select Crops', 'Optimize Lighting', 'Train Staff', 'Plan Harvest', 'Recycle Waste', 'Analyze Demand', 'Plan Logistics', 'Monitor Systems']:
    root.order.add((activity, activity))
root.order.add((activity, activity + ' - Check'))
root.order.add((activity, activity + ' - Design'))
root.order.add((activity, activity + ' - Install'))
root.order.add((activity, activity + ' - Integrate'))
root.order.add((activity, activity + ' - Calibrate'))
root.order.add((activity, activity + ' - Program'))
root.order.add((activity, activity + ' - Select'))
root.order.add((activity, activity + ' - Optimize'))
root.order.add((activity, activity + ' - Train'))
root.order.add((activity, activity + ' - Plan'))
root.order.add((activity, activity + ' - Analyze'))
root.order.add((activity, activity + ' - Plan'))
root.order.add((activity, activity + ' - Monitor'))
root.order.add((activity, activity + ' - Waste'))
root.order.add((activity, activity + ' - Harvest'))
root.order.add((activity, activity + ' - Distribution'))
root.order.add((activity, activity + ' - Check'))
root.order.add((activity, activity + ' - Design'))
root.order.add((activity, activity + ' - Install'))
root.order.add((activity, activity + ' - Integrate'))
root.order.add((activity, activity + ' - Calibrate'))
root.order.add((activity, activity + ' - Program'))
root.order.add((activity, activity + ' - Select'))
root.order.add((activity, activity + ' - Optimize'))
root.order.add((activity, activity + ' - Train'))
root.order.add((activity, activity + ' - Plan'))
root.order.add((activity, activity + ' - Analyze'))
root.order.add((activity, activity + ' - Plan'))
root.order.add((activity, activity + ' - Monitor'))
root.order.add((activity, activity + ' - Waste'))
root.order.add((activity, activity + ' - Harvest'))
root.order.add((activity, activity + ' - Distribution'))