A = Transition(label='Artifact Intake')
B = Transition(label='Preliminary Check')
C = Transition(label='Historical Review')
D = Transition(label='Chemical Test')
E = Transition(label='Provenance Audit')
F = Transition(label='Expert Panel')
G = Transition(label='Token Minting')
H = Transition(label='Legal Review')
I = Transition(label='Compliance Check')
J = Transition(label='Insurance Valuation')
K = Transition(label='Risk Assessment')
L = Transition(label='Packaging Prep')
M = Transition(label='Climate Control')
N = Transition(label='Transport Setup')
O = Transition(label='Final Approval')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)
root.order.add_edge(B, C)
root.order.add_edge(B, D)
root.order.add_edge(B, E)
root.order.add_edge(B, F)
root.order.add_edge(B, G)
root.order.add_edge(B, H)
root.order.add_edge(B, I)
root.order.add_edge(B, J)
root.order.add_edge(B, K)
root.order.add_edge(B, L)
root.order.add_edge(B, M)
root.order.add_edge(B, N)
root.order.add_edge(B, O)