import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_survey = Transition(label='Site Survey')
climate_check = Transition(label='Climate Check')
soil_testing = Transition(label='Soil Testing')
media_select = Transition(label='Media Select')
design_layout = Transition(label='Design Layout')
hydro_setup = Transition(label='Hydro Setup')
nutrient_mix = Transition(label='Nutrient Mix')
sensor_install = Transition(label='Sensor Install')
regulation_review = Transition(label='Regulation Review')
permit_apply = Transition(label='Permit Apply')
stakeholder_meet = Transition(label='Stakeholder Meet')
community_train = Transition(label='Community Train')
plant_seed = Transition(label='Plant Seed')
monitor_growth = Transition(label='Monitor Growth')
adjust_controls = Transition(label='Adjust Controls')
harvest_plan = Transition(label='Harvest Plan')
waste_recycle = Transition(label='Waste Recycle')
feedback_loop = Transition(label='Feedback Loop')

site_survey_choice = OperatorPOWL(operator=Operator.XOR, children=[site_survey, climate_check])
soil_testing_choice = OperatorPOWL(operator=Operator.XOR, children=[soil_testing, media_select])
design_layout_choice = OperatorPOWL(operator=Operator.XOR, children=[design_layout, hydro_setup])
nutrient_mix_choice = OperatorPOWL(operator=Operator.XOR, children=[nutrient_mix, sensor_install])
regulation_review_choice = OperatorPOWL(operator=Operator.XOR, children=[regulation_review, permit_apply])
stakeholder_meet_choice = OperatorPOWL(operator=Operator.XOR, children=[stakeholder_meet, community_train])
plant_seed_choice = OperatorPOWL(operator=Operator.XOR, children=[plant_seed, monitor_growth])
adjust_controls_choice = OperatorPOWL(operator=Operator.XOR, children=[adjust_controls, harvest_plan])
waste_recycle_choice = OperatorPOWL(operator=Operator.XOR, children=[waste_recycle, feedback_loop])

root = StrictPartialOrder(nodes=[site_survey_choice, soil_testing_choice, design_layout_choice, nutrient_mix_choice, regulation_review_choice, stakeholder_meet_choice, plant_seed_choice, adjust_controls_choice, waste_recycle_choice])
root.order.add_edge(site_survey_choice, soil_testing_choice)
root.order.add_edge(soil_testing_choice, design_layout_choice)
root.order.add_edge(design_layout_choice, nutrient_mix_choice)
root.order.add_edge(nutrient_mix_choice, regulation_review_choice)
root.order.add_edge(regulation_review_choice, stakeholder_meet_choice)
root.order.add_edge(stakeholder_meet_choice, plant_seed_choice)
root.order.add_edge(plant_seed_choice, adjust_controls_choice)
root.order.add_edge(adjust_controls_choice, waste_recycle_choice)