import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
A = Transition(label='Milk Sourcing')
B = Transition(label='Supplier Audit')
C = Transition(label='Culture Prep')
D = Transition(label='Milk Testing')
E = Transition(label='Fermentation Start')
F = Transition(label='pH Monitoring')
G = Transition(label='Curd Cutting')
H = Transition(label='Mold Inoculation')
I = Transition(label='Aging Setup')
J = Transition(label='Humidity Control')
K = Transition(label='Texture Check')
L = Transition(label='Flavor Profiling')
M = Transition(label='Batch Labeling')
N = Transition(label='Packaging')
O = Transition(label='Distribution')
P = Transition(label='Feedback Review')
Q = Transition(label='Sustainability Audit')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip, loop])
root = StrictPartialOrder(nodes=[xor])
root.order.add_edge(xor, skip)
root.order.add_edge(xor, loop)