root = StrictPartialOrder(
    nodes=[
        Transition(label='Site Survey'),
        Transition(label='Env Assessment'),
        Transition(label='Reg Compliance'),
        Transition(label='Modular Setup'),
        Transition(label='Crop Selection'),
        Transition(label='IoT Integration'),
        Transition(label='Nutrient Flow'),
        Transition(label='Light Calibration'),
        Transition(label='Staff Training'),
        Transition(label='Pest Control'),
        Transition(label='Market Strategy'),
        Transition(label='Logistics Plan'),
        Transition(label='Yield Analysis'),
        Transition(label='Data Review'),
        Transition(label='Community Engage'),
    ],
    order={
        'Site Survey': ['Env Assessment'],
        'Env Assessment': ['Reg Compliance'],
        'Reg Compliance': ['Modular Setup'],
        'Modular Setup': ['Crop Selection'],
        'Crop Selection': ['IoT Integration'],
        'IoT Integration': ['Nutrient Flow'],
        'Nutrient Flow': ['Light Calibration'],
        'Light Calibration': ['Staff Training'],
        'Staff Training': ['Pest Control'],
        'Pest Control': ['Market Strategy'],
        'Market Strategy': ['Logistics Plan'],
        'Logistics Plan': ['Yield Analysis'],
        'Yield Analysis': ['Data Review'],
        'Data Review': ['Community Engage'],
    }
)