import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_survey = Transition(label='Site Survey')
permit_check = Transition(label='Permit Check')
hive_setup = Transition(label='Hive Setup')
community_meet = Transition(label='Community Meet')
hive_monitor = Transition(label='Hive Monitor')
pest_control = Transition(label='Pest Control')
honey_harvest = Transition(label='Honey Harvest')
data_logging = Transition(label='Data Logging')
workshop_plan = Transition(label='Workshop Plan')
supply_order = Transition(label='Supply Order')
volunteer_coord = Transition(label='Volunteer Coord')
regulation_review = Transition(label='Regulation Review')
pollination_map = Transition(label='Pollination Map')
apiary_audit = Transition(label='Apiary Audit')
feedback_gather = Transition(label='Feedback Gather')
waste_manage = Transition(label='Waste Manage')

skip = SilentTransition()

site_survey_and_permit_check = OperatorPOWL(operator=Operator.XOR, children=[site_survey, permit_check])
hive_setup_and_community_meet = OperatorPOWL(operator=Operator.XOR, children=[hive_setup, community_meet])
hive_monitor_and_pest_control = OperatorPOWL(operator=Operator.XOR, children=[hive_monitor, pest_control])
honey_harvest_and_data_logging = OperatorPOWL(operator=Operator.XOR, children=[honey_harvest, data_logging])
workshop_plan_and_supply_order = OperatorPOWL(operator=Operator.XOR, children=[workshop_plan, supply_order])
volunteer_coord_and_regulation_review = OperatorPOWL(operator=Operator.XOR, children=[volunteer_coord, regulation_review])
pollination_map_and_apiary_audit = OperatorPOWL(operator=Operator.XOR, children=[pollination_map, apiary_audit])
feedback_gather_and_waste_manage = OperatorPOWL(operator=Operator.XOR, children=[feedback_gather, waste_manage])

root = StrictPartialOrder(nodes=[site_survey_and_permit_check, hive_setup_and_community_meet, hive_monitor_and_pest_control, honey_harvest_and_data_logging, workshop_plan_and_supply_order, volunteer_coord_and_regulation_review, pollination_map_and_apiary_audit, feedback_gather_and_waste_manage])
root.order.add_edge(site_survey_and_permit_check, hive_setup_and_community_meet)
root.order.add_edge(site_survey_and_permit_check, hive_monitor_and_pest_control)
root.order.add_edge(site_survey_and_permit_check, honey_harvest_and_data_logging)
root.order.add_edge(site_survey_and_permit_check, workshop_plan_and_supply_order)
root.order.add_edge(site_survey_and_permit_check, volunteer_coord_and_regulation_review)
root.order.add_edge(site_survey_and_permit_check, pollination_map_and_apiary_audit)
root.order.add_edge(site_survey_and_permit_check, feedback_gather_and_waste_manage)
root.order.add_edge(hive_setup_and_community_meet, hive_monitor_and_pest_control)
root.order.add_edge(hive_setup_and_community_meet, honey_harvest_and_data_logging)
root.order.add_edge(hive_setup_and_community_meet, workshop_plan_and_supply_order)
root.order.add_edge(hive_setup_and_community_meet, volunteer_coord_and_regulation_review)
root.order.add_edge(hive_setup_and_community_meet, pollination_map_and_apiary_audit)
root.order.add_edge(hive_setup_and_community_meet, feedback_gather_and_waste_manage)
root.order.add_edge(hive_monitor_and_pest_control, honey_harvest_and_data_logging)
root.order.add_edge(hive_monitor_and_pest_control, workshop_plan_and_supply_order)
root.order.add_edge(hive_monitor_and_pest_control, volunteer_coord_and_regulation_review)
root.order.add_edge(hive_monitor_and_pest_control, pollination_map_and_apiary_audit)
root.order.add_edge(hive_monitor_and_pest_control, feedback_gather_and_waste_manage)
root.order.add_edge(honey_harvest_and_data_logging, workshop_plan_and_supply_order)
root.order.add_edge(honey_harvest_and_data_logging, volunteer_coord_and_regulation_review)
root.order.add_edge(honey_harvest_and_data_logging, pollination_map_and_apiary_audit)
root.order.add_edge(honey_harvest_and_data_logging, feedback_gather_and_waste_manage)
root.order.add_edge(workshop_plan_and_supply_order, volunteer_coord_and_regulation_review)
root.order.add_edge(workshop_plan_and_supply_order, pollination_map_and_apiary_audit)
root.order.add_edge(workshop_plan_and_supply_order, feedback_gather_and_waste_manage)
root.order.add_edge(volunteer_coord_and_regulation_review, pollination_map_and_apiary_audit)
root.order.add_edge(volunteer_coord_and_regulation_review, feedback_gather_and_waste_manage)
root.order.add_edge(pollination_map_and_apiary_audit, feedback_gather_and_waste_manage)