A = Transition(label='Site Survey')
B = Transition(label='Design Layout')
C = Transition(label='Permit Acquire')
D = Transition(label='Modular Build')
E = Transition(label='Climate Setup')
F = Transition(label='Nutrient Mix')
G = Transition(label='Seed Automation')
H = Transition(label='Pest Control')
I = Transition(label='Energy Audit')
J = Transition(label='Sensor Install')
K = Transition(label='Growth Monitor')
L = Transition(label='Waste Process')
M = Transition(label='Data Analysis')
N = Transition(label='Staff Train')
O = Transition(label='Community Link')
P = Transition(label='Yield Report')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip, loop])
root = StrictPartialOrder(nodes=[xor])
root.order.add_edge(loop, xor)
root.order.add_edge(xor, xor)