import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
A = Transition(label='Site Analysis')
B = Transition(label='Structural Check')
C = Transition(label='System Design')
D = Transition(label='Hydroponics Setup')
E = Transition(label='Lighting Install')
F = Transition(label='Sensor Install')
G = Transition(label='Climate Control')
H = Transition(label='Nutrient Monitor')
I = Transition(label='Seed Selection')
J = Transition(label='Germination Start')
K = Transition(label='Auto Planting')
L = Transition(label='Growth Monitoring')
M = Transition(label='AI Analytics')
N = Transition(label='Robotic Harvest')
O = Transition(label='Packaging')
P = Transition(label='Trace Labeling')
Q = Transition(label='Logistics Plan')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)