root = StrictPartialOrder(nodes=[Transition(label='Soil Analyze'), Transition(label='Site Mapping'), Transition(label='Bed Setup'), Transition(label='Crop Select'), Transition(label='Sensor Deploy'), Transition(label='Irrigation Adjust'), Transition(label='Nutrient Feed'), Transition(label='Pest Scouting'), Transition(label='Pest Predict'), Transition(label='Workshop Host'), Transition(label='Crop Rotate'), Transition(label='Waste Compost'), Transition(label='Water Recycle'), Transition(label='Data Analyze'), Transition(label='Cycle Refine'), Transition(label='Resource Share'), Transition(label='Yield Report')])

root.order.add_edge(root.nodes[0], root.nodes[1])
root.order.add_edge(root.nodes[1], root.nodes[2])
root.order.add_edge(root.nodes[2], root.nodes[3])
root.order.add_edge(root.nodes[3], root.nodes[4])
root.order.add_edge(root.nodes[4], root.nodes[5])
root.order.add_edge(root.nodes[5], root.nodes[6])
root.order.add_edge(root.nodes[6], root.nodes[7])
root.order.add_edge(root.nodes[7], root.nodes[8])
root.order.add_edge(root.nodes[8], root.nodes[9])
root.order.add_edge(root.nodes[9], root.nodes[10])
root.order.add_edge(root.nodes[10], root.nodes[11])
root.order.add_edge(root.nodes[11], root.nodes[12])
root.order.add_edge(root.nodes[12], root.nodes[13])
root.order.add_edge(root.nodes[13], root.nodes[14])
root.order.add_edge(root.nodes[14], root.nodes[15])
root.order.add_edge(root.nodes[15], root.nodes[16])