root = StrictPartialOrder(
    nodes=[
        Transition('Site Survey'),
        Transition('Structural Check'),
        Transition('Climate Study'),
        Transition('Soil Prep'),
        Transition('Seed Selection'),
        Transition('Irrigation Setup'),
        Transition('Nutrient Mix'),
        Transition('Sensor Install'),
        Transition('Pest Monitor'),
        Transition('Data Analysis'),
        Transition('Regulation Review'),
        Transition('Community Meet'),
        Transition('Harvest Plan'),
        Transition('Packaging Design'),
        Transition('Distribution Map'),
        Transition('Feedback Loop'),
        Transition('Maintenance Schedule'),
    ],
    order={
        'Site Survey': 'Structural Check',
        'Structural Check': 'Climate Study',
        'Climate Study': 'Soil Prep',
        'Soil Prep': 'Seed Selection',
        'Seed Selection': 'Irrigation Setup',
        'Irrigation Setup': 'Nutrient Mix',
        'Nutrient Mix': 'Sensor Install',
        'Sensor Install': 'Pest Monitor',
        'Pest Monitor': 'Data Analysis',
        'Data Analysis': 'Regulation Review',
        'Regulation Review': 'Community Meet',
        'Community Meet': 'Harvest Plan',
        'Harvest Plan': 'Packaging Design',
        'Packaging Design': 'Distribution Map',
        'Distribution Map': 'Feedback Loop',
        'Feedback Loop': 'Maintenance Schedule',
    }
)