A = Transition(label='Ingredient Sourcing')
B = Transition(label='Botanical Extraction')
C = Transition(label='Initial Blending')
D = Transition(label='Sensory Testing')
E = Transition(label='Chemical Analysis')
F = Transition(label='Recipe Refinement')
G = Transition(label='Stability Check')
H = Transition(label='Client Sampling')
I = Transition(label='Feedback Review')
J = Transition(label='Final Adjustment')
K = Transition(label='Custom Packaging')
L = Transition(label='Label Design')
M = Transition(label='Hand Labeling')
N = Transition(label='Regulatory Audit')
O = Transition(label='Batch Documentation')
P = Transition(label='Limited Release')
Q = Transition(label='Market Launch')
skip = SilentTransition()
ingredient_sourcing = OperatorPOWL(operator=Operator.PARALLEL, children=[A, B])
botanical_extraction = OperatorPOWL(operator=Operator.PARALLEL, children=[C, D])
initial_blending = OperatorPOWL(operator=Operator.PARALLEL, children=[E, F])
sensory_testing = OperatorPOWL(operator=Operator.PARALLEL, children=[G, H])
chemical_analysis = OperatorPOWL(operator=Operator.PARALLEL, children=[I, J])
recipe_refinement = OperatorPOWL(operator=Operator.PARALLEL, children=[K, L])
custom_packaging = OperatorPOWL(operator=Operator.PARALLEL, children=[M, N])
hand_labeling = OperatorPOWL(operator=Operator.PARALLEL, children=[O, P])
regulatory_audit = OperatorPOWL(operator=Operator.PARALLEL, children=[Q, skip])
root = StrictPartialOrder(nodes=[ingredient_sourcing, botanical_extraction, initial_blending, sensory_testing, chemical_analysis, recipe_refinement, custom_packaging, hand_labeling, regulatory_audit])
root.order.add_edge(ingredient_sourcing, botanical_extraction)
root.order.add_edge(botanical_extraction, initial_blending)
root.order.add_edge(initial_blending, sensory_testing)
root.order.add_edge(sensory_testing, chemical_analysis)
root.order.add_edge(chemical_analysis, recipe_refinement)
root.order.add_edge(recipe_refinement, custom_packaging)
root.order.add_edge(custom_packaging, hand_labeling)
root.order.add_edge(hand_labeling, regulatory_audit)