import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
A = Transition(label='Ingredient Sourcing')
B = Transition(label='Botanical Extraction')
C = Transition(label='Initial Blending')
D = Transition(label='Sensory Testing')
E = Transition(label='Chemical Analysis')
F = Transition(label='Recipe Refinement')
G = Transition(label='Stability Check')
H = Transition(label='Client Sampling')
I = Transition(label='Feedback Review')
J = Transition(label='Final Adjustment')
K = Transition(label='Custom Packaging')
L = Transition(label='Label Design')
M = Transition(label='Hand Labeling')
N = Transition(label='Regulatory Audit')
O = Transition(label='Batch Documentation')
P = Transition(label='Limited Release')
Q = Transition(label='Market Launch')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[D, E, F, G, H, I, J, K, L, M, N, O, P, Q])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip, loop])
root = StrictPartialOrder(nodes=[A, B, C, xor])
root.order.add_edge(A, B)
root.order.add_edge(B, C)
root.order.add_edge(C, D)
root.order.add_edge(D, E)
root.order.add_edge(E, F)
root.order.add_edge(F, G)
root.order.add_edge(G, H)
root.order.add_edge(H, I)
root.order.add_edge(I, J)
root.order.add_edge(J, K)
root.order.add_edge(K, L)
root.order.add_edge(L, M)
root.order.add_edge(M, N)
root.order.add_edge(N, O)
root.order.add_edge(O, P)
root.order.add_edge(P, Q)