import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
A = Transition(label='Artifact Intake')
B = Transition(label='Provenance Check')
C = Transition(label='Material Sampling')
D = Transition(label='Scientific Test')
E = Transition(label='Expert Review')
F = Transition(label='Archive Search')
G = Transition(label='Legal Verify')
H = Transition(label='Ownership Confirm')
I = Transition(label='Compliance Audit')
J = Transition(label='Data Documentation')
K = Transition(label='Interim Report')
L = Transition(label='Department Review')
M = Transition(label='Consensus Meeting')
N = Transition(label='Final Approval')
O = Transition(label='Artifact Release')
skip = SilentTransition()
loop1 = OperatorPOWL(operator=Operator.LOOP, children=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip, loop1])
root = StrictPartialOrder(nodes=[xor])
root.order.add_edge(xor, loop1)
root.order.add_edge(loop1, xor)