import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
IntakeReview = Transition(label='Intake Review')
PreliminaryInspect = Transition(label='Preliminary Inspect')
ProvenanceCheck = Transition(label='Provenance Check')
ArchivalResearch = Transition(label='Archival Research')
MaterialTesting = Transition(label='Material Testing')
RadiocarbonDate = Transition(label='Radiocarbon Date')
StylisticAssess = Transition(label='Stylistic Assess')
ExpertConsult = Transition(label='Expert Consult')
FindingsCompile = Transition(label='Findings Compile')
InternalReview = Transition(label='Internal Review')
ClientPresent = Transition(label='Client Present')
ApprovalConfirm = Transition(label='Approval Confirm')
SecurePackage = Transition(label='Secure Package')
TransportArrange = Transition(label='Transport Arrange')
ChainCustody = Transition(label='Chain Custody')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[IntakeReview, PreliminaryInspect, ProvenanceCheck, ArchivalResearch, MaterialTesting, RadiocarbonDate, StylisticAssess, ExpertConsult, FindingsCompile, InternalReview, ClientPresent, ApprovalConfirm, SecurePackage, TransportArrange, ChainCustody])
xor = OperatorPOWL(operator=Operator.XOR, children=[TransportArrange, skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)