root = StrictPartialOrder(nodes=[ArtifactIntake, CatalogEntry, VisualInspect, MaterialTest, Spectroscopy, HistoricalCheck, ProvenanceTrace, StyleCompare, ThreeDScanning, ConditionAssess, PreservationPlan, LegalReview, ReportDraft, ReportFinalize, ArchiveData, SalePrep])
root.order.add_edge(ArtifactIntake, CatalogEntry)
root.order.add_edge(CatalogEntry, VisualInspect)
root.order.add_edge(VisualInspect, MaterialTest)
root.order.add_edge(MaterialTest, Spectroscopy)
root.order.add_edge(Spectroscopy, HistoricalCheck)
root.order.add_edge(HistoricalCheck, ProvenanceTrace)
root.order.add_edge(ProvenanceTrace, StyleCompare)
root.order.add_edge(StyleCompare, ThreeDScanning)
root.order.add_edge(ThreeDScanning, ConditionAssess)
root.order.add_edge(ConditionAssess, PreservationPlan)
root.order.add_edge(PreservationPlan, LegalReview)
root.order.add_edge(LegalReview, ReportDraft)
root.order.add_edge(ReportDraft, ReportFinalize)
root.order.add_edge(ReportFinalize, ArchiveData)
root.order.add_edge(ArchiveData, SalePrep)