import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
A = Transition(label='Site Survey')
B = Transition(label='Permit Review')
C = Transition(label='Design Layout')
D = Transition(label='Material Sourcing')
E = Transition(label='Irrigation Setup')
F = Transition(label='Sensor Install')
G = Transition(label='Structural Test')
H = Transition(label='Recruit Farmers')
I = Transition(label='Trial Planting')
J = Transition(label='Pest Control')
K = Transition(label='Soilless Prep')
L = Transition(label='System Calibrate')
M = Transition(label='Data Monitor')
N = Transition(label='Harvest Plan')
O = Transition(label='Community Outreach')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O])
xor = OperatorPOWL(operator=Operator.XOR, children=[loop, skip])
root = StrictPartialOrder(nodes=[xor])
root.order.add_edge(xor, A)
root.order.add_edge(xor, B)
root.order.add_edge(xor, C)
root.order.add_edge(xor, D)
root.order.add_edge(xor, E)
root.order.add_edge(xor, F)
root.order.add_edge(xor, G)
root.order.add_edge(xor, H)
root.order.add_edge(xor, I)
root.order.add_edge(xor, J)
root.order.add_edge(xor, K)
root.order.add_edge(xor, L)
root.order.add_edge(xor, M)
root.order.add_edge(xor, N)
root.order.add_edge(xor, O)