import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define the POWL model
root = StrictPartialOrder()

# Define the transitions (activities)
site_analysis = Transition(label='Site Analysis')
climate_setup = Transition(label='Climate Setup')
nutrient_mix = Transition(label='Nutrient Mix')
seed_germinate = Transition(label='Seed Germinate')
auto_planting = Transition(label='Auto Planting')
irrigation_setup = Transition(label='Irrigation Setup')
iot_monitoring = Transition(label='IoT Monitoring')
pest_detection = Transition(label='Pest Detection')
drone_pollinate = Transition(label='Drone Pollinate')
pesticide_spray = Transition(label='Pesticide Spray')
robotic_harvest = Transition(label='Robotic Harvest')
quality_check = Transition(label='Quality Check')
package_product = Transition(label='Package Product')
waste_recycle = Transition(label='Waste Recycle')
energy_optimize = Transition(label='Energy Optimize')
data_logging = Transition(label='Data Logging')

# Define the operators
xor = OperatorPOWL(operator=Operator.XOR, children=[pest_detection, drone_pollinate, pesticide_spray])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor8 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor9 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor10 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor11 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor12 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor13 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor14 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor15 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor16 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor17 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor18 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor19 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor20 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor21 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor22 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor23 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor24 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor25 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor26 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor27 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor28 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor29 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor30 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor31 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor32 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor33 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor34 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor35 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor36 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor37 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor38 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor39 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor40 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor41 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor42 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor43 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor44 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor45 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor46 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor47 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor48 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor49 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor50 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor51 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor52 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor53 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor54 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor55 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor56 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor57 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor58 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor59 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor60 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor61 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor62 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor63 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor64 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor65 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor66 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor67 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor68 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor69 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor70 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor71 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor72 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor73 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor74 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor75 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor76 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor77 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor78 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor79 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor80 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor81 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor82 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor83 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor84 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor85 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor86 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor87 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor88 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor89 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor90 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor91 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor92 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor93 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor94 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor95 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor96 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor97 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor98 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor99 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor100 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor101 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor102 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor103 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor104 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor105 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor106 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor107 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor108 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor109 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor110 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor111 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor112 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor113 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor114 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor115 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor116 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor117 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor118 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor119 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor120 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor121 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor122 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor123 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor124 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor125 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor126 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor127 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor128 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor129 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor130 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor131 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor132 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor133 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor134 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor135 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor136 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor137 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor138 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor139 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor140 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor141 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor142 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor143 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor144 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor145 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor146 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor147 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor148 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor149 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor150 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor151 = OperatorPOWL(operator=Operator.XOR, children=[pesticide_spray, data_logging])
xor152 = OperatorPOWL(operator=Operator.XOR, children=[drone_pollinate, pesticide_spray, data_logging])
xor153 = OperatorPOWL(operator=