import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

Milk_Sourcing = Transition(label='Milk Sourcing')
Culture_Selection = Transition(label='Culture Selection')
Milk_Testing = Transition(label='Milk Testing')
Curd_Cutting = Transition(label='Curd Cutting')
Whey_Draining = Transition(label='Whey Draining')
Mold_Inoculation = Transition(label='Mold Inoculation')
Forming_Cheese = Transition(label='Forming Cheese')
Salting_Stage = Transition(label='Salting Stage')
Aging_Setup = Transition(label='Aging Setup')
Climate_Control = Transition(label='Climate Control')
Quality_Tasting = Transition(label='Quality Tasting')
Packaging_Prep = Transition(label='Packaging Prep')
Label_Printing = Transition(label='Label Printing')
Distribution_Plan = Transition(label='Distribution Plan')
Retail_Delivery = Transition(label='Retail Delivery')
Event_Coordination = Transition(label='Event Coordination')
Regulatory_Audit = Transition(label='Regulatory Audit')

skip = SilentTransition()

# Define the process model using POWL
loop1 = OperatorPOWL(operator=Operator.LOOP, children=[Aging_Setup, Climate_Control, Quality_Tasting, Regulatory_Audit])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[Packaging_Prep, Label_Printing, Distribution_Plan])
xor1 = OperatorPOWL(operator=Operator.XOR, children=[Retail_Delivery, Event_Coordination])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor1])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor2])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor3])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor4])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor5])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor6])
xor8 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor7])
xor9 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor8])
xor10 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor9])
xor11 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor10])
xor12 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor11])
xor13 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor12])
xor14 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor13])
xor15 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor14])
xor16 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor15])
xor17 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor16])
xor18 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor17])
xor19 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor18])
xor20 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor19])
xor21 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor20])
xor22 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor21])
xor23 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor22])
xor24 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor23])
xor25 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor24])
xor26 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor25])
xor27 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor26])
xor28 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor27])
xor29 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor28])
xor30 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor29])
xor31 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor30])
xor32 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor31])
xor33 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor32])
xor34 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor33])
xor35 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor34])
xor36 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor35])
xor37 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor36])
xor38 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor37])
xor39 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor38])
xor40 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor39])
xor41 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor40])
xor42 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor41])
xor43 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor42])
xor44 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor43])
xor45 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor44])
xor46 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor45])
xor47 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor46])
xor48 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor47])
xor49 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor48])
xor50 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor49])
xor51 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor50])
xor52 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor51])
xor53 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor52])
xor54 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor53])
xor55 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor54])
xor56 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor55])
xor57 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor56])
xor58 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor57])
xor59 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor58])
xor60 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor59])
xor61 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor60])
xor62 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor61])
xor63 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor62])
xor64 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor63])
xor65 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor64])
xor66 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor65])
xor67 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor66])
xor68 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor67])
xor69 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor68])
xor70 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor69])
xor71 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor70])
xor72 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor71])
xor73 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor72])
xor74 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor73])
xor75 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor74])
xor76 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor75])
xor77 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor76])
xor78 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor77])
xor79 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor78])
xor80 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor79])
xor81 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor80])
xor82 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor81])
xor83 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor82])
xor84 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor83])
xor85 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor84])
xor86 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor85])
xor87 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor86])
xor88 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor87])
xor89 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor88])
xor90 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor89])
xor91 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor90])
xor92 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor91])
xor93 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor92])
xor94 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor93])
xor95 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor94])
xor96 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor95])
xor97 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor96])
xor98 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor97])
xor99 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor98])
xor100 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor99])
xor101 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor100])
xor102 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor101])
xor103 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor102])
xor104 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor103])
xor105 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor104])
xor106 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor105])
xor107 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor106])
xor108 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor107])
xor109 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor108])
xor110 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor109])
xor111 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor110])
xor112 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor111])
xor113 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor112])
xor114 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor113])
xor115 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor114])
xor116 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor115])
xor117 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor116])
xor118 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor117])
xor119 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor118])
xor120 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor119])
xor121 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor120])
xor122 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor121])
xor123 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor122])
xor124 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor123])
xor125 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor124])
xor126 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor125])
xor127 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor126])
xor128 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor127])
xor129 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor128])
xor130 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor129])
xor131 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor130])
xor132 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor131])
xor133 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor132])
xor134 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor133])
xor135 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor134])
xor136 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor135])
xor137 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor136])
xor138 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor137])
xor139 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor138])
xor140 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor139])
xor141 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor140])
xor142 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor141])
xor143 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor142])
xor144 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor143])
xor145 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor144])
xor146 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor145])
xor147 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor146])
xor148 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor147])
xor149 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor148])
xor150 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor149])
xor151 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor150])
xor152 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor151])
xor153 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor152])
xor154 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor153])
xor155 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor154])
xor156 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor155])
xor157 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor156])
xor158 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor157])
xor159 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor158])
xor160 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor159])
xor161 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor160])
xor162 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor161])
xor163 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor162])
xor164 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor163])
xor165 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor164])
xor166 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor165])
xor167 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor166])
xor168 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor167])
xor169 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor168])
xor170 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor169])
xor171 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor170])
xor172 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor171])
xor173 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor172])
xor174 = OperatorPOWL(operator=Operator.XOR, children=[skip, xor