import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

client_brief = Transition(label='Client Brief')
design_draft = Transition(label='Design Draft')
part_sourcing = Transition(label='Part Sourcing')
component_fabric = Transition(label='Component Fabric')
circuit_assembly = Transition(label='Circuit Assembly')
software_upload = Transition(label='Software Upload')
initial_testing = Transition(label='Initial Testing')
flight_calibrate = Transition(label='Flight Calibrate')
payload_mount = Transition(label='Payload Mount')
stress_testing = Transition(label='Stress Testing')
feedback_loop = Transition(label='Feedback Loop')
quality_check = Transition(label='Quality Check')
certification = Transition(label='Certification')
packaging = Transition(label='Packaging')
delivery_plan = Transition(label='Delivery Plan')
post_support = Transition(label='Post Support')
skip = SilentTransition()

# Initial client consultation
client_brief_next_design_draft = OperatorPOWL(operator=Operator.XOR, children=[client_brief, skip])
design_draft_next_part_sourcing = OperatorPOWL(operator=Operator.XOR, children=[design_draft, skip])
part_sourcing_next_component_fabric = OperatorPOWL(operator=Operator.XOR, children=[part_sourcing, skip])
component_fabric_next_circuit_assembly = OperatorPOWL(operator=Operator.XOR, children=[component_fabric, skip])
circuit_assembly_next_software_upload = OperatorPOWL(operator=Operator.XOR, children=[circuit_assembly, skip])
software_upload_next_initial_testing = OperatorPOWL(operator=Operator.XOR, children=[software_upload, skip])
initial_testing_next_flight_calibrate = OperatorPOWL(operator=Operator.XOR, children=[initial_testing, skip])
flight_calibrate_next_payload_mount = OperatorPOWL(operator=Operator.XOR, children=[flight_calibrate, skip])
payload_mount_next_stress_testing = OperatorPOWL(operator=Operator.XOR, children=[payload_mount, skip])
stress_testing_next_feedback_loop = OperatorPOWL(operator=Operator.XOR, children=[stress_testing, skip])
feedback_loop_next_quality_check = OperatorPOWL(operator=Operator.XOR, children=[feedback_loop, skip])
quality_check_next_certification = OperatorPOWL(operator=Operator.XOR, children=[quality_check, skip])
certification_next_packaging = OperatorPOWL(operator=Operator.XOR, children=[certification, skip])
packaging_next_delivery_plan = OperatorPOWL(operator=Operator.XOR, children=[packaging, skip])
delivery_plan_next_post_support = OperatorPOWL(operator=Operator.XOR, children=[delivery_plan, skip])

# Define the loop for feedback between hardware adjustments and software tuning
loop = OperatorPOWL(operator=Operator.LOOP, children=[initial_testing, software_upload])

# Define the partial order
root = StrictPartialOrder(nodes=[client_brief_next_design_draft, design_draft_next_part_sourcing, part_sourcing_next_component_fabric, component_fabric_next_circuit_assembly, circuit_assembly_next_software_upload, software_upload_next_initial_testing, initial_testing_next_flight_calibrate, flight_calibrate_next_payload_mount, payload_mount_next_stress_testing, stress_testing_next_feedback_loop, feedback_loop_next_quality_check, quality_check_next_certification, certification_next_packaging, packaging_next_delivery_plan, delivery_plan_next_post_support, loop])
root.order.add_edge(client_brief_next_design_draft, design_draft_next_part_sourcing)
root.order.add_edge(design_draft_next_part_sourcing, part_sourcing_next_component_fabric)
root.order.add_edge(part_sourcing_next_component_fabric, component_fabric_next_circuit_assembly)
root.order.add_edge(component_fabric_next_circuit_assembly, circuit_assembly_next_software_upload)
root.order.add_edge(circuit_assembly_next_software_upload, software_upload_next_initial_testing)
root.order.add_edge(software_upload_next_initial_testing, initial_testing_next_flight_calibrate)
root.order.add_edge(initial_testing_next_flight_calibrate, flight_calibrate_next_payload_mount)
root.order.add_edge(flight_calibrate_next_payload_mount, payload_mount_next_stress_testing)
root.order.add_edge(payload_mount_next_stress_testing, stress_testing_next_feedback_loop)
root.order.add_edge(stress_testing_next_feedback_loop, feedback_loop_next_quality_check)
root.order.add_edge(feedback_loop_next_quality_check, quality_check_next_certification)
root.order.add_edge(quality_check_next_certification, certification_next_packaging)
root.order.add_edge(certification_next_packaging, packaging_next_delivery_plan)
root.order.add_edge(packaging_next_delivery_plan, delivery_plan_next_post_support)
root.order.add_edge(delivery_plan_next_post_support, loop)
root.order.add_edge(loop, initial_testing)
root.order.add_edge(loop, software_upload)