import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_survey = Transition(label='Site Survey')
permit_review = Transition(label='Permit Review')
design_layout = Transition(label='Design Layout')
system_assembly = Transition(label='System Assembly')
climate_setup = Transition(label='Climate Setup')
nutrient_prep = Transition(label='Nutrient Prep')
irrigation_test = Transition(label='Irrigation Test')
lighting_config = Transition(label='Lighting Config')
energy_install = Transition(label='Energy Install')
sensor_setup = Transition(label='Sensor Setup')
automation_deploy = Transition(label='Automation Deploy')
crop_seeding = Transition(label='Crop Seeding')
waste_plan = Transition(label='Waste Plan')
staff_training = Transition(label='Staff Training')
community_outreach = Transition(label='Community Outreach')
yield_monitor = Transition(label='Yield Monitor')
maintenance_check = Transition(label='Maintenance Check')

skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[site_survey, permit_review])
xor = OperatorPOWL(operator=Operator.XOR, children=[design_layout, system_assembly])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, nutrient_prep])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[irrigation_test, lighting_config])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[energy_install, sensor_setup])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[automation_deploy, crop_seeding])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[waste_plan, staff_training])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[community_outreach, yield_monitor])
xor8 = OperatorPOWL(operator=Operator.XOR, children=[maintenance_check])

root = StrictPartialOrder(nodes=[loop, xor, xor2, xor3, xor4, xor5, xor6, xor7, xor8])
root.order.add_edge(loop, xor)
root.order.add_edge(xor, xor2)
root.order.add_edge(xor2, xor3)
root.order.add_edge(xor3, xor4)
root.order.add_edge(xor4, xor5)
root.order.add_edge(xor5, xor6)
root.order.add_edge(xor6, xor7)
root.order.add_edge(xor7, xor8)
root.order.add_edge(xor8, loop)

print(root)