import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define the transitions
initial_assess = Transition(label='Initial Assess')
disassemble_parts = Transition(label='Disassemble Parts')
ultrasonic_clean = Transition(label='Ultrasonic Clean')
inspect_components = Transition(label='Inspect Components')
fabricate_gears = Transition(label='Fabricate Gears')
dial_restoration = Transition(label='Dial Restoration')
repaint_markers = Transition(label='Repaint Markers')
reassemble_movement = Transition(label='Reassemble Movement')
lubricate_bearings = Transition(label='Lubricate Bearings')
calibrate_timing = Transition(label='Calibrate Timing')
polish_case = Transition(label='Polish Case')
re_case_watch = Transition(label='Re-case Watch')
quality_testing = Transition(label='Quality Testing')
document_process = Transition(label='Document Process')
package_product = Transition(label='Package Product')

# Define the silent transitions
skip1 = SilentTransition()
skip2 = SilentTransition()
skip3 = SilentTransition()
skip4 = SilentTransition()

# Define the exclusive choice operators
xor1 = OperatorPOWL(operator=Operator.XOR, children=[fabricate_gears, skip1])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[repaint_markers, skip2])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[reassemble_movement, skip3])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[lubricate_bearings, skip4])

# Define the loop operators
loop1 = OperatorPOWL(operator=Operator.LOOP, children=[inspect_components, xor1])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[dial_restoration, xor2])
loop3 = OperatorPOWL(operator=Operator.LOOP, children=[calibrate_timing, xor3])
loop4 = OperatorPOWL(operator=Operator.LOOP, children=[polish_case, xor4])

# Define the root model
root = StrictPartialOrder(nodes=[initial_assess, disassemble_parts, ultrasonic_clean, loop1, loop2, loop3, loop4, xor1, xor2, xor3, xor4, reassemble_movement, lubricate_bearings, calibrate_timing, polish_case, re_case_watch, quality_testing, document_process, package_product])
root.order.add_edge(initial_assess, disassemble_parts)
root.order.add_edge(disassemble_parts, ultrasonic_clean)
root.order.add_edge(ultrasonic_clean, loop1)
root.order.add_edge(loop1, inspect_components)
root.order.add_edge(inspect_components, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, fabricate_gears)
root.order.add_edge(fabricate_gears, inspect_components)
root.order.add_edge(inspect_components, loop1)
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, skip1)
root.order.add_edge(skip1, inspect_components)
root.order.add_edge(inspect_components, loop1)
root