root = StrictPartialOrder(
    nodes=[
        Transition(label='Client Consult'),
        Transition(label='Payload Assess'),
        Transition(label='Drone Configure'),
        Transition(label='Regulation Check'),
        Transition(label='Flight Simulate'),
        Transition(label='Route Optimize'),
        Transition(label='Package Secure'),
        Transition(label='Pre-Flight Inspect'),
        Transition(label='Weather Monitor'),
        Transition(label='Launch Drone'),
        Transition(label='Flight Track'),
        Transition(label='Delivery Confirm'),
        Transition(label='Data Analyze'),
        Transition(label='Feedback Collect'),
        Transition(label='Warranty Register'),
        Transition(label='Issue Resolve'),
        Transition(label='Package Return'),
    ],
    order={
        'Client Consult': 'Payload Assess',
        'Payload Assess': 'Drone Configure',
        'Drone Configure': 'Regulation Check',
        'Regulation Check': 'Flight Simulate',
        'Flight Simulate': 'Route Optimize',
        'Route Optimize': 'Package Secure',
        'Package Secure': 'Pre-Flight Inspect',
        'Pre-Flight Inspect': 'Weather Monitor',
        'Weather Monitor': 'Launch Drone',
        'Launch Drone': 'Flight Track',
        'Flight Track': 'Delivery Confirm',
        'Delivery Confirm': 'Data Analyze',
        'Data Analyze': 'Feedback Collect',
        'Feedback Collect': 'Warranty Register',
        'Warranty Register': 'Issue Resolve',
        'Issue Resolve': 'Package Return',
    }
)