import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
SiteSurvey = Transition(label='Site Survey')
StructuralAudit = Transition(label='Structural Audit')
PermitFiling = Transition(label='Permit Filing')
DesignLayout = Transition(label='Design Layout')
InstallHVAC = Transition(label='Install HVAC')
SetLighting = Transition(label='Set Lighting')
BuildRacks = Transition(label='Build Racks')
InstallHydroponics = Transition(label='Install Hydroponics')
ConfigureSensors = Transition(label='Configure Sensors')
SelectCrops = Transition(label='Select Crops')
SeedPlanting = Transition(label='Seed Planting')
MonitorGrowth = Transition(label='Monitor Growth')
NutrientMixing = Transition(label='Nutrient Mixing')
StaffTraining = Transition(label='Staff Training')
MarketLaunch = Transition(label='Market Launch')
WasteRecycling = Transition(label='Waste Recycling')
CustomerOnboarding = Transition(label='Customer Onboarding')
skip = SilentTransition()
loop1 = OperatorPOWL(operator=Operator.LOOP, children=[SiteSurvey, StructuralAudit, PermitFiling, DesignLayout, InstallHVAC, SetLighting, BuildRacks, InstallHydroponics, ConfigureSensors])
xor1 = OperatorPOWL(operator=Operator.XOR, children=[SelectCrops, SeedPlanting])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[MonitorGrowth, NutrientMixing, StaffTraining, MarketLaunch])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[WasteRecycling, CustomerOnboarding])
root = StrictPartialOrder(nodes=[loop1, xor1, loop2, xor2])
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, loop2)
root.order.add_edge(loop2, xor2)