import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
DiscoverItem = Transition(label='Discover Item')
DocumentFind = Transition(label='Document Find')
InitialSurvey = Transition(label='Initial Survey')
ImageCapture = Transition(label='Image Capture')
MaterialTesting = Transition(label='Material Testing')
StyleCompare = Transition(label='Style Compare')
ExpertConsult = Transition(label='Expert Consult')
ProvenanceCheck = Transition(label='Provenance Check')
OwnershipVerify = Transition(label='Ownership Verify')
LegalReview = Transition(label='Legal Review')
RiskAssess = Transition(label='Risk Assess')
ConservationPlan = Transition(label='Conservation Plan')
Certification = Transition(label='Certification')
SecureTransfer = Transition(label='Secure Transfer')
DisputeResolve = Transition(label='Dispute Resolve')
FinalArchive = Transition(label='Final Archive')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[DiscoverItem, DocumentFind, InitialSurvey, ImageCapture, MaterialTesting, StyleCompare, ExpertConsult, ProvenanceCheck, OwnershipVerify, LegalReview, RiskAssess, ConservationPlan, Certification, SecureTransfer, DisputeResolve, FinalArchive])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip, loop])
root = StrictPartialOrder(nodes=[xor])
root.order.add_edge(xor, loop)