import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

initial_assess = Transition(label='Initial Assess')
condition_scan = Transition(label='Condition Scan')
material_test = Transition(label='Material Test')
historical_check = Transition(label='Historical Check')
provenance_verify = Transition(label='Provenance Verify')
parts_sourcing = Transition(label='Parts Sourcing')
gentle_clean = Transition(label='Gentle Clean')
stabilize_item = Transition(label='Stabilize Item')
structural_repair = Transition(label='Structural Repair')
surface_finish = Transition(label='Surface Finish')
expert_consult = Transition(label='Expert Consult')
archival_review = Transition(label='Archival Review')
ethics_audit = Transition(label='Ethics Audit')
quality_inspect = Transition(label='Quality Inspect')
photo_document = Transition(label='Photo Document')
packaging_prep = Transition(label='Packaging Prep')
report_generate = Transition(label='Report Generate')
certify_provenance = Transition(label='Certify Provenance')

skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[initial_assess, condition_scan, material_test, historical_check, provenance_verify, parts_sourcing, gentle_clean, stabilize_item, structural_repair, surface_finish])
xor = OperatorPOWL(operator=Operator.XOR, children=[expert_consult, archival_review, ethics_audit])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[quality_inspect, photo_document])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[packaging_prep, report_generate])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[certify_provenance, skip])

root = StrictPartialOrder(nodes=[loop, xor, xor2, xor3, xor4])
root.order.add_edge(loop, xor)
root.order.add_edge(loop, xor2)
root.order.add_edge(loop, xor3)
root.order.add_edge(loop, xor4)