import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_survey = Transition(label='Site Survey')
load_test = Transition(label='Load Test')
soil_sample = Transition(label='Soil Sample')
crop_select = Transition(label='Crop Select')
irrigation_plan = Transition(label='Irrigation Plan')
permit_apply = Transition(label='Permit Apply')
material_order = Transition(label='Material Order')
bed_install = Transition(label='Bed Install')
pest_control = Transition(label='Pest Control')
solar_setup = Transition(label='Solar Setup')
staff_train = Transition(label='Staff Train')
market_outreach = Transition(label='Market Outreach')
system_setup = Transition(label='System Setup')
supplier_contact = Transition(label='Supplier Contact')
health_monitor = Transition(label='Health Monitor')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[load_test, soil_sample, crop_select, irrigation_plan])
xor = OperatorPOWL(operator=Operator.XOR, children=[permit_apply, material_order])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[bed_install, pest_control])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[solar_setup, skip])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[staff_train, market_outreach])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[system_setup, supplier_contact])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[health_monitor, skip])
root = StrictPartialOrder(nodes=[loop, xor, xor2, xor3, xor4, xor5, xor6])
root.order.add_edge(loop, xor)
root.order.add_edge(xor, xor2)
root.order.add_edge(xor2, xor3)
root.order.add_edge(xor3, xor4)
root.order.add_edge(xor4, xor5)
root.order.add_edge(xor5, xor6)
root.order.add_edge(xor6, loop)