import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
A = Transition(label='Light Sourcing')
B = Transition(label='Nutrient Order')
C = Transition(label='Climate Setup')
D = Transition(label='Growth Planning')
E = Transition(label='Seed Planting')
F = Transition(label='Irrigation Check')
G = Transition(label='Pest Monitoring')
H = Transition(label='Energy Tracking')
I = Transition(label='Quality Testing')
J = Transition(label='Data Analysis')
K = Transition(label='Equipment Repair')
L = Transition(label='Packaging Prep')
M = Transition(label='Inventory Update')
N = Transition(label='Delivery Scheduling')
O = Transition(label='Customer Feedback')
P = Transition(label='Market Forecast')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)