import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

Site_Survey = Transition(label='Site Survey')
Design_Layout = Transition(label='Design Layout')
System_Build = Transition(label='System Build')
Install_Sensors = Transition(label='Install Sensors')
Select_Crops = Transition(label='Select Crops')
Setup_Lighting = Transition(label='Setup Lighting')
Configure_Climate = Transition(label='Configure Climate')
Nutrient_Mix = Transition(label='Nutrient Mix')
Automate_Watering = Transition(label='Automate Watering')
Test_Systems = Transition(label='Test Systems')
Train_Staff = Transition(label='Train Staff')
Waste_Plan = Transition(label='Waste Plan')
Market_Link = Transition(label='Market Link')
Data_Monitor = Transition(label='Data Monitor')
Optimize_Yield = Transition(label='Optimize Yield')

skip = SilentTransition()

Site_Survey_to_Design_Layout = OperatorPOWL(operator=Operator.XOR, children=[Site_Survey, skip])
Design_Layout_to_System_Build = OperatorPOWL(operator=Operator.XOR, children=[Design_Layout, skip])
System_Build_to_Install_Sensors = OperatorPOWL(operator=Operator.XOR, children=[System_Build, skip])
Install_Sensors_to_Select_Crops = OperatorPOWL(operator=Operator.XOR, children=[Install_Sensors, skip])
Select_Crops_to_Setup_Lighting = OperatorPOWL(operator=Operator.XOR, children=[Select_Crops, skip])
Setup_Lighting_to_Configure_Climate = OperatorPOWL(operator=Operator.XOR, children=[Setup_Lighting, skip])
Configure_Climate_to_Nutrient_Mix = OperatorPOWL(operator=Operator.XOR, children=[Configure_Climate, skip])
Nutrient_Mix_to_Automate_Watering = OperatorPOWL(operator=Operator.XOR, children=[Nutrient_Mix, skip])
Automate_Watering_to_Test_Systems = OperatorPOWL(operator=Operator.XOR, children=[Automate_Watering, skip])
Test_Systems_to_Train_Staff = OperatorPOWL(operator=Operator.XOR, children=[Test_Systems, skip])
Train_Staff_to_Waste_Plan = OperatorPOWL(operator=Operator.XOR, children=[Train_Staff, skip])
Waste_Plan_to_Market_Link = OperatorPOWL(operator=Operator.XOR, children=[Waste_Plan, skip])
Market_Link_to_Data_Monitor = OperatorPOWL(operator=Operator.XOR, children=[Market_Link, skip])
Data_Monitor_to_Optimize_Yield = OperatorPOWL(operator=Operator.XOR, children=[Data_Monitor, skip])

root = StrictPartialOrder(nodes=[Site_Survey_to_Design_Layout, Design_Layout_to_System_Build, System_Build_to_Install_Sensors, Install_Sensors_to_Select_Crops, Select_Crops_to_Setup_Lighting, Setup_Lighting_to_Configure_Climate, Configure_Climate_to_Nutrient_Mix, Nutrient_Mix_to_Automate_Watering, Automate_Watering_to_Test_Systems, Test_Systems_to_Train_Staff, Train_Staff_to_Waste_Plan, Waste_Plan_to_Market_Link, Market_Link_to_Data_Monitor, Data_Monitor_to_Optimize_Yield])

root.order.add_edge(Site_Survey_to_Design_Layout, Design_Layout_to_System_Build)
root.order.add_edge(Design_Layout_to_System_Build, System_Build_to_Install_Sensors)
root.order.add_edge(System_Build_to_Install_Sensors, Install_Sensors_to_Select_Crops)
root.order.add_edge(Install_Sensors_to_Select_Crops, Select_Crops_to_Setup_Lighting)
root.order.add_edge(Select_Crops_to_Setup_Lighting, Setup_Lighting_to_Configure_Climate)
root.order.add_edge(Setup_Lighting_to_Configure_Climate, Configure_Climate_to_Nutrient_Mix)
root.order.add_edge(Configure_Climate_to_Nutrient_Mix, Nutrient_Mix_to_Automate_Watering)
root.order.add_edge(Nutrient_Mix_to_Automate_Watering, Automate_Watering_to_Test_Systems)
root.order.add_edge(Automate_Watering_to_Test_Systems, Test_Systems_to_Train_Staff)
root.order.add_edge(Test_Systems_to_Train_Staff, Train_Staff_to_Waste_Plan)
root.order.add_edge(Train_Staff_to_Waste_Plan, Waste_Plan_to_Market_Link)
root.order.add_edge(Waste_Plan_to_Market_Link, Market_Link_to_Data_Monitor)
root.order.add_edge(Market_Link_to_Data_Monitor, Data_Monitor_to_Optimize_Yield)