import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
Milk_Sourcing = Transition(label='Milk Sourcing')
Quality_Testing = Transition(label='Quality Testing')
Batch_Selection = Transition(label='Batch Selection')
Curd_Preparation = Transition(label='Curd Preparation')
Pressing_Cheese = Transition(label='Pressing Cheese')
Aging_Control = Transition(label='Aging Control')
Flavor_Profiling = Transition(label='Flavor Profiling')
Packaging_Prep = Transition(label='Packaging Prep')
Climate_Packing = Transition(label='Climate Packing')
Export_Licensing = Transition(label='Export Licensing')
Customs_Filing = Transition(label='Customs Filing')
Freight_Booking = Transition(label='Freight Booking')
Cold_Storage = Transition(label='Cold Storage')
Transport_Tracking = Transition(label='Transport Tracking')
Retail_Delivery = Transition(label='Retail Delivery')
Feedback_Collection = Transition(label='Feedback Collection')
skip = SilentTransition()
loop1 = OperatorPOWL(operator=Operator.LOOP, children=[Milk_Sourcing, Quality_Testing])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[Batch_Selection, Curd_Preparation])
loop3 = OperatorPOWL(operator=Operator.LOOP, children=[Pressing_Cheese, Aging_Control])
loop4 = OperatorPOWL(operator=Operator.LOOP, children=[Flavor_Profiling, Packaging_Prep])
loop5 = OperatorPOWL(operator=Operator.LOOP, children=[Climate_Packing, Export_Licensing])
loop6 = OperatorPOWL(operator=Operator.LOOP, children=[Customs_Filing, Freight_Booking])
loop7 = OperatorPOWL(operator=Operator.LOOP, children=[Cold_Storage, Transport_Tracking])
loop8 = OperatorPOWL(operator=Operator.LOOP, children=[Retail_Delivery, Feedback_Collection])
root = StrictPartialOrder(nodes=[loop1, loop2, loop3, loop4, loop5, loop6, loop7, loop8])
root.order.add_edge(loop1, loop2)
root.order.add_edge(loop2, loop3)
root.order.add_edge(loop3, loop4)
root.order.add_edge(loop4, loop5)
root.order.add_edge(loop5, loop6)
root.order.add_edge(loop6, loop7)
root.order.add_edge(loop7, loop8)
root.order.add_edge(loop8, loop1)