import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
site_survey = Transition(label='Site Survey')
structural_audit = Transition(label='Structural Audit')
layout_design = Transition(label='Layout Design')
system_install = Transition(label='System Install')
climate_setup = Transition(label='Climate Setup')
water_testing = Transition(label='Water Testing')
nutrient_mix = Transition(label='Nutrient Mix')
seed_selection = Transition(label='Seed Selection')
planting_prep = Transition(label='Planting Prep')
growth_monitor = Transition(label='Growth Monitor')
pest_inspect = Transition(label='Pest Inspect')
harvest_plan = Transition(label='Harvest Plan')
packaging_prep = Transition(label='Packaging Prep')
distribution = Transition(label='Distribution')
sustainability = Transition(label='Sustainability')
skip = SilentTransition()
loop_site = OperatorPOWL(operator=Operator.LOOP, children=[site_survey, structural_audit])
loop_layout = OperatorPOWL(operator=Operator.LOOP, children=[layout_design, system_install])
loop_climate = OperatorPOWL(operator=Operator.LOOP, children=[climate_setup, water_testing])
loop_nutrient = OperatorPOWL(operator=Operator.LOOP, children=[nutrient_mix, seed_selection])
loop_planting = OperatorPOWL(operator=Operator.LOOP, children=[planting_prep, growth_monitor])
loop_pest = OperatorPOWL(operator=Operator.LOOP, children=[pest_inspect, harvest_plan])
loop_packaging = OperatorPOWL(operator=Operator.LOOP, children=[packaging_prep, distribution])
loop_sustainability = OperatorPOWL(operator=Operator.LOOP, children=[sustainability, skip])
root = StrictPartialOrder(nodes=[loop_site, loop_layout, loop_climate, loop_nutrient, loop_planting, loop_pest, loop_packaging, loop_sustainability])
root.order.add_edge(loop_site, loop_layout)
root.order.add_edge(loop_layout, loop_climate)
root.order.add_edge(loop_climate, loop_nutrient)
root.order.add_edge(loop_nutrient, loop_planting)
root.order.add_edge(loop_planting, loop_pest)
root.order.add_edge(loop_pest, loop_packaging)
root.order.add_edge(loop_packaging, loop_sustainability)