import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define transitions for each activity
milk_sourcing = Transition(label='Milk Sourcing')
quality_testing = Transition(label='Quality Testing')
starter_prep = Transition(label='Starter Prep')
milk_pasteurize = Transition(label='Milk Pasteurize')
curd_formation = Transition(label='Curd Formation')
whey_drain = Transition(label='Whey Drain')
cheese_press = Transition(label='Cheese Press')
salting_process = Transition(label='Salting Process')
aging_setup = Transition(label='Aging Setup')
temperature_control = Transition(label='Temperature Control')
batch_labeling = Transition(label='Batch Labeling')
eco_packaging = Transition(label='Eco Packaging')
inventory_audit = Transition(label='Inventory Audit')
order_coordination = Transition(label='Order Coordination')
regulatory_check = Transition(label='Regulatory Check')
shipment_planning = Transition(label='Shipment Planning')
vendor_liaison = Transition(label='Vendor Liaison')
waste_reduction = Transition(label='Waste Reduction')

# Define silent transitions for each activity
skip_milk_sourcing = SilentTransition()
skip_quality_testing = SilentTransition()
skip_starter_prep = SilentTransition()
skip_milk_pasteurize = SilentTransition()
skip_curd_formation = SilentTransition()
skip_whey_drain = SilentTransition()
skip_cheese_press = SilentTransition()
skip_salting_process = SilentTransition()
skip_aging_setup = SilentTransition()
skip_temperature_control = SilentTransition()
skip_batch_labeling = SilentTransition()
skip_eco_packaging = SilentTransition()
skip_inventory_audit = SilentTransition()
skip_order_coordination = SilentTransition()
skip_regulatory_check = SilentTransition()
skip_shipment_planning = SilentTransition()
skip_vendor_liaison = SilentTransition()
skip_waste_reduction = SilentTransition()

# Define loop nodes for each activity
loop_milk_sourcing = OperatorPOWL(operator=Operator.LOOP, children=[milk_sourcing, skip_milk_sourcing])
loop_quality_testing = OperatorPOWL(operator=Operator.LOOP, children=[quality_testing, skip_quality_testing])
loop_starter_prep = OperatorPOWL(operator=Operator.LOOP, children=[starter_prep, skip_starter_prep])
loop_milk_pasteurize = OperatorPOWL(operator=Operator.LOOP, children=[milk_pasteurize, skip_milk_pasteurize])
loop_curd_formation = OperatorPOWL(operator=Operator.LOOP, children=[curd_formation, skip_curd_formation])
loop_whey_drain = OperatorPOWL(operator=Operator.LOOP, children=[whey_drain, skip_whey_drain])
loop_cheese_press = OperatorPOWL(operator=Operator.LOOP, children=[cheese_press, skip_cheese_press])
loop_salting_process = OperatorPOWL(operator=Operator.LOOP, children=[salting_process, skip_salting_process])
loop_aging_setup = OperatorPOWL(operator=Operator.LOOP, children=[aging_setup, skip_aging_setup])
loop_temperature_control = OperatorPOWL(operator=Operator.LOOP, children=[temperature_control, skip_temperature_control])
loop_batch_labeling = OperatorPOWL(operator=Operator.LOOP, children=[batch_labeling, skip_batch_labeling])
loop_eco_packaging = OperatorPOWL(operator=Operator.LOOP, children=[eco_packaging, skip_eco_packaging])
loop_inventory_audit = OperatorPOWL(operator=Operator.LOOP, children=[inventory_audit, skip_inventory_audit])
loop_order_coordination = OperatorPOWL(operator=Operator.LOOP, children=[order_coordination, skip_order_coordination])
loop_regulatory_check = OperatorPOWL(operator=Operator.LOOP, children=[regulatory_check, skip_regulatory_check])
loop_shipment_planning = OperatorPOWL(operator=Operator.LOOP, children=[shipment_planning, skip_shipment_planning])
loop_vendor_liaison = OperatorPOWL(operator=Operator.LOOP, children=[vendor_liaison, skip_vendor_liaison])
loop_waste_reduction = OperatorPOWL(operator=Operator.LOOP, children=[waste_reduction, skip_waste_reduction])

# Define XOR nodes for each activity
xor_milk_sourcing = OperatorPOWL(operator=Operator.XOR, children=[loop_milk_sourcing, skip_milk_sourcing])
xor_quality_testing = OperatorPOWL(operator=Operator.XOR, children=[loop_quality_testing, skip_quality_testing])
xor_starter_prep = OperatorPOWL(operator=Operator.XOR, children=[loop_starter_prep, skip_starter_prep])
xor_milk_pasteurize = OperatorPOWL(operator=Operator.XOR, children=[loop_milk_pasteurize, skip_milk_pasteurize])
xor_curd_formation = OperatorPOWL(operator=Operator.XOR, children=[loop_curd_formation, skip_curd_formation])
xor_whey_drain = OperatorPOWL(operator=Operator.XOR, children=[loop_whey_drain, skip_whey_drain])
xor_cheese_press = OperatorPOWL(operator=Operator.XOR, children=[loop_cheese_press, skip_cheese_press])
xor_salting_process = OperatorPOWL(operator=Operator.XOR, children=[loop_salting_process, skip_salting_process])
xor_aging_setup = OperatorPOWL(operator=Operator.XOR, children=[loop_aging_setup, skip_aging_setup])
xor_temperature_control = OperatorPOWL(operator=Operator.XOR, children=[loop_temperature_control, skip_temperature_control])
xor_batch_labeling = OperatorPOWL(operator=Operator.XOR, children=[loop_batch_labeling, skip_batch_labeling])
xor_eco_packaging = OperatorPOWL(operator=Operator.XOR, children=[loop_eco_packaging, skip_eco_packaging])
xor_inventory_audit = OperatorPOWL(operator=Operator.XOR, children=[loop_inventory_audit, skip_inventory_audit])
xor_order_coordination = OperatorPOWL(operator=Operator.XOR, children=[loop_order_coordination, skip_order_coordination])
xor_regulatory_check = OperatorPOWL(operator=Operator.XOR, children=[loop_regulatory_check, skip_regulatory_check])
xor_shipment_planning = OperatorPOWL(operator=Operator.XOR, children=[loop_shipment_planning, skip_shipment_planning])
xor_vendor_liaison = OperatorPOWL(operator=Operator.XOR, children=[loop_vendor_liaison, skip_vendor_liaison])
xor_waste_reduction = OperatorPOWL(operator=Operator.XOR, children=[loop_waste_reduction, skip_waste_reduction])

# Define the root POWL model
root = StrictPartialOrder(nodes=[xor_milk_sourcing, xor_quality_testing, xor_starter_prep, xor_milk_pasteurize, xor_curd_formation, xor_whey_drain, xor_cheese_press, xor_salting_process, xor_aging_setup, xor_temperature_control, xor_batch_labeling, xor_eco_packaging, xor_inventory_audit, xor_order_coordination, xor_regulatory_check, xor_shipment_planning, xor_vendor_liaison, xor_waste_reduction])
root.order.add_edge(xor_milk_sourcing, xor_quality_testing)
root.order.add_edge(xor_quality_testing, xor_starter_prep)
root.order.add_edge(xor_starter_prep, xor_milk_pasteurize)
root.order.add_edge(xor_milk_pasteurize, xor_curd_formation)
root.order.add_edge(xor_curd_formation, xor_whey_drain)
root.order.add_edge(xor_whey_drain, xor_cheese_press)
root.order.add_edge(xor_cheese_press, xor_salting_process)
root.order.add_edge(xor_salting_process, xor_aging_setup)
root.order.add_edge(xor_aging_setup, xor_temperature_control)
root.order.add_edge(xor_temperature_control, xor_batch_labeling)
root.order.add_edge(xor_batch_labeling, xor_eco_packaging)
root.order.add_edge(xor_eco_packaging, xor_inventory_audit)
root.order.add_edge(xor_inventory_audit, xor_order_coordination)
root.order.add_edge(xor_order_coordination, xor_regulatory_check)
root.order.add_edge(xor_regulatory_check, xor_shipment_planning)
root.order.add_edge(xor_shipment_planning, xor_vendor_liaison)
root.order.add_edge(xor_vendor_liaison, xor_waste_reduction)

print(root)