import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

artifact_intake = Transition(label='Artifact Intake')
visual_inspection = Transition(label='Visual Inspection')
material_testing = Transition(label='Material Testing')
radiocarbon_dating = Transition(label='Radiocarbon Dating')
provenance_check = Transition(label='Provenance Check')
archive_research = Transition(label='Archive Research')
expert_review = Transition(label='Expert Review')
style_analysis = Transition(label='Style Analysis')
craftsmanship_eval = Transition(label='Craftsmanship Eval')
condition_check = Transition(label='Condition Check')
restoration_plan = Transition(label='Restoration Plan')
forger_risk = Transition(label='Forgery Risk')
legal_review = Transition(label='Legal Review')
report_drafting = Transition(label='Report Drafting')
catalog_entry = Transition(label='Catalog Entry')

skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[material_testing, radiocarbon_dating])
xor = OperatorPOWL(operator=Operator.XOR, children=[provenance_check, skip])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[style_analysis, craftsmanship_eval])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[condition_check, restoration_plan])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[forger_risk, legal_review])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[report_drafting, catalog_entry])

root = StrictPartialOrder(nodes=[artifact_intake, visual_inspection, loop, xor, xor2, xor3, xor4, xor5])
root.order.add_edge(artifact_intake, visual_inspection)
root.order.add_edge(artifact_intake, loop)
root.order.add_edge(artifact_intake, xor)
root.order.add_edge(loop, xor)
root.order.add_edge(loop, xor2)
root.order.add_edge(xor, xor2)
root.order.add_edge(xor, xor3)
root.order.add_edge(xor2, xor3)
root.order.add_edge(xor2, xor4)
root.order.add_edge(xor3, xor4)
root.order.add_edge(xor3, xor5)
root.order.add_edge(xor4, xor5)
root.order.add_edge(xor5, report_drafting)
root.order.add_edge(xor5, catalog_entry)