import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

SiteSurvey = Transition(label='Site Survey')
LoadTest = Transition(label='Load Test')
SoilSample = Transition(label='Soil Sample')
ClimateCheck = Transition(label='Climate Check')
CropSelect = Transition(label='Crop Select')
IrrigationPlan = Transition(label='Irrigation Plan')
EnergySetup = Transition(label='Energy Setup')
PestControl = Transition(label='Pest Control')
PermitObtain = Transition(label='Permit Obtain')
StakeholderMeet = Transition(label='Stakeholder Meet')
BedConstruction = Transition(label='Bed Construction')
SeedPlanting = Transition(label='Seed Planting')
WaterSchedule = Transition(label='Water Schedule')
GrowthMonitor = Transition(label='Growth Monitor')
HarvestPlan = Transition(label='Harvest Plan')
WasteRecycle = Transition(label='Waste Recycle')
YieldReport = Transition(label='Yield Report')

skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[SiteSurvey, LoadTest])
xor = OperatorPOWL(operator=Operator.XOR, children=[SoilSample, ClimateCheck])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[CropSelect, IrrigationPlan])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[EnergySetup, PestControl])
loop3 = OperatorPOWL(operator=Operator.LOOP, children=[PermitObtain, StakeholderMeet])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[BedConstruction, SeedPlanting])
loop4 = OperatorPOWL(operator=Operator.LOOP, children=[WaterSchedule, GrowthMonitor])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[HarvestPlan, WasteRecycle])
loop5 = OperatorPOWL(operator=Operator.LOOP, children=[YieldReport, skip])

root = StrictPartialOrder(nodes=[loop, xor, loop2, xor2, loop3, xor3, loop4, xor4, loop5])
root.order.add_edge(loop, xor)
root.order.add_edge(loop2, xor2)
root.order.add_edge(loop3, xor3)
root.order.add_edge(loop4, xor4)
root.order.add_edge(loop5, xor4)