import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_survey = Transition(label='Site Survey')
load_test = Transition(label='Load Test')
soil_sample = Transition(label='Soil Sample')
climate_check = Transition(label='Climate Check')
crop_select = Transition(label='Crop Select')
irrigation_plan = Transition(label='Irrigation Plan')
energy_setup = Transition(label='Energy Setup')
pest_control = Transition(label='Pest Control')
permit_obtain = Transition(label='Permit Obtain')
stakeholder_meet = Transition(label='Stakeholder Meet')
bed_construction = Transition(label='Bed Construction')
seed_planting = Transition(label='Seed Planting')
water_schedule = Transition(label='Water Schedule')
growth_monitor = Transition(label='Growth Monitor')
harvest_plan = Transition(label='Harvest Plan')
waste_recycle = Transition(label='Waste Recycle')
yield_report = Transition(label='Yield Report')
skip = SilentTransition()

site_survey_loop = OperatorPOWL(operator=Operator.LOOP, children=[site_survey, load_test])
soil_check_loop = OperatorPOWL(operator=Operator.LOOP, children=[soil_sample, climate_check])
crop_select_loop = OperatorPOWL(operator=Operator.LOOP, children=[crop_select, irrigation_plan])
energy_setup_loop = OperatorPOWL(operator=Operator.LOOP, children=[energy_setup, pest_control])
permit_obtain_loop = OperatorPOWL(operator=Operator.LOOP, children=[permit_obtain, stakeholder_meet])
bed_construction_loop = OperatorPOWL(operator=Operator.LOOP, children=[bed_construction, seed_planting])
water_schedule_loop = OperatorPOWL(operator=Operator.LOOP, children=[water_schedule, growth_monitor])
harvest_plan_loop = OperatorPOWL(operator=Operator.LOOP, children=[harvest_plan, waste_recycle])
yield_report_loop = OperatorPOWL(operator=Operator.LOOP, children=[yield_report, skip])

root = StrictPartialOrder(nodes=[site_survey_loop, soil_check_loop, crop_select_loop, energy_setup_loop, permit_obtain_loop, bed_construction_loop, water_schedule_loop, harvest_plan_loop, yield_report_loop])
root.order.add_edge(site_survey_loop, soil_check_loop)
root.order.add_edge(soil_check_loop, crop_select_loop)
root.order.add_edge(crop_select_loop, energy_setup_loop)
root.order.add_edge(energy_setup_loop, permit_obtain_loop)
root.order.add_edge(permit_obtain_loop, stakeholder_meet)
root.order.add_edge(stakeholder_meet, bed_construction_loop)
root.order.add_edge(bed_construction_loop, seed_planting)
root.order.add_edge(seed_planting, water_schedule_loop)
root.order.add_edge(water_schedule_loop, growth_monitor)
root.order.add_edge(growth_monitor, harvest_plan_loop)
root.order.add_edge(harvest_plan_loop, waste_recycle)
root.order.add_edge(waste_recycle, yield_report_loop)