import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
SiteSurvey = Transition(label='Site Survey')
DesignLayout = Transition(label='Design Layout')
PermitsCheck = Transition(label='Permits Check')
FoundationPrep = Transition(label='Foundation Prep')
FrameAssembly = Transition(label='Frame Assembly')
HydroSetup = Transition(label='Hydro Setup')
ClimateSetup = Transition(label='Climate Setup')
SeedSelection = Transition(label='Seed Selection')
NutrientMix = Transition(label='Nutrient Mix')
SystemCalibration = Transition(label='System Calibration')
PestControl = Transition(label='Pest Control')
AutomationLink = Transition(label='Automation Link')
StaffTraining = Transition(label='Staff Training')
YieldTracking = Transition(label='Yield Tracking')
DistributionPlan = Transition(label='Distribution Plan')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[SiteSurvey, DesignLayout, PermitsCheck, FoundationPrep, FrameAssembly, HydroSetup, ClimateSetup, SeedSelection, NutrientMix, SystemCalibration, PestControl, AutomationLink, StaffTraining, YieldTracking, DistributionPlan])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)