import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

Site_Survey = Transition(label='Site Survey')
Design_Modules = Transition(label='Design Modules')
Climate_Setup = Transition(label='Climate Setup')
Nutrient_Mix = Transition(label='Nutrient Mix')
LED_Tuning = Transition(label='LED Tuning')
Seed_Automation = Transition(label='Seed Automation')
Growth_Monitor = Transition(label='Growth Monitor')
Pest_Control = Transition(label='Pest Control')
Yield_Forecast = Transition(label='Yield Forecast')
Energy_Audit = Transition(label='Energy Audit')
Waste_System = Transition(label='Waste System')
Community_Meet = Transition(label='Community Meet')
Compliance_Check = Transition(label='Compliance Check')
Crop_Packing = Transition(label='Crop Packing')
Logistics_Plan = Transition(label='Logistics Plan')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[Site_Survey, Design_Modules])
xor = OperatorPOWL(operator=Operator.XOR, children=[Climate_Setup, Nutrient_Mix])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[LED_Tuning, skip])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[Seed_Automation, Growth_Monitor])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[Pest_Control, Yield_Forecast])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[Energy_Audit, Waste_System])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[Community_Meet, Compliance_Check])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[Crop_Packing, Logistics_Plan])
root = StrictPartialOrder(nodes=[loop, xor, xor2, xor3, xor4, xor5, xor6, xor7])
root.order.add_edge(loop, xor)
root.order.add_edge(xor, xor2)
root.order.add_edge(xor2, xor3)
root.order.add_edge(xor3, xor4)
root.order.add_edge(xor4, xor5)
root.order.add_edge(xor5, xor6)
root.order.add_edge(xor6, xor7)