import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_survey = Transition(label='Site Survey')
permit_filing = Transition(label='Permit Filing')
load_testing = Transition(label='Load Testing')
soil_sampling = Transition(label='Soil Sampling')
water_testing = Transition(label='Water Testing')
system_design = Transition(label='System Design')
solar_setup = Transition(label='Solar Setup')
crop_planning = Transition(label='Crop Planning')
stakeholder_meet = Transition(label='Stakeholder Meet')
material_order = Transition(label='Material Order')
system_install = Transition(label='System Install')
environmental_audit = Transition(label='Environmental Audit')
growth_monitoring = Transition(label='Growth Monitoring')
pest_control = Transition(label='Pest Control')
market_launch = Transition(label='Market Launch')

skip = SilentTransition()

site_survey_to_permits = OperatorPOWL(operator=Operator.XOR, children=[site_survey, permit_filing])
permits_to_testing = OperatorPOWL(operator=Operator.XOR, children=[permit_filing, load_testing])
testing_to_soil = OperatorPOWL(operator=Operator.XOR, children=[load_testing, soil_sampling])
soil_to_water = OperatorPOWL(operator=Operator.XOR, children=[soil_sampling, water_testing])
water_to_system = OperatorPOWL(operator=Operator.XOR, children=[water_testing, system_design])
system_to_solar = OperatorPOWL(operator=Operator.XOR, children=[system_design, solar_setup])
solar_to_crop = OperatorPOWL(operator=Operator.XOR, children=[solar_setup, crop_planning])
crop_to_meet = OperatorPOWL(operator=Operator.XOR, children=[crop_planning, stakeholder_meet])
meet_to_order = OperatorPOWL(operator=Operator.XOR, children=[stakeholder_meet, material_order])
order_to_install = OperatorPOWL(operator=Operator.XOR, children=[material_order, system_install])
install_to_audit = OperatorPOWL(operator=Operator.XOR, children=[system_install, environmental_audit])
audit_to_monitor = OperatorPOWL(operator=Operator.XOR, children=[environmental_audit, growth_monitoring])
monitor_to_pest = OperatorPOWL(operator=Operator.XOR, children=[growth_monitoring, pest_control])
pest_to_market = OperatorPOWL(operator=Operator.XOR, children=[pest_control, market_launch])

root = StrictPartialOrder(nodes=[site_survey_to_permits, permits_to_testing, testing_to_soil, soil_to_water, water_to_system, system_to_solar, solar_to_crop, crop_to_meet, meet_to_order, order_to_install, install_to_audit, audit_to_monitor, monitor_to_pest, pest_to_market])
root.order.add_edge(site_survey_to_permits, permits_to_testing)
root.order.add_edge(permits_to_testing, testing_to_soil)
root.order.add_edge(testing_to_soil, soil_to_water)
root.order.add_edge(soil_to_water, water_to_system)
root.order.add_edge(water_to_system, system_to_solar)
root.order.add_edge(system_to_solar, solar_to_crop)
root.order.add_edge(solar_to_crop, crop_to_meet)
root.order.add_edge(crop_to_meet, meet_to_order)
root.order.add_edge(meet_to_order, order_to_install)
root.order.add_edge(order_to_install, install_to_audit)
root.order.add_edge(install_to_audit, audit_to_monitor)
root.order.add_edge(audit_to_monitor, monitor_to_pest)
root.order.add_edge(monitor_to_pest, pest_to_market)