import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_survey = Transition(label='Site Survey')
permit_filing = Transition(label='Permit Filing')
load_testing = Transition(label='Load Testing')
soil_sampling = Transition(label='Soil Sampling')
water_testing = Transition(label='Water Testing')
system_design = Transition(label='System Design')
solar_setup = Transition(label='Solar Setup')
crop_planning = Transition(label='Crop Planning')
stakeholder_meet = Transition(label='Stakeholder Meet')
material_order = Transition(label='Material Order')
system_install = Transition(label='System Install')
environmental_audit = Transition(label='Environmental Audit')
growth_monitoring = Transition(label='Growth Monitoring')
pest_control = Transition(label='Pest Control')
market_launch = Transition(label='Market Launch')

skip = SilentTransition()
loop1 = OperatorPOWL(operator=Operator.LOOP, children=[system_install, system_design])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[material_order, system_install])
xor1 = OperatorPOWL(operator=Operator.XOR, children=[site_survey, permit_filing])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[load_testing, soil_sampling])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[water_testing, system_design])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[solar_setup, system_install])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[crop_planning, stakeholder_meet])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[material_order, system_install])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[environmental_audit, growth_monitoring])
xor8 = OperatorPOWL(operator=Operator.XOR, children=[pest_control, market_launch])
root = StrictPartialOrder(nodes=[loop1, loop2, xor1, xor2, xor3, xor4, xor5, xor6, xor7, xor8])
root.order.add_edge(loop1, xor1)
root.order.add_edge(loop1, xor2)
root.order.add_edge(loop1, xor3)
root.order.add_edge(loop1, xor4)
root.order.add_edge(loop1, xor5)
root.order.add_edge(loop2, xor6)
root.order.add_edge(loop2, xor7)
root.order.add_edge(loop2, xor8)