import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
seed_selection = Transition(label='Seed Selection')
nutrient_setup = Transition(label='Nutrient Setup')
growth_monitoring = Transition(label='Growth Monitoring')
climate_adjust = Transition(label='Climate Adjust')
pest_control = Transition(label='Pest Control')
water_recirculate = Transition(label='Water Recirculate')
light_calibration = Transition(label='Light Calibration')
robotic_harvest = Transition(label='Robotic Harvest')
quality_inspect = Transition(label='Quality Inspect')
waste_process = Transition(label='Waste Process')
energy_reuse = Transition(label='Energy Reuse')
inventory_update = Transition(label='Inventory Update')
demand_forecast = Transition(label='Demand Forecast')
order_dispatch = Transition(label='Order Dispatch')
community_event = Transition(label='Community Event')
feedback_collect = Transition(label='Feedback Collect')
data_analyze = Transition(label='Data Analyze')

skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[seed_selection, nutrient_setup])
xor = OperatorPOWL(operator=Operator.XOR, children=[climate_adjust, pest_control])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[water_recirculate, light_calibration])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[robotic_harvest, quality_inspect])
loop3 = OperatorPOWL(operator=Operator.LOOP, children=[waste_process, energy_reuse])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[inventory_update, demand_forecast])
loop4 = OperatorPOWL(operator=Operator.LOOP, children=[order_dispatch, community_event])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[feedback_collect, data_analyze])

root = StrictPartialOrder(nodes=[loop, xor, loop2, xor2, loop3, xor3, loop4, xor4])
root.order.add_edge(loop, xor)
root.order.add_edge(loop2, xor2)
root.order.add_edge(loop3, xor3)
root.order.add_edge(loop4, xor4)