import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
Site_Survey = Transition(label='Site Survey')
Structural_Audit = Transition(label='Structural Audit')
System_Design = Transition(label='System Design')
Permit_Filing = Transition(label='Permit Filing')
Foundation_Prep = Transition(label='Foundation Prep')
Frame_Build = Transition(label='Frame Build')
Irrigation_Setup = Transition(label='Irrigation Setup')
Lighting_Install = Transition(label='Lighting Install')
Climate_Control = Transition(label='Climate Control')
Nutrient_Mix = Transition(label='Nutrient Mix')
Crop_Planting = Transition(label='Crop Planting')
Pest_Scouting = Transition(label='Pest Scouting')
Data_Monitoring = Transition(label='Data Monitoring')
Waste_Sorting = Transition(label='Waste Sorting')
Energy_Audit = Transition(label='Energy Audit')
Community_Meet = Transition(label='Community Meet')
Yield_Analysis = Transition(label='Yield Analysis')
skip = SilentTransition()
loop1 = OperatorPOWL(operator=Operator.LOOP, children=[Site_Survey, Structural_Audit, System_Design, Permit_Filing, Foundation_Prep, Frame_Build, Irrigation_Setup, Lighting_Install, Climate_Control, Nutrient_Mix, Crop_Planting])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[Pest_Scouting, Data_Monitoring, Waste_Sorting, Energy_Audit, Community_Meet, Yield_Analysis])
xor = OperatorPOWL(operator=Operator.XOR, children=[loop1, skip])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[loop2, skip])
root = StrictPartialOrder(nodes=[xor, xor2])
root.order.add_edge(xor, xor2)