import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define the activities
SiteAssess = Transition(label='Site Assess')
EnvAnalysis = Transition(label='Env Analysis')
ModularInstall = Transition(label='Modular Install')
IrrigationSetup = Transition(label='Irrigation Setup')
CropSelection = Transition(label='Crop Selection')
NutrientMix = Transition(label='Nutrient Mix')
LightingCalibrate = Transition(label='Lighting Calibrate')
PestMonitor = Transition(label='Pest Monitor')
StaffTraining = Transition(label='Staff Training')
EnergyIntegrate = Transition(label='Energy Integrate')
DataAnalytics = Transition(label='Data Analytics')
WasteRecycle = Transition(label='Waste Recycle')
MarketDevelop = Transition(label='Market Develop')
YieldOptimize = Transition(label='Yield Optimize')
ClimateSimulate = Transition(label='Climate Simulate')

# Define silent activities
skip = SilentTransition()

# Define the process model
loopClimateSimulate = OperatorPOWL(operator=Operator.LOOP, children=[ClimateSimulate])
loopIrrigationSetup = OperatorPOWL(operator=Operator.LOOP, children=[IrrigationSetup])
loopStaffTraining = OperatorPOWL(operator=Operator.LOOP, children=[StaffTraining])
loopYieldOptimize = OperatorPOWL(operator=Operator.LOOP, children=[YieldOptimize])

xorEnergyIntegrate = OperatorPOWL(operator=Operator.XOR, children=[EnergyIntegrate, skip])
xorDataAnalytics = OperatorPOWL(operator=Operator.XOR, children=[DataAnalytics, skip])

xorMarketDevelop = OperatorPOWL(operator=Operator.XOR, children=[MarketDevelop, skip])
xorWasteRecycle = OperatorPOWL(operator=Operator.XOR, children=[WasteRecycle, skip])

xorCropSelection = OperatorPOWL(operator=Operator.XOR, children=[CropSelection, skip])
xorNutrientMix = OperatorPOWL(operator=Operator.XOR, children=[NutrientMix, skip])
xorLightingCalibrate = OperatorPOWL(operator=Operator.XOR, children=[LightingCalibrate, skip])
xorPestMonitor = OperatorPOWL(operator=Operator.XOR, children=[PestMonitor, skip])

xorModularInstall = OperatorPOWL(operator=Operator.XOR, children=[ModularInstall, skip])

xorEnvAnalysis = OperatorPOWL(operator=Operator.XOR, children=[EnvAnalysis, skip])

xorSiteAssess = OperatorPOWL(operator=Operator.XOR, children=[SiteAssess, skip])

root = StrictPartialOrder(nodes=[xorSiteAssess, xorEnvAnalysis, xorModularInstall, xorIrrigationSetup, loopIrrigationSetup, xorCropSelection, loopCropSelection, xorNutrientMix, xorLightingCalibrate, xorPestMonitor, xorStaffTraining, loopStaffTraining, xorEnergyIntegrate, xorDataAnalytics, xorMarketDevelop, xorWasteRecycle, loopMarketDevelop, loopWasteRecycle, loopEnergyIntegrate, loopDataAnalytics, loopStaffTraining, loopCropSelection, loopIrrigationSetup, loopModularInstall, loopSiteAssess, loopEnvAnalysis, loopNutrientMix, loopLightingCalibrate, loopPestMonitor, loopStaffTraining, loopIrrigationSetup, loopCropSelection, loopNutrientMix, loopLightingCalibrate, loopPestMonitor, loopStaffTraining, loopEnergyIntegrate, loopDataAnalytics, loopMarketDevelop, loopWasteRecycle, loopYieldOptimize, loopClimateSimulate])

# Define the order
root.order.add_edge(xorSiteAssess, xorEnvAnalysis)
root.order.add_edge(xorSiteAssess, xorModularInstall)
root.order.add_edge(xorEnvAnalysis, xorIrrigationSetup)
root.order.add_edge(xorModularInstall, xorCropSelection)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorCropSelection, xorNutrientMix)
root.order.add_edge(xorCropSelection, xorLightingCalibrate)
root.order.add_edge(xorCropSelection, xorPestMonitor)
root.order.add_edge(xorNutrientMix, xorStaffTraining)
root.order.add_edge(xorLightingCalibrate, xorEnergyIntegrate)
root.order.add_edge(xorPestMonitor, xorDataAnalytics)
root.order.add_edge(xorStaffTraining, xorMarketDevelop)
root.order.add_edge(xorEnergyIntegrate, xorWasteRecycle)
root.order.add_edge(xorDataAnalytics, loopEnergyIntegrate)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorIrrigationSetup, loopIrrigationSetup)
root.order.add_edge(xorModularInstall, loopModularInstall)
root.order.add_edge(xorEnvAnalysis, loopEnvAnalysis)
root.order.add_edge(xorSiteAssess, loopSiteAssess)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorIrrigationSetup, loopIrrigationSetup)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopWasteRecycle)
root.order.add_edge(xorCropSelection, loopCropSelection)
root.order.add_edge(xorNutrientMix, loopNutrientMix)
root.order.add_edge(xorLightingCalibrate, loopLightingCalibrate)
root.order.add_edge(xorPestMonitor, loopPestMonitor)
root.order.add_edge(xorStaffTraining, loopStaffTraining)
root.order.add_edge(xorEnergyIntegrate, loopEnergyIntegrate)
root.order.add_edge(xorDataAnalytics, loopDataAnalytics)
root.order.add_edge(xorMarketDevelop, loopMarketDevelop)
root.order.add_edge(xorWasteRecycle, loopW