import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
site_survey = Transition(label='Site Survey')
design_layout = Transition(label='Design Layout')
climate_setup = Transition(label='Climate Setup')
sensor_install = Transition(label='Sensor Install')
nutrient_mix = Transition(label='Nutrient Mix')
automation_code = Transition(label='Automation Code')
crop_planning = Transition(label='Crop Planning')
pest_control = Transition(label='Pest Control')
energy_audit = Transition(label='Energy Audit')
waste_sort = Transition(label='Waste Sort')
planting_tier = Transition(label='Planting Tier')
harvest_prep = Transition(label='Harvest Prep')
logistics_plan = Transition(label='Logistics Plan')
community_meet = Transition(label='Community Meet')
data_review = Transition(label='Data Review')
system_upgrade = Transition(label='System Upgrade')
skip = SilentTransition()
site_survey_loop = OperatorPOWL(operator=Operator.LOOP, children=[site_survey])
design_layout_loop = OperatorPOWL(operator=Operator.LOOP, children=[design_layout])
climate_setup_loop = OperatorPOWL(operator=Operator.LOOP, children=[climate_setup])
sensor_install_loop = OperatorPOWL(operator=Operator.LOOP, children=[sensor_install])
nutrient_mix_loop = OperatorPOWL(operator=Operator.LOOP, children=[nutrient_mix])
automation_code_loop = OperatorPOWL(operator=Operator.LOOP, children=[automation_code])
crop_planning_loop = OperatorPOWL(operator=Operator.LOOP, children=[crop_planning])
pest_control_loop = OperatorPOWL(operator=Operator.LOOP, children=[pest_control])
energy_audit_loop = OperatorPOWL(operator=Operator.LOOP, children=[energy_audit])
waste_sort_loop = OperatorPOWL(operator=Operator.LOOP, children=[waste_sort])
planting_tier_loop = OperatorPOWL(operator=Operator.LOOP, children=[planting_tier])
harvest_prep_loop = OperatorPOWL(operator=Operator.LOOP, children=[harvest_prep])
logistics_plan_loop = OperatorPOWL(operator=Operator.LOOP, children=[logistics_plan])
community_meet_loop = OperatorPOWL(operator=Operator.LOOP, children=[community_meet])
data_review_loop = OperatorPOWL(operator=Operator.LOOP, children=[data_review])
system_upgrade_loop = OperatorPOWL(operator=Operator.LOOP, children=[system_upgrade])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip, system_upgrade_loop])
root = StrictPartialOrder(nodes=[site_survey_loop, design_layout_loop, climate_setup_loop, sensor_install_loop, nutrient_mix_loop, automation_code_loop, crop_planning_loop, pest_control_loop, energy_audit_loop, waste_sort_loop, planting_tier_loop, harvest_prep_loop, logistics_plan_loop, community_meet_loop, data_review_loop, system_upgrade_loop, xor])
root.order.add_edge(site_survey_loop, design_layout_loop)
root.order.add_edge(site_survey_loop, climate_setup_loop)
root.order.add_edge(site_survey_loop, sensor_install_loop)
root.order.add_edge(site_survey_loop, nutrient_mix_loop)
root.order.add_edge(site_survey_loop, automation_code_loop)
root.order.add_edge(site_survey_loop, crop_planning_loop)
root.order.add_edge(site_survey_loop, pest_control_loop)
root.order.add_edge(site_survey_loop, energy_audit_loop)
root.order.add_edge(site_survey_loop, waste_sort_loop)
root.order.add_edge(site_survey_loop, planting_tier_loop)
root.order.add_edge(site_survey_loop, harvest_prep_loop)
root.order.add_edge(site_survey_loop, logistics_plan_loop)
root.order.add_edge(site_survey_loop, community_meet_loop)
root.order.add_edge(site_survey_loop, data_review_loop)
root.order.add_edge(site_survey_loop, system_upgrade_loop)
root.order.add_edge(design_layout_loop, climate_setup_loop)
root.order.add_edge(design_layout_loop, sensor_install_loop)
root.order.add_edge(design_layout_loop, nutrient_mix_loop)
root.order.add_edge(design_layout_loop, automation_code_loop)
root.order.add_edge(design_layout_loop, crop_planning_loop)
root.order.add_edge(design_layout_loop, pest_control_loop)
root.order.add_edge(design_layout_loop, energy_audit_loop)
root.order.add_edge(design_layout_loop, waste_sort_loop)
root.order.add_edge(design_layout_loop, planting_tier_loop)
root.order.add_edge(design_layout_loop, harvest_prep_loop)
root.order.add_edge(design_layout_loop, logistics_plan_loop)
root.order.add_edge(design_layout_loop, community_meet_loop)
root.order.add_edge(design_layout_loop, data_review_loop)
root.order.add_edge(design_layout_loop, system_upgrade_loop)
root.order.add_edge(climate_setup_loop, sensor_install_loop)
root.order.add_edge(climate_setup_loop, nutrient_mix_loop)
root.order.add_edge(climate_setup_loop, automation_code_loop)
root.order.add_edge(climate_setup_loop, crop_planning_loop)
root.order.add_edge(climate_setup_loop, pest_control_loop)
root.order.add_edge(climate_setup_loop, energy_audit_loop)
root.order.add_edge(climate_setup_loop, waste_sort_loop)
root.order.add_edge(climate_setup_loop, planting_tier_loop)
root.order.add_edge(climate_setup_loop, harvest_prep_loop)
root.order.add_edge(climate_setup_loop, logistics_plan_loop)
root.order.add_edge(climate_setup_loop, community_meet_loop)
root.order.add_edge(climate_setup_loop, data_review_loop)
root.order.add_edge(climate_setup_loop, system_upgrade_loop)
root.order.add_edge(sensor_install_loop, nutrient_mix_loop)
root.order.add_edge(sensor_install_loop, automation_code_loop)
root.order.add_edge(sensor_install_loop, crop_planning_loop)
root.order.add_edge(sensor_install_loop, pest_control_loop)
root.order.add_edge(sensor_install_loop, energy_audit_loop)
root.order.add_edge(sensor_install_loop, waste_sort_loop)
root.order.add_edge(sensor_install_loop, planting_tier_loop)
root.order.add_edge(sensor_install_loop, harvest_prep_loop)
root.order.add_edge(sensor_install_loop, logistics_plan_loop)
root.order.add_edge(sensor_install_loop, community_meet_loop)
root.order.add_edge(sensor_install_loop, data_review_loop)
root.order.add_edge(sensor_install_loop, system_upgrade_loop)
root.order.add_edge(nutrient_mix_loop, automation_code_loop)
root.order.add_edge(nutrient_mix_loop, crop_planning_loop)
root.order.add_edge(nutrient_mix_loop, pest_control_loop)
root.order.add_edge(nutrient_mix_loop, energy_audit_loop)
root.order.add_edge(nutrient_mix_loop, waste_sort_loop)
root.order.add_edge(nutrient_mix_loop, planting_tier_loop)
root.order.add_edge(nutrient_mix_loop, harvest_prep_loop)
root.order.add_edge(nutrient_mix_loop, logistics_plan_loop)
root.order.add_edge(nutrient_mix_loop, community_meet_loop)
root.order.add_edge(nutrient_mix_loop, data_review_loop)
root.order.add_edge(nutrient_mix_loop, system_upgrade_loop)
root.order.add_edge(automation_code_loop, crop_planning_loop)
root.order.add_edge(automation_code_loop, pest_control_loop)
root.order.add_edge(automation_code_loop, energy_audit_loop)
root.order.add_edge(automation_code_loop, waste_sort_loop)
root.order.add_edge(automation_code_loop, planting_tier_loop)
root.order.add_edge(automation_code_loop, harvest_prep_loop)
root.order.add_edge(automation_code_loop, logistics_plan_loop)
root.order.add_edge(automation_code_loop, community_meet_loop)
root.order.add_edge(automation_code_loop, data_review_loop)
root.order.add_edge(automation_code_loop, system_upgrade_loop)
root.order.add_edge(crop_planning_loop, pest_control_loop)
root.order.add_edge(crop_planning_loop, energy_audit_loop)
root.order.add_edge(crop_planning_loop, waste_sort_loop)
root.order.add_edge(crop_planning_loop, planting_tier_loop)
root.order.add_edge(crop_planning_loop, harvest_prep_loop)
root.order.add_edge(crop_planning_loop, logistics_plan_loop)
root.order.add_edge(crop_planning_loop, community_meet_loop)
root.order.add_edge(crop_planning_loop, data_review_loop)
root.order.add_edge(crop_planning_loop, system_upgrade_loop)
root.order.add_edge(pest_control_loop, energy_audit_loop)
root.order.add_edge(pest_control_loop, waste_sort_loop)
root.order.add_edge(pest_control_loop, planting_tier_loop)
root.order.add_edge(pest_control_loop, harvest_prep_loop)
root.order.add_edge(pest_control_loop, logistics_plan_loop)
root.order.add_edge(pest_control_loop, community_meet_loop)
root.order.add_edge(pest_control_loop, data_review_loop)
root.order.add_edge(pest_control_loop, system_upgrade_loop)
root.order.add_edge(energy_audit_loop, waste_sort_loop)
root.order.add_edge(energy_audit_loop, planting_tier_loop)
root.order.add_edge(energy_audit_loop, harvest_prep_loop)
root.order.add_edge(energy_audit_loop, logistics_plan_loop)
root.order.add_edge(energy_audit_loop, community_meet_loop)
root.order.add_edge(energy_audit_loop, data_review_loop)
root.order.add_edge(energy_audit_loop, system_upgrade_loop)
root.order.add_edge(waste_sort_loop, planting_tier_loop)
root.order.add_edge(waste_sort_loop, harvest_prep_loop)
root.order.add_edge(waste_sort_loop, logistics_plan_loop)
root.order.add_edge(waste_sort_loop, community_meet_loop)
root.order.add_edge(waste_sort_loop, data_review_loop)
root.order.add_edge(waste_sort_loop, system_upgrade_loop)
root.order.add_edge(planting_tier_loop, harvest_prep_loop)
root.order.add_edge(planting_tier_loop, logistics_plan_loop)
root.order.add_edge(planting_tier_loop, community_meet_loop)
root.order.add_edge(planting_tier_loop, data_review_loop)
root.order.add_edge(planting_tier_loop, system_upgrade_loop)
root.order.add_edge(harvest_prep_loop, logistics_plan_loop)
root.order.add_edge(harvest_prep_loop, community_meet_loop)
root.order.add_edge(harvest_prep_loop, data_review_loop)
root.order.add_edge(harvest_prep_loop, system_upgrade_loop)
root.order.add_edge(logistics_plan_loop, community_meet_loop)
root.order.add_edge(logistics_plan_loop, data_review_loop)
root.order.add_edge(logistics_plan_loop, system_upgrade_loop)
root.order.add_edge(community_meet_loop, data_review_loop)
root.order.add_edge(community_meet_loop, system_upgrade_loop)
root.order.add_edge(data_review_loop, system_upgrade_loop)