import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define transitions
SiteAssess = Transition(label='Site Assess')
StructureCheck = Transition(label='Structure Check')
SoilTest = Transition(label='Soil Test')
ClimateEval = Transition(label='Climate Eval')
PermitObtain = Transition(label='Permit Obtain')
DesignLayout = Transition(label='Design Layout')
SeedSourcing = Transition(label='Seed Sourcing')
IrrigationSet = Transition(label='Irrigation Set')
NutrientMix = Transition(label='Nutrient Mix')
PestControl = Transition(label='Pest Control')
SensorInstall = Transition(label='Sensor Install')
StaffTrain = Transition(label='Staff Train')
CropPlanting = Transition(label='Crop Planting')
YieldMonitor = Transition(label='Yield Monitor')
MarketSetup = Transition(label='Market Setup')
Maintenance = Transition(label='Maintenance')
WasteManage = Transition(label='Waste Manage')
skip = SilentTransition()

# Define exclusive choices
site_structure = OperatorPOWL(operator=Operator.XOR, children=[SiteAssess, StructureCheck])
soil_climate = OperatorPOWL(operator=Operator.XOR, children=[SoilTest, ClimateEval])
permit_design = OperatorPOWL(operator=Operator.XOR, children=[PermitObtain, DesignLayout])
seed_irrigation = OperatorPOWL(operator=Operator.XOR, children=[SeedSourcing, IrrigationSet])
nutrient_pest = OperatorPOWL(operator=Operator.XOR, children=[NutrientMix, PestControl])
sensor_staff = OperatorPOWL(operator=Operator.XOR, children=[SensorInstall, StaffTrain])
plant_monitor = OperatorPOWL(operator=Operator.XOR, children=[CropPlanting, YieldMonitor])
market_maintenance = OperatorPOWL(operator=Operator.XOR, children=[MarketSetup, Maintenance])
waste_manage = OperatorPOWL(operator=Operator.XOR, children=[WasteManage])

# Define loops
watering_loop = OperatorPOWL(operator=Operator.LOOP, children=[seed_irrigation, nutrient_pest])
pest_loop = OperatorPOWL(operator=Operator.LOOP, children=[pest_control, nutrient_mix])
monitor_loop = OperatorPOWL(operator=Operator.LOOP, children=[yield_monitor, market_setup])

# Define partial order
root = StrictPartialOrder(nodes=[watering_loop, pest_loop, monitor_loop, site_structure, soil_climate, permit_design, seed_irrigation, nutrient_pest, sensor_staff, plant_monitor, market_maintenance, waste_manage])
root.order.add_edge(site_structure, soil_climate)
root.order.add_edge(soil_climate, permit_design)
root.order.add_edge(permit_design, seed_irrigation)
root.order.add_edge(seed_irrigation, nutrient_pest)
root.order.add_edge(nutrient_pest, pest_control)
root.order.add_edge(pest_control, nutrient_mix)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(pest_control, nutrient_mix)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest_control)
root.order.add_edge(nutrient_mix, pest