import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_survey = Transition(label='Site Survey')
permit_acquire = Transition(label='Permit Acquire')
rack_design = Transition(label='Rack Design')
seed_selection = Transition(label='Seed Selection')
nutrient_mix = Transition(label='Nutrient Mix')
lighting_setup = Transition(label='Lighting Setup')
sensor_install = Transition(label='Sensor Install')
system_test = Transition(label='System Test')
staff_hire = Transition(label='Staff Hire')
training_lead = Transition(label='Training Lead')
waste_manage = Transition(label='Waste Manage')
supply_chain = Transition(label='Supply Chain')
crop_cycle = Transition(label='Crop Cycle')
data_monitor = Transition(label='Data Monitor')
harvest_plan = Transition(label='Harvest Plan')
distribution = Transition(label='Distribution')

skip = SilentTransition()

site_survey_loop = OperatorPOWL(operator=Operator.LOOP, children=[site_survey, permit_acquire])
rack_design_loop = OperatorPOWL(operator=Operator.LOOP, children=[rack_design, seed_selection])
nutrient_mix_loop = OperatorPOWL(operator=Operator.LOOP, children=[nutrient_mix, lighting_setup])
sensor_install_loop = OperatorPOWL(operator=Operator.LOOP, children=[sensor_install, system_test])
staff_hire_loop = OperatorPOWL(operator=Operator.LOOP, children=[staff_hire, training_lead])
waste_manage_loop = OperatorPOWL(operator=Operator.LOOP, children=[waste_manage, supply_chain])
crop_cycle_loop = OperatorPOWL(operator=Operator.LOOP, children=[crop_cycle, data_monitor])
harvest_plan_loop = OperatorPOWL(operator=Operator.LOOP, children=[harvest_plan, distribution])

root = StrictPartialOrder(nodes=[site_survey_loop, rack_design_loop, nutrient_mix_loop, sensor_install_loop, staff_hire_loop, waste_manage_loop, crop_cycle_loop, harvest_plan_loop])
root.order.add_edge(site_survey_loop, rack_design_loop)
root.order.add_edge(rack_design_loop, nutrient_mix_loop)
root.order.add_edge(nutrient_mix_loop, lighting_setup_loop)
root.order.add_edge(sensor_install_loop, system_test_loop)
root.order.add_edge(system_test_loop, staff_hire_loop)
root.order.add_edge(staff_hire_loop, training_lead_loop)
root.order.add_edge(training_lead_loop, waste_manage_loop)
root.order.add_edge(waste_manage_loop, supply_chain_loop)
root.order.add_edge(supply_chain_loop, crop_cycle_loop)
root.order.add_edge(crop_cycle_loop, data_monitor_loop)
root.order.add_edge(data_monitor_loop, harvest_plan_loop)
root.order.add_edge(harvest_plan_loop, distribution_loop)