import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
seed_selection = Transition(label='Seed Selection')
nutrient_mix = Transition(label='Nutrient Mix')
planting_setup = Transition(label='Planting Setup')
climate_control = Transition(label='Climate Control')
water_cycling = Transition(label='Water Cycling')
growth_monitoring = Transition(label='Growth Monitoring')
pest_detection = Transition(label='Pest Detection')
light_adjustment = Transition(label='Light Adjustment')
data_analysis = Transition(label='Data Analysis')
harvest_planning = Transition(label='Harvest Planning')
crop_harvest = Transition(label='Crop Harvest')
yield_sorting = Transition(label='Yield Sorting')
packaging_prep = Transition(label='Packaging Prep')
distribution_plan = Transition(label='Distribution Plan')
regulation_check = Transition(label='Regulation Check')
waste_recycling = Transition(label='Waste Recycling')
system_maintenance = Transition(label='System Maintenance')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[climate_control, water_cycling, growth_monitoring, pest_detection, light_adjustment, data_analysis])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[yield_sorting, packaging_prep])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[distribution_plan, regulation_check])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[waste_recycling, system_maintenance])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[regulation_check, system_maintenance])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[distribution_plan, waste_recycling])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[yield_sorting, packaging_prep])
xor8 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor9 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor10 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor11 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor12 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor13 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor14 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor15 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor16 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor17 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor18 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor19 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor20 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor21 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor22 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor23 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor24 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor25 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor26 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor27 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor28 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor29 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor30 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor31 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor32 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor33 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor34 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor35 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor36 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor37 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor38 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor39 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor40 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor41 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor42 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor43 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor44 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor45 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor46 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor47 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor48 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor49 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor50 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor51 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor52 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor53 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor54 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor55 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor56 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor57 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor58 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor59 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor60 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor61 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor62 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor63 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor64 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor65 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor66 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor67 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor68 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor69 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor70 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor71 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor72 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor73 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor74 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor75 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor76 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor77 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor78 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor79 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor80 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor81 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor82 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor83 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor84 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor85 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor86 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor87 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor88 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor89 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor90 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor91 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor92 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor93 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor94 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor95 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor96 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor97 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor98 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor99 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor100 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor101 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor102 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor103 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor104 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor105 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor106 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor107 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor108 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor109 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor110 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor111 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor112 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor113 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor114 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor115 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor116 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor117 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor118 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor119 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor120 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor121 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor122 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor123 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor124 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor125 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor126 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor127 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor128 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor129 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor130 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor131 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor132 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor133 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor134 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor135 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor136 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor137 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor138 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor139 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor140 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor141 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor142 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor143 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor144 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor145 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor146 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor147 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor148 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor149 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor150 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor151 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor152 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor153 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor154 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor155 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor156 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor157 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor158 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor159 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor160 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor161 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor162 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor163 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor164 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor165 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor166 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor167 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor168 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor169 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor170 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor171 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor172 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor173 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor174 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor175 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor176 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor177 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor178 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor179 = OperatorPOWL(operator=Operator.XOR, children=[skip, harvest_planning])
xor