import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
SeedSelect = Transition(label='Seed Select')
GerminateSeeds = Transition(label='Germinate Seeds')
TransplantSeedlings = Transition(label='Transplant Seedlings')
MixNutrients = Transition(label='Mix Nutrients')
AdjustPH = Transition(label='Adjust pH')
MonitorClimate = Transition(label='Monitor Climate')
ControlHumidity = Transition(label='Control Humidity')
CO2Regulation = Transition(label='CO2 Regulation')
DetectPests = Transition(label='Detect Pests')
DeployBiocontrols = Transition(label='Deploy Biocontrols')
ScheduleHarvest = Transition(label='Schedule Harvest')
AutomatePicking = Transition(label='Automate Picking')
PackageProduce = Transition(label='Package Produce')
CompostWaste = Transition(label='Compost Waste')
RecycleWater = Transition(label='Recycle Water')
DataLogging = Transition(label='Data Logging')
SystemMaintenance = Transition(label='System Maintenance')

skip = SilentTransition()
loop1 = OperatorPOWL(operator=Operator.LOOP, children=[SeedSelect, GerminateSeeds, TransplantSeedlings, MixNutrients, AdjustPH])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[MonitorClimate, ControlHumidity, CO2Regulation, DetectPests, DeployBiocontrols])
loop3 = OperatorPOWL(operator=Operator.LOOP, children=[ScheduleHarvest, AutomatePicking, PackageProduce, CompostWaste, RecycleWater, DataLogging])
xor = OperatorPOWL(operator=Operator.XOR, children=[SystemMaintenance, skip])
root = StrictPartialOrder(nodes=[loop1, loop2, loop3, xor])
root.order.add_edge(loop1, loop2)
root.order.add_edge(loop2, loop3)
root.order.add_edge(loop3, xor)