import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

Site_Survey = Transition(label='Site Survey')
Structural_Check = Transition(label='Structural Check')
Resource_Sourcing = Transition(label='Resource Sourcing')
System_Install = Transition(label='System Install')
Lighting_Setup = Transition(label='Lighting Setup')
Irrigation_Setup = Transition(label='Irrigation Setup')
Stakeholder_Meet = Transition(label='Stakeholder Meet')
Volunteer_Train = Transition(label='Volunteer Train')
Regulation_Review = Transition(label='Regulation Review')
Crop_Selection = Transition(label='Crop Selection')
Planting_Phase = Transition(label='Planting Phase')
Climate_Control = Transition(label='Climate Control')
Growth_Monitor = Transition(label='Growth Monitor')
Data_Logging = Transition(label='Data Logging')
Harvest_Event = Transition(label='Harvest Event')
Waste_Manage = Transition(label='Waste Manage')
Feedback_Collect = Transition(label='Feedback Collect')

skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[Site_Survey, Structural_Check])
xor = OperatorPOWL(operator=Operator.XOR, children=[Resource_Sourcing, skip])
root = StrictPartialOrder(nodes=[loop, xor, System_Install, Lighting_Setup, Irrigation_Setup, Stakeholder_Meet, Volunteer_Train, Regulation_Review, Crop_Selection, Planting_Phase, Climate_Control, Growth_Monitor, Data_Logging, Harvest_Event, Waste_Manage, Feedback_Collect])
root.order.add_edge(loop, xor)
root.order.add_edge(xor, System_Install)
root.order.add_edge(xor, Irrigation_Setup)
root.order.add_edge(xor, Stakeholder_Meet)
root.order.add_edge(xor, Volunteer_Train)
root.order.add_edge(xor, Regulation_Review)
root.order.add_edge(System_Install, Lighting_Setup)
root.order.add_edge(System_Install, Climate_Control)
root.order.add_edge(Lighting_Setup, Climate_Control)
root.order.add_edge(Lighting_Setup, Growth_Monitor)
root.order.add_edge(Irrigation_Setup, Climate_Control)
root.order.add_edge(Irrigation_Setup, Growth_Monitor)
root.order.add_edge(Stakeholder_Meet, Crop_Selection)
root.order.add_edge(Volunteer_Train, Crop_Selection)
root.order.add_edge(Regulation_Review, Crop_Selection)
root.order.add_edge(Crop_Selection, Planting_Phase)
root.order.add_edge(Planting_Phase, Climate_Control)
root.order.add_edge(Planting_Phase, Growth_Monitor)
root.order.add_edge(Climate_Control, Data_Logging)
root.order.add_edge(Climate_Control, Growth_Monitor)
root.order.add_edge(Growth_Monitor, Harvest_Event)
root.order.add_edge(Growth_Monitor, Waste_Manage)
root.order.add_edge(Growth_Monitor, Feedback_Collect)