import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
A = Transition(label='Colony Sourcing')
B = Transition(label='Hive Design')
C = Transition(label='Site Survey')
D = Transition(label='Installation Prep')
E = Transition(label='Hive Setup')
F = Transition(label='Sensor Install')
G = Transition(label='Health Monitor')
H = Transition(label='Pest Control')
I = Transition(label='Honey Harvest')
J = Transition(label='Wax Processing')
K = Transition(label='Product Packaging')
L = Transition(label='Order Dispatch')
M = Transition(label='Workshop Setup')
N = Transition(label='Community Outreach')
O = Transition(label='Regulation Check')
P = Transition(label='Data Analysis')
Q = Transition(label='Maintenance Plan')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[A, B])
xor = OperatorPOWL(operator=Operator.XOR, children=[C, skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)