import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
Site_Survey = Transition(label='Site Survey')
Permit_Approval = Transition(label='Permit Approval')
Design_Layout = Transition(label='Design Layout')
System_Procure = Transition(label='System Procure')
Nutrient_Prep = Transition(label='Nutrient Prep')
Structure_Build = Transition(label='Structure Build')
Sensor_Install = Transition(label='Sensor Install')
Climate_Setup = Transition(label='Climate Setup')
Seed_Select = Transition(label='Seed Select')
Germinate_Seeds = Transition(label='Germinate Seeds')
Monitor_Growth = Transition(label='Monitor Growth')
Data_Analyze = Transition(label='Data Analyze')
Pest_Control = Transition(label='Pest Control')
Harvest_Crop = Transition(label='Harvest Crop')
Package_Goods = Transition(label='Package Goods')
Ship_Products = Transition(label='Ship Products')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[Site_Survey, Permit_Approval, Design_Layout, System_Procure, Nutrient_Prep, Structure_Build, Sensor_Install, Climate_Setup, Seed_Select, Germinate_Seeds, Monitor_Growth, Data_Analyze, Pest_Control, Harvest_Crop, Package_Goods, Ship_Products])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)