import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define activities
SiteSurvey = Transition(label='Site Survey')
ClimatePlan = Transition(label='Climate Plan')
SystemDesign = Transition(label='System Design')
AISetup = Transition(label='AI Setup')
SeedSourcing = Transition(label='Seed Sourcing')
NutrientMix = Transition(label='Nutrient Mix')
InstallHydro = Transition(label='Install Hydro')
EnergyAudit = Transition(label='Energy Audit')
StaffTraining = Transition(label='Staff Training')
TrialGrowth = Transition(label='Trial Growth')
YieldMeasure = Transition(label='Yield Measure')
WasteCycle = Transition(label='Waste Cycle')
ComplianceCheck = Transition(label='Compliance Check')
MarketStudy = Transition(label='Market Study')
CommunityMeet = Transition(label='Community Meet')
OptimizeEnvironment = Transition(label='Optimize Environment')

# Define silent transitions
skip = SilentTransition()

# Define loop nodes
SiteSurveyLoop = OperatorPOWL(operator=Operator.LOOP, children=[SiteSurvey, skip])
ClimatePlanLoop = OperatorPOWL(operator=Operator.LOOP, children=[ClimatePlan, skip])
SystemDesignLoop = OperatorPOWL(operator=Operator.LOOP, children=[SystemDesign, skip])
AISetupLoop = OperatorPOWL(operator=Operator.LOOP, children=[AISetup, skip])
SeedSourcingLoop = OperatorPOWL(operator=Operator.LOOP, children=[SeedSourcing, skip])
NutrientMixLoop = OperatorPOWL(operator=Operator.LOOP, children=[NutrientMix, skip])
InstallHydroLoop = OperatorPOWL(operator=Operator.LOOP, children=[InstallHydro, skip])
EnergyAuditLoop = OperatorPOWL(operator=Operator.LOOP, children=[EnergyAudit, skip])
StaffTrainingLoop = OperatorPOWL(operator=Operator.LOOP, children=[StaffTraining, skip])
TrialGrowthLoop = OperatorPOWL(operator=Operator.LOOP, children=[TrialGrowth, skip])
YieldMeasureLoop = OperatorPOWL(operator=Operator.LOOP, children=[YieldMeasure, skip])
WasteCycleLoop = OperatorPOWL(operator=Operator.LOOP, children=[WasteCycle, skip])
ComplianceCheckLoop = OperatorPOWL(operator=Operator.LOOP, children=[ComplianceCheck, skip])
MarketStudyLoop = OperatorPOWL(operator=Operator.LOOP, children=[MarketStudy, skip])
CommunityMeetLoop = OperatorPOWL(operator=Operator.LOOP, children=[CommunityMeet, skip])
OptimizeEnvironmentLoop = OperatorPOWL(operator=Operator.LOOP, children=[OptimizeEnvironment, skip])

# Define exclusive choice nodes
SiteSurveyChoice = OperatorPOWL(operator=Operator.XOR, children=[SiteSurveyLoop, skip])
ClimatePlanChoice = OperatorPOWL(operator=Operator.XOR, children=[ClimatePlanLoop, skip])
SystemDesignChoice = OperatorPOWL(operator=Operator.XOR, children=[SystemDesignLoop, skip])
AISetupChoice = OperatorPOWL(operator=Operator.XOR, children=[AISetupLoop, skip])
SeedSourcingChoice = OperatorPOWL(operator=Operator.XOR, children=[SeedSourcingLoop, skip])
NutrientMixChoice = OperatorPOWL(operator=Operator.XOR, children=[NutrientMixLoop, skip])
InstallHydroChoice = OperatorPOWL(operator=Operator.XOR, children=[InstallHydroLoop, skip])
EnergyAuditChoice = OperatorPOWL(operator=Operator.XOR, children=[EnergyAuditLoop, skip])
StaffTrainingChoice = OperatorPOWL(operator=Operator.XOR, children=[StaffTrainingLoop, skip])
TrialGrowthChoice = OperatorPOWL(operator=Operator.XOR, children=[TrialGrowthLoop, skip])
YieldMeasureChoice = OperatorPOWL(operator=Operator.XOR, children=[YieldMeasureLoop, skip])
WasteCycleChoice = OperatorPOWL(operator=Operator.XOR, children=[WasteCycleLoop, skip])
ComplianceCheckChoice = OperatorPOWL(operator=Operator.XOR, children=[ComplianceCheckLoop, skip])
MarketStudyChoice = OperatorPOWL(operator=Operator.XOR, children=[MarketStudyLoop, skip])
CommunityMeetChoice = OperatorPOWL(operator=Operator.XOR, children=[CommunityMeetLoop, skip])
OptimizeEnvironmentChoice = OperatorPOWL(operator=Operator.XOR, children=[OptimizeEnvironmentLoop, skip])

# Define the root
root = StrictPartialOrder(nodes=[SiteSurveyChoice, ClimatePlanChoice, SystemDesignChoice, AISetupChoice, SeedSourcingChoice, NutrientMixChoice, InstallHydroChoice, EnergyAuditChoice, StaffTrainingChoice, TrialGrowthChoice, YieldMeasureChoice, WasteCycleChoice, ComplianceCheckChoice, MarketStudyChoice, CommunityMeetChoice, OptimizeEnvironmentChoice])
root.order.add_edge(SiteSurveyChoice, ClimatePlanChoice)
root.order.add_edge(ClimatePlanChoice, SystemDesignChoice)
root.order.add_edge(SystemDesignChoice, AISetupChoice)
root.order.add_edge(AISetupChoice, SeedSourcingChoice)
root.order.add_edge(SeedSourcingChoice, NutrientMixChoice)
root.order.add_edge(NutrientMixChoice, InstallHydroChoice)
root.order.add_edge(InstallHydroChoice, EnergyAuditChoice)
root.order.add_edge(EnergyAuditChoice, StaffTrainingChoice)
root.order.add_edge(StaffTrainingChoice, TrialGrowthChoice)
root.order.add_edge(TrialGrowthChoice, YieldMeasureChoice)
root.order.add_edge(YieldMeasureChoice, WasteCycleChoice)
root.order.add_edge(WasteCycleChoice, ComplianceCheckChoice)
root.order.add_edge(ComplianceCheckChoice, MarketStudyChoice)
root.order.add_edge(MarketStudyChoice, CommunityMeetChoice)
root.order.add_edge(CommunityMeetChoice, OptimizeEnvironmentChoice)