import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
SiteSurvey = Transition(label='Site Survey')
DesignLayout = Transition(label='Design Layout')
ModularBuild = Transition(label='Modular Build')
InstallPumps = Transition(label='Install Pumps')
SetupSensors = Transition(label='Setup Sensors')
CalibrateLights = Transition(label='Calibrate Lights')
NutrientMix = Transition(label='Nutrient Mix')
PlantSeeding = Transition(label='Plant Seeding')
WaterCycling = Transition(label='Water Cycling')
EnergyAudit = Transition(label='Energy Audit')
PestControl = Transition(label='Pest Control')
GrowthMonitor = Transition(label='Growth Monitor')
DataAnalysis = Transition(label='Data Analysis')
YieldForecast = Transition(label='Yield Forecast')
SupplyOrder = Transition(label='Supply Order')
WasteRecycle = Transition(label='Waste Recycle')
SystemUpgrade = Transition(label='System Upgrade')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[SiteSurvey, DesignLayout, ModularBuild, InstallPumps, SetupSensors, CalibrateLights, NutrientMix, PlantSeeding, WaterCycling, EnergyAudit, PestControl, GrowthMonitor, DataAnalysis, YieldForecast, SupplyOrder, WasteRecycle, SystemUpgrade])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)