import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
Site_Survey = Transition(label='Site Survey')
Design_Layout = Transition(label='Design Layout')
Modular_Build = Transition(label='Modular Build')
Install_Pumps = Transition(label='Install Pumps')
Setup_Sensors = Transition(label='Setup Sensors')
Calibrate_Lights = Transition(label='Calibrate Lights')
Nutrient_Mix = Transition(label='Nutrient Mix')
Plant_Seeding = Transition(label='Plant Seeding')
Water_Cycling = Transition(label='Water Cycling')
Energy_Audit = Transition(label='Energy Audit')
Pest_Control = Transition(label='Pest Control')
Growth_Monitor = Transition(label='Growth Monitor')
Data_Analysis = Transition(label='Data Analysis')
Yield_Forecast = Transition(label='Yield Forecast')
Supply_Order = Transition(label='Supply Order')
Waste_Recycle = Transition(label='Waste Recycle')
System_Upgrade = Transition(label='System Upgrade')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[Site_Survey, Design_Layout])
xor = OperatorPOWL(operator=Operator.XOR, children=[Modular_Build, skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)