import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
initial_review = Transition(label='Initial Review')
provenance_check = Transition(label='Provenance Check')
material_scan = Transition(label='Material Scan')
chemical_test = Transition(label='Chemical Test')
imaging_capture = Transition(label='Imaging Capture')
expert_consult = Transition(label='Expert Consult')
historical_match = Transition(label='Historical Match')
forgery_detect = Transition(label='Forgery Detect')
documentation_verify = Transition(label='Documentation Verify')
cross_border_check = Transition(label='Cross-Border Check')
condition_assess = Transition(label='Condition Assess')
value_estimate = Transition(label='Value Estimate')
report_draft = Transition(label='Report Draft')
report_review = Transition(label='Report Review')
client_approval = Transition(label='Client Approval')
certification_issue = Transition(label='Certification Issue')
archive_record = Transition(label='Archive Record')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[provenance_check, material_scan, chemical_test, imaging_capture, expert_consult, historical_match, forgery_detect, documentation_verify, cross_border_check, condition_assess, value_estimate])
xor = OperatorPOWL(operator=Operator.XOR, children=[report_draft, report_review])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)