import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
SiteSurvey = Transition(label='Site Survey')
PermitFiling = Transition(label='Permit Filing')
StructureDesign = Transition(label='Structure Design')
SystemInstall = Transition(label='System Install')
HydroponicSetup = Transition(label='Hydroponic Setup')
ClimateConfig = Transition(label='Climate Config')
AIIntegration = Transition(label='AI Integration')
NutrientSourcing = Transition(label='Nutrient Sourcing')
WastePlanning = Transition(label='Waste Planning')
StaffTraining = Transition(label='Staff Training')
CropSeeding = Transition(label='Crop Seeding')
GrowthMonitoring = Transition(label='Growth Monitoring')
QualityTesting = Transition(label='Quality Testing')
HarvestScheduling = Transition(label='Harvest Scheduling')
DistributionPlan = Transition(label='Distribution Plan')
DataAnalysis = Transition(label='Data Analysis')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[SiteSurvey, PermitFiling, StructureDesign, SystemInstall, HydroponicSetup, ClimateConfig, AIIntegration, NutrientSourcing, WastePlanning, StaffTraining, CropSeeding, GrowthMonitoring, QualityTesting, HarvestScheduling, DistributionPlan, DataAnalysis])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)