import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
A = Transition(label='Site Survey')
B = Transition(label='Design Plan')
C = Transition(label='Permit Acquire')
D = Transition(label='Structural Retrofit')
E = Transition(label='System Install')
F = Transition(label='Lighting Setup')
G = Transition(label='Sensor Deploy')
H = Transition(label='Seed Sourcing')
I = Transition(label='Nutrient Prep')
J = Transition(label='Staff Training')
K = Transition(label='Data Monitor')
L = Transition(label='Yield Analyze')
M = Transition(label='Compliance Check')
N = Transition(label='Community Meet')
O = Transition(label='Market Launch')
P = Transition(label='Logistics Plan')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P])
xor = OperatorPOWL(operator=Operator.XOR, children=[P, skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)