import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
Site_Survey = Transition(label='Site Survey')
Design_Plan = Transition(label='Design Plan')
Permit_Acquire = Transition(label='Permit Acquire')
Structural_Retrofit = Transition(label='Structural Retrofit')
System_Install = Transition(label='System Install')
Lighting_Setup = Transition(label='Lighting Setup')
Sensor_Deploy = Transition(label='Sensor Deploy')
Seed_Sourcing = Transition(label='Seed Sourcing')
Nutrient_Prep = Transition(label='Nutrient Prep')
Staff_Training = Transition(label='Staff Training')
Data_Monitor = Transition(label='Data Monitor')
Yield_Analyze = Transition(label='Yield Analyze')
Compliance_Check = Transition(label='Compliance Check')
Community_Meet = Transition(label='Community Meet')
Market_Launch = Transition(label='Market Launch')
Logistics_Plan = Transition(label='Logistics Plan')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[Site_Survey, Design_Plan, Permit_Acquire])
xor = OperatorPOWL(operator=Operator.XOR, children=[Structural_Retrofit, skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)