import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

Farm_Visit = Transition(label='Farm Visit')
Quality_Cupping = Transition(label='Quality Cupping')
Sustainability_Audit = Transition(label='Sustainability Audit')
Contract_Draft = Transition(label='Contract Draft')
Price_Negotiate = Transition(label='Price Negotiate')
Sample_Testing = Transition(label='Sample Testing')
Shipment_Plan = Transition(label='Shipment Plan')
Customs_Clear = Transition(label='Customs Clear')
Inventory_Update = Transition(label='Inventory Update')
Supplier_Review = Transition(label='Supplier Review')
Risk_Assess = Transition(label='Risk Assess')
Forecast_Adjust = Transition(label='Forecast Adjust')
Payment_Process = Transition(label='Payment Process')
Relationship_Call = Transition(label='Relationship Call')
Traceability_Log = Transition(label='Traceability Log')
Market_Research = Transition(label='Market Research')
Compliance_Check = Transition(label='Compliance Check')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[Farm_Visit, Quality_Cupping, Sustainability_Audit])
xor = OperatorPOWL(operator=Operator.XOR, children=[Contract_Draft, skip])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[Price_Negotiate, skip])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[Sample_Testing, skip])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[Shipment_Plan, skip])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[Customs_Clear, skip])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[Inventory_Update, skip])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[Supplier_Review, skip])
xor8 = OperatorPOWL(operator=Operator.XOR, children=[Risk_Assess, skip])
xor9 = OperatorPOWL(operator=Operator.XOR, children=[Forecast_Adjust, skip])
xor10 = OperatorPOWL(operator=Operator.XOR, children=[Payment_Process, skip])
xor11 = OperatorPOWL(operator=Operator.XOR, children=[Relationship_Call, skip])
xor12 = OperatorPOWL(operator=Operator.XOR, children=[Traceability_Log, skip])
xor13 = OperatorPOWL(operator=Operator.XOR, children=[Market_Research, skip])
xor14 = OperatorPOWL(operator=Operator.XOR, children=[Compliance_Check, skip])
root = StrictPartialOrder(nodes=[loop, xor, xor2, xor3, xor4, xor5, xor6, xor7, xor8, xor9, xor10, xor11, xor12, xor13, xor14])
root.order.add_edge(loop, xor)
root.order.add_edge(loop, xor2)
root.order.add_edge(loop, xor3)
root.order.add_edge(loop, xor4)
root.order.add_edge(loop, xor5)
root.order.add_edge(loop, xor6)
root.order.add_edge(loop, xor7)
root.order.add_edge(loop, xor8)
root.order.add_edge(loop, xor9)
root.order.add_edge(loop, xor10)
root.order.add_edge(loop, xor11)
root.order.add_edge(loop, xor12)
root.order.add_edge(loop, xor13)
root.order.add_edge(loop, xor14)