import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
Milk_Sourcing = Transition(label='Milk Sourcing')
Culture_Blending = Transition(label='Culture Blending')
Milk_Pasteurize = Transition(label='Milk Pasteurize')
Curd_Cutting = Transition(label='Curd Cutting')
Whey_Drain = Transition(label='Whey Drain')
Mold_Inoculate = Transition(label='Mold Inoculate')
Press_Cheese = Transition(label='Press Cheese')
Salt_Brine = Transition(label='Salt Brine')
Age_Monitor = Transition(label='Age Monitor')
Quality_Test = Transition(label='Quality Test')
Packaging_Prep = Transition(label='Packaging Prep')
Label_Design = Transition(label='Label Design')
Order_Allocation = Transition(label='Order Allocation')
Transport_Arrange = Transition(label='Transport Arrange')
Retail_Sync = Transition(label='Retail Sync')
Customer_Review = Transition(label='Customer Review')
Feedback_Analyze = Transition(label='Feedback Analyze')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[Age_Monitor, Quality_Test])
xor = OperatorPOWL(operator=Operator.XOR, children=[Order_Allocation, Transport_Arrange])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)