import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
ClientConsult = Transition(label='Client Consult')
NeedsAssess = Transition(label='Needs Assess')
ArtSelection = Transition(label='Art Selection')
InventoryCheck = Transition(label='Inventory Check')
LegalDraft = Transition(label='Legal Draft')
ContractSign = Transition(label='Contract Sign')
InsuranceSetup = Transition(label='Insurance Setup')
TransportPlan = Transition(label='Transport Plan')
SecureTransit = Transition(label='Secure Transit')
ArtInstall = Transition(label='Art Install')
ConditionCheck = Transition(label='Condition Check')
AppraisalLog = Transition(label='Appraisal Log')
LeaseRenew = Transition(label='Lease Renew')
PaymentProcess = Transition(label='Payment Process')
DeinstallArt = Transition(label='Deinstall Art')
ReturnInspect = Transition(label='Return Inspect')
PurchaseOption = Transition(label='Purchase Option')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[ClientConsult, NeedsAssess, ArtSelection, InventoryCheck, LegalDraft, ContractSign, InsuranceSetup, TransportPlan, SecureTransit, ArtInstall, ConditionCheck, AppraisalLog, LeaseRenew, PaymentProcess, DeinstallArt, ReturnInspect, PurchaseOption])
xor = OperatorPOWL(operator=Operator.XOR, children=[loop, skip])
root = StrictPartialOrder(nodes=[xor])
root.order.add_edge(loop, xor)