import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
site_analysis = Transition(label='Site Analysis')
structure_check = Transition(label='Structure Check')
farm_design = Transition(label='Farm Design')
env_control = Transition(label='Env Control')
nutrient_prep = Transition(label='Nutrient Prep')
seed_selection = Transition(label='Seed Selection')
automated_plant = Transition(label='Automated Plant')
sensor_setup = Transition(label='Sensor Setup')
microclimate_mon = Transition(label='Microclimate Mon')
health_monitor = Transition(label='Health Monitor')
light_adjust = Transition(label='Light Adjust')
irrigation_mod = Transition(label='Irrigation Mod')
waste_recycle = Transition(label='Waste Recycle')
energy_optimize = Transition(label='Energy Optimize')
quality_check = Transition(label='Quality Check')
crop_harvest = Transition(label='Crop Harvest')
distribution_plan = Transition(label='Distribution Plan')
skip = SilentTransition()
loop1 = OperatorPOWL(operator=Operator.LOOP, children=[site_analysis, structure_check, farm_design, env_control])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[nutrient_prep, seed_selection, automated_plant])
loop3 = OperatorPOWL(operator=Operator.LOOP, children=[sensor_setup, microclimate_mon, health_monitor, light_adjust, irrigation_mod, waste_recycle, energy_optimize])
loop4 = OperatorPOWL(operator=Operator.LOOP, children=[quality_check, crop_harvest, distribution_plan])
xor1 = OperatorPOWL(operator=Operator.XOR, children=[loop2, loop3])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[loop4, skip])
root = StrictPartialOrder(nodes=[loop1, xor1, xor2])
root.order.add_edge(loop1, xor1)
root.order.add_edge(loop1, xor2)
root.order.add_edge(xor1, xor2)