import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
A = Transition(label='Concept Approve')
B = Transition(label='Budget Align')
C = Transition(label='Design Review')
D = Transition(label='Structure Simulate')
E = Transition(label='Material Procure')
F = Transition(label='Vendor Select')
G = Transition(label='Permit Apply')
H = Transition(label='Safety Check')
I = Transition(label='Site Prep')
J = Transition(label='Logistics Plan')
K = Transition(label='Fabricate Parts')
L = Transition(label='Assemble Onsite')
M = Transition(label='Quality Inspect')
N = Transition(label='Weather Monitor')
O = Transition(label='Public Unveil')
P = Transition(label='Maintenance Plan')
Q = Transition(label='Stakeholder Meet')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[A, B])
xor = OperatorPOWL(operator=Operator.XOR, children=[C, skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)