import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

initial_assess = Transition(label='Initial Assess')
disassemble_parts = Transition(label='Disassemble Parts')
ultrasonic_clean = Transition(label='Ultrasonic Clean')
inspect_components = Transition(label='Inspect Components')
fabricate_gears = Transition(label='Fabricate Gears')
dial_restoration = Transition(label='Dial Restoration')
repaint_markers = Transition(label='Repaint Markers')
reassemble_movement = Transition(label='Reassemble Movement')
lubricate_bearings = Transition(label='Lubricate Bearings')
calibrate_timing = Transition(label='Calibrate Timing')
polish_case = Transition(label='Polish Case')
re_case_watch = Transition(label='Re-case Watch')
quality_testing = Transition(label='Quality Testing')
document_process = Transition(label='Document Process')
package_product = Transition(label='Package Product')

skip = SilentTransition()
loop_inspect = OperatorPOWL(operator=Operator.LOOP, children=[inspect_components, fabricate_gears])
loop_dial = OperatorPOWL(operator=Operator.LOOP, children=[dial_restoration, repaint_markers])
loop_reassemble = OperatorPOWL(operator=Operator.LOOP, children=[reassemble_movement, lubricate_bearings, calibrate_timing])
loop_polish = OperatorPOWL(operator=Operator.LOOP, children=[polish_case, re_case_watch, quality_testing])
xor_document = OperatorPOWL(operator=Operator.XOR, children=[document_process, skip])
root = StrictPartialOrder(nodes=[initial_assess, disassemble_parts, ultrasonic_clean, loop_inspect, loop_dial, loop_reassemble, loop_polish, xor_document])
root.order.add_edge(initial_assess, disassemble_parts)
root.order.add_edge(disassemble_parts, ultrasonic_clean)
root.order.add_edge(ultrasonic_clean, inspect_components)
root.order.add_edge(inspect_components, fabricate_gears)
root.order.add_edge(fabricate_gears, loop_inspect)
root.order.add_edge(loop_inspect, dial_restoration)
root.order.add_edge(dial_restoration, repaint_markers)
root.order.add_edge(repaint_markers, loop_dial)
root.order.add_edge(loop_dial, reassemble_movement)
root.order.add_edge(reassemble_movement, lubricate_bearings)
root.order.add_edge(lubricate_bearings, calibrate_timing)
root.order.add_edge(calibrate_timing, loop_reassemble)
root.order.add_edge(loop_reassemble, polish_case)
root.order.add_edge(polish_case, re_case_watch)
root.order.add_edge(re_case_watch, quality_testing)
root.order.add_edge(quality_testing, loop_polish)
root.order.add_edge(loop_polish, document_process)
root.order.add_edge(document_process, xor_document)
root.order.add_edge(xor_document, package_product)