import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

AssetID = Transition(label='Asset ID')
ValueAssess = Transition(label='Value Assess')
RiskScan = Transition(label='Risk Scan')
MarketReview = Transition(label='Market Review')
InitialOffer = Transition(label='Initial Offer')
CounterOffer = Transition(label='Counter Offer')
Negotiation = Transition(label='Negotiation')
ContractDraft = Transition(label='Contract Draft')
LegalReview = Transition(label='Legal Review')
DigitalSign = Transition(label='Digital Sign')
RoyaltySetup = Transition(label='Royalty Setup')
TransferRecord = Transition(label='Transfer Record')
ComplianceCheck = Transition(label='Compliance Check')
AuditSchedule = Transition(label='Audit Schedule')
MarketFeedback = Transition(label='Market Feedback')
StrategyUpdate = Transition(label='Strategy Update')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[AssetID, ValueAssess, RiskScan, MarketReview])
xor = OperatorPOWL(operator=Operator.XOR, children=[InitialOffer, CounterOffer])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[Negotiation, skip])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[ContractDraft, LegalReview])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[DigitalSign, RoyaltySetup])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[TransferRecord, ComplianceCheck])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[AuditSchedule, MarketFeedback])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[StrategyUpdate, skip])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[xor2, xor3, xor4, xor5, xor6, xor7])
root = StrictPartialOrder(nodes=[loop, loop2])
root.order.add_edge(loop, loop2)