import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
ClientConsult = Transition(label='Client Consult')
PayloadAssess = Transition(label='Payload Assess')
DroneConfigure = Transition(label='Drone Configure')
RegulationCheck = Transition(label='Regulation Check')
FlightSimulate = Transition(label='Flight Simulate')
RouteOptimize = Transition(label='Route Optimize')
PackageSecure = Transition(label='Package Secure')
PreFlightInspect = Transition(label='Pre-Flight Inspect')
WeatherMonitor = Transition(label='Weather Monitor')
LaunchDrone = Transition(label='Launch Drone')
FlightTrack = Transition(label='Flight Track')
DeliveryConfirm = Transition(label='Delivery Confirm')
DataAnalyze = Transition(label='Data Analyze')
FeedbackCollect = Transition(label='Feedback Collect')
WarrantyRegister = Transition(label='Warranty Register')
IssueResolve = Transition(label='Issue Resolve')
PackageReturn = Transition(label='Package Return')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[PayloadAssess, DroneConfigure])
xor = OperatorPOWL(operator=Operator.XOR, children=[RegulationCheck, skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)