import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
A = Transition(label='Scenario Setup')
B = Transition(label='Resource Mapping')
C = Transition(label='Team Briefing')
D = Transition(label='Tech Deployment')
E = Transition(label='Data Sync')
F = Transition(label='Comm Setup')
G = Transition(label='Live Monitoring')
H = Transition(label='Variable Adjust')
I = Transition(label='Incident Injection')
J = Transition(label='Response Tracking')
K = Transition(label='Interlock Check')
L = Transition(label='Real-time Feedback')
M = Transition(label='Debrief Session')
N = Transition(label='Outcome Analysis')
O = Transition(label='Report Generation')
P = Transition(label='Improvement Plan')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P])
xor = OperatorPOWL(operator=Operator.XOR, children=[P, skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)