from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define transitions (activities)
artifact_research = Transition(label='Artifact Research')
ownership_verify = Transition(label='Ownership Verify')
stakeholder_meet = Transition(label='Stakeholder Meet')
legal_review = Transition(label='Legal Review')
diplomatic_contact = Transition(label='Diplomatic Contact')
condition_report = Transition(label='Condition Report')
transport_plan = Transition(label='Transport Plan')
insurance_setup = Transition(label='Insurance Setup')
customs_clear = Transition(label='Customs Clear')
secure_packaging = Transition(label='Secure Packaging')
shipping_monitor = Transition(label='Shipping Monitor')
community_brief = Transition(label='Community Brief')
arrival_inspect = Transition(label='Arrival Inspect')
exhibit_prepare = Transition(label='Exhibit Prepare')
public_release = Transition(label='Public Release')

# Define silent transitions
skip = SilentTransition()

# Define partial order nodes
artifact_research_node = StrictPartialOrder(nodes=[artifact_research])
ownership_verify_node = StrictPartialOrder(nodes=[ownership_verify])
stakeholder_meet_node = StrictPartialOrder(nodes=[stakeholder_meet])
legal_review_node = StrictPartialOrder(nodes=[legal_review])
diplomatic_contact_node = StrictPartialOrder(nodes=[diplomatic_contact])
condition_report_node = StrictPartialOrder(nodes=[condition_report])
transport_plan_node = StrictPartialOrder(nodes=[transport_plan])
insurance_setup_node = StrictPartialOrder(nodes=[insurance_setup])
customs_clear_node = StrictPartialOrder(nodes=[customs_clear])
secure_packaging_node = StrictPartialOrder(nodes=[secure_packaging])
shipping_monitor_node = StrictPartialOrder(nodes=[shipping_monitor])
community_brief_node = StrictPartialOrder(nodes=[community_brief])
arrival_inspect_node = StrictPartialOrder(nodes=[arrival_inspect])
exhibit_prepare_node = StrictPartialOrder(nodes=[exhibit_prepare])
public_release_node = StrictPartialOrder(nodes=[public_release])

# Define the loop and exclusive choice nodes
loop_node = OperatorPOWL(operator=Operator.LOOP, children=[secure_packaging_node, shipping_monitor_node])
exclusive_choice_node = OperatorPOWL(operator=Operator.XOR, children=[diplomatic_contact_node, skip])
exclusive_choice_node2 = OperatorPOWL(operator=Operator.XOR, children=[legal_review_node, skip])
exclusive_choice_node3 = OperatorPOWL(operator=Operator.XOR, children=[condition_report_node, skip])
exclusive_choice_node4 = OperatorPOWL(operator=Operator.XOR, children=[transport_plan_node, skip])
exclusive_choice_node5 = OperatorPOWL(operator=Operator.XOR, children=[insurance_setup_node, skip])
exclusive_choice_node6 = OperatorPOWL(operator=Operator.XOR, children=[customs_clear_node, skip])
exclusive_choice_node7 = OperatorPOWL(operator=Operator.XOR, children=[arrival_inspect_node, skip])
exclusive_choice_node8 = OperatorPOWL(operator=Operator.XOR, children=[community_brief_node, skip])
exclusive_choice_node9 = OperatorPOWL(operator=Operator.XOR, children=[exhibit_prepare_node, skip])
exclusive_choice_node10 = OperatorPOWL(operator=Operator.XOR, children=[public_release_node, skip])

# Define the partial order
root = StrictPartialOrder(nodes=[artifact_research_node, ownership_verify_node, stakeholder_meet_node, legal_review_node, diplomatic_contact_node, condition_report_node, transport_plan_node, insurance_setup_node, customs_clear_node, secure_packaging_node, shipping_monitor_node, community_brief_node, arrival_inspect_node, exhibit_prepare_node, public_release_node, loop_node, exclusive_choice_node, exclusive_choice_node2, exclusive_choice_node3, exclusive_choice_node4, exclusive_choice_node5, exclusive_choice_node6, exclusive_choice_node7, exclusive_choice_node8, exclusive_choice_node9, exclusive_choice_node10])

# Add dependencies
root.order.add_edge(artifact_research_node, ownership_verify_node)
root.order.add_edge(ownership_verify_node, stakeholder_meet_node)
root.order.add_edge(stakeholder_meet_node, legal_review_node)
root.order.add_edge(legal_review_node, diplomatic_contact_node)
root.order.add_edge(diplomatic_contact_node, condition_report_node)
root.order.add_edge(condition_report_node, transport_plan_node)
root.order.add_edge(transport_plan_node, insurance_setup_node)
root.order.add_edge(insurance_setup_node, customs_clear_node)
root.order.add_edge(customs_clear_node, secure_packaging_node)
root.order.add_edge(secure_packaging_node, shipping_monitor_node)
root.order.add_edge(shipping_monitor_node, community_brief_node)
root.order.add_edge(community_brief_node, arrival_inspect_node)
root.order.add_edge(arrival_inspect_node, exhibit_prepare_node)
root.order.add_edge(exhibit_prepare_node, public_release_node)
root.order.add_edge(artifact_research_node, exclusive_choice_node)
root.order.add_edge(ownership_verify_node, exclusive_choice_node2)
root.order.add_edge(stakeholder_meet_node, exclusive_choice_node3)
root.order.add_edge(legal_review_node, exclusive_choice_node4)
root.order.add_edge(diplomatic_contact_node, exclusive_choice_node5)
root.order.add_edge(condition_report_node, exclusive_choice_node6)
root.order.add_edge(transport_plan_node, exclusive_choice_node7)
root.order.add_edge(insurance_setup_node, exclusive_choice_node8)
root.order.add_edge(customs_clear_node, exclusive_choice_node9)
root.order.add_edge(secure_packaging_node, exclusive_choice_node10)
root.order.add_edge(exclusive_choice_node, artifact_research_node)
root.order.add_edge(exclusive_choice_node2, ownership_verify_node)
root.order.add_edge(exclusive_choice_node3, stakeholder_meet_node)
root.order.add_edge(exclusive_choice_node4, legal_review_node)
root.order.add_edge(exclusive_choice_node5, diplomatic_contact_node)
root.order.add_edge(exclusive_choice_node6, condition_report_node)
root.order.add_edge(exclusive_choice_node7, transport_plan_node)
root.order.add_edge(exclusive_choice_node8, insurance_setup_node)
root.order.add_edge(exclusive_choice_node9, customs_clear_node)
root.order.add_edge(exclusive_choice_node10, secure_packaging_node)
root.order.add_edge(loop_node, artifact_research_node)
root.order.add_edge(loop_node, ownership_verify_node)
root.order.add_edge(loop_node, stakeholder_meet_node)
root.order.add_edge(loop_node, legal_review_node)
root.order.add_edge(loop_node, diplomatic_contact_node)
root.order.add_edge(loop_node, condition_report_node)
root.order.add_edge(loop_node, transport_plan_node)
root.order.add_edge(loop_node, insurance_setup_node)
root.order.add_edge(loop_node, customs_clear_node)
root.order.add_edge(loop_node, secure_packaging_node)
root.order.add_edge(loop_node, shipping_monitor_node)
root.order.add_edge(loop_node, community_brief_node)
root.order.add_edge(loop_node, arrival_inspect_node)
root.order.add_edge(loop_node, exhibit_prepare_node)
root.order.add_edge(loop_node, public_release_node)