root = StrictPartialOrder(
    nodes=[
        Transition(label='Milk Sourcing'),
        Transition(label='Quality Testing'),
        Transition(label='Starter Culture'),
        Transition(label='Coagulation'),
        Transition(label='Curd Cutting'),
        Transition(label='Whey Draining'),
        Transition(label='Molding Cheese'),
        Transition(label='Pressing Block'),
        Transition(label='Brining Bath'),
        Transition(label='Aging Control'),
        Transition(label='Flavor Profiling'),
        Transition(label='Packaging Design'),
        Transition(label='Demand Forecast'),
        Transition(label='Retail Outreach'),
        Transition(label='Customer Feedback'),
    ],
    order=[
        ('Milk Sourcing', 'Quality Testing'),
        ('Quality Testing', 'Starter Culture'),
        ('Starter Culture', 'Coagulation'),
        ('Coagulation', 'Curd Cutting'),
        ('Curd Cutting', 'Whey Draining'),
        ('Whey Draining', 'Molding Cheese'),
        ('Molding Cheese', 'Pressing Block'),
        ('Pressing Block', 'Brining Bath'),
        ('Brining Bath', 'Aging Control'),
        ('Aging Control', 'Flavor Profiling'),
        ('Flavor Profiling', 'Packaging Design'),
        ('Packaging Design', 'Demand Forecast'),
        ('Demand Forecast', 'Retail Outreach'),
        ('Retail Outreach', 'Customer Feedback'),
    ]
)