from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

initial_assess = Transition(label='Initial Assess')
condition_scan = Transition(label='Condition Scan')
material_test = Transition(label='Material Test')
historical_check = Transition(label='Historical Check')
provenance_verify = Transition(label='Provenance Verify')
parts_sourcing = Transition(label='Parts Sourcing')
gentle_clean = Transition(label='Gentle Clean')
stabilize_item = Transition(label='Stabilize Item')
structural_repair = Transition(label='Structural Repair')
surface_finish = Transition(label='Surface Finish')
expert_consult = Transition(label='Expert Consult')
archival_review = Transition(label='Archival Review')
ethics_audit = Transition(label='Ethics Audit')
quality_inspect = Transition(label='Quality Inspect')
photo_document = Transition(label='Photo Document')
packaging_prep = Transition(label='Packaging Prep')
report_generate = Transition(label='Report Generate')
certify_provenance = Transition(label='Certify Provenance')

xor1 = OperatorPOWL(operator=Operator.XOR, children=[historical_check, archival_review])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[provenance_verify, ethics_audit])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[parts_sourcing, expert_consult])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[quality_inspect, photo_document])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[packaging_prep, report_generate])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[certify_provenance, None])

loop1 = OperatorPOWL(operator=Operator.LOOP, children=[material_test, initial_assess])
loop2 = OperatorPOWL(operator=Operator.LOOP, children=[condition_scan, stabilize_item])
loop3 = OperatorPOWL(operator=Operator.LOOP, children=[structural_repair, surface_finish])

root = StrictPartialOrder(nodes=[loop1, loop2, loop3, xor1, xor2, xor3, xor4, xor5, xor6])
root.order.add_edge(loop1, xor1)
root.order.add_edge(loop2, xor2)
root.order.add_edge(loop3, xor3)
root.order.add_edge(xor1, xor4)
root.order.add_edge(xor2, xor5)
root.order.add_edge(xor3, xor6)
root.order.add_edge(xor4, None)
root.order.add_edge(xor5, None)
root.order.add_edge(xor6, None)