root = StrictPartialOrder(
    nodes=[
        Transition(label='Site Survey'),
        Transition(label='Load Test'),
        Transition(label='Soil Sample'),
        Transition(label='Crop Select'),
        Transition(label='Irrigation Plan'),
        Transition(label='Permit Apply'),
        Transition(label='Material Order'),
        Transition(label='Bed Install'),
        Transition(label='Pest Control'),
        Transition(label='Solar Setup'),
        Transition(label='Staff Train'),
        Transition(label='Market Outreach'),
        Transition(label='System Setup'),
        Transition(label='Supplier Contact'),
        Transition(label='Health Monitor'),
    ],
    order=[
        (Transition(label='Site Survey'), Transition(label='Load Test')),
        (Transition(label='Load Test'), Transition(label='Soil Sample')),
        (Transition(label='Soil Sample'), Transition(label='Crop Select')),
        (Transition(label='Crop Select'), Transition(label='Irrigation Plan')),
        (Transition(label='Irrigation Plan'), Transition(label='Permit Apply')),
        (Transition(label='Permit Apply'), Transition(label='Material Order')),
        (Transition(label='Material Order'), Transition(label='Bed Install')),
        (Transition(label='Bed Install'), Transition(label='Pest Control')),
        (Transition(label='Pest Control'), Transition(label='Solar Setup')),
        (Transition(label='Solar Setup'), Transition(label='Staff Train')),
        (Transition(label='Staff Train'), Transition(label='Market Outreach')),
        (Transition(label='Market Outreach'), Transition(label='System Setup')),
        (Transition(label='System Setup'), Transition(label='Supplier Contact')),
        (Transition(label='Supplier Contact'), Transition(label='Health Monitor')),
    ]
)