root = StrictPartialOrder(
    nodes=[
        Transition(label='Seed Sourcing'),
        Transition(label='Germination Check'),
        Transition(label='Nutrient Mix'),
        Transition(label='Automated Planting'),
        Transition(label='Climate Control'),
        Transition(label='Crop Scanning'),
        Transition(label='Pest Monitoring'),
        Transition(label='Growth Analysis'),
        Transition(label='Robotic Harvest'),
        Transition(label='Quality Sort'),
        Transition(label='Eco Packaging'),
        Transition(label='Blockchain Track'),
        Transition(label='Route Planning'),
        Transition(label='Feedback Collect'),
        Transition(label='Waste Recycling'),
        Transition(label='Data Analytics'),
        Transition(label='Demand Forecast'),
        Transition(label='Maintenance Alert'),
    ],
    order=[
        (Transition(label='Seed Sourcing'), Transition(label='Germination Check')),
        (Transition(label='Germination Check'), Transition(label='Nutrient Mix')),
        (Transition(label='Nutrient Mix'), Transition(label='Automated Planting')),
        (Transition(label='Automated Planting'), Transition(label='Climate Control')),
        (Transition(label='Climate Control'), Transition(label='Crop Scanning')),
        (Transition(label='Crop Scanning'), Transition(label='Pest Monitoring')),
        (Transition(label='Pest Monitoring'), Transition(label='Growth Analysis')),
        (Transition(label='Growth Analysis'), Transition(label='Robotic Harvest')),
        (Transition(label='Robotic Harvest'), Transition(label='Quality Sort')),
        (Transition(label='Quality Sort'), Transition(label='Eco Packaging')),
        (Transition(label='Eco Packaging'), Transition(label='Blockchain Track')),
        (Transition(label='Blockchain Track'), Transition(label='Route Planning')),
        (Transition(label='Route Planning'), Transition(label='Feedback Collect')),
        (Transition(label='Feedback Collect'), Transition(label='Waste Recycling')),
        (Transition(label='Waste Recycling'), Transition(label='Data Analytics')),
        (Transition(label='Data Analytics'), Transition(label='Demand Forecast')),
        (Transition(label='Demand Forecast'), Transition(label='Maintenance Alert')),
    ]
)