import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

light_sourcing = Transition(label='Light Sourcing')
nutrient_order = Transition(label='Nutrient Order')
climate_setup = Transition(label='Climate Setup')
growth_planning = Transition(label='Growth Planning')
seed_planting = Transition(label='Seed Planting')
irrigation_check = Transition(label='Irrigation Check')
pest_monitoring = Transition(label='Pest Monitoring')
energy_tracking = Transition(label='Energy Tracking')
quality_testing = Transition(label='Quality Testing')
data_analysis = Transition(label='Data Analysis')
equipment_repair = Transition(label='Equipment Repair')
packaging_prep = Transition(label='Packaging Prep')
inventory_update = Transition(label='Inventory Update')
delivery_scheduling = Transition(label='Delivery Scheduling')
customer_feedback = Transition(label='Customer Feedback')
market_forecast = Transition(label='Market Forecast')

skip = SilentTransition()

# Process steps
light_sourcing_next_nutrient_order = OperatorPOWL(operator=Operator.XOR, children=[light_sourcing, nutrient_order])
nutrient_order_next_climate_setup = OperatorPOWL(operator=Operator.XOR, children=[nutrient_order, climate_setup])
climate_setup_next_growth_planning = OperatorPOWL(operator=Operator.XOR, children=[climate_setup, growth_planning])
growth_planning_next_seed_planting = OperatorPOWL(operator=Operator.XOR, children=[growth_planning, seed_planting])
seed_planting_next_irrigation_check = OperatorPOWL(operator=Operator.XOR, children=[seed_planting, irrigation_check])
irrigation_check_next_pest_monitoring = OperatorPOWL(operator=Operator.XOR, children=[irrigation_check, pest_monitoring])
pest_monitoring_next_energy_tracking = OperatorPOWL(operator=Operator.XOR, children=[pest_monitoring, energy_tracking])
energy_tracking_next_quality_testing = OperatorPOWL(operator=Operator.XOR, children=[energy_tracking, quality_testing])
quality_testing_next_data_analysis = OperatorPOWL(operator=Operator.XOR, children=[quality_testing, data_analysis])
data_analysis_next_equipment_repair = OperatorPOWL(operator=Operator.XOR, children=[data_analysis, equipment_repair])
equipment_repair_next_packaging_prep = OperatorPOWL(operator=Operator.XOR, children=[equipment_repair, packaging_prep])
packaging_prep_next_inventory_update = OperatorPOWL(operator=Operator.XOR, children=[packaging_prep, inventory_update])
inventory_update_next_delivery_scheduling = OperatorPOWL(operator=Operator.XOR, children=[inventory_update, delivery_scheduling])
delivery_scheduling_next_customer_feedback = OperatorPOWL(operator=Operator.XOR, children=[delivery_scheduling, customer_feedback])
customer_feedback_next_market_forecast = OperatorPOWL(operator=Operator.XOR, children=[customer_feedback, market_forecast])
market_forecast_next_light_sourcing = OperatorPOWL(operator=Operator.XOR, children=[market_forecast, light_sourcing])

root = StrictPartialOrder(nodes=[light_sourcing_next_nutrient_order, nutrient_order_next_climate_setup, climate_setup_next_growth_planning, growth_planning_next_seed_planting, seed_planting_next_irrigation_check, irrigation_check_next_pest_monitoring, pest_monitoring_next_energy_tracking, energy_tracking_next_quality_testing, quality_testing_next_data_analysis, data_analysis_next_equipment_repair, equipment_repair_next_packaging_prep, packaging_prep_next_inventory_update, inventory_update_next_delivery_scheduling, delivery_scheduling_next_customer_feedback, customer_feedback_next_market_forecast, market_forecast_next_light_sourcing])
root.order.add_edge(light_sourcing_next_nutrient_order, nutrient_order_next_climate_setup)
root.order.add_edge(nutrient_order_next_climate_setup, climate_setup_next_growth_planning)
root.order.add_edge(climate_setup_next_growth_planning, growth_planning_next_seed_planting)
root.order.add_edge(growth_planning_next_seed_planting, seed_planting_next_irrigation_check)
root.order.add_edge(seed_planting_next_irrigation_check, irrigation_check_next_pest_monitoring)
root.order.add_edge(irrigation_check_next_pest_monitoring, pest_monitoring_next_energy_tracking)
root.order.add_edge(pest_monitoring_next_energy_tracking, energy_tracking_next_quality_testing)
root.order.add_edge(energy_tracking_next_quality_testing, quality_testing_next_data_analysis)
root.order.add_edge(quality_testing_next_data_analysis, data_analysis_next_equipment_repair)
root.order.add_edge(data_analysis_next_equipment_repair, equipment_repair_next_packaging_prep)
root.order.add_edge(equipment_repair_next_packaging_prep, packaging_prep_next_inventory_update)
root.order.add_edge(packaging_prep_next_inventory_update, inventory_update_next_delivery_scheduling)
root.order.add_edge(inventory_update_next_delivery_scheduling, delivery_scheduling_next_customer_feedback)
root.order.add_edge(delivery_scheduling_next_customer_feedback, customer_feedback_next_market_forecast)
root.order.add_edge(customer_feedback_next_market_forecast, market_forecast_next_light_sourcing)