root = StrictPartialOrder(
    nodes=[
        Transition(label='Light Sourcing'),
        Transition(label='Nutrient Order'),
        Transition(label='Climate Setup'),
        Transition(label='Growth Planning'),
        Transition(label='Seed Planting'),
        Transition(label='Irrigation Check'),
        Transition(label='Pest Monitoring'),
        Transition(label='Energy Tracking'),
        Transition(label='Quality Testing'),
        Transition(label='Data Analysis'),
        Transition(label='Equipment Repair'),
        Transition(label='Packaging Prep'),
        Transition(label='Inventory Update'),
        Transition(label='Delivery Scheduling'),
        Transition(label='Customer Feedback'),
        Transition(label='Market Forecast')
    ],
    order={
        ('Light Sourcing', 'Nutrient Order'): None,
        ('Light Sourcing', 'Climate Setup'): None,
        ('Light Sourcing', 'Growth Planning'): None,
        ('Nutrient Order', 'Climate Setup'): None,
        ('Nutrient Order', 'Growth Planning'): None,
        ('Climate Setup', 'Growth Planning'): None,
        ('Growth Planning', 'Seed Planting'): None,
        ('Growth Planning', 'Irrigation Check'): None,
        ('Growth Planning', 'Pest Monitoring'): None,
        ('Growth Planning', 'Energy Tracking'): None,
        ('Growth Planning', 'Quality Testing'): None,
        ('Seed Planting', 'Irrigation Check'): None,
        ('Seed Planting', 'Pest Monitoring'): None,
        ('Seed Planting', 'Energy Tracking'): None,
        ('Seed Planting', 'Quality Testing'): None,
        ('Irrigation Check', 'Pest Monitoring'): None,
        ('Irrigation Check', 'Energy Tracking'): None,
        ('Irrigation Check', 'Quality Testing'): None,
        ('Pest Monitoring', 'Energy Tracking'): None,
        ('Pest Monitoring', 'Quality Testing'): None,
        ('Energy Tracking', 'Quality Testing'): None,
        ('Quality Testing', 'Data Analysis'): None,
        ('Quality Testing', 'Equipment Repair'): None,
        ('Quality Testing', 'Packaging Prep'): None,
        ('Data Analysis', 'Inventory Update'): None,
        ('Data Analysis', 'Delivery Scheduling'): None,
        ('Data Analysis', 'Customer Feedback'): None,
        ('Data Analysis', 'Market Forecast'): None,
        ('Equipment Repair', 'Packaging Prep'): None,
        ('Packaging Prep', 'Inventory Update'): None,
        ('Packaging Prep', 'Delivery Scheduling'): None,
        ('Inventory Update', 'Delivery Scheduling'): None,
        ('Inventory Update', 'Customer Feedback'): None,
        ('Inventory Update', 'Market Forecast'): None,
        ('Delivery Scheduling', 'Customer Feedback'): None,
        ('Delivery Scheduling', 'Market Forecast'): None,
        ('Customer Feedback', 'Market Forecast'): None
    }
)