from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_survey = Transition(label='Site Survey')
design_layout = Transition(label='Design Layout')
system_build = Transition(label='System Build')
install_sensors = Transition(label='Install Sensors')
select_crops = Transition(label='Select Crops')
setup_lighting = Transition(label='Setup Lighting')
configure_climate = Transition(label='Configure Climate')
nutrient_mix = Transition(label='Nutrient Mix')
automate_watering = Transition(label='Automate Watering')
test_systems = Transition(label='Test Systems')
train_staff = Transition(label='Train Staff')
waste_plan = Transition(label='Waste Plan')
market_link = Transition(label='Market Link')
data_monitor = Transition(label='Data Monitor')
optimize_yield = Transition(label='Optimize Yield')

skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[site_survey, design_layout])
xor = OperatorPOWL(operator=Operator.XOR, children=[system_build, install_sensors])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[select_crops, setup_lighting])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[configure_climate, nutrient_mix])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[automate_watering, test_systems])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[train_staff, waste_plan])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[market_link, data_monitor])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[optimize_yield, skip])

root = StrictPartialOrder(nodes=[loop, xor, xor2, xor3, xor4, xor5, xor6, xor7])
root.order.add_edge(loop, xor)
root.order.add_edge(xor, xor2)
root.order.add_edge(xor2, xor3)
root.order.add_edge(xor3, xor4)
root.order.add_edge(xor4, xor5)
root.order.add_edge(xor5, xor6)
root.order.add_edge(xor6, xor7)