root = StrictPartialOrder(
    nodes=[
        Transition(label='Milk Sourcing'),
        Transition(label='Curd Preparation'),
        Transition(label='starter Culture'),
        Transition(label='Temperature Control'),
        Transition(label='Pressing Cheese'),
        Transition(label='Salting Stage'),
        Transition(label='Aging Process'),
        Transition(label='Microbial Test'),
        Transition(label='Quality Check'),
        Transition(label='Eco Packaging'),
        Transition(label='Label Printing'),
        Transition(label='Inventory Audit'),
        Transition(label='Order Processing'),
        Transition(label='Retail Shipping'),
        Transition(label='Customer Feedback'),
        Transition(label='Recipe Update'),
        Transition(label='Market Analysis'),
    ],
    order=[
        ('Milk Sourcing', 'Curd Preparation'),
        ('Curd Preparation', 'starter Culture'),
        ('starter Culture', 'Temperature Control'),
        ('Temperature Control', 'Pressing Cheese'),
        ('Pressing Cheese', 'Salting Stage'),
        ('Salting Stage', 'Aging Process'),
        ('Aging Process', 'Microbial Test'),
        ('Microbial Test', 'Quality Check'),
        ('Quality Check', 'Eco Packaging'),
        ('Eco Packaging', 'Label Printing'),
        ('Label Printing', 'Inventory Audit'),
        ('Inventory Audit', 'Order Processing'),
        ('Order Processing', 'Retail Shipping'),
        ('Retail Shipping', 'Customer Feedback'),
        ('Customer Feedback', 'Recipe Update'),
        ('Recipe Update', 'Market Analysis'),
        ('Market Analysis', 'Milk Sourcing'),
    ]
)