import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
A = Transition(label='Milk Sourcing')
B = Transition(label='Quality Testing')
C = Transition(label='Batch Selection')
D = Transition(label='Curd Preparation')
E = Transition(label='Pressing Cheese')
F = Transition(label='Aging Control')
G = Transition(label='Flavor Profiling')
H = Transition(label='Packaging Prep')
I = Transition(label='Climate Packing')
J = Transition(label='Export Licensing')
K = Transition(label='Customs Filing')
L = Transition(label='Freight Booking')
M = Transition(label='Cold Storage')
N = Transition(label='Transport Tracking')
O = Transition(label='Retail Delivery')
P = Transition(label='Feedback Collection')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P])
xor = OperatorPOWL(operator=Operator.XOR, children=[skip])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)