root = StrictPartialOrder(
    nodes=[
        Transition(label='Scan Markets'),
        Transition(label='Host Workshops'),
        Transition(label='Form Teams'),
        Transition(label='Develop Prototypes'),
        Transition(label='Simulate Tests'),
        Transition(label='Collect Feedback'),
        Transition(label='Review Ethics'),
        Transition(label='Conduct Analysis'),
        Transition(label='Identify Partners'),
        Transition(label='Align Strategy'),
        Transition(label='Launch Pilots'),
        Transition(label='Monitor Trends'),
        Transition(label='AI Analytics'),
        Transition(label='Pivot Plans'),
        Transition(label='Cycle Renewal'),
    ],
    order=[
        ('Scan Markets', 'Host Workshops'),
        ('Host Workshops', 'Form Teams'),
        ('Form Teams', 'Develop Prototypes'),
        ('Develop Prototypes', 'Simulate Tests'),
        ('Simulate Tests', 'Collect Feedback'),
        ('Collect Feedback', 'Review Ethics'),
        ('Review Ethics', 'Conduct Analysis'),
        ('Conduct Analysis', 'Identify Partners'),
        ('Identify Partners', 'Align Strategy'),
        ('Align Strategy', 'Launch Pilots'),
        ('Launch Pilots', 'Monitor Trends'),
        ('Monitor Trends', 'AI Analytics'),
        ('AI Analytics', 'Pivot Plans'),
        ('Pivot Plans', 'Cycle Renewal'),
    ]
)