root = StrictPartialOrder(
    nodes=[
        Transition(label='Structural Check'),
        Transition(label='Permit Apply'),
        Transition(label='Design Layout'),
        Transition(label='Soil Prep'),
        Transition(label='Bed Install'),
        Transition(label='Irrigation Setup'),
        Transition(label='Sensor Mount'),
        Transition(label='Solar Connect'),
        Transition(label='Seed Order'),
        Transition(label='Nutrient Mix'),
        Transition(label='Community Meet'),
        Transition(label='Staff Train'),
        Transition(label='Plant Crop'),
        Transition(label='Maintenance Plan'),
        Transition(label='Harvest Schedule'),
        Transition(label='Waste Manage'),
    ],
    order={
        ('Structural Check', 'Permit Apply'): None,
        ('Permit Apply', 'Design Layout'): None,
        ('Design Layout', 'Soil Prep'): None,
        ('Soil Prep', 'Bed Install'): None,
        ('Bed Install', 'Irrigation Setup'): None,
        ('Irrigation Setup', 'Sensor Mount'): None,
        ('Sensor Mount', 'Solar Connect'): None,
        ('Solar Connect', 'Seed Order'): None,
        ('Seed Order', 'Nutrient Mix'): None,
        ('Nutrient Mix', 'Community Meet'): None,
        ('Community Meet', 'Staff Train'): None,
        ('Staff Train', 'Plant Crop'): None,
        ('Plant Crop', 'Maintenance Plan'): None,
        ('Maintenance Plan', 'Harvest Schedule'): None,
        ('Harvest Schedule', 'Waste Manage'): None,
    },
)