root = StrictPartialOrder(nodes=[
    Transition(label='Site Prep'),
    Transition(label='Seed Select'),
    Transition(label='Nutrient Mix'),
    Transition(label='Planting Rows'),
    Transition(label='Env Monitor'),
    Transition(label='Water Adjust'),
    Transition(label='Pest Control'),
    Transition(label='Growth Check'),
    Transition(label='Light Calibrate'),
    Transition(label='Energy Manage'),
    Transition(label='Harvest Crop'),
    Transition(label='Quality Sort'),
    Transition(label='Pack Goods'),
    Transition(label='Cold Store'),
    Transition(label='Market Ship'),
    Transition(label='Data Analyze'),
], order={
    ('Site Prep', 'Seed Select'): None,
    ('Seed Select', 'Nutrient Mix'): None,
    ('Nutrient Mix', 'Planting Rows'): None,
    ('Planting Rows', 'Env Monitor'): None,
    ('Env Monitor', 'Water Adjust'): None,
    ('Water Adjust', 'Pest Control'): None,
    ('Pest Control', 'Growth Check'): None,
    ('Growth Check', 'Light Calibrate'): None,
    ('Light Calibrate', 'Energy Manage'): None,
    ('Energy Manage', 'Harvest Crop'): None,
    ('Harvest Crop', 'Quality Sort'): None,
    ('Quality Sort', 'Pack Goods'): None,
    ('Pack Goods', 'Cold Store'): None,
    ('Cold Store', 'Market Ship'): None,
    ('Market Ship', 'Data Analyze'): None
})