root = StrictPartialOrder(
    nodes=[
        Transition(label='Site Survey'),
        Transition(label='Structural Audit'),
        Transition(label='Climate Design'),
        Transition(label='Lighting Setup'),
        Transition(label='Irrigation Plan'),
        Transition(label='Nutrient Mix'),
        Transition(label='Sensor Install'),
        Transition(label='AI Calibration'),
        Transition(label='Pest Scan'),
        Transition(label='Energy Audit'),
        Transition(label='Renewable Sync'),
        Transition(label='Data Modeling'),
        Transition(label='Staff Briefing'),
        Transition(label='Compliance Check'),
        Transition(label='Community Meet'),
        Transition(label='Yield Review'),
        Transition(label='Feedback Loop'),
    ],
    order=[
        (Transition(label='Site Survey'), Transition(label='Structural Audit')),
        (Transition(label='Structural Audit'), Transition(label='Climate Design')),
        (Transition(label='Climate Design'), Transition(label='Lighting Setup')),
        (Transition(label='Lighting Setup'), Transition(label='Irrigation Plan')),
        (Transition(label='Irrigation Plan'), Transition(label='Nutrient Mix')),
        (Transition(label='Nutrient Mix'), Transition(label='Sensor Install')),
        (Transition(label='Sensor Install'), Transition(label='AI Calibration')),
        (Transition(label='AI Calibration'), Transition(label='Pest Scan')),
        (Transition(label='Pest Scan'), Transition(label='Energy Audit')),
        (Transition(label='Energy Audit'), Transition(label='Renewable Sync')),
        (Transition(label='Renewable Sync'), Transition(label='Data Modeling')),
        (Transition(label='Data Modeling'), Transition(label='Staff Briefing')),
        (Transition(label='Staff Briefing'), Transition(label='Compliance Check')),
        (Transition(label='Compliance Check'), Transition(label='Community Meet')),
        (Transition(label='Community Meet'), Transition(label='Yield Review')),
        (Transition(label='Yield Review'), Transition(label='Feedback Loop')),
    ]
)