root = StrictPartialOrder(
    nodes=[
        Transition(label='Document Review'),
        Transition(label='Material Testing'),
        Transition(label='Radiocarbon Date'),
        Transition(label='Stylistic Eval'),
        Transition(label='Database Check'),
        Transition(label='Ownership Audit'),
        Transition(label='Export Verify'),
        Transition(label='Expert Arbitration'),
        Transition(label='Conservation Plan'),
        Transition(label='Risk Assessment'),
        Transition(label='Approval Review'),
        Transition(label='Insurance Setup'),
        Transition(label='Secure Transport'),
        Transition(label='Acquisitions Meet'),
        Transition(label='Final Documentation')
    ],
    order=[
        ('Document Review', 'Material Testing'),
        ('Material Testing', 'Radiocarbon Date'),
        ('Material Testing', 'Stylistic Eval'),
        ('Material Testing', 'Database Check'),
        ('Material Testing', 'Ownership Audit'),
        ('Material Testing', 'Export Verify'),
        ('Material Testing', 'Expert Arbitration'),
        ('Material Testing', 'Conservation Plan'),
        ('Material Testing', 'Risk Assessment'),
        ('Material Testing', 'Approval Review'),
        ('Material Testing', 'Insurance Setup'),
        ('Material Testing', 'Secure Transport'),
        ('Material Testing', 'Acquisitions Meet'),
        ('Material Testing', 'Final Documentation'),
        ('Radiocarbon Date', 'Approval Review'),
        ('Stylistic Eval', 'Approval Review'),
        ('Database Check', 'Approval Review'),
        ('Ownership Audit', 'Approval Review'),
        ('Export Verify', 'Approval Review'),
        ('Expert Arbitration', 'Approval Review'),
        ('Conservation Plan', 'Approval Review'),
        ('Risk Assessment', 'Approval Review'),
        ('Approval Review', 'Insurance Setup'),
        ('Insurance Setup', 'Secure Transport'),
        ('Secure Transport', 'Acquisitions Meet'),
        ('Acquisitions Meet', 'Final Documentation')
    ]
)