root = StrictPartialOrder(
    nodes=[
        Transition(label='Client Inquiry'),
        Transition(label='Requirement Gather'),
        Transition(label='Concept Sketch'),
        Transition(label='Client Feedback'),
        Transition(label='Revision Cycle'),
        Transition(label='Final Approval'),
        Transition(label='Art Creation'),
        Transition(label='Progress Update'),
        Transition(label='Quality Check'),
        Transition(label='Final Adjust'),
        Transition(label='Invoice Issue'),
        Transition(label='Shipment Prep'),
        Transition(label='Delivery Confirm'),
        Transition(label='Post Support'),
        Transition(label='License Setup'),
        Transition(label='Frame Arrange'),
    ],
    order=[
        ('Client Inquiry', 'Requirement Gather'),
        ('Requirement Gather', 'Concept Sketch'),
        ('Concept Sketch', 'Client Feedback'),
        ('Client Feedback', 'Revision Cycle'),
        ('Revision Cycle', 'Final Approval'),
        ('Final Approval', 'Art Creation'),
        ('Art Creation', 'Progress Update'),
        ('Progress Update', 'Quality Check'),
        ('Quality Check', 'Final Adjust'),
        ('Final Adjust', 'Invoice Issue'),
        ('Invoice Issue', 'Shipment Prep'),
        ('Shipment Prep', 'Delivery Confirm'),
        ('Delivery Confirm', 'Post Support'),
        ('Post Support', 'License Setup'),
        ('License Setup', 'Frame Arrange'),
    ]
)