root = StrictPartialOrder(nodes=[
    Transition(label='Site Survey'),
    Transition(label='Permit Acquire'),
    Transition(label='Rack Design'),
    Transition(label='Seed Selection'),
    Transition(label='Nutrient Mix'),
    Transition(label='Lighting Setup'),
    Transition(label='Sensor Install'),
    Transition(label='System Test'),
    Transition(label='Staff Hire'),
    Transition(label='Training Lead'),
    Transition(label='Waste Manage'),
    Transition(label='Supply Chain'),
    Transition(label='Crop Cycle'),
    Transition(label='Data Monitor'),
    Transition(label='Harvest Plan'),
    Transition(label='Distribution'),
], order={
    ('Site Survey', 'Permit Acquire'): 0,
    ('Permit Acquire', 'Rack Design'): 0,
    ('Rack Design', 'Seed Selection'): 0,
    ('Seed Selection', 'Nutrient Mix'): 0,
    ('Nutrient Mix', 'Lighting Setup'): 0,
    ('Lighting Setup', 'Sensor Install'): 0,
    ('Sensor Install', 'System Test'): 0,
    ('System Test', 'Staff Hire'): 0,
    ('Staff Hire', 'Training Lead'): 0,
    ('Training Lead', 'Waste Manage'): 0,
    ('Waste Manage', 'Supply Chain'): 0,
    ('Supply Chain', 'Crop Cycle'): 0,
    ('Crop Cycle', 'Data Monitor'): 0,
    ('Data Monitor', 'Harvest Plan'): 0,
    ('Harvest Plan', 'Distribution'): 0
})