root = StrictPartialOrder(
    nodes=[
        Transition(label='Intake Review'),
        Transition(label='Visual Inspect'),
        Transition(label='Material Test'),
        Transition(label='Provenance Check'),
        Transition(label='Archival Search'),
        Transition(label='Expert Consult'),
        Transition(label='Digital Scan'),
        Transition(label='Condition Report'),
        Transition(label='Forgery Assess'),
        Transition(label='Legal Review'),
        Transition(label='Risk Analysis'),
        Transition(label='Acquisition Vote'),
        Transition(label='Catalog Entry'),
        Transition(label='Storage Prep'),
        Transition(label='Final Approval')
    ],
    order=[
        ('Intake Review', 'Visual Inspect'),
        ('Intake Review', 'Material Test'),
        ('Visual Inspect', 'Provenance Check'),
        ('Visual Inspect', 'Archival Search'),
        ('Visual Inspect', 'Expert Consult'),
        ('Visual Inspect', 'Digital Scan'),
        ('Visual Inspect', 'Condition Report'),
        ('Visual Inspect', 'Forgery Assess'),
        ('Material Test', 'Provenance Check'),
        ('Material Test', 'Archival Search'),
        ('Material Test', 'Expert Consult'),
        ('Material Test', 'Digital Scan'),
        ('Material Test', 'Condition Report'),
        ('Material Test', 'Forgery Assess'),
        ('Provenance Check', 'Acquisition Vote'),
        ('Archival Search', 'Acquisition Vote'),
        ('Expert Consult', 'Acquisition Vote'),
        ('Digital Scan', 'Acquisition Vote'),
        ('Condition Report', 'Acquisition Vote'),
        ('Forgery Assess', 'Acquisition Vote'),
        ('Legal Review', 'Risk Analysis'),
        ('Risk Analysis', 'Acquisition Vote'),
        ('Catalog Entry', 'Storage Prep'),
        ('Storage Prep', 'Final Approval'),
        ('Final Approval', 'Acquisition Vote')
    ]
)