root = StrictPartialOrder(nodes=[
    Transition(label='Site Analysis'),
    Transition(label='Infrastructure Setup'),
    Transition(label='Seed Selection'),
    Transition(label='Nutrient Mix'),
    Transition(label='Planting Cycle'),
    Transition(label='Climate Adjust'),
    Transition(label='Growth Monitor'),
    Transition(label='Pest Control'),
    Transition(label='Harvesting Mode'),
    Transition(label='Quality Check'),
    Transition(label='Packaging Phase'),
    Transition(label='Cold Storage'),
    Transition(label='Order Dispatch'),
    Transition(label='Waste Recycling'),
    Transition(label='System Maintain'),
    OperatorPOWL(operator=Operator.XOR, children=[
        Transition(label='Site Analysis'),
        Transition(label='Infrastructure Setup'),
        Transition(label='Seed Selection'),
        Transition(label='Nutrient Mix'),
        Transition(label='Planting Cycle'),
        Transition(label='Climate Adjust'),
        Transition(label='Growth Monitor'),
        Transition(label='Pest Control'),
        Transition(label='Harvesting Mode'),
        Transition(label='Quality Check'),
        Transition(label='Packaging Phase'),
        Transition(label='Cold Storage'),
        Transition(label='Order Dispatch'),
        Transition(label='Waste Recycling'),
        Transition(label='System Maintain')
    ])
])