root = StrictPartialOrder(nodes=[
    Transition(label='Artifact Intake'),
    Transition(label='Provenance Check'),
    Transition(label='Material Sampling'),
    Transition(label='Scientific Test'),
    Transition(label='Expert Review'),
    Transition(label='Archive Search'),
    Transition(label='Legal Verify'),
    Transition(label='Ownership Confirm'),
    Transition(label='Compliance Audit'),
    Transition(label='Data Documentation'),
    Transition(label='Interim Report'),
    Transition(label='Department Review'),
    Transition(label='Consensus Meeting'),
    Transition(label='Final Approval'),
    Transition(label='Artifact Release')
])
root.order.add_edge(root.nodes[0], root.nodes[1])
root.order.add_edge(root.nodes[0], root.nodes[2])
root.order.add_edge(root.nodes[1], root.nodes[3])
root.order.add_edge(root.nodes[1], root.nodes[4])
root.order.add_edge(root.nodes[2], root.nodes[5])
root.order.add_edge(root.nodes[3], root.nodes[6])
root.order.add_edge(root.nodes[3], root.nodes[7])
root.order.add_edge(root.nodes[4], root.nodes[8])
root.order.add_edge(root.nodes[4], root.nodes[9])
root.order.add_edge(root.nodes[5], root.nodes[10])
root.order.add_edge(root.nodes[6], root.nodes[11])
root.order.add_edge(root.nodes[7], root.nodes[12])
root.order.add_edge(root.nodes[8], root.nodes[13])
root.order.add_edge(root.nodes[9], root.nodes[13])
root.order.add_edge(root.nodes[10], root.nodes[14])
root.order.add_edge(root.nodes[11], root.nodes[15])
root.order.add_edge(root.nodes[12], root.nodes[16])
root.order.add_edge(root.nodes[13], root.nodes[17])
root.order.add_edge(root.nodes[14], root.nodes[17])
root.order.add_edge(root.nodes[15], root.nodes[17])
root.order.add_edge(root.nodes[16], root.nodes[17])