root = StrictPartialOrder(nodes=[
    Transition(label='Client Intake'),
    Transition(label='Needs Analysis'),
    Transition(label='Developer Match'),
    Transition(label='Expert Vetting'),
    Transition(label='Prototype Build'),
    Transition(label='Feedback Loop'),
    Transition(label='Model Refinement'),
    Transition(label='License Draft'),
    Transition(label='IP Negotiation'),
    Transition(label='Contract Sign'),
    Transition(label='Deployment Prep'),
    Transition(label='Go Live'),
    Transition(label='Monitor Model'),
    Transition(label='Optimize AI'),
    Transition(label='Support Handoff'),
    Transition(label='Compliance Check'),
    Transition(label='Final Review')
])

root.order.add_edge(root.nodes[0], root.nodes[1])
root.order.add_edge(root.nodes[1], root.nodes[2])
root.order.add_edge(root.nodes[2], root.nodes[3])
root.order.add_edge(root.nodes[3], root.nodes[4])
root.order.add_edge(root.nodes[4], root.nodes[5])
root.order.add_edge(root.nodes[5], root.nodes[6])
root.order.add_edge(root.nodes[6], root.nodes[7])
root.order.add_edge(root.nodes[7], root.nodes[8])
root.order.add_edge(root.nodes[8], root.nodes[9])
root.order.add_edge(root.nodes[9], root.nodes[10])
root.order.add_edge(root.nodes[10], root.nodes[11])
root.order.add_edge(root.nodes[11], root.nodes[12])
root.order.add_edge(root.nodes[12], root.nodes[13])
root.order.add_edge(root.nodes[13], root.nodes[14])
root.order.add_edge(root.nodes[14], root.nodes[15])
root.order.add_edge(root.nodes[15], root.nodes[16])
root.order.add_edge(root.nodes[16], root.nodes[17])
root.order.add_edge(root.nodes[17], root.nodes[18])
root.order.add_edge(root.nodes[18], root.nodes[19])
root.order.add_edge(root.nodes[19], root.nodes[20])
root.order.add_edge(root.nodes[20], root.nodes[21])