root = StrictPartialOrder(
    nodes=[
        Transition('Site Survey'),
        Transition('Structure Check'),
        Transition('Hydroponic Install'),
        Transition('Lighting Setup'),
        Transition('Climate Control'),
        Transition('Seed Selection'),
        Transition('Nutrient Mix'),
        Transition('Water Recycling'),
        Transition('Sensor Deploy'),
        Transition('Pest Control'),
        Transition('Growth Monitor'),
        Transition('Harvest Plan'),
        Transition('Packaging Prep'),
        Transition('Delivery Route'),
        Transition('Data Analysis'),
        Transition('Yield Forecast'),
    ],
    order=[
        ('Site Survey', 'Structure Check'),
        ('Structure Check', 'Hydroponic Install'),
        ('Hydroponic Install', 'Lighting Setup'),
        ('Lighting Setup', 'Climate Control'),
        ('Climate Control', 'Seed Selection'),
        ('Seed Selection', 'Nutrient Mix'),
        ('Nutrient Mix', 'Water Recycling'),
        ('Water Recycling', 'Sensor Deploy'),
        ('Sensor Deploy', 'Pest Control'),
        ('Pest Control', 'Growth Monitor'),
        ('Growth Monitor', 'Harvest Plan'),
        ('Harvest Plan', 'Packaging Prep'),
        ('Packaging Prep', 'Delivery Route'),
        ('Delivery Route', 'Data Analysis'),
        ('Data Analysis', 'Yield Forecast'),
    ]
)