from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

client_consult = Transition(label='Client Consult')
spec_gathering = Transition(label='Spec Gathering')
supplier_sourcing = Transition(label='Supplier Sourcing')
design_review = Transition(label='Design Review')
simulation_test = Transition(label='Simulation Test')
proto_assembly = Transition(label='Proto Assembly')
quality_check = Transition(label='Quality Check')
firmware_flash = Transition(label='Firmware Flash')
sensor_install = Transition(label='Sensor Install')
final_testing = Transition(label='Final Testing')
brand_packaging = Transition(label='Brand Packaging')
shipping_prep = Transition(label='Shipping Prep')
delivery_schedule = Transition(label='Delivery Schedule')
client_training = Transition(label='Client Training')
diagnostics_setup = Transition(label='Diagnostics Setup')

skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[spec_gathering, supplier_sourcing])
xor = OperatorPOWL(operator=Operator.XOR, children=[design_review, simulation_test])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[proto_assembly, quality_check])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[firmware_flash, sensor_install])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[final_testing, brand_packaging])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[shipping_prep, delivery_schedule])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[client_training, diagnostics_setup])

root = StrictPartialOrder(nodes=[loop, xor, xor2, xor3, xor4, xor5, xor6])
root.order.add_edge(loop, xor)
root.order.add_edge(xor, xor2)
root.order.add_edge(xor2, xor3)
root.order.add_edge(xor3, xor4)
root.order.add_edge(xor4, xor5)
root.order.add_edge(xor5, xor6)