from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

data_capture = Transition(label='Data Capture')
fingerprint_art = Transition(label='Fingerprint Art')
record_input = Transition(label='Record Input')
historical_check = Transition(label='Historical Check')
stakeholder_vote = Transition(label='Stakeholder Vote')
consensus_validate = Transition(label='Consensus Validate')
timestamp_entry = Transition(label='Timestamp Entry')
ledger_update = Transition(label='Ledger Update')
ai_patternscan = Transition(label='AI PatternScan')
flag_anomaly = Transition(label='Flag Anomaly')
dispute_submit = Transition(label='Dispute Submit')
panel_review = Transition(label='Panel Review')
arbitrate_case = Transition(label='Arbitrate Case')
trade_monitor = Transition(label='Trade Monitor')
feedback_loop = Transition(label='Feedback Loop')
insurance_sync = Transition(label='Insurance Sync')
collector_notify = Transition(label='Collector Notify')

xor1 = OperatorPOWL(operator=Operator.XOR, children=[data_capture, fingerprint_art])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[record_input, historical_check])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[stakeholder_vote, consensus_validate])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[timestamp_entry, ledger_update])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[ai_patternscan, flag_anomaly])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[dispute_submit, panel_review])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[arbitrate_case, trade_monitor])
xor8 = OperatorPOWL(operator=Operator.XOR, children=[feedback_loop, insurance_sync])
xor9 = OperatorPOWL(operator=Operator.XOR, children=[collector_notify, insurance_sync])

root = StrictPartialOrder(nodes=[xor1, xor2, xor3, xor4, xor5, xor6, xor7, xor8, xor9])
root.order.add_edge(xor1, xor2)
root.order.add_edge(xor2, xor3)
root.order.add_edge(xor3, xor4)
root.order.add_edge(xor4, xor5)
root.order.add_edge(xor5, xor6)
root.order.add_edge(xor6, xor7)
root.order.add_edge(xor7, xor8)
root.order.add_edge(xor8, xor9)