root = StrictPartialOrder(
    nodes=[
        Transition(label='Site Survey'),
        Transition(label='Design Layout'),
        Transition(label='System Assembly'),
        Transition(label='Climate Setup'),
        Transition(label='Light Calibration'),
        Transition(label='Seed Selection'),
        Transition(label='Seedling Prep'),
        Transition(label='Nutrient Mix'),
        Transition(label='Irrigation Setup'),
        Transition(label='Sensor Install'),
        Transition(label='Data Integration'),
        Transition(label='Waste Routing'),
        Transition(label='Energy Audit'),
        Transition(label='Regulation Check'),
        Transition(label='Operational Test'),
        Transition(label='Community Outreach'),
    ],
    order=[
        ('Site Survey', 'Design Layout'),
        ('Design Layout', 'System Assembly'),
        ('System Assembly', 'Climate Setup'),
        ('Climate Setup', 'Light Calibration'),
        ('Light Calibration', 'Seed Selection'),
        ('Seed Selection', 'Seedling Prep'),
        ('Seedling Prep', 'Nutrient Mix'),
        ('Nutrient Mix', 'Irrigation Setup'),
        ('Irrigation Setup', 'Sensor Install'),
        ('Sensor Install', 'Data Integration'),
        ('Data Integration', 'Waste Routing'),
        ('Waste Routing', 'Energy Audit'),
        ('Energy Audit', 'Regulation Check'),
        ('Regulation Check', 'Operational Test'),
        ('Operational Test', 'Community Outreach'),
    ],
)