import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
Milk_Sourcing = Transition(label='Milk Sourcing')
Culture_Selection = Transition(label='Culture Selection')
Milk_Testing = Transition(label='Milk Testing')
Fermentation_Start = Transition(label='Fermentation Start')
Temperature_Control = Transition(label='Temperature Control')
pH_Monitoring = Transition(label='pH Monitoring')
Curd_Cutting = Transition(label='Curd Cutting')
Whey_Draining = Transition(label='Whey Draining')
Molding_Cheese = Transition(label='Molding Cheese')
Salting_Process = Transition(label='Salting Process')
Aging_Setup = Transition(label='Aging Setup')
Quality_Check = Transition(label='Quality Check')
Packaging_Preparation = Transition(label='Packaging Prep')
Label_Design = Transition(label='Label Design')
Distribution_Plan = Transition(label='Distribution Plan')
Retail_Delivery = Transition(label='Retail Delivery')
Customer_Feedback = Transition(label='Customer Feedback')
skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[Milk_Sourcing, Culture_Selection, Milk_Testing, Fermentation_Start, Temperature_Control, pH_Monitoring, Curd_Cutting, Whey_Draining, Molding_Cheese, Salting_Process, Aging_Setup, Quality_Check, Packaging_Preparation, Label_Design, Distribution_Plan])
xor = OperatorPOWL(operator=Operator.XOR, children=[Retail_Delivery, Customer_Feedback])
root = StrictPartialOrder(nodes=[loop, xor])
root.order.add_edge(loop, xor)