root = StrictPartialOrder(
    nodes=[
        Transition(label='Receive Returns'),
        Transition(label='Inspect Items'),
        Transition(label='Segregate Stock'),
        Transition(label='Wipe Data'),
        Transition(label='Harvest Parts'),
        Transition(label='Refurbish Units'),
        Transition(label='Test Quality'),
        Transition(label='Recycle Waste'),
        Transition(label='Dispose Defects'),
        Transition(label='Update Inventory'),
        Transition(label='Coordinate Resale'),
        Transition(label='Process Refunds'),
        Transition(label='Analyze Patterns'),
        Transition(label='Improve Design'),
        Transition(label='Report Metrics'),
    ],
    order=[
        ('Receive Returns', 'Inspect Items'),
        ('Inspect Items', 'Segregate Stock'),
        ('Segregate Stock', 'Wipe Data'),
        ('Wipe Data', 'Harvest Parts'),
        ('Harvest Parts', 'Refurbish Units'),
        ('Refurbish Units', 'Test Quality'),
        ('Test Quality', 'Recycle Waste'),
        ('Recycle Waste', 'Dispose Defects'),
        ('Dispose Defects', 'Update Inventory'),
        ('Update Inventory', 'Coordinate Resale'),
        ('Coordinate Resale', 'Process Refunds'),
        ('Process Refunds', 'Analyze Patterns'),
        ('Analyze Patterns', 'Improve Design'),
        ('Improve Design', 'Report Metrics'),
    ]
)