import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define activities
MilkSourcing = Transition(label='Milk Sourcing')
CultureSelection = Transition(label='Culture Selection')
MilkTesting = Transition(label='Milk Testing')
CurdCutting = Transition(label='Curd Cutting')
WheyDraining = Transition(label='Whey Draining')
MoldInoculation = Transition(label='Mold Inoculation')
FormingCheese = Transition(label='Forming Cheese')
SaltingStage = Transition(label='Salting Stage')
AgingSetup = Transition(label='Aging Setup')
ClimateControl = Transition(label='Climate Control')
QualityTasting = Transition(label='Quality Tasting')
PackagingPrep = Transition(label='Packaging Prep')
LabelPrinting = Transition(label='Label Printing')
DistributionPlan = Transition(label='Distribution Plan')
RetailDelivery = Transition(label='Retail Delivery')
EventCoordination = Transition(label='Event Coordination')
RegulatoryAudit = Transition(label='Regulatory Audit')

# Define control-flow operators
xor1 = OperatorPOWL(operator=Operator.XOR, children=[AgingSetup, ClimateControl])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[QualityTasting, RegulatoryAudit])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[PackagingPrep, LabelPrinting])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[DistributionPlan, RetailDelivery])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[EventCoordination, RegulatoryAudit])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor8 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor9 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor10 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor11 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor12 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor13 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor14 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor15 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor16 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor17 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor18 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor19 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor20 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor21 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor22 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor23 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor24 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor25 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor26 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor27 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor28 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor29 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor30 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor31 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor32 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor33 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor34 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor35 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor36 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor37 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor38 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor39 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor40 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor41 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor42 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor43 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor44 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor45 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor46 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor47 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor48 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor49 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor50 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor51 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor52 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor53 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor54 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor55 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor56 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor57 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor58 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor59 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor60 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor61 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor62 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor63 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor64 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor65 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor66 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor67 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor68 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor69 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor70 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor71 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor72 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor73 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor74 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor75 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor76 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor77 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor78 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor79 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor80 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor81 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor82 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor83 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor84 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor85 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor86 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor87 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor88 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor89 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor90 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor91 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor92 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor93 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor94 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor95 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor96 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor97 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor98 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor99 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor100 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor101 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor102 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor103 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor104 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor105 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor106 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor107 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor108 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor109 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor110 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor111 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor112 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor113 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor114 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor115 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor116 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor117 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor118 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor119 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor120 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor121 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor122 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor123 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor124 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor125 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor126 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor127 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor128 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor129 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor130 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor131 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor132 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor133 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor134 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor135 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor136 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor137 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor138 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor139 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor140 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor141 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor142 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor143 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor144 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor145 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor146 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor147 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor148 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor149 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor150 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor151 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor152 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor153 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor154 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor155 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor156 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor157 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor158 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor159 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor160 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor161 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor162 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor163 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor164 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor165 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor166 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor167 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor168 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor169 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor170 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor171 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor172 = OperatorPOWL(operator=Operator.XOR, children=[RegulatoryAudit, RegulatoryAudit])
xor173 = OperatorPOWL(operator