from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

root = StrictPartialOrder()

site_survey = Transition('Site Survey')
design_plan = Transition('Design Plan')
permit_acquire = Transition('Permit Acquire')
structural_retrofit = Transition('Structural Retrofit')
system_install = Transition('System Install')
lighting_setup = Transition('Lighting Setup')
sensor_deploy = Transition('Sensor Deploy')
seed_sourcing = Transition('Seed Sourcing')
nutrient_prep = Transition('Nutrient Prep')
staff_training = Transition('Staff Training')
data_monitor = Transition('Data Monitor')
yield_analyze = Transition('Yield Analyze')
compliance_check = Transition('Compliance Check')
community_meet = Transition('Community Meet')
market_launch = Transition('Market Launch')
logistics_plan = Transition('Logistics Plan')

root.children.append(site_survey)
root.children.append(design_plan)
root.children.append(permit_acquire)
root.children.append(structural_retrofit)
root.children.append(system_install)
root.children.append(lighting_setup)
root.children.append(sensor_deploy)
root.children.append(seed_sourcing)
root.children.append(nutrient_prep)
root.children.append(staff_training)
root.children.append(data_monitor)
root.children.append(yield_analyze)
root.children.append(compliance_check)
root.children.append(community_meet)
root.children.append(market_launch)
root.children.append(logistics_plan)