from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

farm_visit = Transition(label='Farm Visit')
quality_cupping = Transition(label='Quality Cupping')
sustainability_audit = Transition(label='Sustainability Audit')
contract_draft = Transition(label='Contract Draft')
price_negotiate = Transition(label='Price Negotiate')
sample_testing = Transition(label='Sample Testing')
shipment_plan = Transition(label='Shipment Plan')
customs_clear = Transition(label='Customs Clear')
inventory_update = Transition(label='Inventory Update')
supplier_review = Transition(label='Supplier Review')
risk_assess = Transition(label='Risk Assess')
forecast_adjust = Transition(label='Forecast Adjust')
payment_process = Transition(label='Payment Process')
relationship_call = Transition(label='Relationship Call')
traceability_log = Transition(label='Traceability Log')
market_research = Transition(label='Market Research')
compliance_check = Transition(label='Compliance Check')

skip = SilentTransition()

farm_visit_audit = OperatorPOWL(operator=Operator.XOR, children=[farm_visit, sustainability_audit])
quality_audit = OperatorPOWL(operator=Operator.XOR, children=[quality_cupping, sample_testing])
shipment_audit = OperatorPOWL(operator=Operator.XOR, children=[shipment_plan, customs_clear])
inventory_audit = OperatorPOWL(operator=Operator.XOR, children=[inventory_update, supplier_review])
risk_audit = OperatorPOWL(operator=Operator.XOR, children=[risk_assess, forecast_adjust])
payment_audit = OperatorPOWL(operator=Operator.XOR, children=[payment_process, relationship_call])
traceability_audit = OperatorPOWL(operator=Operator.XOR, children=[traceability_log, market_research])
compliance_audit = OperatorPOWL(operator=Operator.XOR, children=[compliance_check, contract_draft])

root = StrictPartialOrder(nodes=[farm_visit_audit, quality_audit, shipment_audit, inventory_audit, risk_audit, payment_audit, traceability_audit, compliance_audit])
root.order.add_edge(farm_visit_audit, quality_audit)
root.order.add_edge(farm_visit_audit, shipment_audit)
root.order.add_edge(farm_visit_audit, inventory_audit)
root.order.add_edge(farm_visit_audit, risk_audit)
root.order.add_edge(farm_visit_audit, payment_audit)
root.order.add_edge(farm_visit_audit, traceability_audit)
root.order.add_edge(farm_visit_audit, compliance_audit)
root.order.add_edge(quality_audit, shipment_audit)
root.order.add_edge(quality_audit, inventory_audit)
root.order.add_edge(quality_audit, risk_audit)
root.order.add_edge(quality_audit, payment_audit)
root.order.add_edge(quality_audit, traceability_audit)
root.order.add_edge(quality_audit, compliance_audit)
root.order.add_edge(shipment_audit, inventory_audit)
root.order.add_edge(shipment_audit, risk_audit)
root.order.add_edge(shipment_audit, payment_audit)
root.order.add_edge(shipment_audit, traceability_audit)
root.order.add_edge(shipment_audit, compliance_audit)
root.order.add_edge(inventory_audit, risk_audit)
root.order.add_edge(inventory_audit, payment_audit)
root.order.add_edge(inventory_audit, traceability_audit)
root.order.add_edge(inventory_audit, compliance_audit)
root.order.add_edge(risk_audit, payment_audit)
root.order.add_edge(risk_audit, traceability_audit)
root.order.add_edge(risk_audit, compliance_audit)
root.order.add_edge(payment_audit, traceability_audit)
root.order.add_edge(payment_audit, compliance_audit)
root.order.add_edge(traceability_audit, compliance_audit)