from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition

A = Transition(label='Trend Scan')
B = Transition(label='Idea Sprint')
C = Transition(label='Feasibility Check')
D = Transition(label='Risk Review')
E = Transition(label='Tech Prototype')
F = Transition(label='Market Simulate')
G = Transition(label='Stakeholder Align')
H = Transition(label='Budget Adjust')
I = Transition(label='Talent Source')
J = Transition(label='Pilot Launch')
K = Transition(label='Data Refine')
L = Transition(label='Scale Analysis')
M = Transition(label='Integration Plan')
N = Transition(label='Change Manage')
O = Transition(label='Knowledge Transfer')
skip = SilentTransition()

root = StrictPartialOrder(nodes=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O])
root.order.add_edge(A, B)
root.order.add_edge(B, C)
root.order.add_edge(C, D)
root.order.add_edge(D, E)
root.order.add_edge(E, F)
root.order.add_edge(F, G)
root.order.add_edge(G, H)
root.order.add_edge(H, I)
root.order.add_edge(I, J)
root.order.add_edge(J, K)
root.order.add_edge(K, L)
root.order.add_edge(L, M)
root.order.add_edge(M, N)
root.order.add_edge(N, O)