root = StrictPartialOrder(
    nodes=[
        Transition(label='Provenance Check'),
        Transition(label='Material Test'),
        Transition(label='Archive Search'),
        Transition(label='Expert Review'),
        Transition(label='3D Scanning'),
        Transition(label='Wear Analysis'),
        Transition(label='Database Cross'),
        Transition(label='Law Consult'),
        Transition(label='Forgery Detect'),
        Transition(label='Certification'),
        Transition(label='Document Prep'),
        Transition(label='Client Brief'),
        Transition(label='Secure Storage'),
        Transition(label='Risk Assessment'),
        Transition(label='Final Approval'),
    ],
    order=[
        ('Provenance Check', 'Material Test'),
        ('Provenance Check', 'Archive Search'),
        ('Provenance Check', 'Expert Review'),
        ('Material Test', '3D Scanning'),
        ('Material Test', 'Wear Analysis'),
        ('Archive Search', 'Database Cross'),
        ('Expert Review', 'Law Consult'),
        ('3D Scanning', 'Database Cross'),
        ('Wear Analysis', 'Database Cross'),
        ('Database Cross', 'Forgery Detect'),
        ('Law Consult', 'Forgery Detect'),
        ('Forgery Detect', 'Certification'),
        ('Forgery Detect', 'Document Prep'),
        ('Forgery Detect', 'Client Brief'),
        ('Forgery Detect', 'Secure Storage'),
        ('Forgery Detect', 'Risk Assessment'),
        ('Forgery Detect', 'Final Approval'),
    ]
)