root = StrictPartialOrder(
    nodes=[
        Transition('Site Survey'),
        Transition('Permit Filing'),
        Transition('Structure Prep'),
        Transition('System Install'),
        Transition('Nutrient Mix'),
        Transition('Sensor Setup'),
        Transition('AI Calibration'),
        Transition('Seed Sourcing'),
        Transition('Staff Training'),
        Transition('Energy Connect'),
        Transition('Water Cycle'),
        Transition('Growth Monitor'),
        Transition('Waste Audit'),
        Transition('Community Meet'),
        Transition('Data Review'),
        Transition('Yield Forecast'),
    ],
    order={
        ('Site Survey', 'Permit Filing'): None,
        ('Permit Filing', 'Structure Prep'): None,
        ('Structure Prep', 'System Install'): None,
        ('System Install', 'Nutrient Mix'): None,
        ('Nutrient Mix', 'Sensor Setup'): None,
        ('Sensor Setup', 'AI Calibration'): None,
        ('AI Calibration', 'Seed Sourcing'): None,
        ('Seed Sourcing', 'Staff Training'): None,
        ('Staff Training', 'Energy Connect'): None,
        ('Energy Connect', 'Water Cycle'): None,
        ('Water Cycle', 'Growth Monitor'): None,
        ('Growth Monitor', 'Waste Audit'): None,
        ('Waste Audit', 'Community Meet'): None,
        ('Community Meet', 'Data Review'): None,
        ('Data Review', 'Yield Forecast'): None,
    }
)