root = StrictPartialOrder(
    nodes=[
        Transition(label='Provenance Check'),
        Transition(label='Radiocarbon Test'),
        Transition(label='Material Analysis'),
        Transition(label='Microscopic Scan'),
        Transition(label='Expert Review'),
        Transition(label='Context Validation'),
        Transition(label='Legal Audit'),
        Transition(label='Export Verify'),
        Transition(label='Digital Imaging'),
        Transition(label='3D Modeling'),
        Transition(label='Consensus Meeting'),
        Transition(label='Final Approval'),
        Transition(label='Catalog Entry'),
        Transition(label='Virtual Setup'),
        Transition(label='Archival Backup')
    ],
    order=[
        ('Provenance Check', 'Radiocarbon Test'),
        ('Provenance Check', 'Material Analysis'),
        ('Provenance Check', 'Microscopic Scan'),
        ('Provenance Check', 'Expert Review'),
        ('Provenance Check', 'Context Validation'),
        ('Provenance Check', 'Legal Audit'),
        ('Provenance Check', 'Export Verify'),
        ('Provenance Check', 'Digital Imaging'),
        ('Provenance Check', '3D Modeling'),
        ('Provenance Check', 'Consensus Meeting'),
        ('Provenance Check', 'Final Approval'),
        ('Provenance Check', 'Catalog Entry'),
        ('Provenance Check', 'Virtual Setup'),
        ('Provenance Check', 'Archival Backup'),
        ('Radiocarbon Test', 'Material Analysis'),
        ('Radiocarbon Test', 'Microscopic Scan'),
        ('Radiocarbon Test', 'Expert Review'),
        ('Radiocarbon Test', 'Context Validation'),
        ('Radiocarbon Test', 'Legal Audit'),
        ('Radiocarbon Test', 'Export Verify'),
        ('Radiocarbon Test', 'Digital Imaging'),
        ('Radiocarbon Test', '3D Modeling'),
        ('Radiocarbon Test', 'Consensus Meeting'),
        ('Radiocarbon Test', 'Final Approval'),
        ('Radiocarbon Test', 'Catalog Entry'),
        ('Radiocarbon Test', 'Virtual Setup'),
        ('Radiocarbon Test', 'Archival Backup'),
        ('Material Analysis', 'Microscopic Scan'),
        ('Material Analysis', 'Expert Review'),
        ('Material Analysis', 'Context Validation'),
        ('Material Analysis', 'Legal Audit'),
        ('Material Analysis', 'Export Verify'),
        ('Material Analysis', 'Digital Imaging'),
        ('Material Analysis', '3D Modeling'),
        ('Material Analysis', 'Consensus Meeting'),
        ('Material Analysis', 'Final Approval'),
        ('Material Analysis', 'Catalog Entry'),
        ('Material Analysis', 'Virtual Setup'),
        ('Material Analysis', 'Archival Backup'),
        ('Microscopic Scan', 'Expert Review'),
        ('Microscopic Scan', 'Context Validation'),
        ('Microscopic Scan', 'Legal Audit'),
        ('Microscopic Scan', 'Export Verify'),
        ('Microscopic Scan', 'Digital Imaging'),
        ('Microscopic Scan', '3D Modeling'),
        ('Microscopic Scan', 'Consensus Meeting'),
        ('Microscopic Scan', 'Final Approval'),
        ('Microscopic Scan', 'Catalog Entry'),
        ('Microscopic Scan', 'Virtual Setup'),
        ('Microscopic Scan', 'Archival Backup'),
        ('Expert Review', 'Context Validation'),
        ('Expert Review', 'Legal Audit'),
        ('Expert Review', 'Export Verify'),
        ('Expert Review', 'Digital Imaging'),
        ('Expert Review', '3D Modeling'),
        ('Expert Review', 'Consensus Meeting'),
        ('Expert Review', 'Final Approval'),
        ('Expert Review', 'Catalog Entry'),
        ('Expert Review', 'Virtual Setup'),
        ('Expert Review', 'Archival Backup'),
        ('Context Validation', 'Legal Audit'),
        ('Context Validation', 'Export Verify'),
        ('Context Validation', 'Digital Imaging'),
        ('Context Validation', '3D Modeling'),
        ('Context Validation', 'Consensus Meeting'),
        ('Context Validation', 'Final Approval'),
        ('Context Validation', 'Catalog Entry'),
        ('Context Validation', 'Virtual Setup'),
        ('Context Validation', 'Archival Backup'),
        ('Legal Audit', 'Export Verify'),
        ('Legal Audit', 'Digital Imaging'),
        ('Legal Audit', '3D Modeling'),
        ('Legal Audit', 'Consensus Meeting'),
        ('Legal Audit', 'Final Approval'),
        ('Legal Audit', 'Catalog Entry'),
        ('Legal Audit', 'Virtual Setup'),
        ('Legal Audit', 'Archival Backup'),
        ('Export Verify', 'Digital Imaging'),
        ('Export Verify', '3D Modeling'),
        ('Export Verify', 'Consensus Meeting'),
        ('Export Verify', 'Final Approval'),
        ('Export Verify', 'Catalog Entry'),
        ('Export Verify', 'Virtual Setup'),
        ('Export Verify', 'Archival Backup'),
        ('Digital Imaging', '3D Modeling'),
        ('Digital Imaging', 'Consensus Meeting'),
        ('Digital Imaging', 'Final Approval'),
        ('Digital Imaging', 'Catalog Entry'),
        ('Digital Imaging', 'Virtual Setup'),
        ('Digital Imaging', 'Archival Backup'),
        ('3D Modeling', 'Consensus Meeting'),
        ('3D Modeling', 'Final Approval'),
        ('3D Modeling', 'Catalog Entry'),
        ('3D Modeling', 'Virtual Setup'),
        ('3D Modeling', 'Archival Backup'),
        ('Consensus Meeting', 'Final Approval'),
        ('Consensus Meeting', 'Catalog Entry'),
        ('Consensus Meeting', 'Virtual Setup'),
        ('Consensus Meeting', 'Archival Backup'),
        ('Final Approval', 'Catalog Entry'),
        ('Final Approval', 'Virtual Setup'),
        ('Final Approval', 'Archival Backup'),
        ('Catalog Entry', 'Virtual Setup'),
        ('Catalog Entry', 'Archival Backup'),
        ('Virtual Setup', 'Archival Backup'),
        ('Archival Backup', 'Archival Backup')
    ]
)