root = StrictPartialOrder(
    nodes=[
        Transition(label='Sensor Setup'),
        Transition(label='Data Capture'),
        Transition(label='Nutrient Mix'),
        Transition(label='Crop Rotate'),
        Transition(label='Waste Collect'),
        Transition(label='Compost Process'),
        Transition(label='Drone Dispatch'),
        Transition(label='Pest Control'),
        Transition(label='Pollination Run'),
        Transition(label='Volunteer Assign'),
        Transition(label='Feedback Gather'),
        Transition(label='Model Update'),
        Transition(label='Yield Forecast'),
        Transition(label='Water Adjust'),
        Transition(label='Report Generate'),
        Transition(label='Resource Audit'),
        Transition(label='Schedule Sync'),
    ],
    order={
        'Sensor Setup': 'Data Capture',
        'Data Capture': 'Nutrient Mix',
        'Nutrient Mix': 'Crop Rotate',
        'Crop Rotate': 'Waste Collect',
        'Waste Collect': 'Compost Process',
        'Compost Process': 'Drone Dispatch',
        'Drone Dispatch': 'Pest Control',
        'Pest Control': 'Pollination Run',
        'Pollination Run': 'Volunteer Assign',
        'Volunteer Assign': 'Feedback Gather',
        'Feedback Gather': 'Model Update',
        'Model Update': 'Yield Forecast',
        'Yield Forecast': 'Water Adjust',
        'Water Adjust': 'Report Generate',
        'Report Generate': 'Resource Audit',
        'Resource Audit': 'Schedule Sync',
    }
)