from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition

# Define the POWL model
milk_sourcing = Transition(label='Milk Sourcing')
quality_testing = Transition(label='Quality Testing')
milk_pasteurize = Transition(label='Milk Pasteurize')
culture_inoculate = Transition(label='Culture Inoculate')
coagulation = Transition(label='Coagulation')
curd_cutting = Transition(label='Curd Cutting')
whey_drain = Transition(label='Whey Drain')
pressing = Transition(label='Pressing')
salting = Transition(label='Salting')
aging_control = Transition(label='Aging Control')
sensory_audit = Transition(label='Sensory Audit')
packaging_design = Transition(label='Packaging Design')
label_approval = Transition(label='Label Approval')
order_customization = Transition(label='Order Customization')
logistics_plan = Transition(label='Logistics Plan')
market_delivery = Transition(label='Market Delivery')
customer_feedback = Transition(label='Customer Feedback')
regulatory_check = Transition(label='Regulatory Check')

# Define the POWL model
milk_sourcing_order = OperatorPOWL(operator=Operator.ORDER, children=[milk_sourcing, quality_testing])
quality_testing_order = OperatorPOWL(operator=Operator.ORDER, children=[milk_pasteurize, culture_inoculate])
milk_pasteurize_order = OperatorPOWL(operator=Operator.ORDER, children=[coagulation, curd_cutting])
coagulation_order = OperatorPOWL(operator=Operator.ORDER, children=[whey_drain, pressing])
curd_cutting_order = OperatorPOWL(operator=Operator.ORDER, children=[salting, aging_control])
whey_drain_order = OperatorPOWL(operator=Operator.ORDER, children=[sensory_audit, packaging_design])
pressing_order = OperatorPOWL(operator=Operator.ORDER, children=[label_approval, order_customization])
salting_order = OperatorPOWL(operator=Operator.ORDER, children=[logistics_plan, market_delivery])
aging_control_order = OperatorPOWL(operator=Operator.ORDER, children=[customer_feedback, regulatory_check])

# Define the partial order
root = StrictPartialOrder(nodes=[milk_sourcing_order, quality_testing_order, milk_pasteurize_order, coagulation_order, curd_cutting_order, whey_drain_order, pressing_order, salting_order, aging_control_order])
root.order.add_edge(milk_sourcing_order, quality_testing_order)
root.order.add_edge(quality_testing_order, milk_pasteurize_order)
root.order.add_edge(milk_pasteurize_order, coagulation_order)
root.order.add_edge(coagulation_order, whey_drain_order)
root.order.add_edge(whey_drain_order, curd_cutting_order)
root.order.add_edge(curd_cutting_order, pressing_order)
root.order.add_edge(pressing_order, label_approval_order)
root.order.add_edge(label_approval_order, order_customization_order)
root.order.add_edge(salting_order, logistics_plan_order)
root.order.add_edge(logistics_plan_order, market_delivery_order)
root.order.add_edge(customer_feedback_order, regulatory_check_order)
root.order.add_edge(aging_control_order, customer_feedback_order)
root.order.add_edge(aging_control_order, regulatory_check_order)

print(root)