from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition

# Define the POWL model
A = Transition(label='Artifact Intake')
B = Transition(label='Condition Check')
C = Transition(label='Material Test')
D = Transition(label='Archival Search')
E = Transition(label='Style Compare')
F = Transition(label='Expert Review')
G = Transition(label='Restoration Check')
H = Transition(label='Provenance Trace')
I = Transition(label='Legal Verify')
J = Transition(label='Value Appraise')
K = Transition(label='Catalog Entry')
L = Transition(label='Marketing Plan')
M = Transition(label='Auction Setup')
N = Transition(label='Certify Final')
O = Transition(label='Sales Report')

# Define the workflow
root = StrictPartialOrder(nodes=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O])
root.order.add_edge(A, B)
root.order.add_edge(A, C)
root.order.add_edge(A, D)
root.order.add_edge(A, E)
root.order.add_edge(A, F)
root.order.add_edge(A, G)
root.order.add_edge(A, H)
root.order.add_edge(A, I)
root.order.add_edge(A, J)
root.order.add_edge(A, K)
root.order.add_edge(A, L)
root.order.add_edge(A, M)
root.order.add_edge(A, N)
root.order.add_edge(A, O)

root.order.add_edge(B, N)
root.order.add_edge(C, N)
root.order.add_edge(D, N)
root.order.add_edge(E, N)
root.order.add_edge(F, N)
root.order.add_edge(G, N)
root.order.add_edge(H, N)
root.order.add_edge(I, N)
root.order.add_edge(J, N)
root.order.add_edge(K, N)
root.order.add_edge(L, N)
root.order.add_edge(M, N)
root.order.add_edge(O, N)

root.order.add_edge(N, O)