root = StrictPartialOrder(
    nodes=[
        Transition(label='Site Analysis'),
        Transition(label='Zoning Review'),
        Transition(label='Modular Design'),
        Transition(label='Climate Setup'),
        Transition(label='Nutrient Mix'),
        Transition(label='Seed Selection'),
        Transition(label='AI Monitoring'),
        Transition(label='Lighting Control'),
        Transition(label='Energy Audit'),
        Transition(label='Water Reclaim'),
        Transition(label='Waste Sorting'),
        Transition(label='Community Meet'),
        Transition(label='Staff Training'),
        Transition(label='Yield Forecast'),
        Transition(label='Market Sync'),
        Transition(label='Supply Chain'),
    ],
    order=[
        ('Site Analysis', 'Zoning Review'),
        ('Site Analysis', 'Modular Design'),
        ('Zoning Review', 'Climate Setup'),
        ('Modular Design', 'Climate Setup'),
        ('Climate Setup', 'Nutrient Mix'),
        ('Climate Setup', 'AI Monitoring'),
        ('Climate Setup', 'Lighting Control'),
        ('Nutrient Mix', 'Energy Audit'),
        ('Energy Audit', 'Water Reclaim'),
        ('Water Reclaim', 'Waste Sorting'),
        ('Waste Sorting', 'Community Meet'),
        ('Community Meet', 'Staff Training'),
        ('Staff Training', 'Yield Forecast'),
        ('Yield Forecast', 'Market Sync'),
        ('Market Sync', 'Supply Chain'),
    ]
)