from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

artifact_intake = Transition(label='Artifact Intake')
visual_inspection = Transition(label='Visual Inspection')
material_testing = Transition(label='Material Testing')
radiocarbon_dating = Transition(label='Radiocarbon Dating')
provenance_check = Transition(label='Provenance Check')
archive_research = Transition(label='Archive Research')
expert_review = Transition(label='Expert Review')
style_analysis = Transition(label='Style Analysis')
craftsmanship_eval = Transition(label='Craftsmanship Eval')
condition_check = Transition(label='Condition Check')
restoration_plan = Transition(label='Restoration Plan')
forgeries_risk = Transition(label='Forgery Risk')
legal_review = Transition(label='Legal Review')
report_drafting = Transition(label='Report Drafting')
catalog_entry = Transition(label='Catalog Entry')

skip = SilentTransition()
loop1 = OperatorPOWL(operator=Operator.LOOP, children=[artifact_intake, visual_inspection])
xor1 = OperatorPOWL(operator=Operator.XOR, children=[material_testing, radiocarbon_dating])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[provenance_check, archive_research])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[expert_review, style_analysis])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[craftsmanship_eval, condition_check])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[restoration_plan, forgeries_risk])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[legal_review, report_drafting])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[catalog_entry, skip])

root = StrictPartialOrder(nodes=[loop1, xor1, xor2, xor3, xor4, xor5, xor6, xor7])
root.order.add_edge(loop1, xor1)
root.order.add_edge(xor1, xor2)
root.order.add_edge(xor2, xor3)
root.order.add_edge(xor3, xor4)
root.order.add_edge(xor4, xor5)
root.order.add_edge(xor5, xor6)
root.order.add_edge(xor6, xor7)