import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define transitions for each activity
AssessStructure = Transition(label='Assess Structure')
AnalyzeEnvironment = Transition(label='Analyze Environment')
DesignModules = Transition(label='Design Modules')
ProcureMaterials = Transition(label='Procure Materials')
InstallIrrigation = Transition(label='Install Irrigation')
SetSensors = Transition(label='Set Sensors')
SelectSeeds = Transition(label='Select Seeds')
SchedulePlanting = Transition(label='Schedule Planting')
MonitorGrowth = Transition(label='Monitor Growth')
CollectData = Transition(label='Collect Data')
ManagePests = Transition(label='Manage Pests')
HarvestCrops = Transition(label='Harvest Crops')
CoordinateSales = Transition(label='Coordinate Sales')
CompostWaste = Transition(label='Compost Waste')
ReviewFeedback = Transition(label='Review Feedback')

# Define silent transitions
skip = SilentTransition()

# Define exclusive choice for environmental analysis and structural assessment
xor = OperatorPOWL(operator=Operator.XOR, children=[AnalyzeEnvironment, AssessStructure])

# Define loop for planting scheduling
loop = OperatorPOWL(operator=Operator.LOOP, children=[SchedulePlanting])

# Define the root partial order with all activities and dependencies
root = StrictPartialOrder(nodes=[AssessStructure, AnalyzeEnvironment, DesignModules, ProcureMaterials, InstallIrrigation, SetSensors, SelectSeeds, SchedulePlanting, MonitorGrowth, CollectData, ManagePests, HarvestCrops, CoordinateSales, CompostWaste, ReviewFeedback, xor, loop])
root.order.add_edge(AnalyzeEnvironment, DesignModules)
root.order.add_edge(AnalyzeEnvironment, ProcureMaterials)
root.order.add_edge(AnalyzeEnvironment, InstallIrrigation)
root.order.add_edge(AnalyzeEnvironment, SetSensors)
root.order.add_edge(AnalyzeEnvironment, SelectSeeds)
root.order.add_edge(AnalyzeEnvironment, SchedulePlanting)
root.order.add_edge(AnalyzeEnvironment, MonitorGrowth)
root.order.add_edge(AnalyzeEnvironment, CollectData)
root.order.add_edge(AnalyzeEnvironment, ManagePests)
root.order.add_edge(AnalyzeEnvironment, HarvestCrops)
root.order.add_edge(AnalyzeEnvironment, CoordinateSales)
root.order.add_edge(AnalyzeEnvironment, CompostWaste)
root.order.add_edge(AnalyzeEnvironment, ReviewFeedback)
root.order.add_edge(AssessStructure, DesignModules)
root.order.add_edge(AssessStructure, ProcureMaterials)
root.order.add_edge(AssessStructure, InstallIrrigation)
root.order.add_edge(AssessStructure, SetSensors)
root.order.add_edge(AssessStructure, SelectSeeds)
root.order.add_edge(AssessStructure, SchedulePlanting)
root.order.add_edge(AssessStructure, MonitorGrowth)
root.order.add_edge(AssessStructure, CollectData)
root.order.add_edge(AssessStructure, ManagePests)
root.order.add_edge(AssessStructure, HarvestCrops)
root.order.add_edge(AssessStructure, CoordinateSales)
root.order.add_edge(AssessStructure, CompostWaste)
root.order.add_edge(AssessStructure, ReviewFeedback)
root.order.add_edge(DesignModules, ProcureMaterials)
root.order.add_edge(DesignModules, InstallIrrigation)
root.order.add_edge(DesignModules, SetSensors)
root.order.add_edge(DesignModules, SelectSeeds)
root.order.add_edge(DesignModules, SchedulePlanting)
root.order.add_edge(DesignModules, MonitorGrowth)
root.order.add_edge(DesignModules, CollectData)
root.order.add_edge(DesignModules, ManagePests)
root.order.add_edge(DesignModules, HarvestCrops)
root.order.add_edge(DesignModules, CoordinateSales)
root.order.add_edge(DesignModules, CompostWaste)
root.order.add_edge(DesignModules, ReviewFeedback)
root.order.add_edge(ProcureMaterials, InstallIrrigation)
root.order.add_edge(ProcureMaterials, SetSensors)
root.order.add_edge(ProcureMaterials, SelectSeeds)
root.order.add_edge(ProcureMaterials, SchedulePlanting)
root.order.add_edge(ProcureMaterials, MonitorGrowth)
root.order.add_edge(ProcureMaterials, CollectData)
root.order.add_edge(ProcureMaterials, ManagePests)
root.order.add_edge(ProcureMaterials, HarvestCrops)
root.order.add_edge(ProcureMaterials, CoordinateSales)
root.order.add_edge(ProcureMaterials, CompostWaste)
root.order.add_edge(ProcureMaterials, ReviewFeedback)
root.order.add_edge(InstallIrrigation, SetSensors)
root.order.add_edge(InstallIrrigation, SelectSeeds)
root.order.add_edge(InstallIrrigation, SchedulePlanting)
root.order.add_edge(InstallIrrigation, MonitorGrowth)
root.order.add_edge(InstallIrrigation, CollectData)
root.order.add_edge(InstallIrrigation, ManagePests)
root.order.add_edge(InstallIrrigation, HarvestCrops)
root.order.add_edge(InstallIrrigation, CoordinateSales)
root.order.add_edge(InstallIrrigation, CompostWaste)
root.order.add_edge(InstallIrrigation, ReviewFeedback)
root.order.add_edge(SetSensors, SelectSeeds)
root.order.add_edge(SetSensors, SchedulePlanting)
root.order.add_edge(SetSensors, MonitorGrowth)
root.order.add_edge(SetSensors, CollectData)
root.order.add_edge(SetSensors, ManagePests)
root.order.add_edge(SetSensors, HarvestCrops)
root.order.add_edge(SetSensors, CoordinateSales)
root.order.add_edge(SetSensors, CompostWaste)
root.order.add_edge(SetSensors, ReviewFeedback)
root.order.add_edge(SelectSeeds, SchedulePlanting)
root.order.add_edge(SelectSeeds, MonitorGrowth)
root.order.add_edge(SelectSeeds, CollectData)
root.order.add_edge(SelectSeeds, ManagePests)
root.order.add_edge(SelectSeeds, HarvestCrops)
root.order.add_edge(SelectSeeds, CoordinateSales)
root.order.add_edge(SelectSeeds, CompostWaste)
root.order.add_edge(SelectSeeds, ReviewFeedback)
root.order.add_edge(SchedulePlanting, MonitorGrowth)
root.order.add_edge(SchedulePlanting, CollectData)
root.order.add_edge(SchedulePlanting, ManagePests)
root.order.add_edge(SchedulePlanting, HarvestCrops)
root.order.add_edge(SchedulePlanting, CoordinateSales)
root.order.add_edge(SchedulePlanting, CompostWaste)
root.order.add_edge(SchedulePlanting, ReviewFeedback)
root.order.add_edge(MonitorGrowth, CollectData)
root.order.add_edge(MonitorGrowth, ManagePests)
root.order.add_edge(MonitorGrowth, HarvestCrops)
root.order.add_edge(MonitorGrowth, CoordinateSales)
root.order.add_edge(MonitorGrowth, CompostWaste)
root.order.add_edge(MonitorGrowth, ReviewFeedback)
root.order.add_edge(CollectData, ManagePests)
root.order.add_edge(CollectData, HarvestCrops)
root.order.add_edge(CollectData, CoordinateSales)
root.order.add_edge(CollectData, CompostWaste)
root.order.add_edge(CollectData, ReviewFeedback)
root.order.add_edge(ManagePests, HarvestCrops)
root.order.add_edge(ManagePests, CoordinateSales)
root.order.add_edge(ManagePests, CompostWaste)
root.order.add_edge(ManagePests, ReviewFeedback)
root.order.add_edge(HarvestCrops, CoordinateSales)
root.order.add_edge(HarvestCrops, CompostWaste)
root.order.add_edge(HarvestCrops, ReviewFeedback)
root.order.add_edge(CoordinateSales, CompostWaste)
root.order.add_edge(CoordinateSales, ReviewFeedback)
root.order.add_edge(CompostWaste, ReviewFeedback)