root = StrictPartialOrder(
    nodes=[
        Transition(label='Site Survey'),
        Transition(label='Design Layout'),
        Transition(label='Install Modules'),
        Transition(label='Set Controls'),
        Transition(label='Select Crops'),
        Transition(label='Configure Irrigation'),
        Transition(label='Setup Lighting'),
        Transition(label='Deploy Sensors'),
        Transition(label='Train Staff'),
        Transition(label='Start Cultivation'),
        Transition(label='Monitor Growth'),
        Transition(label='Manage Pests'),
        Transition(label='Harvest Crops'),
        Transition(label='Pack Produce'),
        Transition(label='Distribute Goods'),
    ],
    order=[
        ('Site Survey', 'Design Layout'),
        ('Design Layout', 'Install Modules'),
        ('Install Modules', 'Set Controls'),
        ('Set Controls', 'Select Crops'),
        ('Select Crops', 'Configure Irrigation'),
        ('Configure Irrigation', 'Setup Lighting'),
        ('Setup Lighting', 'Deploy Sensors'),
        ('Deploy Sensors', 'Train Staff'),
        ('Train Staff', 'Start Cultivation'),
        ('Start Cultivation', 'Monitor Growth'),
        ('Monitor Growth', 'Manage Pests'),
        ('Manage Pests', 'Harvest Crops'),
        ('Harvest Crops', 'Pack Produce'),
        ('Pack Produce', 'Distribute Goods'),
    ],
)