from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition

# Define activities
site_survey = Transition(label='Site Survey')
climate_check = Transition(label='Climate Check')
soil_testing = Transition(label='Soil Testing')
media_select = Transition(label='Media Select')
design_layout = Transition(label='Design Layout')
hydro_setup = Transition(label='Hydro Setup')
nutrient_mix = Transition(label='Nutrient Mix')
sensor_install = Transition(label='Sensor Install')
regulation_review = Transition(label='Regulation Review')
permit_apply = Transition(label='Permit Apply')
stakeholder_meet = Transition(label='Stakeholder Meet')
community_train = Transition(label='Community Train')
plant_seed = Transition(label='Plant Seed')
monitor_growth = Transition(label='Monitor Growth')
adjust_controls = Transition(label='Adjust Controls')
harvest_plan = Transition(label='Harvest Plan')
waste_recycle = Transition(label='Waste Recycle')
feedback_loop = Transition(label='Feedback Loop')

# Define exclusive choice (XOR) for resource optimization and community engagement
xor = OperatorPOWL(operator=Operator.XOR, children=[stakeholder_meet, community_train])

# Define partial order for the process
root = StrictPartialOrder(nodes=[site_survey, climate_check, soil_testing, media_select, design_layout, hydro_setup, nutrient_mix, sensor_install, regulation_review, permit_apply, xor, monitor_growth, adjust_controls, harvest_plan, waste_recycle, feedback_loop])
root.order.add_edge(site_survey, climate_check)
root.order.add_edge(site_survey, soil_testing)
root.order.add_edge(site_survey, media_select)
root.order.add_edge(site_survey, design_layout)
root.order.add_edge(climate_check, hydro_setup)
root.order.add_edge(soil_testing, nutrient_mix)
root.order.add_edge(media_select, sensor_install)
root.order.add_edge(design_layout, regulation_review)
root.order.add_edge(hydro_setup, permit_apply)
root.order.add_edge(nutrient_mix, xor)
root.order.add_edge(sensor_install, xor)
root.order.add_edge(regulation_review, permit_apply)
root.order.add_edge(permit_apply, monitor_growth)
root.order.add_edge(monitor_growth, adjust_controls)
root.order.add_edge(adjust_controls, harvest_plan)
root.order.add_edge(harvest_plan, waste_recycle)
root.order.add_edge(waste_recycle, feedback_loop)

print(root)