import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define activities
site_survey = Transition(label='Site Survey')
permit_acquire = Transition(label='Permit Acquire')
rack_design = Transition(label='Rack Design')
seed_selection = Transition(label='Seed Selection')
nutrient_mix = Transition(label='Nutrient Mix')
lighting_setup = Transition(label='Lighting Setup')
sensor_install = Transition(label='Sensor Install')
system_test = Transition(label='System Test')
staff_hire = Transition(label='Staff Hire')
training_lead = Transition(label='Training Lead')
waste_manage = Transition(label='Waste Manage')
supply_chain = Transition(label='Supply Chain')
crop_cycle = Transition(label='Crop Cycle')
data_monitor = Transition(label='Data Monitor')
harvest_plan = Transition(label='Harvest Plan')
distribution = Transition(label='Distribution')

# Define process structure
site_survey_choice = OperatorPOWL(operator=Operator.XOR, children=[site_survey, permit_acquire])
rack_design_choice = OperatorPOWL(operator=Operator.XOR, children=[rack_design, site_survey_choice])
seed_selection_choice = OperatorPOWL(operator=Operator.XOR, children=[seed_selection, rack_design_choice])
nutrient_mix_choice = OperatorPOWL(operator=Operator.XOR, children=[nutrient_mix, seed_selection_choice])
lighting_setup_choice = OperatorPOWL(operator=Operator.XOR, children=[lighting_setup, nutrient_mix_choice])
sensor_install_choice = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, lighting_setup_choice])
system_test_choice = OperatorPOWL(operator=Operator.XOR, children=[system_test, sensor_install_choice])
staff_hire_choice = OperatorPOWL(operator=Operator.XOR, children=[staff_hire, system_test_choice])
training_lead_choice = OperatorPOWL(operator=Operator.XOR, children=[training_lead, staff_hire_choice])
waste_manage_choice = OperatorPOWL(operator=Operator.XOR, children=[waste_manage, training_lead_choice])
supply_chain_choice = OperatorPOWL(operator=Operator.XOR, children=[supply_chain, waste_manage_choice])
crop_cycle_choice = OperatorPOWL(operator=Operator.XOR, children=[crop_cycle, supply_chain_choice])
data_monitor_choice = OperatorPOWL(operator=Operator.XOR, children=[data_monitor, crop_cycle_choice])
harvest_plan_choice = OperatorPOWL(operator=Operator.XOR, children=[harvest_plan, data_monitor_choice])
distribution_choice = OperatorPOWL(operator=Operator.XOR, children=[distribution, harvest_plan_choice])

root = StrictPartialOrder(nodes=[site_survey_choice, permit_acquire, rack_design_choice, seed_selection_choice, nutrient_mix_choice, lighting_setup_choice, sensor_install_choice, system_test_choice, staff_hire_choice, training_lead_choice, waste_manage_choice, supply_chain_choice, crop_cycle_choice, data_monitor_choice, harvest_plan_choice, distribution_choice])
root.order.add_edge(site_survey_choice, permit_acquire)
root.order.add_edge(permit_acquire, rack_design_choice)
root.order.add_edge(rack_design_choice, seed_selection_choice)
root.order.add_edge(seed_selection_choice, nutrient_mix_choice)
root.order.add_edge(nutrient_mix_choice, lighting_setup_choice)
root.order.add_edge(lighting_setup_choice, sensor_install_choice)
root.order.add_edge(sensor_install_choice, system_test_choice)
root.order.add_edge(system_test_choice, staff_hire_choice)
root.order.add_edge(staff_hire_choice, training_lead_choice)
root.order.add_edge(training_lead_choice, waste_manage_choice)
root.order.add_edge(waste_manage_choice, supply_chain_choice)
root.order.add_edge(supply_chain_choice, crop_cycle_choice)
root.order.add_edge(crop_cycle_choice, data_monitor_choice)
root.order.add_edge(data_monitor_choice, harvest_plan_choice)
root.order.add_edge(harvest_plan_choice, distribution_choice)