root = StrictPartialOrder(
    nodes=[
        Transition(label='Gather Specs'),
        Transition(label='Adapt Design'),
        Transition(label='Source Parts'),
        Transition(label='Component Test'),
        Transition(label='Assemble Frame'),
        Transition(label='Install Firmware'),
        Transition(label='Calibrate Sensors'),
        Transition(label='Stress Test'),
        Transition(label='Flight Simulate'),
        Transition(label='Validate Battery'),
        Transition(label='Check Accuracy'),
        Transition(label='Package Units'),
        Transition(label='Create Manuals'),
        Transition(label='Ship Drones'),
        Transition(label='Collect Feedback'),
    ],
    order={
        'Gather Specs': 'Adapt Design',
        'Adapt Design': 'Source Parts',
        'Source Parts': 'Component Test',
        'Component Test': 'Assemble Frame',
        'Assemble Frame': 'Install Firmware',
        'Install Firmware': 'Calibrate Sensors',
        'Calibrate Sensors': 'Stress Test',
        'Stress Test': 'Flight Simulate',
        'Flight Simulate': 'Validate Battery',
        'Validate Battery': 'Check Accuracy',
        'Check Accuracy': 'Package Units',
        'Package Units': 'Create Manuals',
        'Create Manuals': 'Ship Drones',
        'Ship Drones': 'Collect Feedback',
    }
)