from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition

# Define activities
A = Transition(label='Site Analysis')
B = Transition(label='Load Test')
C = Transition(label='Sunlight Map')
D = Transition(label='Medium Select')
E = Transition(label='Hydro Design')
F = Transition(label='Procure Seeds')
G = Transition(label='Install Irrigation')
H = Transition(label='Setup Climate')
I = Transition(label='Create Schedule')
J = Transition(label='Pest Control')
K = Transition(label='Monitor Growth')
L = Transition(label='Adjust Systems')
M = Transition(label='Harvest Crops')
N = Transition(label='Package Produce')
O = Transition(label='Engage Community')
P = Transition(label='Host Workshops')

# Define connections
root = StrictPartialOrder(nodes=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P])
root.order.add_edge(A, B)
root.order.add_edge(A, C)
root.order.add_edge(B, D)
root.order.add_edge(B, E)
root.order.add_edge(C, D)
root.order.add_edge(C, E)
root.order.add_edge(D, F)
root.order.add_edge(E, F)
root.order.add_edge(F, G)
root.order.add_edge(G, H)
root.order.add_edge(H, I)
root.order.add_edge(I, J)
root.order.add_edge(J, K)
root.order.add_edge(K, L)
root.order.add_edge(L, M)
root.order.add_edge(M, N)
root.order.add_edge(N, O)
root.order.add_edge(O, P)

print(root)