import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_survey = Transition(label='Site Survey')
structural_check = Transition(label='Structural Check')
climate_study = Transition(label='Climate Study')
soil_prep = Transition(label='Soil Prep')
seed_selection = Transition(label='Seed Selection')
irrigation_setup = Transition(label='Irrigation Setup')
nutrient_mix = Transition(label='Nutrient Mix')
sensor_install = Transition(label='Sensor Install')
pest_monitor = Transition(label='Pest Monitor')
data_analysis = Transition(label='Data Analysis')
regulation_review = Transition(label='Regulation Review')
community_meet = Transition(label='Community Meet')
harvest_plan = Transition(label='Harvest Plan')
packaging_design = Transition(label='Packaging Design')
distribution_map = Transition(label='Distribution Map')
feedback_loop = Transition(label='Feedback Loop')
maintenance_schedule = Transition(label='Maintenance Schedule')

skip = SilentTransition()

site_survey_to_climate_study = OperatorPOWL(operator=Operator.XOR, children=[site_survey, climate_study])
climate_study_to_soil_prep = OperatorPOWL(operator=Operator.XOR, children=[climate_study, soil_prep])
soil_prep_to_seed_selection = OperatorPOWL(operator=Operator.XOR, children=[soil_prep, seed_selection])
seed_selection_to_irrigation_setup = OperatorPOWL(operator=Operator.XOR, children=[seed_selection, irrigation_setup])
irrigation_setup_to_nutrient_mix = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, nutrient_mix])
nutrient_mix_to_sensor_install = OperatorPOWL(operator=Operator.XOR, children=[nutrient_mix, sensor_install])
sensor_install_to_pest_monitor = OperatorPOWL(operator=Operator.XOR, children=[sensor_install, pest_monitor])
pest_monitor_to_data_analysis = OperatorPOWL(operator=Operator.XOR, children=[pest_monitor, data_analysis])
data_analysis_to_regulation_review = OperatorPOWL(operator=Operator.XOR, children=[data_analysis, regulation_review])
regulation_review_to_community_meet = OperatorPOWL(operator=Operator.XOR, children=[regulation_review, community_meet])
community_meet_to_harvest_plan = OperatorPOWL(operator=Operator.XOR, children=[community_meet, harvest_plan])
harvest_plan_to_packaging_design = OperatorPOWL(operator=Operator.XOR, children=[harvest_plan, packaging_design])
packaging_design_to_distribution_map = OperatorPOWL(operator=Operator.XOR, children=[packaging_design, distribution_map])
distribution_map_to_feedback_loop = OperatorPOWL(operator=Operator.XOR, children=[distribution_map, feedback_loop])
feedback_loop_to_maintenance_schedule = OperatorPOWL(operator=Operator.XOR, children=[feedback_loop, maintenance_schedule])

root = StrictPartialOrder(nodes=[site_survey_to_climate_study, climate_study_to_soil_prep, soil_prep_to_seed_selection, seed_selection_to_irrigation_setup, irrigation_setup_to_nutrient_mix, nutrient_mix_to_sensor_install, sensor_install_to_pest_monitor, pest_monitor_to_data_analysis, data_analysis_to_regulation_review, regulation_review_to_community_meet, community_meet_to_harvest_plan, harvest_plan_to_packaging_design, packaging_design_to_distribution_map, distribution_map_to_feedback_loop, feedback_loop_to_maintenance_schedule])
root.order.add_edge(site_survey_to_climate_study, climate_study_to_soil_prep)
root.order.add_edge(climate_study_to_soil_prep, soil_prep_to_seed_selection)
root.order.add_edge(soil_prep_to_seed_selection, seed_selection_to_irrigation_setup)
root.order.add_edge(seed_selection_to_irrigation_setup, irrigation_setup_to_nutrient_mix)
root.order.add_edge(irrigation_setup_to_nutrient_mix, nutrient_mix_to_sensor_install)
root.order.add_edge(nutrient_mix_to_sensor_install, sensor_install_to_pest_monitor)
root.order.add_edge(sensor_install_to_pest_monitor, pest_monitor_to_data_analysis)
root.order.add_edge(pest_monitor_to_data_analysis, data_analysis_to_regulation_review)
root.order.add_edge(data_analysis_to_regulation_review, regulation_review_to_community_meet)
root.order.add_edge(regulation_review_to_community_meet, community_meet_to_harvest_plan)
root.order.add_edge(community_meet_to_harvest_plan, harvest_plan_to_packaging_design)
root.order.add_edge(harvest_plan_to_packaging_design, packaging_design_to_distribution_map)
root.order.add_edge(packaging_design_to_distribution_map, distribution_map_to_feedback_loop)
root.order.add_edge(distribution_map_to_feedback_loop, feedback_loop_to_maintenance_schedule)