from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define transitions for each activity
farm_selection = Transition(label='Farm Selection')
milk_testing = Transition(label='Milk Testing')
starter_culture = Transition(label='Starter Culture')
curd_formation = Transition(label='Curd Formation')
pressing_cheese = Transition(label='Pressing Cheese')
microbial_profiling = Transition(label='Microbial Profiling')
aging_control = Transition(label='Aging Control')
hand_wrapping = Transition(label='Hand Wrapping')
quality_audit = Transition(label='Quality Audit')
packaging_prep = Transition(label='Packaging Prep')
climate_shipping = Transition(label='Climate Shipping')
retail_coordination = Transition(label='Retail Coordination')
seasonal_review = Transition(label='Seasonal Review')
consumer_survey = Transition(label='Consumer Survey')
feedback_analysis = Transition(label='Feedback Analysis')
market_adjustment = Transition(label='Market Adjustment')

# Define silent transitions for concurrency
skip_milk_testing = SilentTransition()
skip_starter_culture = SilentTransition()
skip_curd_formation = SilentTransition()
skip_pressing_cheese = SilentTransition()
skip_microbial_profiling = SilentTransition()
skip_aging_control = SilentTransition()
skip_hand_wrapping = SilentTransition()
skip_quality_audit = SilentTransition()
skip_packaging_prep = SilentTransition()
skip_climate_shipping = SilentTransition()
skip_retail_coordination = SilentTransition()
skip_seasonal_review = SilentTransition()
skip_consumer_survey = SilentTransition()
skip_feedback_analysis = SilentTransition()
skip_market_adjustment = SilentTransition()

# Define exclusive choices
milk_testing_choice = OperatorPOWL(operator=Operator.XOR, children=[milk_testing, skip_milk_testing])
starter_culture_choice = OperatorPOWL(operator=Operator.XOR, children=[starter_culture, skip_starter_culture])
curd_formation_choice = OperatorPOWL(operator=Operator.XOR, children=[curd_formation, skip_curd_formation])
pressing_cheese_choice = OperatorPOWL(operator=Operator.XOR, children=[pressing_cheese, skip_pressing_cheese])
microbial_profiling_choice = OperatorPOWL(operator=Operator.XOR, children=[microbial_profiling, skip_microbial_profiling])
aging_control_choice = OperatorPOWL(operator=Operator.XOR, children=[aging_control, skip_aging_control])
hand_wrapping_choice = OperatorPOWL(operator=Operator.XOR, children=[hand_wrapping, skip_hand_wrapping])
quality_audit_choice = OperatorPOWL(operator=Operator.XOR, children=[quality_audit, skip_quality_audit])
packaging_prep_choice = OperatorPOWL(operator=Operator.XOR, children=[packaging_prep, skip_packaging_prep])
climate_shipping_choice = OperatorPOWL(operator=Operator.XOR, children=[climate_shipping, skip_climate_shipping])
retail_coordination_choice = OperatorPOWL(operator=Operator.XOR, children=[retail_coordination, skip_retail_coordination])
seasonal_review_choice = OperatorPOWL(operator=Operator.XOR, children=[seasonal_review, skip_seasonal_review])
consumer_survey_choice = OperatorPOWL(operator=Operator.XOR, children=[consumer_survey, skip_consumer_survey])
feedback_analysis_choice = OperatorPOWL(operator=Operator.XOR, children=[feedback_analysis, skip_feedback_analysis])
market_adjustment_choice = OperatorPOWL(operator=Operator.XOR, children=[market_adjustment, skip_market_adjustment])

# Define loops
aging_loop = OperatorPOWL(operator=Operator.LOOP, children=[aging_control_choice, hand_wrapping_choice])
packaging_loop = OperatorPOWL(operator=Operator.LOOP, children=[packaging_prep_choice, climate_shipping_choice])
retail_loop = OperatorPOWL(operator=Operator.LOOP, children=[retail_coordination_choice, market_adjustment_choice])

# Define the root node
root = StrictPartialOrder(nodes=[farm_selection, milk_testing_choice, starter_culture_choice, curd_formation_choice, pressing_cheese_choice, microbial_profiling_choice, aging_loop, packaging_loop, retail_loop, seasonal_review_choice, consumer_survey_choice, feedback_analysis_choice, market_adjustment_choice])
root.order.add_edge(farm_selection, milk_testing_choice)
root.order.add_edge(farm_selection, starter_culture_choice)
root.order.add_edge(farm_selection, curd_formation_choice)
root.order.add_edge(farm_selection, pressing_cheese_choice)
root.order.add_edge(farm_selection, microbial_profiling_choice)
root.order.add_edge(farm_selection, aging_loop)
root.order.add_edge(farm_selection, packaging_loop)
root.order.add_edge(farm_selection, retail_loop)
root.order.add_edge(farm_selection, seasonal_review_choice)
root.order.add_edge(farm_selection, consumer_survey_choice)
root.order.add_edge(farm_selection, feedback_analysis_choice)
root.order.add_edge(farm_selection, market_adjustment_choice)

print(root)