root = StrictPartialOrder(
    nodes=[
        Transition(label='Source Materials'),
        Transition(label='Vet Suppliers'),
        Transition(label='Design Modules'),
        Transition(label='Prototype Build'),
        Transition(label='Test Durability'),
        Transition(label='Secure Permits'),
        Transition(label='Map Habitats'),
        Transition(label='Micro Warehouse'),
        Transition(label='Inventory Sync'),
        Transition(label='Pack Sustainably'),
        Transition(label='Route Optimize'),
        Transition(label='Engage Community'),
        Transition(label='Collect Feedback'),
        Transition(label='Adjust Production'),
        Transition(label='Partner NGOs'),
        Transition(label='Launch Campaign'),
        Transition(label='Monitor Sensors'),
        Transition(label='Report Impact'),
    ],
    order={
        'Source Materials': ['Vet Suppliers'],
        'Vet Suppliers': ['Design Modules'],
        'Design Modules': ['Prototype Build'],
        'Prototype Build': ['Test Durability'],
        'Test Durability': ['Secure Permits'],
        'Secure Permits': ['Map Habitats'],
        'Map Habitats': ['Micro Warehouse'],
        'Micro Warehouse': ['Inventory Sync'],
        'Inventory Sync': ['Pack Sustainably'],
        'Pack Sustainably': ['Route Optimize'],
        'Route Optimize': ['Engage Community'],
        'Engage Community': ['Collect Feedback'],
        'Collect Feedback': ['Adjust Production'],
        'Adjust Production': ['Partner NGOs'],
        'Partner NGOs': ['Launch Campaign'],
        'Launch Campaign': ['Monitor Sensors'],
        'Monitor Sensors': ['Report Impact'],
    }
)