root = StrictPartialOrder(
    nodes=[
        Transition(label='Seed Selection'),
        Transition(label='Nutrient Mix'),
        Transition(label='Environment Setup'),
        Transition(label='Pest Scan'),
        Transition(label='Light Control'),
        Transition(label='Growth Monitor'),
        Transition(label='Water Cycle'),
        Transition(label='Air Quality'),
        Transition(label='Robotic Harvest'),
        Transition(label='Quality Check'),
        Transition(label='Data Logging'),
        Transition(label='Packaging'),
        Transition(label='Waste Sort'),
        Transition(label='Energy Audit'),
        Transition(label='Retail Sync'),
    ],
    order={
        ('Seed Selection', 'Nutrient Mix'): 0,
        ('Seed Selection', 'Environment Setup'): 0,
        ('Nutrient Mix', 'Pest Scan'): 0,
        ('Nutrient Mix', 'Light Control'): 0,
        ('Nutrient Mix', 'Growth Monitor'): 0,
        ('Environment Setup', 'Water Cycle'): 0,
        ('Environment Setup', 'Air Quality'): 0,
        ('Pest Scan', 'Light Control'): 0,
        ('Pest Scan', 'Growth Monitor'): 0,
        ('Light Control', 'Water Cycle'): 0,
        ('Light Control', 'Air Quality'): 0,
        ('Growth Monitor', 'Water Cycle'): 0,
        ('Growth Monitor', 'Air Quality'): 0,
        ('Water Cycle', 'Robotic Harvest'): 0,
        ('Water Cycle', 'Quality Check'): 0,
        ('Water Cycle', 'Data Logging'): 0,
        ('Water Cycle', 'Packaging'): 0,
        ('Air Quality', 'Robotic Harvest'): 0,
        ('Air Quality', 'Quality Check'): 0,
        ('Air Quality', 'Data Logging'): 0,
        ('Air Quality', 'Packaging'): 0,
        ('Robotic Harvest', 'Quality Check'): 0,
        ('Robotic Harvest', 'Data Logging'): 0,
        ('Robotic Harvest', 'Packaging'): 0,
        ('Quality Check', 'Data Logging'): 0,
        ('Quality Check', 'Packaging'): 0,
        ('Data Logging', 'Packaging'): 0,
        ('Packaging', 'Waste Sort'): 0,
        ('Packaging', 'Energy Audit'): 0,
        ('Waste Sort', 'Retail Sync'): 0,
        ('Energy Audit', 'Retail Sync'): 0,
    }
)