from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define the transitions (activities) with their labels
Site_Survey = Transition(label='Site Survey')
Design_Layout = Transition(label='Design Layout')
Legal_Review = Transition(label='Legal Review')
Tech_Sourcing = Transition(label='Tech Sourcing')
Structural_Build = Transition(label='Structural Build')
Climate_Setup = Transition(label='Climate Setup')
Irrigation_Install = Transition(label='Irrigation Install')
Sensor_Deploy = Transition(label='Sensor Deploy')
Crop_Select = Transition(label='Crop Select')
Nutrient_Prep = Transition(label='Nutrient Prep')
Waste_System = Transition(label='Waste System')
Automation_Config = Transition(label='Automation Config')
Trial_Growth = Transition(label='Trial Growth')
Data_Analysis = Transition(label='Data Analysis')
Quality_Audit = Transition(label='Quality Audit')
Stakeholder_Meet = Transition(label='Stakeholder Meet')
Compliance_Check = Transition(label='Compliance Check')

# Define the silent transitions
skip = SilentTransition()

# Define the process using POWL operators
site_survey = OperatorPOWL(operator=Operator.SILENT, children=[Site_Survey])
design_layout = OperatorPOWL(operator=Operator.SILENT, children=[Design_Layout])
legal_review = OperatorPOWL(operator=Operator.SILENT, children=[Legal_Review])
tech_sourcing = OperatorPOWL(operator=Operator.SILENT, children=[Tech_Sourcing])
structural_build = OperatorPOWL(operator=Operator.SILENT, children=[Structural_Build])
climate_setup = OperatorPOWL(operator=Operator.SILENT, children=[Climate_Setup])
irrigation_install = OperatorPOWL(operator=Operator.SILENT, children=[Irrigation_Install])
sensor_deploy = OperatorPOWL(operator=Operator.SILENT, children=[Sensor_Deploy])
crop_select = OperatorPOWL(operator=Operator.SILENT, children=[Crop_Select])
nutrient_prep = OperatorPOWL(operator=Operator.SILENT, children=[Nutrient_Prep])
waste_system = OperatorPOWL(operator=Operator.SILENT, children=[Waste_System])
automation_config = OperatorPOWL(operator=Operator.SILENT, children=[Automation_Config])
trial_growth = OperatorPOWL(operator=Operator.SILENT, children=[Trial_Growth])
data_analysis = OperatorPOWL(operator=Operator.SILENT, children=[Data_Analysis])
quality_audit = OperatorPOWL(operator=Operator.SILENT, children=[Quality_Audit])
stakeholder_meet = OperatorPOWL(operator=Operator.SILENT, children=[Stakeholder_Meet])
compliance_check = OperatorPOWL(operator=Operator.SILENT, children=[Compliance_Check])

# Define the partial order structure
root = StrictPartialOrder(nodes=[site_survey, design_layout, legal_review, tech_sourcing, structural_build, climate_setup, irrigation_install, sensor_deploy, crop_select, nutrient_prep, waste_system, automation_config, trial_growth, data_analysis, quality_audit, stakeholder_meet, compliance_check])
root.order.add_edge(site_survey, design_layout)
root.order.add_edge(site_survey, legal_review)
root.order.add_edge(design_layout, tech_sourcing)
root.order.add_edge(design_layout, structural_build)
root.order.add_edge(structural_build, climate_setup)
root.order.add_edge(structural_build, irrigation_install)
root.order.add_edge(climate_setup, sensor_deploy)
root.order.add_edge(sensor_deploy, crop_select)
root.order.add_edge(crop_select, nutrient_prep)
root.order.add_edge(nutrient_prep, waste_system)
root.order.add_edge(waste_system, automation_config)
root.order.add_edge(automation_config, trial_growth)
root.order.add_edge(trial_growth, data_analysis)
root.order.add_edge(data_analysis, quality_audit)
root.order.add_edge(quality_audit, stakeholder_meet)
root.order.add_edge(stakeholder_meet, compliance_check)

print(root)