from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition

# Define the transitions for each activity
provenance_check = Transition(label='Provenance Check')
material_scan = Transition(label='Material Scan')
radiocarbon_test = Transition(label='Radiocarbon Test')
stylistic_review = Transition(label='Stylistic Review')
expert_consult = Transition(label='Expert Consult')
document_audit = Transition(label='Document Audit')
legal_verify = Transition(label='Legal Verify')
condition_report = Transition(label='Condition Report')
discrepancy_flag = Transition(label='Discrepancy Flag')
re_examination = Transition(label='Re-examination')
alternative_source = Transition(label='Alternative Source')
acquisition_vote = Transition(label='Acquisition Vote')
catalog_entry = Transition(label='Catalog Entry')
exhibit_plan = Transition(label='Exhibit Plan')
final_approval = Transition(label='Final Approval')

# Define the operators
xor = OperatorPOWL(operator=Operator.XOR, children=[discrepancy_flag, alternative_source])
loop = OperatorPOWL(operator=Operator.LOOP, children=[condition_report, xor])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, loop])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[expert_consult, xor2])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[stylistic_review, xor3])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[document_audit, xor4])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[re_examination, xor5])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[alternative_source, xor6])
xor8 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor7])
xor9 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor8])
xor10 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor9])
xor11 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor10])
xor12 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor11])
xor13 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor12])
xor14 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor13])
xor15 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor14])
xor16 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor15])
xor17 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor16])
xor18 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor17])
xor19 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor18])
xor20 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor19])
xor21 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor20])
xor22 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor21])
xor23 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor22])
xor24 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor23])
xor25 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor24])
xor26 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor25])
xor27 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor26])
xor28 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor27])
xor29 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor28])
xor30 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor29])
xor31 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor30])
xor32 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor31])
xor33 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor32])
xor34 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor33])
xor35 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor34])
xor36 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor35])
xor37 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor36])
xor38 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor37])
xor39 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor38])
xor40 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor39])
xor41 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor40])
xor42 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor41])
xor43 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor42])
xor44 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor43])
xor45 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor44])
xor46 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor45])
xor47 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor46])
xor48 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor47])
xor49 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor48])
xor50 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor49])
xor51 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor50])
xor52 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor51])
xor53 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor52])
xor54 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor53])
xor55 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor54])
xor56 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor55])
xor57 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor56])
xor58 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor57])
xor59 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor58])
xor60 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor59])
xor61 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor60])
xor62 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor61])
xor63 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor62])
xor64 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor63])
xor65 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor64])
xor66 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor65])
xor67 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor66])
xor68 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor67])
xor69 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor68])
xor70 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor69])
xor71 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor70])
xor72 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor71])
xor73 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor72])
xor74 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor73])
xor75 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor74])
xor76 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor75])
xor77 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor76])
xor78 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor77])
xor79 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor78])
xor80 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor79])
xor81 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor80])
xor82 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor81])
xor83 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor82])
xor84 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor83])
xor85 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor84])
xor86 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor85])
xor87 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor86])
xor88 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor87])
xor89 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor88])
xor90 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor89])
xor91 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor90])
xor92 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor91])
xor93 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor92])
xor94 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor93])
xor95 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor94])
xor96 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor95])
xor97 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor96])
xor98 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor97])
xor99 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor98])
xor100 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor99])
xor101 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor100])
xor102 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor101])
xor103 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor102])
xor104 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor103])
xor105 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor104])
xor106 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor105])
xor107 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor106])
xor108 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor107])
xor109 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor108])
xor110 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor109])
xor111 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor110])
xor112 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor111])
xor113 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor112])
xor114 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor113])
xor115 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor114])
xor116 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor115])
xor117 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor116])
xor118 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor117])
xor119 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor118])
xor120 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor119])
xor121 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor120])
xor122 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor121])
xor123 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor122])
xor124 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor123])
xor125 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor124])
xor126 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor125])
xor127 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor126])
xor128 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor127])
xor129 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor128])
xor130 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor129])
xor131 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor130])
xor132 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor131])
xor133 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor132])
xor134 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor133])
xor135 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor134])
xor136 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor135])
xor137 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor136])
xor138 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor137])
xor139 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor138])
xor140 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor139])
xor141 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor140])
xor142 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor141])
xor143 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor142])
xor144 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor143])
xor145 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor144])
xor146 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor145])
xor147 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor146])
xor148 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor147])
xor149 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor148])
xor150 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor149])
xor151 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor150])
xor152 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor151])
xor153 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor152])
xor154 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor153])
xor155 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor154])
xor156 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor155])
xor157 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor156])
xor158 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor157])
xor159 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor158])
xor160 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor159])
xor161 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor160])
xor162 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor161])
xor163 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor162])
xor164 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor163])
xor165 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor164])
xor166 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor165])
xor167 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor166])
xor168 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor167])
xor169 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor168])
xor170 = OperatorPOWL(operator=Operator.XOR, children=[legal_verify, xor169])