root = StrictPartialOrder(
    nodes=[
        Transition(label='Seed Select'),
        Transition(label='Climate Map'),
        Transition(label='IoT Setup'),
        Transition(label='Nutrient Mix'),
        Transition(label='Sensor Check'),
        Transition(label='Light Adjust'),
        Transition(label='Water Cycle'),
        Transition(label='Pest Scan'),
        Transition(label='Growth Audit'),
        Transition(label='Harvest Plan'),
        Transition(label='Demand Sync'),
        Transition(label='Quality Grade'),
        Transition(label='Pack Items'),
        Transition(label='Waste Compost'),
        Transition(label='Data Review'),
        Transition(label='Cycle Reset'),
        OperatorPOWL(operator=Operator.LOOP, children=[
            Transition(label='Seed Select'),
            Transition(label='Climate Map'),
            Transition(label='IoT Setup'),
            Transition(label='Nutrient Mix'),
            Transition(label='Sensor Check'),
            Transition(label='Light Adjust'),
            Transition(label='Water Cycle'),
            Transition(label='Pest Scan'),
            Transition(label='Growth Audit'),
            Transition(label='Harvest Plan'),
            Transition(label='Demand Sync'),
            Transition(label='Quality Grade'),
            Transition(label='Pack Items'),
            Transition(label='Waste Compost'),
            Transition(label='Data Review'),
            OperatorPOWL(operator=Operator.XOR, children=[
                Transition(label='Cycle Reset')
            ])
        ])
    ],
    order={
        (Transition(label='Seed Select'), Transition(label='Climate Map')),
        (Transition(label='Climate Map'), Transition(label='IoT Setup')),
        (Transition(label='IoT Setup'), Transition(label='Nutrient Mix')),
        (Transition(label='Nutrient Mix'), Transition(label='Sensor Check')),
        (Transition(label='Sensor Check'), Transition(label='Light Adjust')),
        (Transition(label='Light Adjust'), Transition(label='Water Cycle')),
        (Transition(label='Water Cycle'), Transition(label='Pest Scan')),
        (Transition(label='Pest Scan'), Transition(label='Growth Audit')),
        (Transition(label='Growth Audit'), Transition(label='Harvest Plan')),
        (Transition(label='Harvest Plan'), Transition(label='Demand Sync')),
        (Transition(label='Demand Sync'), Transition(label='Quality Grade')),
        (Transition(label='Quality Grade'), Transition(label='Pack Items')),
        (Transition(label='Pack Items'), Transition(label='Waste Compost')),
        (Transition(label='Waste Compost'), Transition(label='Data Review')),
        (Transition(label='Data Review'), Transition(label='Cycle Reset')),
        (Transition(label='Cycle Reset'), Transition(label='Seed Select')),
        (Transition(label='Cycle Reset'), Transition(label='Climate Map')),
        (Transition(label='Cycle Reset'), Transition(label='IoT Setup')),
        (Transition(label='Cycle Reset'), Transition(label='Nutrient Mix')),
        (Transition(label='Cycle Reset'), Transition(label='Sensor Check')),
        (Transition(label='Cycle Reset'), Transition(label='Light Adjust')),
        (Transition(label='Cycle Reset'), Transition(label='Water Cycle')),
        (Transition(label='Cycle Reset'), Transition(label='Pest Scan')),
        (Transition(label='Cycle Reset'), Transition(label='Growth Audit')),
        (Transition(label='Cycle Reset'), Transition(label='Harvest Plan')),
        (Transition(label='Cycle Reset'), Transition(label='Demand Sync')),
        (Transition(label='Cycle Reset'), Transition(label='Quality Grade')),
        (Transition(label='Cycle Reset'), Transition(label='Pack Items')),
        (Transition(label='Cycle Reset'), Transition(label='Waste Compost')),
        (Transition(label='Cycle Reset'), Transition(label='Data Review')),
        (Transition(label='Cycle Reset'), Transition(label='Cycle Reset'))
    }
)