import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define activities
site_assess = Transition(label='Site Assess')
structure_check = Transition(label='Structure Check')
permit_obtain = Transition(label='Permit Obtain')
material_source = Transition(label='Material Source')
soil_prepare = Transition(label='Soil Prepare')
waterproof_roof = Transition(label='Waterproof Roof')
irrigation_setup = Transition(label='Irrigation Setup')
bed_assemble = Transition(label='Bed Assemble')
crop_plan = Transition(label='Crop Plan')
pest_monitor = Transition(label='Pest Monitor')
nutrient_calibrate = Transition(label='Nutrient Calibrate')
harvest_schedule = Transition(label='Harvest Schedule')
community_train = Transition(label='Community Train')
yield_record = Transition(label='Yield Record')
impact_review = Transition(label='Impact Review')

# Define process
xor = OperatorPOWL(operator=Operator.XOR, children=[
    material_source, soil_prepare, waterproof_roof, irrigation_setup, bed_assemble, crop_plan, pest_monitor, nutrient_calibrate, harvest_schedule, community_train, yield_record, impact_review
])

root = StrictPartialOrder(nodes=[site_assess, structure_check, permit_obtain, xor])
root.order.add_edge(site_assess, structure_check)
root.order.add_edge(site_assess, permit_obtain)
root.order.add_edge(structure_check, permit_obtain)
root.order.add_edge(permit_obtain, material_source)
root.order.add_edge(permit_obtain, soil_prepare)
root.order.add_edge(permit_obtain, waterproof_roof)
root.order.add_edge(permit_obtain, irrigation_setup)
root.order.add_edge(permit_obtain, bed_assemble)
root.order.add_edge(permit_obtain, crop_plan)
root.order.add_edge(material_source, pest_monitor)
root.order.add_edge(material_source, nutrient_calibrate)
root.order.add_edge(material_source, harvest_schedule)
root.order.add_edge(material_source, community_train)
root.order.add_edge(material_source, yield_record)
root.order.add_edge(material_source, impact_review)
root.order.add_edge(soil_prepare, pest_monitor)
root.order.add_edge(soil_prepare, nutrient_calibrate)
root.order.add_edge(soil_prepare, harvest_schedule)
root.order.add_edge(soil_prepare, community_train)
root.order.add_edge(soil_prepare, yield_record)
root.order.add_edge(soil_prepare, impact_review)
root.order.add_edge(waterproof_roof, pest_monitor)
root.order.add_edge(waterproof_roof, nutrient_calibrate)
root.order.add_edge(waterproof_roof, harvest_schedule)
root.order.add_edge(waterproof_roof, community_train)
root.order.add_edge(waterproof_roof, yield_record)
root.order.add_edge(waterproof_roof, impact_review)
root.order.add_edge(irrigation_setup, pest_monitor)
root.order.add_edge(irrigation_setup, nutrient_calibrate)
root.order.add_edge(irrigation_setup, harvest_schedule)
root.order.add_edge(irrigation_setup, community_train)
root.order.add_edge(irrigation_setup, yield_record)
root.order.add_edge(irrigation_setup, impact_review)
root.order.add_edge(bed_assemble, pest_monitor)
root.order.add_edge(bed_assemble, nutrient_calibrate)
root.order.add_edge(bed_assemble, harvest_schedule)
root.order.add_edge(bed_assemble, community_train)
root.order.add_edge(bed_assemble, yield_record)
root.order.add_edge(bed_assemble, impact_review)
root.order.add_edge(crop_plan, pest_monitor)
root.order.add_edge(crop_plan, nutrient_calibrate)
root.order.add_edge(crop_plan, harvest_schedule)
root.order.add_edge(crop_plan, community_train)
root.order.add_edge(crop_plan, yield_record)
root.order.add_edge(crop_plan, impact_review)
root.order.add_edge(pest_monitor, nutrient_calibrate)
root.order.add_edge(pest_monitor, harvest_schedule)
root.order.add_edge(pest_monitor, community_train)
root.order.add_edge(pest_monitor, yield_record)
root.order.add_edge(pest_monitor, impact_review)
root.order.add_edge(nutrient_calibrate, harvest_schedule)
root.order.add_edge(nutrient_calibrate, community_train)
root.order.add_edge(nutrient_calibrate, yield_record)
root.order.add_edge(nutrient_calibrate, impact_review)
root.order.add_edge(harvest_schedule, community_train)
root.order.add_edge(harvest_schedule, yield_record)
root.order.add_edge(harvest_schedule, impact_review)
root.order.add_edge(community_train, yield_record)
root.order.add_edge(community_train, impact_review)
root.order.add_edge(yield_record, impact_review)

print(root)