root = StrictPartialOrder(
    nodes=[
        Transition(label='Audit Artifacts'),
        Transition(label='Interview Staff'),
        Transition(label='Assess Risks'),
        Transition(label='Plan Retrieval'),
        Transition(label='Legal Review'),
        Transition(label='Security Check'),
        Transition(label='Execute Recovery'),
        Transition(label='Validate Items'),
        Transition(label='Restore Function'),
        Transition(label='Update Systems'),
        Transition(label='Train Users'),
        Transition(label='Document Findings'),
        Transition(label='Archive Records'),
        Transition(label='Review Lessons'),
        Transition(label='Close Process'),
    ],
    order=[
        (Transition(label='Audit Artifacts'), Transition(label='Interview Staff')),
        (Transition(label='Interview Staff'), Transition(label='Assess Risks')),
        (Transition(label='Assess Risks'), Transition(label='Plan Retrieval')),
        (Transition(label='Plan Retrieval'), Transition(label='Legal Review')),
        (Transition(label='Plan Retrieval'), Transition(label='Security Check')),
        (Transition(label='Legal Review'), Transition(label='Execute Recovery')),
        (Transition(label='Security Check'), Transition(label='Execute Recovery')),
        (Transition(label='Execute Recovery'), Transition(label='Validate Items')),
        (Transition(label='Execute Recovery'), Transition(label='Restore Function')),
        (Transition(label='Validate Items'), Transition(label='Restore Function')),
        (Transition(label='Restore Function'), Transition(label='Update Systems')),
        (Transition(label='Update Systems'), Transition(label='Train Users')),
        (Transition(label='Train Users'), Transition(label='Document Findings')),
        (Transition(label='Document Findings'), Transition(label='Archive Records')),
        (Transition(label='Archive Records'), Transition(label='Review Lessons')),
        (Transition(label='Review Lessons'), Transition(label='Close Process')),
    ],
)