from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition

# Define the activities as transitions
site_survey = Transition(label='Site Survey')
load_testing = Transition(label='Load Testing')
crop_selection = Transition(label='Crop Selection')
soil_prep = Transition(label='Soil Prep')
irrigation_setup = Transition(label='Irrigation Setup')
permits_acquire = Transition(label='Permits Acquire')
supplier_outreach = Transition(label='Supplier Outreach')
planting_seedlings = Transition(label='Planting Seedlings')
pest_monitoring = Transition(label='Pest Monitoring')
nutrient_testing = Transition(label='Nutrient Testing')
waste_sorting = Transition(label='Waste Sorting')
staff_training = Transition(label='Staff Training')
community_meet = Transition(label='Community Meet')
harvest_planning = Transition(label='Harvest Planning')
market_launch = Transition(label='Market Launch')
yield_tracking = Transition(label='Yield Tracking')

# Create the partial order
root = StrictPartialOrder(nodes=[
    site_survey,
    load_testing,
    crop_selection,
    soil_prep,
    irrigation_setup,
    permits_acquire,
    supplier_outreach,
    planting_seedlings,
    pest_monitoring,
    nutrient_testing,
    waste_sorting,
    staff_training,
    community_meet,
    harvest_planning,
    market_launch,
    yield_tracking
])

# Define the dependencies
root.order.add_edge(site_survey, load_testing)
root.order.add_edge(site_survey, crop_selection)
root.order.add_edge(site_survey, soil_prep)
root.order.add_edge(site_survey, irrigation_setup)
root.order.add_edge(site_survey, permits_acquire)
root.order.add_edge(site_survey, supplier_outreach)
root.order.add_edge(site_survey, planting_seedlings)
root.order.add_edge(site_survey, pest_monitoring)
root.order.add_edge(site_survey, nutrient_testing)
root.order.add_edge(site_survey, waste_sorting)
root.order.add_edge(site_survey, staff_training)
root.order.add_edge(site_survey, community_meet)
root.order.add_edge(site_survey, harvest_planning)
root.order.add_edge(site_survey, market_launch)
root.order.add_edge(site_survey, yield_tracking)
root.order.add_edge(load_testing, crop_selection)
root.order.add_edge(load_testing, soil_prep)
root.order.add_edge(load_testing, irrigation_setup)
root.order.add_edge(load_testing, permits_acquire)
root.order.add_edge(load_testing, supplier_outreach)
root.order.add_edge(load_testing, planting_seedlings)
root.order.add_edge(load_testing, pest_monitoring)
root.order.add_edge(load_testing, nutrient_testing)
root.order.add_edge(load_testing, waste_sorting)
root.order.add_edge(load_testing, staff_training)
root.order.add_edge(load_testing, community_meet)
root.order.add_edge(load_testing, harvest_planning)
root.order.add_edge(load_testing, market_launch)
root.order.add_edge(load_testing, yield_tracking)
root.order.add_edge(crop_selection, soil_prep)
root.order.add_edge(crop_selection, irrigation_setup)
root.order.add_edge(crop_selection, permits_acquire)
root.order.add_edge(crop_selection, supplier_outreach)
root.order.add_edge(crop_selection, planting_seedlings)
root.order.add_edge(crop_selection, pest_monitoring)
root.order.add_edge(crop_selection, nutrient_testing)
root.order.add_edge(crop_selection, waste_sorting)
root.order.add_edge(crop_selection, staff_training)
root.order.add_edge(crop_selection, community_meet)
root.order.add_edge(crop_selection, harvest_planning)
root.order.add_edge(crop_selection, market_launch)
root.order.add_edge(crop_selection, yield_tracking)
root.order.add_edge(soil_prep, irrigation_setup)
root.order.add_edge(soil_prep, permits_acquire)
root.order.add_edge(soil_prep, supplier_outreach)
root.order.add_edge(soil_prep, planting_seedlings)
root.order.add_edge(soil_prep, pest_monitoring)
root.order.add_edge(soil_prep, nutrient_testing)
root.order.add_edge(soil_prep, waste_sorting)
root.order.add_edge(soil_prep, staff_training)
root.order.add_edge(soil_prep, community_meet)
root.order.add_edge(soil_prep, harvest_planning)
root.order.add_edge(soil_prep, market_launch)
root.order.add_edge(soil_prep, yield_tracking)
root.order.add_edge(irrigation_setup, permits_acquire)
root.order.add_edge(irrigation_setup, supplier_outreach)
root.order.add_edge(irrigation_setup, planting_seedlings)
root.order.add_edge(irrigation_setup, pest_monitoring)
root.order.add_edge(irrigation_setup, nutrient_testing)
root.order.add_edge(irrigation_setup, waste_sorting)
root.order.add_edge(irrigation_setup, staff_training)
root.order.add_edge(irrigation_setup, community_meet)
root.order.add_edge(irrigation_setup, harvest_planning)
root.order.add_edge(irrigation_setup, market_launch)
root.order.add_edge(irrigation_setup, yield_tracking)
root.order.add_edge(permits_acquire, supplier_outreach)
root.order.add_edge(permits_acquire, planting_seedlings)
root.order.add_edge(permits_acquire, pest_monitoring)
root.order.add_edge(permits_acquire, nutrient_testing)
root.order.add_edge(permits_acquire, waste_sorting)
root.order.add_edge(permits_acquire, staff_training)
root.order.add_edge(permits_acquire, community_meet)
root.order.add_edge(permits_acquire, harvest_planning)
root.order.add_edge(permits_acquire, market_launch)
root.order.add_edge(permits_acquire, yield_tracking)
root.order.add_edge(supplier_outreach, planting_seedlings)
root.order.add_edge(supplier_outreach, pest_monitoring)
root.order.add_edge(supplier_outreach, nutrient_testing)
root.order.add_edge(supplier_outreach, waste_sorting)
root.order.add_edge(supplier_outreach, staff_training)
root.order.add_edge(supplier_outreach, community_meet)
root.order.add_edge(supplier_outreach, harvest_planning)
root.order.add_edge(supplier_outreach, market_launch)
root.order.add_edge(supplier_outreach, yield_tracking)
root.order.add_edge(planting_seedlings, pest_monitoring)
root.order.add_edge(planting_seedlings, nutrient_testing)
root.order.add_edge(planting_seedlings, waste_sorting)
root.order.add_edge(planting_seedlings, staff_training)
root.order.add_edge(planting_seedlings, community_meet)
root.order.add_edge(planting_seedlings, harvest_planning)
root.order.add_edge(planting_seedlings, market_launch)
root.order.add_edge(planting_seedlings, yield_tracking)
root.order.add_edge(pest_monitoring, nutrient_testing)
root.order.add_edge(pest_monitoring, waste_sorting)
root.order.add_edge(pest_monitoring, staff_training)
root.order.add_edge(pest_monitoring, community_meet)
root.order.add_edge(pest_monitoring, harvest_planning)
root.order.add_edge(pest_monitoring, market_launch)
root.order.add_edge(pest_monitoring, yield_tracking)
root.order.add_edge(nutrient_testing, waste_sorting)
root.order.add_edge(nutrient_testing, staff_training)
root.order.add_edge(nutrient_testing, community_meet)
root.order.add_edge(nutrient_testing, harvest_planning)
root.order.add_edge(nutrient_testing, market_launch)
root.order.add_edge(nutrient_testing, yield_tracking)
root.order.add_edge(waste_sorting, staff_training)
root.order.add_edge(waste_sorting, community_meet)
root.order.add_edge(waste_sorting, harvest_planning)
root.order.add_edge(waste_sorting, market_launch)
root.order.add_edge(waste_sorting, yield_tracking)
root.order.add_edge(staff_training, community_meet)
root.order.add_edge(staff_training, harvest_planning)
root.order.add_edge(staff_training, market_launch)
root.order.add_edge(staff_training, yield_tracking)
root.order.add_edge(community_meet, harvest_planning)
root.order.add_edge(community_meet, market_launch)
root.order.add_edge(community_meet, yield_tracking)
root.order.add_edge(harvest_planning, market_launch)
root.order.add_edge(harvest_planning, yield_tracking)
root.order.add_edge(market_launch, yield_tracking)