import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

data_capture = Transition(label='Data Capture')
trend_scan = Transition(label='Trend Scan')
idea_workshop = Transition(label='Idea Workshop')
concept_draft = Transition(label='Concept Draft')
expert_review = Transition(label='Expert Review')
prototype_build = Transition(label='Prototype Build')
regulation_check = Transition(label='Regulation Check')
ip_alignment = Transition(label='IP Alignment')
supply_sync = Transition(label='Supply Sync')
market_mapping = Transition(label='Market Mapping')
pilot_launch = Transition(label='Pilot Launch')
feedback_loop = Transition(label='Feedback Loop')
design_iterate = Transition(label='Design Iterate')
impact_measure = Transition(label='Impact Measure')
strategy_adapt = Transition(label='Strategy Adapt')

xor1 = OperatorPOWL(operator=Operator.XOR, children=[data_capture, trend_scan])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[idea_workshop, concept_draft])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[expert_review, prototype_build])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[regulation_check, ip_alignment])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[supply_sync, market_mapping])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[pilot_launch, feedback_loop])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[design_iterate, impact_measure])
xor8 = OperatorPOWL(operator=Operator.XOR, children=[strategy_adapt, silent_transition])

root = StrictPartialOrder(nodes=[xor1, xor2, xor3, xor4, xor5, xor6, xor7, xor8])
root.order.add_edge(xor1, xor2)
root.order.add_edge(xor2, xor3)
root.order.add_edge(xor3, xor4)
root.order.add_edge(xor4, xor5)
root.order.add_edge(xor5, xor6)
root.order.add_edge(xor6, xor7)
root.order.add_edge(xor7, xor8)