from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

quantum_modeling = Transition(label='Quantum Modeling')
data_encoding = Transition(label='Data Encoding')
route_simulation = Transition(label='Route Simulation')
demand_forecast = Transition(label='Demand Forecast')
supplier_sync = Transition(label='Supplier Sync')
entangle_nodes = Transition(label='Entangle Nodes')
risk_analysis = Transition(label='Risk Analysis')
inventory_scan = Transition(label='Inventory Scan')
latency_check = Transition(label='Latency Check')
transport_plan = Transition(label='Transport Plan')
quantum_compute = Transition(label='Quantum Compute')
scenario_test = Transition(label='Scenario Test')
resource_align = Transition(label='Resource Align')
protocol_update = Transition(label='Protocol Update')
feedback_loop = Transition(label='Feedback Loop')
cost_optimize = Transition(label='Cost Optimize')
impact_review = Transition(label='Impact Review')

xor1 = OperatorPOWL(operator=Operator.XOR, children=[route_simulation, demand_forecast])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[risk_analysis, inventory_scan])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[latency_check, transport_plan])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[quantum_compute, scenario_test])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[resource_align, protocol_update])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[feedback_loop, cost_optimize])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[impact_review, quantum_modeling])

root = StrictPartialOrder(nodes=[xor1, xor2, xor3, xor4, xor5, xor6, xor7])
root.order.add_edge(xor1, xor2)
root.order.add_edge(xor1, xor3)
root.order.add_edge(xor1, xor4)
root.order.add_edge(xor1, xor5)
root.order.add_edge(xor1, xor6)
root.order.add_edge(xor1, xor7)
root.order.add_edge(xor2, xor3)
root.order.add_edge(xor2, xor4)
root.order.add_edge(xor2, xor5)
root.order.add_edge(xor2, xor6)
root.order.add_edge(xor2, xor7)
root.order.add_edge(xor3, xor4)
root.order.add_edge(xor3, xor5)
root.order.add_edge(xor3, xor6)
root.order.add_edge(xor3, xor7)
root.order.add_edge(xor4, xor5)
root.order.add_edge(xor4, xor6)
root.order.add_edge(xor4, xor7)
root.order.add_edge(xor5, xor6)
root.order.add_edge(xor5, xor7)
root.order.add_edge(xor6, xor7)