from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_survey = Transition(label='Site Survey')
structural_check = Transition(label='Structural Check')
env_control = Transition(label='Env Control')
hydro_setup = Transition(label='Hydro Setup')
crop_select = Transition(label='Crop Select')
iot_install = Transition(label='IoT Install')
sensor_calibrate = Transition(label='Sensor Calibrate')
water_cycle = Transition(label='Water Cycle')
nutrient_mix = Transition(label='Nutrient Mix')
lighting_adjust = Transition(label='Lighting Adjust')
staff_train = Transition(label='Staff Train')
waste_manage = Transition(label='Waste Manage')
energy_audit = Transition(label='Energy Audit')
harvest_plan = Transition(label='Harvest Plan')
delivery_setup = Transition(label='Delivery Setup')
market_align = Transition(label='Market Align')

skip = SilentTransition()

site_survey_xor = OperatorPOWL(operator=Operator.XOR, children=[structural_check, skip])
site_survey_xor = OperatorPOWL(operator=Operator.XOR, children=[env_control, skip])
site_survey_xor2 = OperatorPOWL(operator=Operator.XOR, children=[hydro_setup, skip])
site_survey_xor3 = OperatorPOWL(operator=Operator.XOR, children=[crop_select, skip])
site_survey_xor4 = OperatorPOWL(operator=Operator.XOR, children=[iot_install, skip])
site_survey_xor5 = OperatorPOWL(operator=Operator.XOR, children=[sensor_calibrate, skip])
site_survey_xor6 = OperatorPOWL(operator=Operator.XOR, children=[water_cycle, skip])
site_survey_xor7 = OperatorPOWL(operator=Operator.XOR, children=[nutrient_mix, skip])
site_survey_xor8 = OperatorPOWL(operator=Operator.XOR, children=[lighting_adjust, skip])
site_survey_xor9 = OperatorPOWL(operator=Operator.XOR, children=[staff_train, skip])
site_survey_xor10 = OperatorPOWL(operator=Operator.XOR, children=[waste_manage, skip])
site_survey_xor11 = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, skip])
site_survey_xor12 = OperatorPOWL(operator=Operator.XOR, children=[harvest_plan, skip])
site_survey_xor13 = OperatorPOWL(operator=Operator.XOR, children=[delivery_setup, skip])
site_survey_xor14 = OperatorPOWL(operator=Operator.XOR, children=[market_align, skip])

root = StrictPartialOrder(nodes=[site_survey, site_survey_xor, site_survey_xor2, site_survey_xor3, site_survey_xor4, site_survey_xor5, site_survey_xor6, site_survey_xor7, site_survey_xor8, site_survey_xor9, site_survey_xor10, site_survey_xor11, site_survey_xor12, site_survey_xor13, site_survey_xor14])
root.order.add_edge(site_survey, site_survey_xor)
root.order.add_edge(site_survey, site_survey_xor2)
root.order.add_edge(site_survey, site_survey_xor3)
root.order.add_edge(site_survey, site_survey_xor4)
root.order.add_edge(site_survey, site_survey_xor5)
root.order.add_edge(site_survey, site_survey_xor6)
root.order.add_edge(site_survey, site_survey_xor7)
root.order.add_edge(site_survey, site_survey_xor8)
root.order.add_edge(site_survey, site_survey_xor9)
root.order.add_edge(site_survey, site_survey_xor10)
root.order.add_edge(site_survey, site_survey_xor11)
root.order.add_edge(site_survey, site_survey_xor12)
root.order.add_edge(site_survey, site_survey_xor13)
root.order.add_edge(site_survey, site_survey_xor14)