from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition

# Define the POWL model
A = Transition(label='Quantum Init')
B = Transition(label='Data Ingest')
C = Transition(label='AI Forecast')
D = Transition(label='Inventory Sync')
E = Transition(label='Procurement Plan')
F = Transition(label='Production Align')
G = Transition(label='Distribution Map')
H = Transition(label='IoT Monitor')
I = Transition(label='Risk Assess')
J = Transition(label='Maintenance Alert')
K = Transition(label='Quantum Compute')
L = Transition(label='Feedback Loop')
M = Transition(label='Schedule Adjust')
N = Transition(label='Demand Update')
O = Transition(label='Delivery Track')
P = Transition(label='Compliance Check')

# Define the partial order
root = StrictPartialOrder(nodes=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P])
root.order.add_edge(A, B)
root.order.add_edge(B, C)
root.order.add_edge(C, D)
root.order.add_edge(D, E)
root.order.add_edge(E, F)
root.order.add_edge(F, G)
root.order.add_edge(G, H)
root.order.add_edge(H, I)
root.order.add_edge(I, J)
root.order.add_edge(J, K)
root.order.add_edge(K, L)
root.order.add_edge(L, M)
root.order.add_edge(M, N)
root.order.add_edge(N, O)
root.order.add_edge(O, P)