import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define each activity as a Transition object
site_survey = Transition(label='Site Survey')
permit_review = Transition(label='Permit Review')
design_layout = Transition(label='Design Layout')
material_sourcing = Transition(label='Material Sourcing')
irrigation_setup = Transition(label='Irrigation Setup')
sensor_install = Transition(label='Sensor Install')
structural_test = Transition(label='Structural Test')
recruit_farmers = Transition(label='Recruit Farmers')
trial_planting = Transition(label='Trial Planting')
pest_control = Transition(label='Pest Control')
soilless_prep = Transition(label='Soilless Prep')
system_calibrate = Transition(label='System Calibrate')
data_monitor = Transition(label='Data Monitor')
harvest_plan = Transition(label='Harvest Plan')
community_outreach = Transition(label='Community Outreach')

# Define partial order nodes
site_survey_node = StrictPartialOrder(nodes=[site_survey])
permit_review_node = StrictPartialOrder(nodes=[permit_review])
design_layout_node = StrictPartialOrder(nodes=[design_layout])
material_sourcing_node = StrictPartialOrder(nodes=[material_sourcing])
irrigation_setup_node = StrictPartialOrder(nodes=[irrigation_setup])
sensor_install_node = StrictPartialOrder(nodes=[sensor_install])
structural_test_node = StrictPartialOrder(nodes=[structural_test])
recruit_farmers_node = StrictPartialOrder(nodes=[recruit_farmers])
trial_planting_node = StrictPartialOrder(nodes=[trial_planting])
pest_control_node = StrictPartialOrder(nodes=[pest_control])
soilless_prep_node = StrictPartialOrder(nodes=[soilless_prep])
system_calibrate_node = StrictPartialOrder(nodes=[system_calibrate])
data_monitor_node = StrictPartialOrder(nodes=[data_monitor])
harvest_plan_node = StrictPartialOrder(nodes=[harvest_plan])
community_outreach_node = StrictPartialOrder(nodes=[community_outreach])

# Define dependencies between nodes
root = StrictPartialOrder(nodes=[site_survey_node, permit_review_node, design_layout_node, material_sourcing_node, irrigation_setup_node, sensor_install_node, structural_test_node, recruit_farmers_node, trial_planting_node, pest_control_node, soilless_prep_node, system_calibrate_node, data_monitor_node, harvest_plan_node, community_outreach_node])
root.order.add_edge(site_survey_node, permit_review_node)
root.order.add_edge(permit_review_node, design_layout_node)
root.order.add_edge(design_layout_node, material_sourcing_node)
root.order.add_edge(material_sourcing_node, irrigation_setup_node)
root.order.add_edge(irrigation_setup_node, sensor_install_node)
root.order.add_edge(sensor_install_node, structural_test_node)
root.order.add_edge(structural_test_node, recruit_farmers_node)
root.order.add_edge(recruit_farmers_node, trial_planting_node)
root.order.add_edge(trial_planting_node, pest_control_node)
root.order.add_edge(pest_control_node, soilless_prep_node)
root.order.add_edge(soilless_prep_node, system_calibrate_node)
root.order.add_edge(system_calibrate_node, data_monitor_node)
root.order.add_edge(data_monitor_node, harvest_plan_node)
root.order.add_edge(harvest_plan_node, community_outreach_node)