from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition

# Define the POWL model
A = Transition(label='Asset ID')
B = Transition(label='Value Assess')
C = Transition(label='Risk Scan')
D = Transition(label='Market Review')
E = Transition(label='Initial Offer')
F = Transition(label='Counter Offer')
G = Transition(label='Negotiation')
H = Transition(label='Contract Draft')
I = Transition(label='Legal Review')
J = Transition(label='Digital Sign')
K = Transition(label='Royalty Setup')
L = Transition(label='Transfer Record')
M = Transition(label='Compliance Check')
N = Transition(label='Audit Schedule')
O = Transition(label='Market Feedback')
P = Transition(label='Strategy Update')

# Define the POWL model structure
root = StrictPartialOrder(nodes=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P])
root.order.add_edge(A, B)
root.order.add_edge(B, C)
root.order.add_edge(C, D)
root.order.add_edge(D, E)
root.order.add_edge(E, F)
root.order.add_edge(F, G)
root.order.add_edge(G, H)
root.order.add_edge(H, I)
root.order.add_edge(I, J)
root.order.add_edge(J, K)
root.order.add_edge(K, L)
root.order.add_edge(L, M)
root.order.add_edge(M, N)
root.order.add_edge(N, O)
root.order.add_edge(O, P)

print(root)