import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
begin_onboarding = Transition(label='Begin onboarding process')
choose_candidate = Transition(label='Choose candidate')
collect_resumes = Transition(label='Collect resumes')
complete_orientation = Transition(label='Complete orientation')
complete_paperwork = Transition(label='Complete paperwork')
complete_training = Transition(label='Complete training')
conduct_virtual_interview = Transition(label='Conduct a virtual interview')
conduct_in_person_interview = Transition(label='Conduct an in-person interview')
conduct_initial_phone_interviews = Transition(label='Conduct initial phone interviews')
create_job_description = Transition(label='Create job description')
extend_offer = Transition(label='Extend offer')
identify_need_for_new_hire = Transition(label='Identify need for new hire')
invite_candidates_for_interviews = Transition(label='Invite candidates for interviews')
negotiate_salary = Transition(label='Negotiate salary')
post_job_description = Transition(label='Post job description')
screen_resumes = Transition(label='Screen resumes')
skip = SilentTransition()
xor = OperatorPOWL(operator=Operator.XOR, children=[complete_orientation, complete_paperwork, complete_training, skip])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[conduct_virtual_interview, conduct_in_person_interview, conduct_initial_phone_interviews])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[invite_candidates_for_interviews, skip])
loop = OperatorPOWL(operator=Operator.LOOP, children=[create_job_description, extend_offer, identify_need_for_new_hire, screen_resumes])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[negotiate_salary, skip])
root = StrictPartialOrder(nodes=[begin_onboarding, choose_candidate, collect_resumes, xor, xor2, xor3, loop, xor4])
root.order.add_edge(begin_onboarding, choose_candidate)
root.order.add_edge(choose_candidate, xor)
root.order.add_edge(xor, xor2)
root.order.add_edge(xor2, xor3)
root.order.add_edge(xor3, loop)
root.order.add_edge(loop, xor4)
root.order.add_edge(xor4, begin_onboarding)