import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
A = Transition(label='Customer places order online')
B = Transition(label='Customer places order over the phone')
C = Transition(label='Generate and send order confirmation')
D = Transition(label='Generate shipping label')
E = Transition(label='Hand over order to logistics provider')
F = Transition(label='Monitor shipment')
G = Transition(label='Pick and pack items')
H = Transition(label='Process customer feedback or returns')
I = Transition(label='Send tracking information to customer')
J = Transition(label='Successful delivery')
skip = SilentTransition()
xor = OperatorPOWL(operator=Operator.XOR, children=[H, skip])
loop = OperatorPOWL(operator=Operator.LOOP, children=[G])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[I, skip])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[J, skip])
root = StrictPartialOrder(nodes=[A, B, C, D, E, F, G, H, I, J, xor, loop, xor2, xor3])
root.order.add_edge(A, C)
root.order.add_edge(B, C)
root.order.add_edge(C, D)
root.order.add_edge(D, E)
root.order.add_edge(E, F)
root.order.add_edge(F, xor)
root.order.add_edge(F, xor2)
root.order.add_edge(xor, xor3)
root.order.add_edge(xor2, xor3)
root.order.add_edge(xor3, J)