root = StrictPartialOrder(
    nodes=[
        Transition(label='Customer searches for ticket'),
        Transition(label='Select route'),
        Transition(label='Select date and time'),
        Transition(label='Provide personal information'),
        Transition(label='Provide payment details'),
        Transition(label='Generate ticket'),
        Transition(label='Send ticket via email'),
        Transition(label='Send ticket via SMS'),
        Transition(label='Update seat inventory'),
        Transition(label='Send instructions'),
        Transition(label='Send reminder'),
        Transition(label='Customer completes journey'),
        Transition(label='Post-travel feedback or services'),
    ],
    order=[
        ('Customer searches for ticket', 'Select route'),
        ('Customer searches for ticket', 'Select date and time'),
        ('Customer searches for ticket', 'Provide personal information'),
        ('Customer searches for ticket', 'Provide payment details'),
        ('Select route', 'Generate ticket'),
        ('Select date and time', 'Generate ticket'),
        ('Select date and time', 'Send instructions'),
        ('Select date and time', 'Send reminder'),
        ('Provide personal information', 'Generate ticket'),
        ('Provide payment details', 'Generate ticket'),
        ('Generate ticket', 'Send ticket via email'),
        ('Generate ticket', 'Send ticket via SMS'),
        ('Generate ticket', 'Update seat inventory'),
        ('Update seat inventory', 'Send instructions'),
        ('Update seat inventory', 'Send reminder'),
        ('Send ticket via email', 'Customer completes journey'),
        ('Send ticket via SMS', 'Customer completes journey'),
        ('Customer completes journey', 'Post-travel feedback or services'),
    ]
)