A = Transition(label='Approve report')
B = Transition(label='Archive report')
C = Transition(label='Check regulatory updates')
D = Transition(label='Close audit process')
E = Transition(label='Compile audit report')
F = Transition(label='Complete risk assessment/mitigation')
G = Transition(label='Conduct data analysis')
H = Transition(label='Conduct interviews')
I = Transition(label='Distribute final report')
J = Transition(label='Evaluate compliance risks')
K = Transition(label='Evaluate financial risks')
L = Transition(label='Evaluate operational risks')
M = Transition(label='Gather necessary documents')
N = Transition(label='Launch detailed investigation')
O = Transition(label='Perform site visits')
P = Transition(label='Prepare financial statements')
Q = Transition(label='Receive clarifications')
R = Transition(label='Request clarifications of discrepancies')
S = Transition(label='Review report by audit director')
T = Transition(label='Review submission')
U = Transition(label='Send notification')
V = Transition(label='Send report for revision')
W = Transition(label='Submit documents')
X = Transition(label='Update and resubmit report')
Y = Transition(label='XOR')
Z = Transition(label='Loop')

xor1 = OperatorPOWL(operator=Operator.XOR, children=[F, G, H, I, J, K, L])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[N, O, P])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[R, S, T, U, V, W, X])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[D, B, Y])
loop = OperatorPOWL(operator=Operator.LOOP, children=[xor1, xor2, xor3, xor4])
root = StrictPartialOrder(nodes=[loop])
root.order.add_edge(loop, xor1)
root.order.add_edge(loop, xor2)
root.order.add_edge(loop, xor3)
root.order.add_edge(loop, xor4)

print(root)