import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define transitions for each activity
check_stock_availability = Transition(label='Check stock availability')
confirm_delivery = Transition(label='Confirm delivery')
customer_reports_issue = Transition(label='Customer reports issue')
dispatch_order = Transition(label='Dispatch order')
gift_wrap_items = Transition(label='Gift wrap items')
inform_customer_about_delay = Transition(label='Inform customer about delay')
initiate_back_order = Transition(label='Initiate back-order')
inspect_returned_items = Transition(label='Inspect returned items')
notify_about_failed_payment = Transition(label='Notify about failed payment')
package_items = Transition(label='Package items')
perform_quality_control_checks = Transition(label='Perform quality control checks')
pick_items_from_warehouse = Transition(label='Pick items from warehouse')
place_order = Transition(label='Place order')
prepare_documentation_for_international_orders = Transition(label='Prepare documentation for international orders')
prepare_shipping_documents_and_labels = Transition(label='Prepare shipping documents and labels')
process_payment = Transition(label='Process payment')
process_refund = Transition(label='Process refund')
process_replacement = Transition(label='Process replacement')
receive_back_order = Transition(label='Receive back-order')
receive_returned_items = Transition(label='Receive returned items')
record_order_details = Transition(label='Record order details')
send_follow_up_email = Transition(label='Send follow-up email')
send_return_shipping_label = Transition(label='Send return shipping label')
send_shipping_confirmation_to_customer = Transition(label='Send shipping confirmation to customer')
update_inventory_levels = Transition(label='Update inventory levels')

# Define silent transitions
skip = SilentTransition()

# Define the POWL model
loop_check_stock_availability = OperatorPOWL(operator=Operator.LOOP, children=[check_stock_availability, gift_wrap_items, package_items, perform_quality_control_checks, pick_items_from_warehouse])
xor_confirm_delivery = OperatorPOWL(operator=Operator.XOR, children=[confirm_delivery, skip])
xor_process_payment = OperatorPOWL(operator=Operator.XOR, children=[process_payment, skip])
xor_process_refund = OperatorPOWL(operator=Operator.XOR, children=[process_refund, skip])
xor_process_replacement = OperatorPOWL(operator=Operator.XOR, children=[process_replacement, skip])
xor_receive_returned_items = OperatorPOWL(operator=Operator.XOR, children=[receive_returned_items, skip])
xor_send_follow_up_email = OperatorPOWL(operator=Operator.XOR, children=[send_follow_up_email, skip])
xor_send_return_shipping_label = OperatorPOWL(operator=Operator.XOR, children=[send_return_shipping_label, skip])
xor_send_shipping_confirmation_to_customer = OperatorPOWL(operator=Operator.XOR, children=[send_shipping_confirmation_to_customer, skip])
xor_update_inventory_levels = OperatorPOWL(operator=Operator.XOR, children=[update_inventory_levels, skip])

xor_initiate_back_order = OperatorPOWL(operator=Operator.XOR, children=[initiate_back_order, skip])
xor_receive_back_order = OperatorPOWL(operator=Operator.XOR, children=[receive_back_order, skip])
xor_inspect_returned_items = OperatorPOWL(operator=Operator.XOR, children=[inspect_returned_items, skip])

xor_send_shipping_documents_and_labels = OperatorPOWL(operator=Operator.XOR, children=[prepare_shipping_documents_and_labels, skip])
xor_prepare_documentation_for_international_orders = OperatorPOWL(operator=Operator.XOR, children=[prepare_documentation_for_international_orders, skip])

xor_notify_about_failed_payment = OperatorPOWL(operator=Operator.XOR, children=[notify_about_failed_payment, skip])

xor_customer_reports_issue = OperatorPOWL(operator=Operator.XOR, children=[customer_reports_issue, skip])

xor_place_order = OperatorPOWL(operator=Operator.XOR, children=[place_order, skip])

xor_record_order_details = OperatorPOWL(operator=Operator.XOR, children=[record_order_details, skip])

root = StrictPartialOrder(nodes=[xor_initiate_back_order, xor_receive_returned_items, xor_inspect_returned_items, xor_process_payment, xor_process_refund, xor_process_replacement, xor_send_shipping_documents_and_labels, xor_prepare_documentation_for_international_orders, xor_notify_about_failed_payment, xor_customer_reports_issue, xor_place_order, xor_record_order_details, loop_check_stock_availability, xor_confirm_delivery, xor_send_follow_up_email, xor_send_return_shipping_label, xor_send_shipping_confirmation_to_customer, xor_update_inventory_levels])
root.order.add_edge(loop_check_stock_availability, xor_confirm_delivery)
root.order.add_edge(loop_check_stock_availability, xor_process_payment)
root.order.add_edge(loop_check_stock_availability, xor_process_refund)
root.order.add_edge(loop_check_stock_availability, xor_process_replacement)
root.order.add_edge(loop_check_stock_availability, xor_send_shipping_documents_and_labels)
root.order.add_edge(loop_check_stock_availability, xor_prepare_documentation_for_international_orders)
root.order.add_edge(loop_check_stock_availability, xor_notify_about_failed_payment)
root.order.add_edge(loop_check_stock_availability, xor_customer_reports_issue)
root.order.add_edge(loop_check_stock_availability, xor_place_order)
root.order.add_edge(loop_check_stock_availability, xor_record_order_details)
root.order.add_edge(xor_initiate_back_order, xor_receive_returned_items)
root.order.add_edge(xor_initiate_back_order, xor_inspect_returned_items)
root.order.add_edge(xor_receive_returned_items, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_receive_returned_items, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_receive_returned_items, xor_notify_about_failed_payment)
root.order.add_edge(xor_receive_returned_items, xor_customer_reports_issue)
root.order.add_edge(xor_receive_returned_items, xor_place_order)
root.order.add_edge(xor_receive_returned_items, xor_record_order_details)
root.order.add_edge(xor_inspect_returned_items, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_inspect_returned_items, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_inspect_returned_items, xor_notify_about_failed_payment)
root.order.add_edge(xor_inspect_returned_items, xor_customer_reports_issue)
root.order.add_edge(xor_inspect_returned_items, xor_place_order)
root.order.add_edge(xor_inspect_returned_items, xor_record_order_details)
root.order.add_edge(xor_process_payment, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_process_payment, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_process_payment, xor_notify_about_failed_payment)
root.order.add_edge(xor_process_payment, xor_customer_reports_issue)
root.order.add_edge(xor_process_payment, xor_place_order)
root.order.add_edge(xor_process_payment, xor_record_order_details)
root.order.add_edge(xor_process_refund, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_process_refund, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_process_refund, xor_notify_about_failed_payment)
root.order.add_edge(xor_process_refund, xor_customer_reports_issue)
root.order.add_edge(xor_process_refund, xor_place_order)
root.order.add_edge(xor_process_refund, xor_record_order_details)
root.order.add_edge(xor_process_replacement, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_process_replacement, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_process_replacement, xor_notify_about_failed_payment)
root.order.add_edge(xor_process_replacement, xor_customer_reports_issue)
root.order.add_edge(xor_process_replacement, xor_place_order)
root.order.add_edge(xor_process_replacement, xor_record_order_details)
root.order.add_edge(xor_send_shipping_documents_and_labels, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_send_shipping_documents_and_labels, xor_notify_about_failed_payment)
root.order.add_edge(xor_send_shipping_documents_and_labels, xor_customer_reports_issue)
root.order.add_edge(xor_send_shipping_documents_and_labels, xor_place_order)
root.order.add_edge(xor_send_shipping_documents_and_labels, xor_record_order_details)
root.order.add_edge(xor_prepare_documentation_for_international_orders, xor_notify_about_failed_payment)
root.order.add_edge(xor_prepare_documentation_for_international_orders, xor_customer_reports_issue)
root.order.add_edge(xor_prepare_documentation_for_international_orders, xor_place_order)
root.order.add_edge(xor_prepare_documentation_for_international_orders, xor_record_order_details)
root.order.add_edge(xor_notify_about_failed_payment, xor_customer_reports_issue)
root.order.add_edge(xor_notify_about_failed_payment, xor_place_order)
root.order.add_edge(xor_notify_about_failed_payment, xor_record_order_details)
root.order.add_edge(xor_customer_reports_issue, xor_place_order)
root.order.add_edge(xor_customer_reports_issue, xor_record_order_details)
root.order.add_edge(xor_place_order, xor_record_order_details)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record_order_details, xor_notify_about_failed_payment)
root.order.add_edge(xor_record_order_details, xor_customer_reports_issue)
root.order.add_edge(xor_record_order_details, xor_place_order)
root.order.add_edge(xor_record_order_details, xor_send_shipping_documents_and_labels)
root.order.add_edge(xor_record_order_details, xor_prepare_documentation_for_international_orders)
root.order.add_edge(xor_record