import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator
# Define the activities
add_drop_courses = Transition(label='Add/drop courses')
assist_with_visa = Transition(label='Assist with visa processing')
await_decision = Transition(label='Await decision')
begin_attending_classes = Transition(label='Begin attending classes')
cancel_application = Transition(label='Cancel application')
confirm_enrollment = Transition(label='Confirm enrollment')
evaluate_application = Transition(label='Evaluate application by admissions committee')
graduate = Transition(label='Graduate')
meet_with_advisor = Transition(label='Meet with academic advisor')
meet_with_appeals = Transition(label='Meet with appeals committee')
notify_applicant = Transition(label='Notify applicant of missing documents')
obtain_id_card = Transition(label='Obtain student ID card')
post_grades = Transition(label='Post grades')
process_fees = Transition(label='Process fees or waivers')
provide_missing_documents = Transition(label='Provide missing documents')
resolve_schedule_conflicts = Transition(label='Resolve schedule conflicts')
review_application = Transition(label='Review application and documents')
review_grades = Transition(label='Review grades online')
select_courses = Transition(label='Select courses')
send_acceptance = Transition(label='Send acceptance letter')
send_orientation = Transition(label='Send orientation materials')
send_rejection = Transition(label='Send rejection letter')
setup_it = Transition(label='Set up IT accounts')
submit_appeal = Transition(label='Submit appeal form')
submit_application = Transition(label='Submit application online')
withdraw = Transition(label='Withdraw')

# Define the transitions
xor = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[cancel_application, withdraw])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[graduate, await_decision])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[graduate, await_decision])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor8 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor9 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor10 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor11 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor12 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor13 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor14 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor15 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor16 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor17 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor18 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor19 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor20 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor21 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor22 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor23 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor24 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor25 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor26 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor27 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor28 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor29 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor30 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor31 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor32 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor33 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor34 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor35 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor36 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor37 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor38 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor39 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor40 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor41 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor42 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor43 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor44 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor45 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor46 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor47 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor48 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor49 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor50 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor51 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor52 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor53 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor54 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor55 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor56 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor57 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor58 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor59 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor60 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor61 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor62 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor63 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor64 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor65 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor66 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor67 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor68 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor69 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor70 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor71 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor72 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor73 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor74 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor75 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor76 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor77 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor78 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor79 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor80 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor81 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor82 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor83 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor84 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor85 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor86 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor87 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor88 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor89 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor90 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor91 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor92 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor93 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor94 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor95 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor96 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor97 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor98 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor99 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor100 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor101 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor102 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor103 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor104 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor105 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor106 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor107 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor108 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor109 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor110 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor111 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor112 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor113 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor114 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor115 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor116 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor117 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor118 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor119 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor120 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor121 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor122 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor123 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor124 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor125 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor126 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor127 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor128 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor129 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor130 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor131 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor132 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor133 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor134 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor135 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor136 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor137 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor138 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor139 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor140 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor141 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor142 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor143 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor144 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor145 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor146 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor147 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor148 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor149 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor150 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor151 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor152 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor153 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor154 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor155 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor156 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor157 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor158 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor159 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor160 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor161 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor162 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor163 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor164 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor165 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor166 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor167 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor168 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor169 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor170 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor171 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor172 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor173 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor174 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor175 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor176 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor177 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor178 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor179 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor180 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor181 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor182 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor183 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor184 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor185 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor186 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor187 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor188 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor189 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor190 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor191 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor192 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor193 = OperatorPOWL(operator=Operator.XOR, children=[graduate, withdraw])
xor19