root = StrictPartialOrder(nodes=[Transition('Guest calls room service'), Transition('Kitchen prepares food'), Transition('Manager assigns order to waiter'), Transition('Manager gives order to sommelier'), Transition('Manager submits order ticket to kitchen'), Transition('Manager takes down the order'), Transition('Sommelier fetches wine and prepare alcoholic beverages'), Transition('Waiter debits guest\'s account'), Transition('Waiter delivers order to guest\'s room'), Transition('Waiter prepares nonalcoholic drinks'), Transition('Waiter readies cart'), Transition('Waiter returns to room-service station'), Transition('Waiter waits/delays debiting')])
root.order.add_edge(Transition('Guest calls room service'), Transition('Manager takes down the order'))
root.order.add_edge(Transition('Manager takes down the order'), Transition('Manager submits order ticket to kitchen'))
root.order.add_edge(Transition('Manager submits order ticket to kitchen'), Transition('Kitchen prepares food'))
root.order.add_edge(Transition('Manager takes down the order'), Transition('Manager gives order to sommelier'))
root.order.add_edge(Transition('Manager gives order to sommelier'), Transition('Sommelier fetches wine and prepare alcoholic beverages'))
root.order.add_edge(Transition('Manager takes down the order'), Transition('Manager assigns order to waiter'))
root.order.add_edge(Transition('Manager assigns order to waiter'), Transition('Waiter prepares nonalcoholic drinks'))
root.order.add_edge(Transition('Manager assigns order to waiter'), Transition('Waiter readies cart'))
root.order.add_edge(Transition('Kitchen prepares food'), Transition('Waiter delivers order to guest\'s room'))
root.order.add_edge(Transition('Sommelier fetches wine and prepare alcoholic beverages'), Transition('Waiter delivers order to guest\'s room'))
root.order.add_edge(Transition('Waiter delivers order to guest\'s room'), Transition('Waiter debits guest\'s account'))
root.order.add_edge(Transition('Waiter debits guest\'s account'), Transition('Waiter returns to room-service station'))
root.order.add_edge(Transition('Waiter returns to room-service station'), Transition('Waiter waits/delays debiting'))