import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_survey = Transition(label='Site Survey')
design_layout = Transition(label='Design Layout')
permits_check = Transition(label='Permits Check')
foundation_prep = Transition(label='Foundation Prep')
frame_assembly = Transition(label='Frame Assembly')
hydro_setup = Transition(label='Hydro Setup')
climate_setup = Transition(label='Climate Setup')
seed_selection = Transition(label='Seed Selection')
nutrient_mix = Transition(label='Nutrient Mix')
system_calibration = Transition(label='System Calibration')
pest_control = Transition(label='Pest Control')
automation_link = Transition(label='Automation Link')
staff_training = Transition(label='Staff Training')
yield_tracking = Transition(label='Yield Tracking')
distribution_plan = Transition(label='Distribution Plan')

skip = SilentTransition()
xor = OperatorPOWL(operator=Operator.XOR, children=[skip, seed_selection])
loop = OperatorPOWL(operator=Operator.LOOP, children=[hydro_setup, climate_setup, nutrient_mix, system_calibration, pest_control, automation_link])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[staff_training, yield_tracking])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[distribution_plan, xor2])
root = StrictPartialOrder(nodes=[site_survey, design_layout, permits_check, foundation_prep, frame_assembly, loop, xor3])
root.order.add_edge(site_survey, design_layout)
root.order.add_edge(design_layout, permits_check)
root.order.add_edge(permits_check, foundation_prep)
root.order.add_edge(foundation_prep, frame_assembly)
root.order.add_edge(frame_assembly, loop)
root.order.add_edge(loop, xor)
root.order.add_edge(xor, xor3)