import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_survey = Transition(label='Site Survey')
structural_audit = Transition(label='Structural Audit')
system_design = Transition(label='System Design')
permit_filing = Transition(label='Permit Filing')
foundation_prep = Transition(label='Foundation Prep')
frame_build = Transition(label='Frame Build')
irrigation_setup = Transition(label='Irrigation Setup')
lighting_install = Transition(label='Lighting Install')
climate_control = Transition(label='Climate Control')
nutrient_mix = Transition(label='Nutrient Mix')
crop_planting = Transition(label='Crop Planting')
pest_scouting = Transition(label='Pest Scouting')
data_monitoring = Transition(label='Data Monitoring')
waste_sorting = Transition(label='Waste Sorting')
energy_audit = Transition(label='Energy Audit')
community_meet = Transition(label='Community Meet')
yield_analysis = Transition(label='Yield Analysis')
skip = SilentTransition()

site_audit = OperatorPOWL(operator=Operator.XOR, children=[site_survey, structural_audit])
system_design_and_permit = OperatorPOWL(operator=Operator.XOR, children=[system_design, permit_filing])
foundation_prep_and_frame_build = OperatorPOWL(operator=Operator.XOR, children=[foundation_prep, frame_build])
irrigation_setup_and_lighting_install = OperatorPOWL(operator=Operator.XOR, children=[irrigation_setup, lighting_install])
climate_control_and_nutrient_mix = OperatorPOWL(operator=Operator.XOR, children=[climate_control, nutrient_mix])
crop_planting_and_pest_scouting = OperatorPOWL(operator=Operator.XOR, children=[crop_planting, pest_scouting])
data_monitoring_and_waste_sorting = OperatorPOWL(operator=Operator.XOR, children=[data_monitoring, waste_sorting])
energy_audit_and_community_meet = OperatorPOWL(operator=Operator.XOR, children=[energy_audit, community_meet])
yield_analysis_and_end = OperatorPOWL(operator=Operator.XOR, children=[yield_analysis, skip])

root = StrictPartialOrder(nodes=[site_audit, system_design_and_permit, foundation_prep_and_frame_build, irrigation_setup_and_lighting_install, climate_control_and_nutrient_mix, crop_planting_and_pest_scouting, data_monitoring_and_waste_sorting, energy_audit_and_community_meet, yield_analysis_and_end])
root.order.add_edge(site_audit, system_design_and_permit)
root.order.add_edge(system_design_and_permit, foundation_prep_and_frame_build)
root.order.add_edge(foundation_prep_and_frame_build, irrigation_setup_and_lighting_install)
root.order.add_edge(irrigation_setup_and_lighting_install, climate_control_and_nutrient_mix)
root.order.add_edge(climate_control_and_nutrient_mix, crop_planting_and_pest_scouting)
root.order.add_edge(crop_planting_and_pest_scouting, data_monitoring_and_waste_sorting)
root.order.add_edge(data_monitoring_and_waste_sorting, energy_audit_and_community_meet)
root.order.add_edge(energy_audit_and_community_meet, yield_analysis_and_end)

print(root)