import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

provenance_check = Transition(label='Provenance Check')
specimen_sampling = Transition(label='Specimen Sampling')
spectroscopy_test = Transition(label='Spectroscopy Test')
radiocarbon_date = Transition(label='Radiocarbon Date')
material_analysis = Transition(label='Material Analysis')
forensic_review = Transition(label='Forensic Review')
expert_consult = Transition(label='Expert Consult')
legal_verify = Transition(label='Legal Verify')
ownership_audit = Transition(label='Ownership Audit')
risk_assess = Transition(label='Risk Assess')
insurance_quote = Transition(label='Insurance Quote')
condition_report = Transition(label='Condition Report')
documentation = Transition(label='Documentation')
committee_review = Transition(label='Committee Review')
final_approval = Transition(label='Final Approval')

root = StrictPartialOrder(nodes=[
    provenance_check, specimen_sampling, spectroscopy_test, radiocarbon_date,
    material_analysis, forensic_review, expert_consult, legal_verify, ownership_audit,
    risk_assess, insurance_quote, condition_report, documentation, committee_review,
    final_approval
])

root.order.add_edge(provenance_check, specimen_sampling)
root.order.add_edge(provenance_check, spectroscopy_test)
root.order.add_edge(provenance_check, radiocarbon_date)
root.order.add_edge(provenance_check, material_analysis)
root.order.add_edge(provenance_check, forensic_review)
root.order.add_edge(provenance_check, expert_consult)
root.order.add_edge(provenance_check, legal_verify)
root.order.add_edge(provenance_check, ownership_audit)
root.order.add_edge(provenance_check, risk_assess)
root.order.add_edge(provenance_check, insurance_quote)
root.order.add_edge(provenance_check, condition_report)
root.order.add_edge(provenance_check, documentation)
root.order.add_edge(provenance_check, committee_review)
root.order.add_edge(provenance_check, final_approval)

root.order.add_edge(specimen_sampling, spectroscopy_test)
root.order.add_edge(specimen_sampling, radiocarbon_date)
root.order.add_edge(specimen_sampling, material_analysis)
root.order.add_edge(specimen_sampling, forensic_review)
root.order.add_edge(specimen_sampling, expert_consult)
root.order.add_edge(specimen_sampling, legal_verify)
root.order.add_edge(specimen_sampling, ownership_audit)
root.order.add_edge(specimen_sampling, risk_assess)
root.order.add_edge(specimen_sampling, insurance_quote)
root.order.add_edge(specimen_sampling, condition_report)
root.order.add_edge(specimen_sampling, documentation)
root.order.add_edge(specimen_sampling, committee_review)
root.order.add_edge(specimen_sampling, final_approval)

root.order.add_edge(spectroscopy_test, radiocarbon_date)
root.order.add_edge(spectroscopy_test, material_analysis)
root.order.add_edge(spectroscopy_test, forensic_review)
root.order.add_edge(spectroscopy_test, expert_consult)
root.order.add_edge(spectroscopy_test, legal_verify)
root.order.add_edge(spectroscopy_test, ownership_audit)
root.order.add_edge(spectroscopy_test, risk_assess)
root.order.add_edge(spectroscopy_test, insurance_quote)
root.order.add_edge(spectroscopy_test, condition_report)
root.order.add_edge(spectroscopy_test, documentation)
root.order.add_edge(spectroscopy_test, committee_review)
root.order.add_edge(spectroscopy_test, final_approval)

root.order.add_edge(radiocarbon_date, material_analysis)
root.order.add_edge(radiocarbon_date, forensic_review)
root.order.add_edge(radiocarbon_date, expert_consult)
root.order.add_edge(radiocarbon_date, legal_verify)
root.order.add_edge(radiocarbon_date, ownership_audit)
root.order.add_edge(radiocarbon_date, risk_assess)
root.order.add_edge(radiocarbon_date, insurance_quote)
root.order.add_edge(radiocarbon_date, condition_report)
root.order.add_edge(radiocarbon_date, documentation)
root.order.add_edge(radiocarbon_date, committee_review)
root.order.add_edge(radiocarbon_date, final_approval)

root.order.add_edge(material_analysis, forensic_review)
root.order.add_edge(material_analysis, expert_consult)
root.order.add_edge(material_analysis, legal_verify)
root.order.add_edge(material_analysis, ownership_audit)
root.order.add_edge(material_analysis, risk_assess)
root.order.add_edge(material_analysis, insurance_quote)
root.order.add_edge(material_analysis, condition_report)
root.order.add_edge(material_analysis, documentation)
root.order.add_edge(material_analysis, committee_review)
root.order.add_edge(material_analysis, final_approval)

root.order.add_edge(forensic_review, expert_consult)
root.order.add_edge(forensic_review, legal_verify)
root.order.add_edge(forensic_review, ownership_audit)
root.order.add_edge(forensic_review, risk_assess)
root.order.add_edge(forensic_review, insurance_quote)
root.order.add_edge(forensic_review, condition_report)
root.order.add_edge(forensic_review, documentation)
root.order.add_edge(forensic_review, committee_review)
root.order.add_edge(forensic_review, final_approval)

root.order.add_edge(expert_consult, legal_verify)
root.order.add_edge(expert_consult, ownership_audit)
root.order.add_edge(expert_consult, risk_assess)
root.order.add_edge(expert_consult, insurance_quote)
root.order.add_edge(expert_consult, condition_report)
root.order.add_edge(expert_consult, documentation)
root.order.add_edge(expert_consult, committee_review)
root.order.add_edge(expert_consult, final_approval)

root.order.add_edge(legal_verify, ownership_audit)
root.order.add_edge(legal_verify, risk_assess)
root.order.add_edge(legal_verify, insurance_quote)
root.order.add_edge(legal_verify, condition_report)
root.order.add_edge(legal_verify, documentation)
root.order.add_edge(legal_verify, committee_review)
root.order.add_edge(legal_verify, final_approval)

root.order.add_edge(ownership_audit, risk_assess)
root.order.add_edge(ownership_audit, insurance_quote)
root.order.add_edge(ownership_audit, condition_report)
root.order.add_edge(ownership_audit, documentation)
root.order.add_edge(ownership_audit, committee_review)
root.order.add_edge(ownership_audit, final_approval)

root.order.add_edge(risk_assess, insurance_quote)
root.order.add_edge(risk_assess, condition_report)
root.order.add_edge(risk_assess, documentation)
root.order.add_edge(risk_assess, committee_review)
root.order.add_edge(risk_assess, final_approval)

root.order.add_edge(insurance_quote, condition_report)
root.order.add_edge(insurance_quote, documentation)
root.order.add_edge(insurance_quote, committee_review)
root.order.add_edge(insurance_quote, final_approval)

root.order.add_edge(condition_report, documentation)
root.order.add_edge(condition_report, committee_review)
root.order.add_edge(condition_report, final_approval)

root.order.add_edge(documentation, committee_review)
root.order.add_edge(documentation, final_approval)

root.order.add_edge(committee_review, final_approval)