import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define the POWL model for the process
demand_forecast = Transition(label='Demand Forecast')
courier_match = Transition(label='Courier Match')
credential_check = Transition(label='Credential Check')
route_design = Transition(label='Route Design')
load_assign = Transition(label='Load Assign')
traffic_scan = Transition(label='Traffic Scan')
package_secure = Transition(label='Package Secure')
dispatch_alert = Transition(label='Dispatch Alert')
real_time_track = Transition(label='Real-time Track')
incentive_issue = Transition(label='Incentive Issue')
dispute_review = Transition(label='Dispute Review')
customer_notify = Transition(label='Customer Notify')
feedback_collect = Transition(label='Feedback Collect')
performance_log = Transition(label='Performance Log')
ledger_update = Transition(label='Ledger Update')
hub_sync = Transition(label='Hub Sync')

# Define the process tree
demand_forecast_to_courier_match = OperatorPOWL(operator=Operator.XOR, children=[demand_forecast, courier_match])
courier_match_to_credential_check = OperatorPOWL(operator=Operator.XOR, children=[courier_match, credential_check])
credential_check_to_route_design = OperatorPOWL(operator=Operator.XOR, children=[credential_check, route_design])
route_design_to_load_assign = OperatorPOWL(operator=Operator.XOR, children=[route_design, load_assign])
load_assign_to_traffic_scan = OperatorPOWL(operator=Operator.XOR, children=[load_assign, traffic_scan])
traffic_scan_to_package_secure = OperatorPOWL(operator=Operator.XOR, children=[traffic_scan, package_secure])
package_secure_to_dispatch_alert = OperatorPOWL(operator=Operator.XOR, children=[package_secure, dispatch_alert])
dispatch_alert_to_real_time_track = OperatorPOWL(operator=Operator.XOR, children=[dispatch_alert, real_time_track])
real_time_track_to_incentive_issue = OperatorPOWL(operator=Operator.XOR, children=[real_time_track, incentive_issue])
incentive_issue_to_dispute_review = OperatorPOWL(operator=Operator.XOR, children=[incentive_issue, dispute_review])
dispute_review_to_customer_notify = OperatorPOWL(operator=Operator.XOR, children=[dispute_review, customer_notify])
customer_notify_to_feedback_collect = OperatorPOWL(operator=Operator.XOR, children=[customer_notify, feedback_collect])
feedback_collect_to_performance_log = OperatorPOWL(operator=Operator.XOR, children=[feedback_collect, performance_log])
performance_log_to_ledger_update = OperatorPOWL(operator=Operator.XOR, children=[performance_log, ledger_update])
ledger_update_to_hub_sync = OperatorPOWL(operator=Operator.XOR, children=[ledger_update, hub_sync])

# Define the partial order
root = StrictPartialOrder(nodes=[demand_forecast_to_courier_match, courier_match_to_credential_check, credential_check_to_route_design, route_design_to_load_assign, load_assign_to_traffic_scan, traffic_scan_to_package_secure, package_secure_to_dispatch_alert, dispatch_alert_to_real_time_track, real_time_track_to_incentive_issue, incentive_issue_to_dispute_review, dispute_review_to_customer_notify, customer_notify_to_feedback_collect, feedback_collect_to_performance_log, performance_log_to_ledger_update, ledger_update_to_hub_sync])
root.order.add_edge(demand_forecast_to_courier_match, courier_match_to_credential_check)
root.order.add_edge(courier_match_to_credential_check, credential_check_to_route_design)
root.order.add_edge(credential_check_to_route_design, route_design_to_load_assign)
root.order.add_edge(route_design_to_load_assign, load_assign_to_traffic_scan)
root.order.add_edge(load_assign_to_traffic_scan, traffic_scan_to_package_secure)
root.order.add_edge(traffic_scan_to_package_secure, package_secure_to_dispatch_alert)
root.order.add_edge(package_secure_to_dispatch_alert, dispatch_alert_to_real_time_track)
root.order.add_edge(dispatch_alert_to_real_time_track, real_time_track_to_incentive_issue)
root.order.add_edge(real_time_track_to_incentive_issue, incentive_issue_to_dispute_review)
root.order.add_edge(incentive_issue_to_dispute_review, dispute_review_to_customer_notify)
root.order.add_edge(dispute_review_to_customer_notify, customer_notify_to_feedback_collect)
root.order.add_edge(customer_notify_to_feedback_collect, feedback_collect_to_performance_log)
root.order.add_edge(feedback_collect_to_performance_log, performance_log_to_ledger_update)
root.order.add_edge(performance_log_to_ledger_update, ledger_update_to_hub_sync)