import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_survey = Transition(label='Site Survey')
design_layout = Transition(label='Design Layout')
system_assembly = Transition(label='System Assembly')
climate_setup = Transition(label='Climate Setup')
light_calibration = Transition(label='Light Calibration')
seed_selection = Transition(label='Seed Selection')
seedling_prep = Transition(label='Seedling Prep')
nutrient_mix = Transition(label='Nutrient Mix')
irrigation_setup = Transition(label='Irrigation Setup')
sensor_install = Transition(label='Sensor Install')
data_integration = Transition(label='Data Integration')
waste_routing = Transition(label='Waste Routing')
energy_audit = Transition(label='Energy Audit')
regulation_check = Transition(label='Regulation Check')
operational_test = Transition(label='Operational Test')
community_outreach = Transition(label='Community Outreach')

skip = SilentTransition()

# Process setup
site_survey_order = OperatorPOWL(operator=Operator.SOURCE, children=[design_layout])
design_layout_order = OperatorPOWL(operator=Operator.SOURCE, children=[system_assembly])
system_assembly_order = OperatorPOWL(operator=Operator.SOURCE, children=[climate_setup])
climate_setup_order = OperatorPOWL(operator=Operator.SOURCE, children=[light_calibration])
light_calibration_order = OperatorPOWL(operator=Operator.SOURCE, children=[seed_selection])
seed_selection_order = OperatorPOWL(operator=Operator.SOURCE, children=[seedling_prep])
seedling_prep_order = OperatorPOWL(operator=Operator.SOURCE, children=[nutrient_mix])
nutrient_mix_order = OperatorPOWL(operator=Operator.SOURCE, children=[irrigation_setup])
irrigation_setup_order = OperatorPOWL(operator=Operator.SOURCE, children=[sensor_install])
sensor_install_order = OperatorPOWL(operator=Operator.SOURCE, children=[data_integration])
data_integration_order = OperatorPOWL(operator=Operator.SOURCE, children=[waste_routing])
waste_routing_order = OperatorPOWL(operator=Operator.SOURCE, children=[energy_audit])
energy_audit_order = OperatorPOWL(operator=Operator.SOURCE, children=[regulation_check])
regulation_check_order = OperatorPOWL(operator=Operator.SOURCE, children=[operational_test])
operational_test_order = OperatorPOWL(operator=Operator.SOURCE, children=[community_outreach])

# Loops and choices
loop_1 = OperatorPOWL(operator=Operator.LOOP, children=[site_survey, design_layout, system_assembly, climate_setup, light_calibration, seed_selection, seedling_prep, nutrient_mix, irrigation_setup, sensor_install, data_integration, waste_routing, energy_audit, regulation_check, operational_test, community_outreach])

root = StrictPartialOrder(nodes=[site_survey_order, design_layout_order, system_assembly_order, climate_setup_order, light_calibration_order, seed_selection_order, seedling_prep_order, nutrient_mix_order, irrigation_setup_order, sensor_install_order, data_integration_order, waste_routing_order, energy_audit_order, regulation_check_order, operational_test_order, community_outreach_order, loop_1])
root.order.add_edge(site_survey_order, design_layout_order)
root.order.add_edge(design_layout_order, system_assembly_order)
root.order.add_edge(system_assembly_order, climate_setup_order)
root.order.add_edge(climate_setup_order, light_calibration_order)
root.order.add_edge(light_calibration_order, seed_selection_order)
root.order.add_edge(seed_selection_order, seedling_prep_order)
root.order.add_edge(seedling_prep_order, nutrient_mix_order)
root.order.add_edge(nutrient_mix_order, irrigation_setup_order)
root.order.add_edge(irrigation_setup_order, sensor_install_order)
root.order.add_edge(sensor_install_order, data_integration_order)
root.order.add_edge(data_integration_order, waste_routing_order)
root.order.add_edge(waste_routing_order, energy_audit_order)
root.order.add_edge(energy_audit_order, regulation_check_order)
root.order.add_edge(regulation_check_order, operational_test_order)
root.order.add_edge(operational_test_order, community_outreach_order)
root.order.add_edge(loop_1, site_survey_order)
root.order.add_edge(loop_1, design_layout_order)
root.order.add_edge(loop_1, system_assembly_order)
root.order.add_edge(loop_1, climate_setup_order)
root.order.add_edge(loop_1, light_calibration_order)
root.order.add_edge(loop_1, seed_selection_order)
root.order.add_edge(loop_1, seedling_prep_order)
root.order.add_edge(loop_1, nutrient_mix_order)
root.order.add_edge(loop_1, irrigation_setup_order)
root.order.add_edge(loop_1, sensor_install_order)
root.order.add_edge(loop_1, data_integration_order)
root.order.add_edge(loop_1, waste_routing_order)
root.order.add_edge(loop_1, energy_audit_order)
root.order.add_edge(loop_1, regulation_check_order)
root.order.add_edge(loop_1, operational_test_order)
root.order.add_edge(loop_1, community_outreach_order)