import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_assess = Transition(label='Site Assess')
plan_layout = Transition(label='Plan Layout')
install_racks = Transition(label='Install Racks')
mix_nutrients = Transition(label='Mix Nutrients')
calibrate_sensors = Transition(label='Calibrate Sensors')
setup_lighting = Transition(label='Setup Lighting')
configure_climate = Transition(label='Configure Climate')
select_seeds = Transition(label='Select Seeds')
monitor_germinate = Transition(label='Monitor Germinate')
apply_bio_controls = Transition(label='Apply Bio-controls')
maintain_systems = Transition(label='Maintain Systems')
analyze_data = Transition(label='Analyze Data')
harvest_crops = Transition(label='Harvest Crops')
quality_check = Transition(label='Quality Check')
package_produce = Transition(label='Package Produce')
distribute_goods = Transition(label='Distribute Goods')

skip = SilentTransition()

site_assess_plan_layout = OperatorPOWL(operator=Operator.XOR, children=[site_assess, plan_layout])
install_racks_mix_nutrients = OperatorPOWL(operator=Operator.XOR, children=[install_racks, mix_nutrients])
calibrate_sensors_setup_lighting = OperatorPOWL(operator=Operator.XOR, children=[calibrate_sensors, setup_lighting])
configure_climate_select_seeds = OperatorPOWL(operator=Operator.XOR, children=[configure_climate, select_seeds])
monitor_germinate_apply_bio_controls = OperatorPOWL(operator=Operator.XOR, children=[monitor_germinate, apply_bio_controls])
maintain_systems_analyze_data = OperatorPOWL(operator=Operator.XOR, children=[maintain_systems, analyze_data])
harvest_crops_quality_check = OperatorPOWL(operator=Operator.XOR, children=[harvest_crops, quality_check])
package_produce_distribute_goods = OperatorPOWL(operator=Operator.XOR, children=[package_produce, distribute_goods])

root = StrictPartialOrder(nodes=[site_assess_plan_layout, install_racks_mix_nutrients, calibrate_sensors_setup_lighting, configure_climate_select_seeds, monitor_germinate_apply_bio_controls, maintain_systems_analyze_data, harvest_crops_quality_check, package_produce_distribute_goods])
root.order.add_edge(site_assess_plan_layout, install_racks_mix_nutrients)
root.order.add_edge(site_assess_plan_layout, calibrate_sensors_setup_lighting)
root.order.add_edge(install_racks_mix_nutrients, configure_climate_select_seeds)
root.order.add_edge(calibrate_sensors_setup_lighting, monitor_germinate_apply_bio_controls)
root.order.add_edge(configure_climate_select_seeds, maintain_systems_analyze_data)
root.order.add_edge(monitor_germinate_apply_bio_controls, harvest_crops_quality_check)
root.order.add_edge(maintain_systems_analyze_data, package_produce_distribute_goods)