import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

# Define the activities
site_survey = Transition(label='Site Survey')
impact_study = Transition(label='Impact Study')
structure_check = Transition(label='Structure Check')
soil_testing = Transition(label='Soil Testing')
system_design = Transition(label='System Design')
seed_selection = Transition(label='Seed Selection')
irrigation_setup = Transition(label='Irrigation Setup')
lighting_install = Transition(label='Lighting Install')
pest_control = Transition(label='Pest Control')
community_meet = Transition(label='Community Meet')
regulation_review = Transition(label='Regulation Review')
waste_plan = Transition(label='Waste Plan')
crop_monitor = Transition(label='Crop Monitor')
harvest_prep = Transition(label='Harvest Prep')
market_launch = Transition(label='Market Launch')

# Define the process
root = StrictPartialOrder(nodes=[
    site_survey, impact_study, structure_check, soil_testing, system_design,
    seed_selection, irrigation_setup, lighting_install, pest_control,
    community_meet, regulation_review, waste_plan, crop_monitor, harvest_prep,
    market_launch
])

# Define the order
root.order.add_edge(site_survey, impact_study)
root.order.add_edge(site_survey, structure_check)
root.order.add_edge(site_survey, soil_testing)
root.order.add_edge(site_survey, system_design)
root.order.add_edge(site_survey, seed_selection)
root.order.add_edge(site_survey, irrigation_setup)
root.order.add_edge(site_survey, lighting_install)
root.order.add_edge(site_survey, pest_control)
root.order.add_edge(site_survey, community_meet)
root.order.add_edge(site_survey, regulation_review)
root.order.add_edge(site_survey, waste_plan)
root.order.add_edge(site_survey, crop_monitor)
root.order.add_edge(site_survey, harvest_prep)
root.order.add_edge(site_survey, market_launch)

root.order.add_edge(impact_study, structure_check)
root.order.add_edge(impact_study, soil_testing)
root.order.add_edge(impact_study, system_design)
root.order.add_edge(impact_study, seed_selection)
root.order.add_edge(impact_study, irrigation_setup)
root.order.add_edge(impact_study, lighting_install)
root.order.add_edge(impact_study, pest_control)
root.order.add_edge(impact_study, community_meet)
root.order.add_edge(impact_study, regulation_review)
root.order.add_edge(impact_study, waste_plan)
root.order.add_edge(impact_study, crop_monitor)
root.order.add_edge(impact_study, harvest_prep)
root.order.add_edge(impact_study, market_launch)

root.order.add_edge(structure_check, soil_testing)
root.order.add_edge(structure_check, system_design)
root.order.add_edge(structure_check, seed_selection)
root.order.add_edge(structure_check, irrigation_setup)
root.order.add_edge(structure_check, lighting_install)
root.order.add_edge(structure_check, pest_control)
root.order.add_edge(structure_check, community_meet)
root.order.add_edge(structure_check, regulation_review)
root.order.add_edge(structure_check, waste_plan)
root.order.add_edge(structure_check, crop_monitor)
root.order.add_edge(structure_check, harvest_prep)
root.order.add_edge(structure_check, market_launch)

root.order.add_edge(soil_testing, system_design)
root.order.add_edge(soil_testing, seed_selection)
root.order.add_edge(soil_testing, irrigation_setup)
root.order.add_edge(soil_testing, lighting_install)
root.order.add_edge(soil_testing, pest_control)
root.order.add_edge(soil_testing, community_meet)
root.order.add_edge(soil_testing, regulation_review)
root.order.add_edge(soil_testing, waste_plan)
root.order.add_edge(soil_testing, crop_monitor)
root.order.add_edge(soil_testing, harvest_prep)
root.order.add_edge(soil_testing, market_launch)

root.order.add_edge(system_design, seed_selection)
root.order.add_edge(system_design, irrigation_setup)
root.order.add_edge(system_design, lighting_install)
root.order.add_edge(system_design, pest_control)
root.order.add_edge(system_design, community_meet)
root.order.add_edge(system_design, regulation_review)
root.order.add_edge(system_design, waste_plan)
root.order.add_edge(system_design, crop_monitor)
root.order.add_edge(system_design, harvest_prep)
root.order.add_edge(system_design, market_launch)

root.order.add_edge(seed_selection, irrigation_setup)
root.order.add_edge(seed_selection, lighting_install)
root.order.add_edge(seed_selection, pest_control)
root.order.add_edge(seed_selection, community_meet)
root.order.add_edge(seed_selection, regulation_review)
root.order.add_edge(seed_selection, waste_plan)
root.order.add_edge(seed_selection, crop_monitor)
root.order.add_edge(seed_selection, harvest_prep)
root.order.add_edge(seed_selection, market_launch)

root.order.add_edge(irrigation_setup, lighting_install)
root.order.add_edge(irrigation_setup, pest_control)
root.order.add_edge(irrigation_setup, community_meet)
root.order.add_edge(irrigation_setup, regulation_review)
root.order.add_edge(irrigation_setup, waste_plan)
root.order.add_edge(irrigation_setup, crop_monitor)
root.order.add_edge(irrigation_setup, harvest_prep)
root.order.add_edge(irrigation_setup, market_launch)

root.order.add_edge(lighting_install, pest_control)
root.order.add_edge(lighting_install, community_meet)
root.order.add_edge(lighting_install, regulation_review)
root.order.add_edge(lighting_install, waste_plan)
root.order.add_edge(lighting_install, crop_monitor)
root.order.add_edge(lighting_install, harvest_prep)
root.order.add_edge(lighting_install, market_launch)

root.order.add_edge(pest_control, community_meet)
root.order.add_edge(pest_control, regulation_review)
root.order.add_edge(pest_control, waste_plan)
root.order.add_edge(pest_control, crop_monitor)
root.order.add_edge(pest_control, harvest_prep)
root.order.add_edge(pest_control, market_launch)

root.order.add_edge(community_meet, regulation_review)
root.order.add_edge(community_meet, waste_plan)
root.order.add_edge(community_meet, crop_monitor)
root.order.add_edge(community_meet, harvest_prep)
root.order.add_edge(community_meet, market_launch)

root.order.add_edge(regulation_review, waste_plan)
root.order.add_edge(regulation_review, crop_monitor)
root.order.add_edge(regulation_review, harvest_prep)
root.order.add_edge(regulation_review, market_launch)

root.order.add_edge(waste_plan, crop_monitor)
root.order.add_edge(waste_plan, harvest_prep)
root.order.add_edge(waste_plan, market_launch)

root.order.add_edge(crop_monitor, harvest_prep)
root.order.add_edge(crop_monitor, market_launch)

root.order.add_edge(harvest_prep, market_launch)