from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_analysis = Transition(label='Site Analysis')
structure_check = Transition(label='Structure Check')
farm_design = Transition(label='Farm Design')
env_control = Transition(label='Env Control')
nutrient_prep = Transition(label='Nutrient Prep')
seed_selection = Transition(label='Seed Selection')
automated_plant = Transition(label='Automated Plant')
sensor_setup = Transition(label='Sensor Setup')
microclimate_mon = Transition(label='Microclimate Mon')
health_monitor = Transition(label='Health Monitor')
light_adjust = Transition(label='Light Adjust')
irrigation_mod = Transition(label='Irrigation Mod')
waste_recycle = Transition(label='Waste Recycle')
energy_optimize = Transition(label='Energy Optimize')
quality_check = Transition(label='Quality Check')
crop_harvest = Transition(label='Crop Harvest')
distribution_plan = Transition(label='Distribution Plan')

skip = SilentTransition()

site_analysis_env_control = OperatorPOWL(operator=Operator.XOR, children=[site_analysis, env_control])
env_control_farm_design = OperatorPOWL(operator=Operator.XOR, children=[env_control, farm_design])
farm_design_nutrient_prep = OperatorPOWL(operator=Operator.XOR, children=[farm_design, nutrient_prep])
nutrient_prep_seed_selection = OperatorPOWL(operator=Operator.XOR, children=[nutrient_prep, seed_selection])
seed_selection_automated_plant = OperatorPOWL(operator=Operator.XOR, children=[seed_selection, automated_plant])
automated_plant_sensor_setup = OperatorPOWL(operator=Operator.XOR, children=[automated_plant, sensor_setup])
sensor_setup_microclimate_mon = OperatorPOWL(operator=Operator.XOR, children=[sensor_setup, microclimate_mon])
microclimate_mon_health_monitor = OperatorPOWL(operator=Operator.XOR, children=[microclimate_mon, health_monitor])
health_monitor_light_adjust = OperatorPOWL(operator=Operator.XOR, children=[health_monitor, light_adjust])
light_adjust_irrigation_mod = OperatorPOWL(operator=Operator.XOR, children=[light_adjust, irrigation_mod])
irrigation_mod_waste_recycle = OperatorPOWL(operator=Operator.XOR, children=[irrigation_mod, waste_recycle])
waste_recycle_energy_optimize = OperatorPOWL(operator=Operator.XOR, children=[waste_recycle, energy_optimize])
energy_optimize_quality_check = OperatorPOWL(operator=Operator.XOR, children=[energy_optimize, quality_check])
quality_check_crop_harvest = OperatorPOWL(operator=Operator.XOR, children=[quality_check, crop_harvest])
crop_harvest_distribution_plan = OperatorPOWL(operator=Operator.XOR, children=[crop_harvest, distribution_plan])

root = StrictPartialOrder(nodes=[
    site_analysis, structure_check, farm_design, env_control, nutrient_prep, seed_selection, automated_plant, sensor_setup, microclimate_mon, health_monitor, light_adjust, irrigation_mod, waste_recycle, energy_optimize, quality_check, crop_harvest, distribution_plan
])

root.order.add_edge(site_analysis, site_analysis_env_control)
root.order.add_edge(site_analysis_env_control, env_control_farm_design)
root.order.add_edge(env_control_farm_design, farm_design_nutrient_prep)
root.order.add_edge(farm_design_nutrient_prep, nutrient_prep_seed_selection)
root.order.add_edge(nutrient_prep_seed_selection, seed_selection_automated_plant)
root.order.add_edge(seed_selection_automated_plant, automated_plant_sensor_setup)
root.order.add_edge(automated_plant_sensor_setup, sensor_setup_microclimate_mon)
root.order.add_edge(sensor_setup_microclimate_mon, microclimate_mon_health_monitor)
root.order.add_edge(microclimate_mon_health_monitor, health_monitor_light_adjust)
root.order.add_edge(health_monitor_light_adjust, light_adjust_irrigation_mod)
root.order.add_edge(light_adjust_irrigation_mod, irrigation_mod_waste_recycle)
root.order.add_edge(irrigation_mod_waste_recycle, waste_recycle_energy_optimize)
root.order.add_edge(waste_recycle_energy_optimize, energy_optimize_quality_check)
root.order.add_edge(energy_optimize_quality_check, quality_check_crop_harvest)
root.order.add_edge(quality_check_crop_harvest, crop_harvest_distribution_plan)