import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

site_analysis = Transition(label='Site Analysis')
structure_check = Transition(label='Structure Check')
modify_layout = Transition(label='Modify Layout')
install_hvac = Transition(label='Install HVAC')
setup_hydroponics = Transition(label='Setup Hydroponics')
prepare_nutrients = Transition(label='Prepare Nutrients')
select_seeds = Transition(label='Select Seeds')
automate_planting = Transition(label='Automate Planting')
deploy_sensors = Transition(label='Deploy Sensors')
pest_control = Transition(label='Pest Control')
optimize_energy = Transition(label='Optimize Energy')
recycle_water = Transition(label='Recycle Water')
automate_harvest = Transition(label='Automate Harvest')
package_crops = Transition(label='Package Crops')
coordinate_delivery = Transition(label='Coordinate Delivery')
analyze_data = Transition(label='Analyze Data')

skip = SilentTransition()

site_analysis_and_structure_check = OperatorPOWL(operator=Operator.XOR, children=[site_analysis, structure_check])
modify_layout_and_install_hvac = OperatorPOWL(operator=Operator.XOR, children=[modify_layout, install_hvac])
setup_hydroponics_and_prepare_nutrients = OperatorPOWL(operator=Operator.XOR, children=[setup_hydroponics, prepare_nutrients])
select_seeds_and_automate_planting = OperatorPOWL(operator=Operator.XOR, children=[select_seeds, automate_planting])
deploy_sensors_and_pest_control = OperatorPOWL(operator=Operator.XOR, children=[deploy_sensors, pest_control])
optimize_energy_and_recycle_water = OperatorPOWL(operator=Operator.XOR, children=[optimize_energy, recycle_water])
automate_harvest_and_package_crops = OperatorPOWL(operator=Operator.XOR, children=[automate_harvest, package_crops])
coordinate_delivery_and_analyze_data = OperatorPOWL(operator=Operator.XOR, children=[coordinate_delivery, analyze_data])

root = StrictPartialOrder(nodes=[site_analysis_and_structure_check, modify_layout_and_install_hvac, setup_hydroponics_and_prepare_nutrients, select_seeds_and_automate_planting, deploy_sensors_and_pest_control, optimize_energy_and_recycle_water, automate_harvest_and_package_crops, coordinate_delivery_and_analyze_data])
root.order.add_edge(site_analysis_and_structure_check, modify_layout_and_install_hvac)
root.order.add_edge(modify_layout_and_install_hvac, setup_hydroponics_and_prepare_nutrients)
root.order.add_edge(setup_hydroponics_and_prepare_nutrients, select_seeds_and_automate_planting)
root.order.add_edge(select_seeds_and_automate_planting, deploy_sensors_and_pest_control)
root.order.add_edge(deploy_sensors_and_pest_control, optimize_energy_and_recycle_water)
root.order.add_edge(optimize_energy_and_recycle_water, automate_harvest_and_package_crops)
root.order.add_edge(automate_harvest_and_package_crops, coordinate_delivery_and_analyze_data)