import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

seed_selection = Transition(label='Seed Selection')
nutrient_setup = Transition(label='Nutrient Setup')
growth_monitoring = Transition(label='Growth Monitoring')
climate_adjust = Transition(label='Climate Adjust')
pest_control = Transition(label='Pest Control')
water_recirculate = Transition(label='Water Recirculate')
light_calibration = Transition(label='Light Calibration')
robotic_harvest = Transition(label='Robotic Harvest')
quality_inspect = Transition(label='Quality Inspect')
waste_process = Transition(label='Waste Process')
energy_reuse = Transition(label='Energy Reuse')
inventory_update = Transition(label='Inventory Update')
demand_forecast = Transition(label='Demand Forecast')
order_dispatch = Transition(label='Order Dispatch')
community_event = Transition(label='Community Event')
feedback_collect = Transition(label='Feedback Collect')
data_analyze = Transition(label='Data Analyze')

skip = SilentTransition()
loop = OperatorPOWL(operator=Operator.LOOP, children=[seed_selection, nutrient_setup])
xor1 = OperatorPOWL(operator=Operator.XOR, children=[growth_monitoring, climate_adjust])
xor2 = OperatorPOWL(operator=Operator.XOR, children=[pest_control, water_recirculate])
xor3 = OperatorPOWL(operator=Operator.XOR, children=[light_calibration, robotic_harvest])
xor4 = OperatorPOWL(operator=Operator.XOR, children=[quality_inspect, waste_process])
xor5 = OperatorPOWL(operator=Operator.XOR, children=[energy_reuse, inventory_update])
xor6 = OperatorPOWL(operator=Operator.XOR, children=[demand_forecast, order_dispatch])
xor7 = OperatorPOWL(operator=Operator.XOR, children=[community_event, feedback_collect])
xor8 = OperatorPOWL(operator=Operator.XOR, children=[data_analyze, skip])

root = StrictPartialOrder(nodes=[loop, xor1, xor2, xor3, xor4, xor5, xor6, xor7, xor8])
root.order.add_edge(loop, xor1)
root.order.add_edge(xor1, xor2)
root.order.add_edge(xor2, xor3)
root.order.add_edge(xor3, xor4)
root.order.add_edge(xor4, xor5)
root.order.add_edge(xor5, xor6)
root.order.add_edge(xor6, xor7)
root.order.add_edge(xor7, xor8)