from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

demand_forecast = Transition(label='Demand Forecast')
courier_match = Transition(label='Courier Match')
credential_check = Transition(label='Credential Check')
route_design = Transition(label='Route Design')
load_assign = Transition(label='Load Assign')
traffic_scan = Transition(label='Traffic Scan')
package_secure = Transition(label='Package Secure')
dispatch_alert = Transition(label='Dispatch Alert')
real_time_track = Transition(label='Real-time Track')
incentive_issue = Transition(label='Incentive Issue')
dispute_review = Transition(label='Dispute Review')
customer_notify = Transition(label='Customer Notify')
feedback_collect = Transition(label='Feedback Collect')
performance_log = Transition(label='Performance Log')
ledger_update = Transition(label='Ledger Update')
hub_sync = Transition(label='Hub Sync')

skip = SilentTransition()

demand_forecast_choice = OperatorPOWL(operator=Operator.XOR, children=[credential_check, skip])
credential_check_loop = OperatorPOWL(operator=Operator.LOOP, children=[route_design, load_assign, traffic_scan, package_secure, dispatch_alert, real_time_track, incentive_issue])
route_design_choice = OperatorPOWL(operator=Operator.XOR, children=[dispute_review, customer_notify])
dispute_review_loop = OperatorPOWL(operator=Operator.LOOP, children=[feedback_collect, performance_log, ledger_update, hub_sync])

root = StrictPartialOrder(nodes=[demand_forecast, courier_match, demand_forecast_choice, credential_check_loop, route_design_choice, dispute_review_loop])
root.order.add_edge(demand_forecast, courier_match)
root.order.add_edge(demand_forecast, demand_forecast_choice)
root.order.add_edge(courier_match, demand_forecast_choice)
root.order.add_edge(demand_forecast_choice, credential_check_loop)
root.order.add_edge(credential_check, credential_check_loop)
root.order.add_edge(credential_check, route_design_loop)
root.order.add_edge(route_design, route_design_loop)
root.order.add_edge(load_assign, route_design_loop)
root.order.add_edge(traffic_scan, route_design_loop)
root.order.add_edge(package_secure, route_design_loop)
root.order.add_edge(dispatch_alert, route_design_loop)
root.order.add_edge(real_time_track, route_design_loop)
root.order.add_edge(incentive_issue, route_design_loop)
root.order.add_edge(route_design_loop, route_design_choice)
root.order.add_edge(route_design_choice, dispute_review_loop)
root.order.add_edge(dispute_review, dispute_review_loop)
root.order.add_edge(dispute_review, feedback_collect)
root.order.add_edge(customer_notify, route_design_choice)
root.order.add_edge(feedback_collect, performance_log)
root.order.add_edge(performance_log, ledger_update)
root.order.add_edge(ledger_update, hub_sync)