import pm4py
from pm4py.objects.powl.obj import StrictPartialOrder, OperatorPOWL, Transition, SilentTransition
from pm4py.objects.process_tree.obj import Operator

seed_selection = Transition(label='Seed Selection')
nutrient_mix = Transition(label='Nutrient Mix')
planting_setup = Transition(label='Planting Setup')
climate_control = Transition(label='Climate Control')
water_cycling = Transition(label='Water Cycling')
growth_monitoring = Transition(label='Growth Monitoring')
pest_detection = Transition(label='Pest Detection')
light_adjustment = Transition(label='Light Adjustment')
data_analysis = Transition(label='Data Analysis')
harvest_planning = Transition(label='Harvest Planning')
crop_harvest = Transition(label='Crop Harvest')
yield_sorting = Transition(label='Yield Sorting')
packaging_prep = Transition(label='Packaging Prep')
distribution_plan = Transition(label='Distribution Plan')
regulation_check = Transition(label='Regulation Check')
waste_recycling = Transition(label='Waste Recycling')
system_maintenance = Transition(label='System Maintenance')

skip = SilentTransition()

seed_selection_to_nutrient_mix = OperatorPOWL(operator=Operator.XOR, children=[seed_selection, nutrient_mix])
nutrient_mix_to_planting_setup = OperatorPOWL(operator=Operator.XOR, children=[nutrient_mix, planting_setup])
planting_setup_to_climate_control = OperatorPOWL(operator=Operator.XOR, children=[planting_setup, climate_control])
climate_control_to_water_cycling = OperatorPOWL(operator=Operator.XOR, children=[climate_control, water_cycling])
water_cycling_to_growth_monitoring = OperatorPOWL(operator=Operator.XOR, children=[water_cycling, growth_monitoring])
growth_monitoring_to_pest_detection = OperatorPOWL(operator=Operator.XOR, children=[growth_monitoring, pest_detection])
pest_detection_to_light_adjustment = OperatorPOWL(operator=Operator.XOR, children=[pest_detection, light_adjustment])
light_adjustment_to_data_analysis = OperatorPOWL(operator=Operator.XOR, children=[light_adjustment, data_analysis])
data_analysis_to_harvest_planning = OperatorPOWL(operator=Operator.XOR, children=[data_analysis, harvest_planning])
harvest_planning_to_crop_harvest = OperatorPOWL(operator=Operator.XOR, children=[harvest_planning, crop_harvest])
crop_harvest_to_yield_sorting = OperatorPOWL(operator=Operator.XOR, children=[crop_harvest, yield_sorting])
yield_sorting_to_packaging_prep = OperatorPOWL(operator=Operator.XOR, children=[yield_sorting, packaging_prep])
packaging_prep_to_distribution_plan = OperatorPOWL(operator=Operator.XOR, children=[packaging_prep, distribution_plan])
distribution_plan_to_regulation_check = OperatorPOWL(operator=Operator.XOR, children=[distribution_plan, regulation_check])
regulation_check_to_waste_recycling = OperatorPOWL(operator=Operator.XOR, children=[regulation_check, waste_recycling])
waste_recycling_to_system_maintenance = OperatorPOWL(operator=Operator.XOR, children=[waste_recycling, system_maintenance])

root = StrictPartialOrder(nodes=[seed_selection_to_nutrient_mix, nutrient_mix_to_planting_setup, planting_setup_to_climate_control, climate_control_to_water_cycling, water_cycling_to_growth_monitoring, growth_monitoring_to_pest_detection, pest_detection_to_light_adjustment, light_adjustment_to_data_analysis, data_analysis_to_harvest_planning, harvest_planning_to_crop_harvest, crop_harvest_to_yield_sorting, yield_sorting_to_packaging_prep, packaging_prep_to_distribution_plan, distribution_plan_to_regulation_check, regulation_check_to_waste_recycling, waste_recycling_to_system_maintenance])
root.order.add_edge(seed_selection_to_nutrient_mix, nutrient_mix_to_planting_setup)
root.order.add_edge(nutrient_mix_to_planting_setup, planting_setup_to_climate_control)
root.order.add_edge(planting_setup_to_climate_control, climate_control_to_water_cycling)
root.order.add_edge(climate_control_to_water_cycling, water_cycling_to_growth_monitoring)
root.order.add_edge(water_cycling_to_growth_monitoring, growth_monitoring_to_pest_detection)
root.order.add_edge(growth_monitoring_to_pest_detection, pest_detection_to_light_adjustment)
root.order.add_edge(pest_detection_to_light_adjustment, light_adjustment_to_data_analysis)
root.order.add_edge(light_adjustment_to_data_analysis, data_analysis_to_harvest_planning)
root.order.add_edge(data_analysis_to_harvest_planning, harvest_planning_to_crop_harvest)
root.order.add_edge(harvest_planning_to_crop_harvest, crop_harvest_to_yield_sorting)
root.order.add_edge(crop_harvest_to_yield_sorting, yield_sorting_to_packaging_prep)
root.order.add_edge(yield_sorting_to_packaging_prep, packaging_prep_to_distribution_plan)
root.order.add_edge(packaging_prep_to_distribution_plan, distribution_plan_to_regulation_check)
root.order.add_edge(distribution_plan_to_regulation_check, regulation_check_to_waste_recycling)
root.order.add_edge(regulation_check_to_waste_recycling, waste_recycling_to_system_maintenance)